### ISSUE TITLE
Update: Theca token Info

### ISSUE THREAD

**Issue by Theca-labs** [solana-labs/token-list#10017]
- **I'm submitting a ...**
  [ ] bug report
  [x ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I wanna update add Token Information : coingeckoId, coinmarketcap, serumV3Usdc
Token address : D3cm6WRnyBct3p7vFqyTt2CaynsGPuVQT2zW6WHSTX6q
token name: Theca

Please check PR :
[#9941](https://github.com/solana-labs/token-list/pull/9941)

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
duplicate entry for D3cm6WRnyBct3p7vFqyTt2CaynsGPuVQT2zW6WHSTX6q
https://github.com/solana-labs/token-list/runs/4610076485?check_suite_focus=true

you need to modify the existing block

**Comment by Theca-labs** [comment]
thanks keone, I would like to add information to the token

"coingeckoId": "theca",
 "coinmarketcap": "https://coinmarketcap.com/currencies/theca/",
 "serumV3Usdc": "6uH2rvVUySwnVFw7CMNV4HTzuxHTUNC7pK22pXcqgSey"

how can I do?

**Comment by keone** [comment]
you need to modify the existing block rather than adding a new one.  look at your diff right now: https://github.com/solana-labs/token-list/pull/9941/files

can't help you with git - ask an friend and learn how to use git better
