### ISSUE TITLE
Update Logo Shiba Poker Coin Token

### ISSUE THREAD

**Issue by shibasolana** [solana-labs/token-list#10254]
Hi,

please update my logo github link, for my token. I accidentally put a wrong link inside the json and the logo does not appear.
Here is my pull request: #10240
Correct url for the logo is: https://raw.githubusercontent.com/shibasolana/crypto/main/logo.png

Thanks in advance.

**Comment by keanuvanderbie** [comment]
Stop creating issues about it this is done every hour or so

**Comment by shibasolana** [comment]
Yes but it won't be automerged... Please read the instructions
