### ISSUE TITLE
Pull request Update DIBU Coin#10258 

### ISSUE THREAD

**Issue by xRoBBeRT** [solana-labs/token-list#10262]
Hello, please accept my request with number #10258. 
We are changing the decimals and logo.
Thanks!
![image](https://user-images.githubusercontent.com/75860781/147236059-c4b4985b-c72a-495b-8669-5c5cb8048d5a.png)
![image](https://user-images.githubusercontent.com/75860781/147236122-7d0ba6a9-2328-4041-86bc-b74535188fab.png)

**Comment by keanuvanderbie** [comment]
This is done automatic every hour

**Comment by xRoBBeRT** [comment]
Yes, but I think it won't be auto merged.
