### ISSUE TITLE
Issue adding extensions

### ISSUE THREAD

**Issue by Theca-labs** [solana-labs/token-list#10281]
We'd like to update our Token Information : coingeckoId , coinmarketcap, serumV3Usdc

Token : D3cm6WRnyBct3p7vFqyTt2CaynsGPuVQT2zW6WHSTX6q
name: Theca
symbol: THECA

Please check My PR: 
 [beb9d06](https://github.com/solana-labs/token-list/pull/10279/commits/beb9d0633cca7039c039c5d28d0e6d01375d662e)

**Comment by keone** [comment]
to understand why this is not valid, look at your diff: https://github.com/solana-labs/token-list/pull/10279/files
`D3cm6WRnyBct3p7vFqyTt2CaynsGPuVQT2zW6WHSTX6q` is already in the json, and then you're adding it again
