### ISSUE TITLE
We would like to change our logo.

### ISSUE THREAD

**Issue by UbikCapital** [solana-labs/token-list#10289]
- **I'm submitting a ...**
  [ ] bug report
  [x ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
We would like to change our logo.
Please see https://github.com/solana-labs/token-list/pull/10286/commits/d137c57b880170e079e986ebd4634adbaaa6edb5
Thank you.
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
please link a PR

**Comment by UbikCapital** [comment]
https://github.com/solana-labs/token-list/pull/10286

**Comment by keone** [comment]
duplicate address `HdpzynkmhceixStgZSbeh8p9avpWGJCHRXfTTfyiXQPH` (it's already in main but you added it again as a new block): https://github.com/solana-labs/token-list/pull/10286/files

**Comment by UbikCapital** [comment]
Please see the following PR
https://github.com/solana-labs/token-list/pull/10335

**Comment by keone** [comment]
merged
