### ISSUE TITLE
Please merge in https://github.com/solana-labs/token-list/pull/10571

### ISSUE THREAD

**Issue by SolChicks** [solana-labs/token-list#10572]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

The PR (https://github.com/solana-labs/token-list/pull/10571) contains updates to the $CHICKS token metadata. It is independently verifiable. Changes are:
1. Website: https://www.solchicks.io/
2. CoinGecko Id: https://www.coingecko.com/en/coins/solchicks-token

The SolChicks team has signed these changes off. 

Could you please merge this in as soon as you can?

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

N/A.

**Comment by keone** [comment]
added comment on the PR

**Comment by SolChicks** [comment]
Please see https://github.com/solana-labs/token-list/pull/10571#issuecomment-1000903652
