### ISSUE TITLE
Please remove PAC devnet token

### ISSUE THREAD

**Issue by cometbeetle** [solana-labs/token-list#10587]
- **I'm submitting a ...**
  [ ] bug report
  [ X ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Hello,

I am attempting to remove a devnet token I added recently due to a wallet error. 
The token address is GhFCdWckbZpDkxXWzzPRCa6JyEWbgbm5EHigEEY83E5y, and the symbol is PAC.
I submitted pull request #9865 with the changes, so any help would be much appreciated. 
Thanks!

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged. thank you for cleaning up your clutter!
