### ISSUE TITLE
issue in yarn build

### ISSUE THREAD

**Issue by sombeProject** [solana-labs/token-list#10685]
failed build yarn build test.
Error in  yarn build  #15143

**Comment by keone** [comment]
please link a PR

**Comment by sombeProject** [comment]
> please link a PR

@keone  update tag and extension #10679

**Comment by keone** [comment]
yeah, this is getting rejected because you tried to commit a whole bunch of unrelated crap: https://github.com/solana-labs/token-list/pull/10679/files
make sure your diff is minimal (just adding one json block with the new token) or it will be autorejected
