### ISSUE TITLE
Personally, something serious. wrong token address. need fix 

### ISSUE THREAD

**Issue by yoo-pro** [solana-labs/token-list#10789]
It has been failing to automerge  for a month. We registered the wrong address when we registered the token. to be in need of assistance

#9852

need your help~~

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by yoo-pro** [comment]
CHB TOKEN

**Comment by keone** [comment]
this PR has a massive diff: https://github.com/solana-labs/token-list/pull/9852/files
please commit the minimal diff and either push it to that PR, or create a new PR and link it here
