### ISSUE TITLE
urgent token list

### ISSUE THREAD

**Issue by Fiverr-Coin-Hunter** [solana-labs/token-list#10810]
Please approve my PR #10800  @keone

Thank You.

**Comment by keone** [comment]
automerge has been disabled due to an influx of spammers.  please be patient and do not open issues for new tokens, as they will be processed when automerge is enabled.  it's ok to open issues for things that would require manual review (edits to existing tokens)

**Comment by Fiverr-Coin-Hunter** [comment]
> please be patient and do not open issues for new tokens

please be patient and do not open issues for new tokens. okay bro

Thank You.
