### ISSUE TITLE
cannot change token symbol

### ISSUE THREAD

**Issue by baylonp** [solana-labs/token-list#10811]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x ] question about how to use this project

- **Summary**
- I'd like to change the token symbol from KRL to KRC but i get the error ---
- 
---->  "duplicate token: token address ZBkNgmPFienXwWVPg5LRSf3nZTKEHc9BQrayWPjJfQ1 is already used", i really don't now what to do . Note that this token address corresponds to the one i "created" and was able to merge with no problems, now i just want to make a modification to the symbol.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
make sure the diff in your commit is modifying the existing block instead of adding a new one!
