### ISSUE TITLE
Coingecko Id check ? // Personal, EDUC & MORS tokens validation workflow

### ISSUE THREAD

**Issue by MoroSteel** [solana-labs/token-list#10817]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [x] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
One week ago I made a new branch (add token EDUC) that has no conflicts with the base branch, only the CoingeckoId was wrong, the automerge failed in the CoingeckoId check (why do you check this info at this stage as we need to publish our token here before getting them in Coingecko.
Afterwards I delete the line of CoingeckoId and re-pull but no way to automerge it.
Could you please help me and validate this 2 branches
[#9568](https://github.com/solana-labs/token-list/pull/9568)
By the way could you please approve this branche for my second token 'MORS', I just fixed the wrong address 
[#8994](https://github.com/solana-labs/token-list/pull/8994)

Thank you very much.
Best regards,
Zak

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by diaz59760** [comment]
bonjour le meme probleme
