### ISSUE TITLE
Please change the token address. It doesn't automerge.

### ISSUE THREAD

**Issue by yoo-pro** [solana-labs/token-list#10923]
Hello.

RP request was made with one commit, but automatic merging is not possible. Please revise it.

I Just want change token address

charactbit token
6D4aGWykMymkFaeVzDS6MiH6QEujsHUze2pPGbJEyh7y
->YtfMZ4jg2ubdz4GasY86iuGjHdo5rCPJnFqgSf8gxAz

Several modifications have been attempted, but they do not change.

**Comment by yoo-pro** [comment]
#10797

plz help me TT

**Comment by keone** [comment]
you committed a huge diff: https://github.com/solana-labs/token-list/pull/10797/files
only a minimal diff will get merged
