### ISSUE TITLE
This workflow is awaiting approval from a maintainer in #10890

### ISSUE THREAD

**Issue by roysnakes** [solana-labs/token-list#10947]
- **I'm submitting a ...**

  [x ] question about the decisions made in the repository
  [ ] question about how to use this project

Hi, I'm having some difficulties with merging my data. 
It requires some actions related with my file

CodeQL #14616
Build #15402

What are my next steps?

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
bad commit:

https://github.com/solana-labs/token-list/pull/10890/files
> 20,343 additions, 0 deletions not shown because the diff is too large. Please use a local Git client to view these changes.

please submit a minimal diff
