### ISSUE TITLE
Clone succeeded, but checkout failed

### ISSUE THREAD

**Issue by sollysolana** [solana-labs/token-list#10940]
- **I'm submitting a ...**
  [ ] bug report

remote: Enumerating objects: 53030, done.        
remote: Counting objects: 100% (11/11), done.        
remote: Compressing objects: 100% (7/7), done.        
remote: Total 53030 (delta 2), reused 9 (delta 2), pack-reused 53019        
Receiving objects: 100% (53030/53030), 422.02 MiB | 12.27 MiB/s, done.
Resolving deltas: 100% (21295/21295), done.
error: unable to create file assets/**mainnet/B45eExdHQmYbVsEYzqYgrMwLBGhz6KXQAAPdpQ2DCGFj/purepng.com-the-witcher-3-logowitcherthe-witcherandrzej-sapkowskiwriterfantasy-serieswitcher-geralt-of-riviawitchersbooksmonster-hunterssupernaturaldeadly-beastsseriesvideo-gamesxbox-1701528661001lrjao.png**: Filename too long
Updating files: 100% (3949/3949), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
mainnet/B45eExdHQmYbVsEYzqYgrMwLBGhz6KXQAAPdpQ2DCGFj/purepng.com-the-witcher-3-logowitcherthe-witcherandrzej-sapkowskiwriterfantasy-serieswitcher-geralt-of-riviawitchersbooksmonster-hunterssupernaturaldeadly-beastsseriesvideo-gamesxbox-1701528661001lrjao.png

file name too long to add to local repository.

so this makes cloning difficult 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by sollysolana** [comment]
measures should be put in place to validate max logo or name length for files

**Comment by NLObedear** [comment]
I have this issue as well

**Comment by sollysolana** [comment]
So i believe this should be address faster.

So i had to do commit via upload. but still not the best practice

**Comment by sollysolana** [comment]
Thanks have been able to make a successful fork

this will now be closed
