### ISSUE TITLE
Website added and Address change Please treat as urgent

### ISSUE THREAD

**Issue by sollysolana** [solana-labs/token-list#10946]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- we just made a few change and will like them to be merged manually
- website added and Address change

- [#10938](https://github.com/solana-labs/token-list/pull/10938)

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
bad change:

https://github.com/solana-labs/token-list/pull/10938/files
> 62,051 additions, 62,051 deletions not shown because the diff is too large. Please use a local Git client to view these changes.

please submit a minimal diff or it won't be merged

**Comment by sollysolana** [comment]
Changes has been Made to the previous commit

we just made a few change and will like them to be merged manually

website added and Address change

[#11001](https://github.com/solana-labs/token-list/pull/11001)

Thanks
