### ISSUE TITLE
fixing a mistake : delete a wrong token that i sent and update the names of the right

### ISSUE THREAD

**Issue by jmorettoni** [solana-labs/token-list#10992]
- **I'm submitting a ...**
  [ ] bug report
  [X] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

I would like to delete one of my token, and update the name of my others tokens to make it right. 
i'm unfortunately make a mistake when i do the first pull request. 
I just sen a new pull request to delete the wrong token, and update the names of the right token.
https://github.com/solana-labs/token-list/pull/10989

**Comment by keone** [comment]
see comment on PR
