### ISSUE TITLE
PR feedback

### ISSUE THREAD

**Issue by krypt0x** [solana-labs/token-list#1100]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x] question about how to use this project

- **Summary**
What's the criteria for merging PRs to add tokens to your list? 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

#932

**Comment by jejdouay** [comment]
Same for me ! I have created and update a pull request a long time ago. Other pull requests have been merge, mine and many others not.
What are the criteria for the merging of PRs ?

**Comment by MCGICWORKS** [comment]
Same here as well, Is there something that I am missing or???

**Comment by jejdouay** [comment]
Just to let you know, got my merge !
You need to pull the repo again, there is a new script to automerge. Update your repo and it will work !

**Comment by MCGICWORKS** [comment]
You right
I updated all the branches and it merged only without my token

**Comment by MCGICWORKS** [comment]
Created a new PR 
didn't change any existing script
only added my details but still getting this error:

Uncaught exception in src/lib/tokenlist.spec.ts

  SyntaxError: /home/runner/work/token-list/token-list/dist/main/tokens/solana.tokenlist.json: Unexpected token ] in JSON at position 630068

  › parse (<anonymous>)
  › Object.<anonymous> (dist/main/lib/tokenlist.js:2:984)

  ✖ src/lib/tokenlist.spec.ts exited with a non-zero exit code: 1

Can anyone help me figure it out?

**Comment by MCGICWORKS** [comment]
I got merged
whoooohoooo
that was hard but I feel like it was the easiest part. lol

**Comment by D0NC0DE** [comment]
I notice something ... you need to edit your .json file with a separate editor, not the Github editor. I tried the GitHub editor 7times and it keeps deleting a line of code for me. But when I tried using notepad++, the story changed

**Comment by Ektwnl** [comment]
Thx 👍

**Comment by krypt0x** [comment]
I'll give it a try as well. Thank you everyone.
