### ISSUE TITLE
kingsolo token added

### ISSUE THREAD

**Issue by sollysolana** [solana-labs/token-list#11045]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
kingsolo token added 

[#11009 ](https://github.com/solana-labs/token-list/pull/11009)

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
do not open tickets for new tokens, they will be automerged occasionally
