### ISSUE TITLE
This workflow is awaiting approval from a maintainer in #11085

### ISSUE THREAD

**Issue by roysnakes** [solana-labs/token-list#11086]
- **I'm submitting a ...**

  [x ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

Another attempt

**Comment by keone** [comment]
invalid json (comma at end), also commits an extraneous file: https://github.com/solana-labs/token-list/pull/11085/files

please stop spamming asking review of a PR that is not going to get merged based on failing checks
