### ISSUE TITLE
Update Staked Sol Invictus Metadata

### ISSUE THREAD

**Issue by AlexLeung** [solana-labs/token-list#11124]
Commit where I added the token: https://github.com/solana-labs/token-list/commit/5e873b60d7c86fd60e6d021c7917ae9f32025e96

Values to be changed:
- Update symbol from `SIN` to `sIN` (first letter made lowercase)
- Update name from `Staked Sol Invictus` to `Staked Sol Invictus (Wrapped)`

**Comment by keone** [comment]
please link a PR

**Comment by keone** [comment]
nvm found it: #10062
