### ISSUE TITLE
Update MTMS token name and website #11143

### ISSUE THREAD

**Issue by itm2018** [solana-labs/token-list#11146]
- **I'm submitting a PR #11143  **
- The commit where I added token is #6957
- I need to change the token name from "MTMS Token" to "MTMS Network"
- I need to change the homepage website from "https://metameetingapp.com" to "https://mtms.live"
  Please help me to merge this PR and thank you for your consideration.

 Kind Regards

**Comment by keone** [comment]
thanks for the thorough description (linking the commit where you added). merged
