### ISSUE TITLE
JayCoin Logo did not merge

### ISSUE THREAD

**Issue by jaycuts** [solana-labs/token-list#11181]
- **I'm submitting a ...**
  [X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- PR 11083 (automerge)
- 
- assets/mainnet/6HPGGdi3XoxwpW3GZyPgijUdJQiQRMCnPiyxFDyrpfW6/logo.png
- 
- Don't know why my logo is not showing up in Solscan.  Logo was uploaded to correct folder, square 600X600 PNG, not large file.  -
- Did resize logo even smaller and uploaded into same folder if a manual merge must be done.

![logo](https://user-images.githubusercontent.com/96754837/147592351-553c85e1-c357-45c0-8b1e-2ecc89ec7d1c.png)

**Comment by keone** [comment]
you need the raw path, i.e. `https://raw.githubusercontent.com/jaycuts/crypto/main/logo.png`

**Comment by jaycuts** [comment]
I knew that…. I’m an idiot.
