### ISSUE TITLE
URunner Coin into Token List

### ISSUE THREAD

**Issue by URunner21** [solana-labs/token-list#11194]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

found removed line: - "name": "Solana Token List" was the response I got from my PR: URunner Application into TokenList #11038 
If anyone can help me understand how this is, please let me know.

**Comment by keone** [comment]
because your diff is massive: https://github.com/solana-labs/token-list/pull/11038/files
please only submit a minimal diff
