### ISSUE TITLE
Update Tokens

### ISSUE THREAD

**Issue by juliotpaez** [solana-labs/token-list#11193]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Hi, I uploaded a PR (#10983) with the updates of our tokens. We have changed the hostname and need to update it in the list.
We can do anything you need to prove that we are the owners, so let us know what you need.

**Comment by keone** [comment]
see comment in PR

**Comment by juliotpaez** [comment]
Thank you very much for mergin it!!
