### ISSUE TITLE
Automerge issue

### ISSUE THREAD

**Issue by adampicker88** [solana-labs/token-list#11289]
- **I'm submitting a ...**
  [x] bug report

Automerge issue with new token - RunGoodKoin.
Successfully created token (#10804), however listed the wrong URL for token logo. Created new fork, updated URL to correct one and created new pull request (#11094) to merge back to the main token list. Appeared to have gone through fine, however a few hours later now has a note of note eligible for automerge.

**Comment by keone** [comment]
edits need to be manually merged
merged
