### ISSUE TITLE
updating the solana token list is a real nightmare.. pls help..

### ISSUE THREAD

**Issue by Terrahasher** [solana-labs/token-list#11357]
- **I'm submitting a ...**
  
  [x ] feature request

Hi There, not sure why it wont work to update the solana-token list but i am having some difficulties with "just" adding my token...
is there anyone out here who can explane what i am doing wrong? i followed all the steps to clone the list, edit my token in as explaned, created a pull request and it keeps getting rejected. 
here below is the code:

{
      "chainId": 101,
      "address": "GX7scixLhnEQk3C1LEDKk5eeeUb2RUwyyKEWYRfAV8SA",
      "symbol": "DSB",
      "name": "Dogstreetbets",
      "decimals": 4,
      "logoURI": "https://raw.githubusercontent.com/Terrahasher/dogstreetbets/main/dogstreetbets.png",
      "tags": [
        "Community-token",
        "Social-token",
        "MetaVerse",
        "DeFi",
        "Payment"
	      "Swap"
      ],
      "extensions": {
        "twitter": "https://twitter.com/dogstreetbets",
        "website": "https://dogstreetbets.com/"
    }
  ],

**Comment by keone** [comment]
please link a PR
