### ISSUE TITLE
Issue Fetching Upstream. Code deleted !

### ISSUE THREAD

**Issue by KyleF0X** [solana-labs/token-list#11388]
I am submitting an issue i had where i got a conflict trying to fetch upstream to update my fork. 

When i tried  the system told me there were conflicts that had to be resolved, and they had to be done via the CLI. When i examined the conflict, it looked like the change was that **my three token codes had been deleted**. I rejected the changed and pushed to my main fork. I then did a pull request to the offical Solana-labs/token-list as i wanted to make sure my code was still there. However it got an error, and i found my code was duplicated. I then got another error saying i dont have write permission to merge, probably because i rejected their changes. 

Im confused what has caused this conflict to begin with?
Did someone try delete my code but it was restored?
Are our code submits safe from being deleted?

Ive now re-merged my fork but this time accepting incoming changes. Im hoping now my fork is in sync with the solana main and able to submit future pull requests. Im not even sure if i have to fetch to most up to date before submitting a pull request?

**Comment by keone** [comment]
sorry, the maintainers can't help you with learning how to use git.  if you have a PR that needs manual review please link it
