### ISSUE TITLE
Hello, i tried to update the logo for my token but it seems that it needs a manual review, can you please check it? thank you

### ISSUE THREAD

**Issue by kisscoins** [solana-labs/token-list#11405]
Hello, i tried to update the logo for my token but it seems that it needs a manual review, can you please check it? thank you

_Originally posted by @kisscoins in https://github.com/solana-labs/token-list/issues/11247#issuecomment-1002735975_

**Comment by keone** [comment]
see comment in PR

**Comment by keone** [comment]
merged

**Comment by kisscoins** [comment]
Thank you so much @keone, I really apreciarte it.
