### ISSUE TITLE
Problem with Build

### ISSUE THREAD

**Issue by URunner21** [solana-labs/token-list#11445]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
src/tokens/solana.tokenlist.json:64948:3 - error TS1136: Property assignment expected.

64948   {
        ~

src/tokens/solana.tokenlist.json:64964:1 - error TS1012: Unexpected token.

64964 }
      ~

Found 2 errors.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build:main" exited with 2.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.

I keep getting this error, however, the token list doesnt even have a line past 64773 after my commit. So I am confused in what I did wrong. Please help if you can. Request Number: Final Submission of URunner Coin into Token List #11437

**Comment by keone** [comment]
invalid json; you added your block to the toplevel dict instead of as an element of `tokens`
