### ISSUE TITLE
Update ISLAMICOIN token Address

### ISSUE THREAD

**Issue by ISLAMIBLOCKCHAIN** [solana-labs/token-list#11440]
Hope you are doing well,

We have our program created on Solana with the address: FFADztSZMCzt1wVX9q66hzmuWk9zDXpxnK7E4H8mTNu5
and submitted a PR #11121 successfully to set the name and logo to Solana-labs. Today we created a wrapped version for our program using wormhole in order to have a bridge between our source token on polygon with our token on Solana. In this regard we would like to request a change of our program address, . Our wrapped program address is: HG2FnifX1WPY6UvnkXnMx2kAt4E4Ssu6DZ2aiB5RmLHo

The New PR is: #11454 

Your support is highly appreciated.

Thank you
Best Regards

**Comment by keone** [comment]
thank you for the clear reference to the original PR
merged
