### ISSUE TITLE
Adding token - PASSED ALL TESTS - no write access to merge

### ISSUE THREAD

**Issue by wavemstudios** [solana-labs/token-list#11450]
- **I'm submitting a ...**
  [ ] bug report

We have passed all tests but cannot merge maybe because of write issues - can you force the merge thanks
  
https://github.com/solana-labs/token-list/pull/11441

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
automergebot merged this shortly after you posted

**Comment by wavemstudios** [comment]
Nice one - thanks Keone - well done to all the team...
