### ISSUE TITLE
Unkown Error

### ISSUE THREAD

**Issue by URunner21** [solana-labs/token-list#11489]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
  1 test failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "test:unit" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.

I don't understand this error.

**Comment by URunner21** [comment]
Error: Final Submission of URunner Coin into Token List #11437

**Comment by keone** [comment]
`Token list does not have duplicate entries`

because you already added it in https://github.com/solana-labs/token-list/pull/11425
