### ISSUE TITLE
remove my tokens

### ISSUE THREAD

**Issue by jmorettoni** [solana-labs/token-list#11504]
[ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

Remove my tokens from list

Hello, I would like to remove my tokens  because they have erros that i need change. I would like to delete to send it again with the correct datas .  thank you.

**Comment by keone** [comment]
please link a PR

**Comment by jmorettoni** [comment]
thank you. the PR link : https://github.com/solana-labs/token-list/pull/11503

**Comment by keone** [comment]
merged
