### ISSUE TITLE
Change Logo

### ISSUE THREAD

**Issue by testsystemca** [solana-labs/token-list#11609]
I am trying to change logo but getting error 

found removed line: - "logoURI": "https://github.com/testsystemca/blcksgn/blob/main/Logo.png",

**Comment by keone** [comment]
please link a PR

**Comment by testsystemca** [comment]
https://github.com/solana-labs/token-list/pull/11631

**Comment by testsystemca** [comment]
https://github.com/solana-labs/token-list/pull/11587/commits/e96c501efe5a6b463648dd05d225855d24e933e7

**Comment by keone** [comment]
that's a commit, not a PR

**Comment by testsystemca** [comment]
https://github.com/solana-labs/token-list/pull/11652/checks?check_run_id=4670469916

**Comment by sollysolana** [comment]
> https://github.com/solana-labs/token-list/pull/11652/checks?check_run_id=4670469916

Here is your Pr link


[#11652]( https://github.com/solana-labs/token-list/pull/11652)

**Comment by testsystemca** [comment]
> > https://github.com/solana-labs/token-list/pull/11652/checks?check_run_id=4670469916
> 
> Here is your Pr link
> 
> [#11652](https://github.com/solana-labs/token-list/pull/11652)

Thanks

Any idea  how to fix it?

**Comment by sollysolana** [comment]
will be manually merged

> > > https://github.com/solana-labs/token-list/pull/11652/checks?check_run_id=4670469916
> > 
> > 
> > Here is your Pr link
> > [#11652](https://github.com/solana-labs/token-list/pull/11652)
> 
> Thanks
> 
> Any idea how to fix it?

will be manually merged

**Comment by testsystemca** [comment]
> will be manually merged
> 
> > > > https://github.com/solana-labs/token-list/pull/11652/checks?check_run_id=4670469916
> > > 
> > > 
> > > Here is your Pr link
> > > [#11652](https://github.com/solana-labs/token-list/pull/11652)
> > 
> > 
> > Thanks
> > Any idea how to fix it?
> 
> will be manually merged

Could you please send me user guide if you have for  that?

**Comment by keone** [comment]
merged

**Comment by testsystemca** [comment]
> merged

Thanks
