### ISSUE TITLE
Can't update token details. It always fail with automerge-error.  Help needed!

### ISSUE THREAD

**Issue by denizTutuncu** [solana-labs/token-list#11655]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x] question about how to use this project

- **Summary**
I am trying to update my token details on the list. 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
I am having error with `found removed line: - "chainId": 101,` which I accidentally put before 103. I also updated some other info.
My PR is `#11647`

Thank you in advance.

**Comment by keone** [comment]
merged
