### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ArtinMB** [solana-labs/token-list#11751]
- **I'm submitting a...**
  [ ] bug report
  [ ] feature request
  [yes ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Please help me i dont understand what I did wrong. Why isnt it merging?
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
please link a PR

**Comment by ArtinMB** [comment]
what is a PR?
