### ISSUE TITLE
Logo and Token Symbol not shown on phantom wallet? please help to check is there any wrong with our PR. Thank you

### ISSUE THREAD

**Issue by DookuSociety** [solana-labs/token-list#11798]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
please link a PR

**Comment by Benomat** [comment]
> please link a PR

I am having the same issue here is my PR: #12017 
and here my issue i opened for that: #12189

**Comment by keone** [comment]
duplicate of #12189
