### ISSUE TITLE
Update AtlasDex Token tags

### ISSUE THREAD

**Issue by yasiriqbal776** [solana-labs/token-list#11959]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [x ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Hi , i want to update my token tags, 
[#11955 ](https://github.com/solana-labs/token-list/pull/11955)

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
