### ISSUE TITLE
Bot automerge does not work

### ISSUE THREAD

**Issue by irishsettersol** [solana-labs/token-list#11961]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Hi Team, it seem bot for automerge not running. Our pull request 9 hours ago not checked for the automerger process. 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
Pull request link #11927

**Comment by keone** [comment]
automerge was disabled due to an influx of spammers.  it will be run periodically (running it now)

**Comment by cavidk** [comment]
Automerge puts an error as new automerge.Its happening  as nonsense while after success pull-request. Solve bug please!!
