### ISSUE TITLE
Wrong Placement of Name & Symbol

### ISSUE THREAD

**Issue by skylrfinance1** [solana-labs/token-list#11988]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- I Wrong Placement of Name & Symbol [https://github.com/solana-labs/token-list/pull/11743](url)

**Comment by keone** [comment]
added comment to PR https://github.com/solana-labs/token-list/pull/11743

**Comment by skylrfinance1** [comment]
How To Edit?Was it on a previous request?[https://github.com/solana-labs/token-list/pull/11720](url)Closed
Am I making a new pull request[https://github.com/solana-labs/token-list/pull/12340](url)

**Comment by keone** [comment]
merged in #12486
