### ISSUE TITLE
Token register

### ISSUE THREAD

**Issue by Slickmojo24g** [solana-labs/token-list#12074]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
if the question is about #11844, you are trying to add extraneous files:
https://github.com/solana-labs/token-list/pull/11844/files

**Comment by Slickmojo24g** [comment]
Closed
