### ISSUE TITLE
New Automerge Error

### ISSUE THREAD

**Issue by cavidk** [solana-labs/token-list#12096]
- Lagrange USDL Automerge error bug.

-  We have created a Lagrange USDL token on tokenlist already.But now we have some trouble on it when making a pull-request  while trying to change token address or delete whole token information. First step was succeed,  but after a hour there is an new <Automerge> error appearing and gives error like deleted address or line. I have put a link below.Please solve an Automerge error and close my pull-request. 

### Automerge puts an error as new automerge.Its happening  as nonsense while after success pull-request.

** https://github.com/solana-labs/token-list/pull/11986/commits/6444afc66ff73b911582a872d3af6f6a9aa6c095****

**Comment by keone** [comment]
please link a PR

**Comment by cavidk** [comment]
Here is pr link below!
 
https://github.com/solana-labs/token-list/pull/11986
  
>Monday, January 3, 2022 9:01 PM +04:00 from keone ***@***.***>:
> 
> 
>please link a PR
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <solana-labs/token-list/issues/12096/1004226357 @ github . com> 
 
 
Best regards,
Cavid Kazimov

**Comment by cavidk** [comment]
> please link a PR

https://github.com/solana-labs/token-list/pull/11986

**Comment by keone** [comment]
merged

**Comment by cavidk** [comment]
Hello! 
  We want to delete our another token called Lag token and it shows an error again.
 This is the pull request error link below :     
https://github.com/solana-labs/token-list/pull/12314
 
  Please merge it to tokenlist.
    This error like last time happened while we wanted to delete USDL token. 
  
>Tuesday, January 4, 2022 12:15 AM +04:00 from keone ***@***.***>:
> 
> 
>Closed  #12096 .
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <solana-labs/token-list/issue/12096/issue_event/5836992806 @ github . com> 
 
 
Best regards,
Cavid Kazimov
