### ISSUE TITLE
Wrong logo link with Automerge

### ISSUE THREAD

**Issue by jejdouay** [solana-labs/token-list#1213]
- **I'm submitting a ...**
  [x ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

during the merge, the link to the logo is created with 
https://raw.githubusercontent.com/solana-labs/token-list/main/assets/assets/J5gLhk6mmQ4PSoir1Ufh8JY2ytEHA93YupzYiTFVCgcL/logo.png
instead of 
https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/J5gLhk6mmQ4PSoir1Ufh8JY2ytEHA93YupzYiTFVCgcL/logo.png
Logo is not displaying on the solana explorer.

**Comment by ngarraud** [comment]
I have the same problem as you. Could you let me know when you find a way to sort it out? Thank you

**Comment by jejdouay** [comment]
no help ! not working ! going somewhere else to setup my project
