### ISSUE TITLE
how will this automerge?

### ISSUE THREAD

**Issue by brandon18lawson** [solana-labs/token-list#12188]
how will this automerge?

_Originally posted by @brandon18lawson in https://github.com/solana-labs/token-list/issues/12143#issuecomment-1004232435_

**Comment by Benomat** [comment]
Your logo has to be a square not a rectangle. I edited your logo to be 582x582 instead of 328x582. Try using this:
![logo](https://user-images.githubusercontent.com/71938735/147961747-91eababa-a853-4515-bd71-869a44642c31.jpg)

**Comment by brandon18lawson** [comment]
Problem solved

**Comment by keone** [comment]
close issues that are done
