### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by brandon18lawson** [solana-labs/token-list#12181]
- **I'm submitting a ..report.**
  [ ] bug report
  [ ] feature request
  [ /\] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.) cannot merge

**Comment by keone** [comment]
please link a PR

**Comment by brandon18lawson** [comment]
what is a PR?

**Comment by Benomat** [comment]
> what is a PR?

a pull request
