### ISSUE TITLE
.png image on assets/mainnet turned into 503 http response

### ISSUE THREAD

**Issue by brainyapegang** [solana-labs/token-list#12199]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
My pull request was auto merged. I can view it on SolScan now. However, my token image is missing and it turns into 503 http response in place of the image. Something went wrong during merge.

- **Other information** 
1.  **Image on origin is different from fork**
Main:
https://github.com/solana-labs/token-list/blob/main/assets/mainnet/BAGcAKTb5xooqS1pDkaNBJnD2WYaK7SuLkntyTi7Dbi7/logo.png
Original (fork):
https://github.com/brainyapegang/token-list/blob/dd14fb3772131cb2205acf5473f2e563876ed9cc/assets/mainnet/BAGcAKTb5xooqS1pDkaNBJnD2WYaK7SuLkntyTi7Dbi7/logo.png

2. **The commit merged a 503 response in html**
https://github.com/solana-labs/token-list/commit/44c5072653f36c81d3d0f434290bc7644ee5f286#diff-605bdfe3ee84261664e91146533b602e6ab82487fbcb477ea63dcab8d7716a87

**Comment by Benomat** [comment]
Your link was to an github page not to the image itself! Try using this link: https://raw.githubusercontent.com/brainyapegang/token-list/dd14fb3772131cb2205acf5473f2e563876ed9cc/assets/mainnet/BAGcAKTb5xooqS1pDkaNBJnD2WYaK7SuLkntyTi7Dbi7/logo.png
