### ISSUE TITLE
I cannot update my old token's address and logo, etc with automerge-error

### ISSUE THREAD

**Issue by monkeyMax-SVG** [solana-labs/token-list#12261]
A two weeks ago, I added my token and remove forked  git repo after successful merge.
Later, I deployed token to mainnet again and now I am gonna update old token info.
So, I forked token-list repo again and made a PR.
But it shows automerge-error.
This is my PR.
https://github.com/solana-labs/token-list/pull/12244
I am appreciate if you can help me. Thank you.

**Comment by keone** [comment]
merged
