### ISSUE TITLE
Update coin 

### ISSUE THREAD

**Issue by JmzTaylor** [solana-labs/token-list#12279]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ x] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Needed to update a few lines and logo.  Automerge error

#12214

**Comment by keone** [comment]
merged
