### ISSUE TITLE
BMRC COIN

### ISSUE THREAD

**Issue by NCBEASTMODERC** [solana-labs/token-list#12305]
- **I'm submitting a ...**
  [x ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I keep getting the following error:
 unsupported file modified: LOGO3.png b/assets/mainnet/HDveJwQE99MbJzNeozSk3Pp45CVmEDyVrGyMuckQg3R1/BMRC LOGO3.png

i have uploaded multiple png files from different sources in different sizes. All of which come up with the same error.

**Comment by NCBEASTMODERC** [comment]
#12296

**Comment by keone** [comment]
see comment in PR

**Comment by NCBEASTMODERC** [comment]
Thank you for your response.

Spaces in the omg file name correct?

**Comment by keone** [comment]
correct
