### ISSUE TITLE
Automerge problem adding "coingeckoId"

### ISSUE THREAD

**Issue by yanselfg** [solana-labs/token-list#12303]
- **I'm submitting a**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I am trying to update a token "coingeckoId" by doing a pull request and I am getting this error: *failed to normalize: failed to parse JSON: json: unknown field "coingeckoId"* .. The field is well written and I have tried a lot of times in many different ways and every time I get that error. This is the pull request of the last attempt I did: https://github.com/solana-labs/token-list/pull/12289
![image](https://user-images.githubusercontent.com/59712355/148016369-a749d2ae-ed7a-4017-a17a-ae618eab9a7d.png)

**Comment by yanselfg** [comment]
@keone Hi .. can you help me with this problem ?

**Comment by keone** [comment]
squashed and merged

**Comment by yanselfg** [comment]
> squashed and merged

thanks !!!

**Comment by yanselfg** [comment]
@keone what was the problem ? .. was I doing something wrong ? .. want to know for future updates
