### ISSUE TITLE
Correct twitter link

### ISSUE THREAD

**Issue by ginoizm** [solana-labs/token-list#12301]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

We want to correct twitter link because old one is removed.
New one is https://twitter.com/Kuncicoin_id
Please accept this PR
#12290 
Thank you.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
