### ISSUE TITLE
help

### ISSUE THREAD

**Issue by brandon18lawson** [solana-labs/token-list#12315]
- **I'm submitting a .request..**
  [ ] bug report
  [ ] feature request
  [ x] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
is my coint BRANT embedded onto solana now?

https://github.com/solana-labs/token-list/commit/682a48d383de65d6df07d9dbf3e9116e5de375bf
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
yes it's in token-list now https://github.com/solana-labs/token-list/pull/12143
please don't spam the issues
