### ISSUE TITLE
wrong logo address

### ISSUE THREAD

**Issue by ngarraud** [solana-labs/token-list#1232]
Hello

I have done a mistake in my logo address for Coban Token.
Can you please replace "assets" with "mainnet"?
So the correct address should be:

https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/7udMmYXh6cuWVY6qQVCd9b429wDVn2J71r5BdxHkQADY/logo.png

Thank you very much

**Comment by SolDev-stack** [comment]
Please read the [SPL-token README](https://github.com/SolDev-stack/token-list/blob/main/README.md), and ensure your SPL-token info uses the correct [Uniswap format](https://github.com/SolDev-stack/token-lists/blob/main/README.md).
