### ISSUE TITLE
Logo change Aurorium token

### ISSUE THREAD

**Issue by tolui** [solana-labs/token-list#12326]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
We decided to change our Aurorium token logo. here is the PR. please merge my changes. Thanks
https://github.com/solana-labs/token-list/pull/12325

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
