### ISSUE TITLE
Update token's website link

### ISSUE THREAD

**Issue by monkeyMax-SVG** [solana-labs/token-list#12359]
Hi, I am gonna update token info (the website link).
I created PR.
https://github.com/solana-labs/token-list/pull/12358

I am appreciate if you help me. thank you.

**Comment by keone** [comment]
added comment in PR

**Comment by monkeyMax-SVG** [comment]
Okay, I did  it again. Can you please check again?
https://github.com/solana-labs/token-list/pull/12358
Thank you

**Comment by monkeyMax-SVG** [comment]
thank you so much. solved.
