### ISSUE TITLE
Update png #12221

### ISSUE THREAD

**Issue by neutralskew** [solana-labs/token-list#12366]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

#12221

**Comment by neutralskew** [comment]
@keone :)

**Comment by keone** [comment]
merged. please don't tag maintainers
