### ISSUE TITLE
New Automerge error

### ISSUE THREAD

**Issue by cavidk** [solana-labs/token-list#12376]
-Remove Lagrange Lag token from tokenlist shows Automerge error bug.

- We have created a Lagrange token on tokenlist already.But now we have some trouble on it when making a pull-request while trying to change token address or delete whole token information. First step was succeed, but after a hour there is an new error appearing and gives error like deleted address or line. I have put a link below.Please solve an Automerge error and close my pull-request.

- [Automerge](https://github.com/solana-labs/token-list/pull/12314)  puts an error as new automerge.Its happening as nonsense while after success pull-request.

**Comment by keone** [comment]
merged

**Comment by keone** [comment]
it's not nonsense, you are trying to re-add `fJGfG6NFM2SGmvXhsNRaN4Ge3UAhqbbmjAkqbR7hn6B` which already exists in the token-list
