### ISSUE TITLE
Looking for manual approve of tag edits.

### ISSUE THREAD

**Issue by tonyboylehub** [solana-labs/token-list#12414]
Currently looking for manual approval of editing of a token I submitted a few days ago. (https://github.com/solana-labs/token-list/pull/12411)

I didn't realise the tags where going to affect the way things were handled in apps such as Phantom Wallet. I wrote one tag as NFT based on the fact we were using them for NFT whitelist tokens and this pulled my token into the Collectables portion of Phantom wallet rather than the main wallet. So looking to get all tags removed currently to fix this.

**Comment by keone** [comment]
merged

**Comment by tonyboylehub** [comment]
Thank you so much! :)
