### ISSUE TITLE
Looking for manual approve of tags edit

### ISSUE THREAD

**Issue by Interstellarwhales** [solana-labs/token-list#12500]
- Currently looking for manual approval of editing of a token I submitted a few hours ago. (#12461)

I just realise the tags where going to affect the way things were handled in apps such as Phantom Wallet. I wrote one tag as NFT based on the fact we were using them for the NFT project and this will pull my token into the Collectables portion of Phantom wallet rather than the main wallet. So looking to get the NFT tag removed or all tags removed currently to fix this.

**Comment by interbiznw** [comment]
if the pr is not merged, just edit again...any changes get added to same PR

**Comment by keone** [comment]
bad diff:
https://github.com/solana-labs/token-list/pull/12461/files
