### ISSUE TITLE
cannot change coin symbol nor logo

### ISSUE THREAD

**Issue by baylonp** [solana-labs/token-list#12522]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x ] question about how to use this project

- **Summary**
i already opened a issue weeks ago, #10811( https://github.com/solana-labs/token-list/issues/10811 ), i tried again but i don't know how to resolve. i would like to change the symbol and the logo, i modified the symbol from KRL to KRC  and added the new logo path but i get the error "unable to merge" and i cant create a PR. I'm new to all of this i don't even know what to troubleshoot.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by baylonp** [comment]
with the previous issue(https://github.com/solana-labs/token-list/issues/10811) i had this error : 

This branch has conflicts that must be resolved

Conflicting files
src/tokens/solana.tokenlist.json

**Comment by Benomat** [comment]
Just be patient, this can take some time. If you want some more information read my reply on my own issue #12189 !

**Comment by keone** [comment]
i replied to your previous issue.  you added a duplicate block instead of modifying the existing one.  if that is unclear to you, please ask a friend for help; can't explain git to you here
