### ISSUE TITLE
Attempting to update Image for Wallito Coin

### ISSUE THREAD

**Issue by memesparky** [solana-labs/token-list#12566]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I am attempting to update my image for my token. My last commit was 71a6516fa9faaa0993a790ae4bd27b2ad1ec2ead which seemed to fail. My coin is Wallito (WaLe). Can you please help me with this request?
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
please link a PR

is it #11800?  if so look at https://github.com/solana-labs/token-list/pull/11800/files
you re-added the same block which creates a duplicate entry; submit a PR with only the image change

**Comment by memesparky** [comment]
Yes, this is the correct PR. I added a new commit which changes the image and image link. Please let me know if this is ok.

Commit: https://github.com/solana-labs/token-list/commit/d657b49813a0ced4145560bf1371c6dfece101c4

**Comment by spacemandev-git** [comment]
in the most recent commit you deleted the entire token list as part of the PR. please try again with modifying only the existing token by grabbing a fresh copy of solana token list repo.
