### ISSUE TITLE
Updating token - automerger unknown field "coingeckoId" 

### ISSUE THREAD

**Issue by Fnjo** [solana-labs/token-list#12571]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- I tried to only add the coingecko id to my token data but got the automerger message: _failed to normalize: failed to parse JSON: json: unknown field "coingeckoId"_. I had no deleted or edited lines up to that point.

- PR: https://github.com/solana-labs/token-list/pull/12463

**Comment by keone** [comment]
merged
