### ISSUE TITLE
SBG Token Replacement

### ISSUE THREAD

**Issue by beargrilo** [solana-labs/token-list#12690]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- Need to replace the token due to wrong decimals in the first token. Since the name conflicts, it's being rejected by automerger. Should I just wait for someone to manually review it? Thank you

- PR: #12679

**Comment by keone** [comment]
re-adds instead of modifying existing: https://github.com/solana-labs/token-list/pull/12679/files

**Comment by beargrilo** [comment]
Made a commit, will it be enough to pass the automerge bot or human action will be needed?

Ty

**Comment by beargrilo** [comment]
Not eligible for automerge (click details for more information)
duplicate token: token name Solana Bear Gang Token is already used

**Comment by keone** [comment]
that's what i meant by "re-adds instead of modifying existing"
you have to modify the existing entry in json

**Comment by beargrilo** [comment]
found modified asset file assets/mainnet/9TufFVQ2Z1F2JucPodVfrocXQcM1RwTZ2CrBHysukXJ5/logo.png - only new assets are allowed

What does this means?

**Comment by keone** [comment]
thanks for fixing; merged

**Comment by beargrilo** [comment]
Ty @keone
