### ISSUE TITLE
Update GÜ data

### ISSUE THREAD

**Issue by DrakeXorn** [solana-labs/token-list#12700]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I am from the Kugle dev team and we want the GÜ token to be more accessible. We decided to change some information about it, including the logo. I I did so in #12634 but the merging bot prevents me from updating the image.
Can you help me? 🙂
Thanks in advance!

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged. thanks, better to avoid non-ascii chars
