### ISSUE TITLE
Change Token Information 

### ISSUE THREAD

**Issue by soldev81** [solana-labs/token-list#12703]
I wanna change my token SYMBOL and NAME because because i was mistaken so please help me merge this request 
[12702](https://github.com/solana-labs/token-list/pull/12702)

This is my previous commit and I want to change it
https://github.com/solana-labs/token-list/pull/12403

https://github.com/solana-labs/token-list/commit/51e1f0afd0f1784e3351c997547d04eb6c210d55

**Comment by keone** [comment]
this re-adds a new block instead of modifying the existing: https://github.com/solana-labs/token-list/pull/12702/files

**Comment by soldev81** [comment]
> this re-adds a new block instead of modifying the existing: https://github.com/solana-labs/token-list/pull/12702/files

I'm trying to addd New but got this error : 
  Token list does not have duplicate entries
This commited i trying add new bock. 
https://github.com/solana-labs/token-list/pull/12806

**Comment by keone** [comment]
i gave you clear instructions on what was wrong with your
