### ISSUE TITLE
Automerge error: "chainId: conflicting values 103 and 0"

### ISSUE THREAD

**Issue by AlphaPrime8** [solana-labs/token-list#12807]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x] question about how to use this project

- **Summary**
Trying to add a new token but automerge gives error "error validating schema: chainId: conflicting values 103 and 0".

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
This is my pull request: https://github.com/solana-labs/token-list/pull/11946
I have the correct chainId: "103" and is valid on mainnet. Not sure what I'm doing wrong. Please advise.

**Comment by topranks** [comment]
I was getting that on a PR I submitted.

Turned out to be a syntax error.  Vim had been adding a new line to the end of the file on me (to be POSIX compliant).  Once I managed to fix that the issue went away.

Anyway just mentioning, might be worth checking all sytnax, whitespace etc.

**Comment by AlphaPrime8** [comment]
@topranks is there a validator tool to check syntax compliance?

**Comment by AlphaPrime8** [comment]
I am running this as a node script as per the linked uniswap spec:
```import fetch from "node-fetch";
import Ajv from 'ajv';

import addFormats from 'ajv-formats';

import { schema } from '@uniswap/token-lists'

const ajv = new Ajv({ allErrors: true });
addFormats(ajv);
const validate = ajv.compile(schema);

const response = await fetch('https://github.com/solana-labs/token-list/blob/main/src/tokens/solana.tokenlist.json')
const listData = await response.json()

const valid = validate(listData)
if (!valid) {
  // oh no!
}
```

I get the following error even when running it on the official token list...
```
file:///home/myware/Downloads/token_list_validation/node_modules/node-fetch/src/body.js:147
		return JSON.parse(buffer.toString());
		            ^

SyntaxError: Unexpected token < in JSON at position 6
    at JSON.parse (<anonymous>)
    at Response.json (file:///home/myware/Downloads/token_list_validation/node_modules/node-fetch/src/body.js:147:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async file:///home/myware/Downloads/token_list_validation/validate_token_list.js:13:18
```

**Comment by topranks** [comment]
Looking at your modified solana.tokenlist.json file it has a new line added at the very end (line 66692).  This is identical to the problem I described so fix that first.  Your JSON has no other syntax errors (or at least Python JSON parser doesn't find any).

I couldn't make VIM not create the newline (apparently to be a valid POSIX file this is needed, and Vim won't allow you to create a invalid one).  So I had to remove the newline character at the end with this perl command before submitting my PR:

    perl -pi -e 'chomp if eof' solana.tokenlist.json

**Comment by Sonicfury** [comment]
For those who face the same issue.

[Prevent Vim from adding new line](https://stackoverflow.com/a/16114535/11584033)

**Comment by keone** [comment]
> For those who face the same issue.
> 
> [Prevent Vim from adding new line](https://stackoverflow.com/a/16114535/11584033)

Thanks @Sonicfury , agreed!
Added this to https://github.com/solana-labs/token-list#error-validating-schema-chainid-conflicting-values-103-and-0
