### ISSUE TITLE
Please Update Token Name for Consistency With Social Media Accounts - PR: #12790

### ISSUE THREAD

**Issue by LegendOfPooShi** [solana-labs/token-list#12811]
Could your team please manually merge in PR: https://github.com/solana-labs/token-list/pull/12790

The Legend Of PooShi Team needs their token name to match their social media accounts' names in order to qualify for certain listings. Unfortunately, we can not change our social media names to PooShi, since it is already taken by someone on most platforms.

Thank you in advance.

**Comment by Flite-Nick** [comment]
We're also hoping to take this opportunity to update our website address within the Solana Token List. This should bring name consistency across all variables associated with us. 

Please let us know if there is anything else we need to provide to you all.

Thank you, again.

**Comment by LegendOfPooShi** [comment]
We're also hoping to take this opportunity to update our website address within the Solana Token List. This should bring name consistency across all variables associated with us. 

Please let us know if there is anything else we need to provide to you all.

Thank you, again.

**Comment by keone** [comment]
merged
