### ISSUE TITLE
Cannot commit changes to token KET

### ISSUE THREAD

**Issue by ketwebb** [solana-labs/token-list#12849]
- **I'm submitting a ...**
  [ ] bug report
  [ X ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Can someone please help me, I have managed to mess up my folk version on token-list and now I have commits to be added, but I made a mistake a reverted my initial submission. Now the folk is a complete mess. I have no idea how to roll back the folk. I was going to delete the repository and start again, but I am assuming that this will remove my ownership of the token. Is that correct? I just wanted to change the image for the token. How do I get back to a version of the folk that will allow me to make the changes?
 
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
<img width="981" alt="Screenshot 2022-01-07 at 16 49 58" src="https://user-images.githubusercontent.com/92038999/148577725-bf8848ad-f9ad-416c-b7dc-1c7065cf4d29.png">

**Comment by keone** [comment]
this issues section is not for issues with using git
