### ISSUE TITLE
Change icon/socials for MILK

### ISSUE THREAD

**Issue by 21e8** [solana-labs/token-list#12888]
- **I'm submitting a ...**
  [ ] bug report
  [ x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Hi, gotta submit an update to the image and meta for $MILK.
https://github.com/solana-labs/token-list/pull/12880
Here is the initial PR https://github.com/solana-labs/token-list/pull/12619

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by 21e8** [comment]
created new branch ... sems to have fixed it... https://github.com/solana-labs/token-list/pull/13026

**Comment by 21e8** [comment]
https://github.com/solana-labs/token-list/pull/13026

this time there is another error

**Comment by keone** [comment]
merged

**Comment by 21e8** [comment]
tyvm
