### ISSUE TITLE
How can i change my tag from social-token to utility-token and community token

### ISSUE THREAD

**Issue by HustlinSharks** [solana-labs/token-list#12937]
how can i change my tags on my solana token from social-token to utility-token,community-token i tried changing the json file and than doing another pull request but it failed because i already am using my token address so it wont change it.

**Comment by HustlinSharks** [comment]
@Kameeno

**Comment by HustlinSharks** [comment]
@keone send help haha

**Comment by keone** [comment]
please link the PR

**Comment by HustlinSharks** [comment]
> please link the PR

https://github.com/solana-labs/token-list/pull/12935

**Comment by HustlinSharks** [comment]
https://github.com/solana-labs/token-list/pull/12935/commits/88e2235323fe0f970a1cfcf22fe4bc31dc0ae34c

**Comment by HustlinSharks** [comment]
https://github.com/solana-labs/token-list/pull/12936


> please link the PR

**Comment by HustlinSharks** [comment]
how do i rebase to the main ive been stuck for hours trying to figure out how to merge my changes with the main branch still no luck @keone

**Comment by HustlinSharks** [comment]
would it be better to just delete my repository and start over fresh?

**Comment by HustlinSharks** [comment]
https://github.com/solana-labs/token-list/pull/13083

need to get this done but just stuck

**Comment by IsNotMyIP** [comment]
I amn trying also to figure out how to do so:
#13131

**Comment by keone** [comment]
> #13083
> 
> need to get this done but just stuck @keone

added comment in PR
