### ISSUE TITLE
Manual update Cry Coin: CoingeckoID

### ISSUE THREAD

**Issue by nomadicmonad** [solana-labs/token-list#13134]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x ] question about how to use this project

- **Summary**

Would it be possible to manually merge our CoinGecko ID update in #13133? thank you!

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
