### ISSUE TITLE
Update GMZA token Logo assest + URI + website 

### ISSUE THREAD

**Issue by AbdallaMalik** [solana-labs/token-list#13212]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [x ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Plz kindly update the logo of the token to the latest logo assest added and its URi also website is added 
thanks in advance 

PR: #13210 

**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
added comment on PR
