### ISSUE TITLE
duplicate token: token address H8bFy62L3ZmUfA3Q4anvneF9nbGjQGce7QTsiXkpCk9y is already used

### ISSUE THREAD

**Issue by HustlinSharks** [solana-labs/token-list#13243]
duplicate token: token address H8bFy62L3ZmUfA3Q4anvneF9nbGjQGce7QTsiXkpCk9y is already used

_Originally posted by @keone in https://github.com/solana-labs/token-list/issues/13083#issuecomment-1008350176_

how do i get passed this or can someone manually merge my changes to the main?

**Comment by akashanova** [comment]
same problem idk..

**Comment by akashanova** [comment]
let me know if you found solution please

**Comment by keone** [comment]
added comment in PR
