### ISSUE TITLE
please help remove X-ID token #13318 from the list

### ISSUE THREAD

**Issue by bahirul** [solana-labs/token-list#13340]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [x] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Please help to remove X-ID token from the list.

- [PR link](https://github.com/solana-labs/token-list/pull/13318)
- Asset folder and link [6RZ1AqT7ENjKy1sCnGW1zXGNboHhsvUFN27MRNqUYpSS](https://github.com/solana-labs/token-list/tree/main/assets/mainnet/6RZ1AqT7ENjKy1sCnGW1zXGNboHhsvUFN27MRNqUYpSS)

**Comment by keone** [comment]
#13468
