### ISSUE TITLE
Add CoinGecko ID for TabTrader Token 

### ISSUE THREAD

**Issue by ymdrkh** [solana-labs/token-list#13363]
- **I'm submitting a ...**
  [ ] bug report
  [*] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Please review https://github.com/solana-labs/token-list/pull/13361

- **Other information** 
Phantom wallet requires CoicGecko id to fetch latest token price

**Comment by keone** [comment]
added in https://github.com/solana-labs/token-list/commit/e75b58ef8d8bd31a759f0ad085ef1e44f7a8a8ae

**Comment by keone** [comment]
merged
