### ISSUE TITLE
added social links to TheSolanDAO token

### ISSUE THREAD

**Issue by thesolandao** [solana-labs/token-list#13370]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Please review [added extensions to TheSolanDAO token #13364](https://github.com/solana-labs/token-list/pull/13364)

- **Other information**
Birdeye requires information from the token-list to show socials

**Comment by keone** [comment]
merged
