### ISSUE TITLE
Token shows up as NFT, please merge fix ASAP

### ISSUE THREAD

**Issue by samogang** [solana-labs/token-list#13396]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Please review this pull request as I found out that the token shows up as a NFT and that was not intended, so I removed the NFT tag!
Token Address: Dd7pji6EruuFPuAxuZG5LwZUdPSzYCTN6NsttrkHeedS
Token Name: SolSamos
Token Symbol: FLUFF
Link to PR: https://github.com/solana-labs/token-list/pull/13387

**Comment by keone** [comment]
merged
