### ISSUE TITLE
duplicate token

### ISSUE THREAD

**Issue by akashanova** [solana-labs/token-list#13399]
I want to change something to an existing coin We've created called Cookie gem. I'm trying to change its decimals. I'm greeted with an error stating 
duplicate token: token address DP9fXAemWm3SGMZ5hE1qNqRBHaaNhEZ9o3aqHUEMBroN is already used

any help is appreciated thank you !

**Comment by keone** [comment]
that means you added another block rather than modifying the existing one

**Comment by akashanova** [comment]
> that means you added another block rather than modifying the existing one

how to i edit exisitng block ?

**Comment by keone** [comment]
it's a text file, edit it in the appropriate place

**Comment by akashanova** [comment]
> it's a text file, edit it in the appropriate place

txt file? is it within solana -labs token list? Any info on how to edit it , and .txt files name ?

**Comment by keone** [comment]
search for `DP9fXAemWm3SGMZ5hE1qNqRBHaaNhEZ9o3aqHUEMBroN` in the unedited version of solana.tokenlist.json.  you will find a json block that already exists. edit that.
