### ISSUE TITLE
Update solana.tokenlist.json #1341

### ISSUE THREAD

**Issue by pukacho** [solana-labs/token-list#1343]
hi I add new token and  I want to change the symbol from WESH to WEHO how I can do this 
the problem we fine another token when this symbol WESHMOON (WESH) and our WeShare (WESH)

**Comment by SolDev-stack** [comment]
Please read the [SPL-token README](https://github.com/SolDev-stack/token-list/blob/main/README.md), and ensure your SPL-token info uses the correct [Uniswap format](https://github.com/SolDev-stack/token-lists/blob/main/README.md).

**Comment by keone** [comment]
please link a PR!
