### ISSUE TITLE
change logo adress / rep closed #13427

### ISSUE THREAD

**Issue by astefanis** [solana-labs/token-list#13474]
- **I'm submitting a ...**
  [x ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Hi, i have entered assets adress by mistake instead of main in the logo url could you please update it for the correct address ?

https://raw.githubusercontent.com/astefanis/HappyX/main/HApexsmall.png 

Thank you for your understanding and sorry for the mess

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by astefanis** [comment]
I am adding a link to my fork : https://github.com/astefanis/token-list/tree/happyx-coin-info

Thnx again

**Comment by keone** [comment]
please submit a PR and link it here

**Comment by astefanis** [comment]
https://github.com/solana-labs/token-list/pull/13518

**Comment by astefanis** [comment]
im not sure if you ment that i changed the url my self then submit the pr so i submited withouth changes.

**Comment by astefanis** [comment]
[astefanis:happyx-coin-info](https://github.com/solana-labs/token-list/pull/13523) 

this is with the changed url. Dont know if i need to do smth else ? ! Sorry, is this okay ?

**Comment by astefanis** [comment]
Im closing this issue and starting a new one with the new PR. Thank you !
