### ISSUE TITLE
Added CoinGeckoID for TheSolanDAO token

### ISSUE THREAD

**Issue by thesolandao** [solana-labs/token-list#13482]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Please merge [added coinGeckoId for TheSolanDAO token #13480](https://github.com/solana-labs/token-list/pull/13480)

- **Other information** 
CoinGeckoID is needed to display value of the token in wallets, in SolScan as well as Birdeye.

**Comment by keone** [comment]
merged
