### ISSUE TITLE
Please Fix logo URI in 2 tokens #13533

### ISSUE THREAD

**Issue by rjdrar** [solana-labs/token-list#13534]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- PR #13533 I am fixing the logo URIs of two tokens and one symbol minor change 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
- This is required for an educational course example in 2 weeks. Thanks in advance

**Comment by keone** [comment]
merged
