### ISSUE TITLE
Change logo url PR #13523

### ISSUE THREAD

**Issue by astefanis** [solana-labs/token-list#13549]
- **I'm submitting a ...**
  [ x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- Please change logo url to correct one submited below. Thank you !
- PR
#13523
 
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
added comment to PR
