### ISSUE TITLE
Change of icon PR #13627

### ISSUE THREAD

**Issue by colinantonell** [solana-labs/token-list#13628]
Could you have a look at the PR #13627, it will fail due to automerge error but it should be fine since it is just a logo change and doesn't break anything. Cheers

**Comment by keone** [comment]
nope, in your diff you also re-added the json block, which causes a duplicate address: https://github.com/solana-labs/token-list/pull/13627/files

**Comment by colinantonell** [comment]
My bad, I re-forked the repo and this time only edited the logo file, hopefully it works now, please have a look in PR #13641

**Comment by keone** [comment]
merged
