### ISSUE TITLE
Logo update 

### ISSUE THREAD

**Issue by benzsteamNFT** [solana-labs/token-list#13658]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
My logo link isn't working, I want to update it to this link :
https://raw.githubusercontent.com/benzsteamNFT/gat/main/logotoken.png

Here is the adress of the token : 99Q3AfFWX3rdidoQCnAPPoZFjsaXr2AAk65RUgxiwfUi
Thank you
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
please link a PR

**Comment by benzsteamNFT** [comment]
the PR : https://github.com/solana-labs/token-list/pull/13560

**Comment by keone** [comment]
merged
