### ISSUE TITLE
PR #13664 Manual Review to Add CoinGeckoID for NANA

### ISSUE THREAD

**Issue by ChimpFight** [solana-labs/token-list#13666]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Hello,

[PR #13664](https://github.com/solana-labs/token-list/pull/13664
) requires manual review to update the NANA coingeckoID. 

If you need any additional information/verification, please let me know

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
