### ISSUE TITLE
Change logo url

### ISSUE THREAD

**Issue by astefanis** [solana-labs/token-list#13676]
- **I'm submitting a ...**
  [ x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
New request to change url logo. The old one had dubble adress entry and was rejected. New url adress https://raw.githubusercontent.com/astefanis/HappyX/main/HApexsmall.png
PR   https://github.com/solana-labs/token-list/pull/13674
Thank you
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
