### ISSUE TITLE
Delete and add tags Mudo token

### ISSUE THREAD

**Issue by Pcheckbox** [solana-labs/token-list#13689]
- **I'm submitting a ...**
  [ ] bug report
  [ x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- Hi. It seems Solflare doesn't want to upload token name and picture because token tag is NFT? Also if you can delete my tags and add: 
"social-token",
        "community-token"
Thank you

**Comment by keone** [comment]
please link a PR

**Comment by Pcheckbox** [comment]
PR #13693
Also added https instead http

**Comment by keone** [comment]
merged
