### ISSUE TITLE
invalid asset path: assets/mainnet/1C2EYVr......

### ISSUE THREAD

**Issue by rianlux20** [solana-labs/token-list#13695]
Pls help me fix that error 
The System counts this as automergeerror 

invalid asset path: assets/mainnet/1C2EYVrwmoXAGbiKirFFBeDFDYUBHPhDeg9trhibTND/nSSud9c8YSNTHVpymRaCPV6qnG8ZDP9mQjpkPXXS6pjgSW4P2d6YBoC8f6WZSc6Q3eBRP9GdMi8oiXWWUjuivsL/t_409_s_letter.jpg

**Comment by keone** [comment]
please link a PR

**Comment by keone** [comment]
but yes, that's an invalid path, you need the full path starting with `https://raw.githubusercontent.com`
