### ISSUE TITLE
Verasaw mint Updated please threat as urgent  thanks

### ISSUE THREAD

**Issue by sollysolana** [solana-labs/token-list#13711]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
verasaw mint updated  ( changed)

#13710  ([13710
](https://github.com/solana-labs/token-list/pull/13710)

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by VerasawOfficial** [comment]
#27997 
https://github.com/solana-labs/token-list/issues/27997

new mints and logo update urgent
