### ISSUE TITLE
Check always fails: Error: Pull request should not contain any deletions.

### ISSUE THREAD

**Issue by grgkro** [solana-labs/token-list#1375]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x] question about how to use this project

- **Summary**
I'm having troublewith my Pull Request. It's set to automerge, but fails one automated test: "Get Changes" -> Error: Pull request should not contain any deletions.
https://github.com/solana-labs/token-list/pull/1106/checks

The line is not deleted by me, it simply happens when you add a token. Git seems to thinks that the last closing bracket was deleted, but I never touched it, it was just of course moved a bit down when I added my token. 
I already tried making a completely new PR, but it's the same then.
![image](https://user-images.githubusercontent.com/56633505/135581868-9bec9bec-0e68-4907-8677-94bdca4b4a17.png)

Another PR from me from last week merged successfully, so I think it's maybe a new bug introduced since then?

Other teams seem to have that problem, too:
https://github.com/solana-labs/token-list/pull/1183/checks?check_run_id=3706929565
https://github.com/solana-labs/token-list/pull/1371/checks?check_run_id=3763304882
https://github.com/solana-labs/token-list/pull/1363/checks?check_run_id=3761079494
...

**Comment by Ektwnl** [comment]
![Screenshot_20211002-081256_Chrome](https://user-images.githubusercontent.com/89343762/135694985-f3b336e9-5b30-48a6-bae6-808243e6a0d2.jpg)

Follow this guy's advice 👍

**Comment by grgkro** [comment]
Worked, thank you. I couldn't manage to get it working in the old Pull Request, so I simply deleted the forked repo and created a new pull request. The cool thing was that I didn't have to wait for approval again, git recognized my changes and immediately did the auto-merge.

**Comment by CEO-NextMindCoin** [comment]
Yes worked with notepad++ on debian Parrotsec. Thanks
