### ISSUE TITLE
Fix logo image PR #13892

### ISSUE THREAD

**Issue by ilov-eu** [solana-labs/token-list#13893]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Need to replace ILOVEU logo image file

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
