### ISSUE TITLE
How to update tokens' info?

### ISSUE THREAD

**Issue by krypt0x** [solana-labs/token-list#1396]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
How to update data/info about a token if the automerge bot doesn't allow deletions?

Thank you

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Please check this PR #1395

**Comment by ciripel** [comment]
I would also like a response to this question. I have PR #1158 since 10 days already and it contains only a simple logo extension change yet can't be automerged due to deletion.

**Comment by andrijaperic** [comment]
I agree with above, I just want to update simple information for my token and I can't auto merge it because it has "deletion" but its actually an edit....

[PR#1468](https://github.com/solana-labs/token-list/pull/1468)

**Comment by fleibfried** [comment]
same question here...

**Comment by ngocbv** [comment]
Same question

**Comment by keone** [comment]
@ngarraud @fleibfried @ngocbv @swts @ciripel feel free to open issues for visibility
