### ISSUE TITLE
Updating UXD Stablecoin

### ISSUE THREAD

**Issue by acamill** [solana-labs/token-list#14015]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I want to update a previously submitted entry for $UXD #14005 
Here is the first PR for it #1498

https://github.com/solana-labs/token-list/pull/14005/files

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
