### ISSUE TITLE
Automerge Failure

### ISSUE THREAD

**Issue by tracy-codes** [solana-labs/token-list#14025]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Automerge failed for an update to token data for the SHDW token. Failure reason is "website line removed", but just a comma was added to the website line. I think this can be manually merged.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

- PR with the automerge failure: https://github.com/solana-labs/token-list/pull/14013

**Comment by tracy-codes** [comment]
@keone tagging for visibility.

**Comment by keone** [comment]
merged
