### ISSUE TITLE
Automerge is not working because it sees a conflict with the main tokenlist (urgent !!)

### ISSUE THREAD

**Issue by kazyon** [solana-labs/token-list#14126]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I have create a new PR with the name https://github.com/solana-labs/token-list/pull/14040 but it's not updating correctly.

Thanks
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
- Issue is that this token needs to be live very soon and the Logo is not showing at all. 
I did an initial PR when i created the token in the tokenlist.solana file and the automerge worked as expected but since the link was not correct i added the logo to the asset/mainnet/tokenaddress and waited. Sadly i have tryied to redo the process by reseting the head to this initial commit but without luck. Token will be live in 3 weeks, can somebody help me out ? the PR needs to add the photo and correct one link, shoul be quite easy. 

Thanks in advance!

**Comment by kazyon** [comment]
can you merge this @keone

**Comment by keone** [comment]
added comment on PR

**Comment by kazyon** [comment]
hello @keone , i tried to rebase the commits with the initial commit as squash but it seems the issue is getting worse, can you help ? token is launching soon

**Comment by kazyon** [comment]
https://github.com/solana-labs/token-list/pull/16728 this is the pull request

**Comment by kazyon** [comment]
hey @keone, i have reforked the repo and seems right now that the issue is solved, there is no other conflict in the file merging. 
this is the pull request, can you check it out and let me know if everything looks ok ? 
https://github.com/solana-labs/token-list/pull/20025

**Comment by keone** [comment]
it looks mostly ok, but the file is huge... we have a 200kb limit on files uploaded.
either:
1. size it down
2. don't include it in the repo at all, as your logoURI is not pointing back to this repo so it's not needed

**Comment by keone** [comment]
merged
