### ISSUE TITLE
Manual Change: The token address. The Dexlab was destroyed.

### ISSUE THREAD

**Issue by shibainusolana** [solana-labs/token-list#14156]
Please change the token address we faced with huge problems 
https://github.com/dexlab-project/assets/issues/72
#14153

**Comment by GemsGame** [comment]
I Approve that actions

**Comment by GemsGame** [comment]
@keone

**Comment by shibainusolana** [comment]
we are available on the Raudium https://birdeye.so/token/5Wgco6reiMwazERpAm3JS1xD7JBHNJJQdNEE9MrUkwtJ

**Comment by shibainusolana** [comment]
@keone please could you take a look at this asap?

**Comment by keone** [comment]
added in https://github.com/solana-labs/token-list/commit/2c6d0c24e5f8bebc30d231522a47bfe762f1df3b
