### ISSUE TITLE
Manual Change - Update logo of KITTY

### ISSUE THREAD

**Issue by MeowCoinSolana** [solana-labs/token-list#14197]
- **I'm submitting a ...**
  [ ] bug report
  [X ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

Hi, 

Automerge of this PR has failed because asset can't be modified => https://github.com/solana-labs/token-list/pull/14179
Can you do a manual review of this PR and approve it ? 

Here is the initial commit made by me to create the token => https://github.com/solana-labs/token-list/pull/3189/

Thanks !

**Comment by keone** [comment]
merged
