### ISSUE TITLE
Update current W token in solana.tokenlist.json 

### ISSUE THREAD

**Issue by WBORSA** [solana-labs/token-list#1425]
` {
      "chainId": 101,
      "address": "UgMdvGuY2HNMmCJQdY6aGty1yDxHBxm9Q9KJVefVjwJ",
      "symbol": "W",
      "name": "W",
      "decimals": 2,
      "logoURI": "https://raw.githubusercontent.com/WBORSA/token-list/main/assets/mainnet/UgMdvGuY2HNMmCJQdY6aGty1yDxHBxm9Q9KJVefVjwJ/W%20Coin.png",
      "tags": [],
      "extensions": {
        "website": "https://app.w.systems/"
      }
    },

Hello Team please update my Token name and Ticker `

**Comment by SolDev-stack** [comment]
Please read the [SPL-token README](https://github.com/SolDev-stack/token-list/blob/main/README.md), and ensure your SPL-token info uses the correct [Uniswap format](https://github.com/SolDev-stack/token-lists/blob/main/README.md).

**Comment by WBORSA** [comment]
Hello thank you for respond , 

the details has been merged but i want to update name and symbol name 

https://explorer.solana.com/address/UgMdvGuY2HNMmCJQdY6aGty1yDxHBxm9Q9KJVefVjwJ


Token name is : W systems
token symbol is : W 

when i follow the formula to make automerge says deletion not allowed so it has to be from your side

**Comment by keone** [comment]
Please link a PR
