### ISSUE TITLE
UPDATE SYMBOL OF FANALYST

### ISSUE THREAD

**Issue by zeddharth** [solana-labs/token-list#14313]
- **I'm submitting a ...**
  [.] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Updated a symbol for Fanalyst, a token for which I placed a pr. 
Please approve this asap
https://github.com/solana-labs/token-list/pull/14314
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by zeddharth** [comment]
@keone please could you take a look at this asap?

**Comment by keone** [comment]
merged
