### ISSUE TITLE
Update Discord Link ISS

### ISSUE THREAD

**Issue by irishsettersol** [solana-labs/token-list#14401]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Hi Team! we change our Discord link. Its will good to make everythink uptodate of our token information. PR link bellow, Thank you!

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
PR Link #14400

**Comment by keone** [comment]
merged
