### ISSUE TITLE
Update coinggeckoId for "SHROOMZ" token

### ISSUE THREAD

**Issue by cryptomushroomz** [solana-labs/token-list#14408]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **i am getting an automerger Error for **failed to normalize: failed to parse JSON: json: unknown field "coingeckoId"**.

Can you tell me how to solve this issue?

Pull [Request:] (https://github.com/solana-labs/token-list/pull/14402) 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged

**Comment by cryptomushroomz** [comment]
Thanks for your quick support.
