### ISSUE TITLE
PR #14416 for adding the coingeckoId to $SVT was rejected by automerger

### ISSUE THREAD

**Issue by exogenesys** [solana-labs/token-list#14419]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Submitted a PR for adding the coingeckoId [14416](https://github.com/solana-labs/token-list/pull/14416) was rejected by automerger.

Please, help merging the PR.

Thanks a lot!

**Comment by shibainusolana** [comment]
@exogenesys you are must fix the formatting

**Comment by shibainusolana** [comment]
yes

**Comment by keone** [comment]
merged

**Comment by exogenesys** [comment]
Hey @keone – Thanks a lot for merging the issue within 12 hours!

However, the coingeckoId has been committed to a wrong token accidentally. (Since Solvent has a lot of tokens, I got confused 😅) 

To fix it, I've pushed another PR. (https://github.com/solana-labs/token-list/pull/14687) It'd be great if you could merge it as well.

Thanks a lot for your help! :)

**Comment by keone** [comment]
k
