### ISSUE TITLE
cant update coin

### ISSUE THREAD

**Issue by jrwesty23** [solana-labs/token-list#14434]
i am trying to remove excess tags from LION coin.

auto merger keeps saying found line removed. cannot New auto merge. 

i had to remove my original fork and start again, what options do i have to remove tags?

**Comment by shibainusolana** [comment]
You are can't delete any lines without manually approve.

**Comment by jrwesty23** [comment]
having difficulty finding the MR option. Can you point me in the right direction?

**Comment by shibainusolana** [comment]
![image](https://user-images.githubusercontent.com/95247974/149783017-6634ce07-04c0-448b-842c-16b56c454918.png)

**Comment by jrwesty23** [comment]
https://github.com/solana-labs/token-list/pull/14357

i have created another pull, is this what i would need to do?

**Comment by shibainusolana** [comment]
@jrwesty23 this all what you need, wait when that will be merged

**Comment by jrwesty23** [comment]
yes all the tags removed besides "social-token", thank you.

**Comment by jrwesty23** [comment]
sorry last question. average time to complete MR?

**Comment by shibainusolana** [comment]
@jrwesty23 i don't know, i wait  when @keone help me

**Comment by keone** [comment]
merged
