### ISSUE TITLE
Update Tigercoin Information - ADD coingeckoId 

### ISSUE THREAD

**Issue by soldev81** [solana-labs/token-list#14447]
Hi Team , 
I need to update Tiger Coin Information 
ADD coingeckoId  tiger-coin

Please help us to merge this request
https://github.com/solana-labs/token-list/pull/14441

First Tiger Coin commited at 
https://github.com/solana-labs/token-list/pull/7930/files
 

Our token already listed on COINGECKO 
https://www.coingecko.com/en/coins/tiger-coin

Token address 
8z4ghJPp3ccvEtuXZbceGRfoX7AZHhcdwiapYzmsxmyC

Token name
TIGER COIN (TIGER)

**Comment by keone** [comment]
merged
