### ISSUE TITLE
Changes Not Reflected on Solscan - (PR #14449)

### ISSUE THREAD

**Issue by nickrawlings2012** [solana-labs/token-list#14481]
Thanks @keone , I can see that the changes have been made on the Solana token list but my search on solscan for Kalia does not reflect the current changes - 8Wf4RCoeBsnjaWuSP8Z2uNKyBjjCVumLhAkpzDcTw175

Can you please advise

**Comment by keone** [comment]
it looks okay now? i think there's just a delay
https://solscan.io/token/8Wf4RCoeBsnjaWuSP8Z2uNKyBjjCVumLhAkpzDcTw175
