### ISSUE TITLE
Is https://explorer.solana.com working?

### ISSUE THREAD

**Issue by DODGsh** [solana-labs/token-list#1454]
Is https://explorer.solana.com working?
I haven't been able to access for a few days.

**Comment by Aadhinana** [comment]
Yes it is.

**Comment by Ektwnl** [comment]
> Yes it is.

Me and some people on solana discord have problem to connect on that site.
I can visit that site but just can see the black balnk.
Can you figure out the problem?
And the Phantom wallet works unproperly.
:(

**Comment by Ektwnl** [comment]
It fixed! but still there is some probs.
I can see my token logo on mobile but not shown on labtop
