### ISSUE TITLE
Modified CLK token icon #14550

### ISSUE THREAD

**Issue by ilov-eu** [solana-labs/token-list#14551]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- Need to change CLK token icon in PR #14550

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
