### ISSUE TITLE
Need to merge open PR with extensions updates

### ISSUE THREAD

**Issue by javmeister** [solana-labs/token-list#14570]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Need to merge an open PR that adds several entries to both our Tokens extensions: #14562 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Original PR merging `SINGULARITY` token, for ownership: #4775
Original PR merging `VELORUM` token, for ownership: #11648

Thanks!

**Comment by keone** [comment]
merged
