### ISSUE TITLE
Delete an invalide token entry

### ISSUE THREAD

**Issue by bruspal** [solana-labs/token-list#14592]
- **I'm submitting a ...**

    [ ] bug report
    [ ] feature request
    [ ] question about the decisions made in the repository
    [X] question about how to use this project

- **Summary**
  Removing invalide entry

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Hello,

I did a mistake using my spl-account address instead of the token address while adding my token. I tried to change the address but automerge failled.
I finally change the name and symbol of my token.
Name : "Bruspal Coin" to "Bruspal Copper"
Symbol : BRSC to BRUSPAL

In order to helps to reduce bad entries in the file could you remove this entry ?
If you need more detail here are my PR :

- https://github.com/solana-labs/token-list/pull/14243#issue-1104970658
- https://github.com/solana-labs/token-list/pull/14260#issue-1105018164

Many thanks

**Comment by keone** [comment]
merged #14676 14676
