### ISSUE TITLE
fix invalid token SILU #14606

### ISSUE THREAD

**Issue by rjdrar** [solana-labs/token-list#14607]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
required to replace toke SILU by QRYES in PR #14606

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
