### ISSUE TITLE
replacing the address for Krabby kooks token

### ISSUE THREAD

**Issue by ODENSAMAOG** [solana-labs/token-list#14649]
- **I'm submitting a ...**
  [ ] bug report
  [x ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
would like to replace the address to krabby kooks token. the old address has been lost and need to be replaced. #14646
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
#14969
