### ISSUE TITLE
Change name from Oink Token to Oink Coin

### ISSUE THREAD

**Issue by kakazgg** [solana-labs/token-list#14724]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- I wish to change the name of Oink Token to Oink Coin, I submitted a PR but it could not be automatically merged.
- From this:
-    {
      "chainId": 101,
      "address": "BZ1DeqbMzf3RKkAJdG2CuY27CgXqC35qca48dfUCf27T",
      "symbol": "COINK",
      "name": "Oink Token",
      "decimals": 0,
      "logoURI": "https://cdn.jsdelivr.net/gh/kakazgg/solswineslogo/SolSwines-OINK-Token_gold.png"
    },

To this:
 {
      "chainId": 101,
      "address": "BZ1DeqbMzf3RKkAJdG2CuY27CgXqC35qca48dfUCf27T",
      "symbol": "COINK",
      "name": "Oink Coin",
      "decimals": 0,
      "logoURI": "https://cdn.jsdelivr.net/gh/kakazgg/solswineslogo/SolSwines-OINK-Token_gold.png"
    },

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
- https://github.com/solana-labs/token-list/pull/14712
- PR:14712

**Comment by keone** [comment]
merged
