### ISSUE TITLE
update phant token info

### ISSUE THREAD

**Issue by WhiteElephantEco** [solana-labs/token-list#14721]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
please accept my update phant info thank you, i add this info: https://github.com/solana-labs/token-list/pull/14720

"coingeckoId": "phant",
        "coinmarketcap": "https://coinmarketcap.com/currencies/phant/",
        "serumV3Usdc": "9GWz5exH52JAHhe4MyKmo96SRAJy96ZKhEpqrnbVzYqU",

**Comment by keone** [comment]
merged
