### ISSUE TITLE
fix CLK icon PR #14784

### ISSUE THREAD

**Issue by ilov-eu** [solana-labs/token-list#14785]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- need to replace the icon PR #14784

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
in the future it'd help to link the commit/PR where you added the token originally
