### ISSUE TITLE
Manual review of token replacement needed

### ISSUE THREAD

**Issue by tonyboylehub** [solana-labs/token-list#14810]
PR: https://github.com/solana-labs/token-list/pull/14803

Assuming this is going to be Keone as usual. Ta for the hard work you put in here doing these issue reports! Need a manual review/update for a clients token that was pushed up earlier.

> This is a pull update to replace a token which was given to me by a client earlier that I had pushed up earlier in the day.
> The token is for NFT Candymachine whitelist which requires a token of 0 decimals of which that token wasn't set up with, so new one has been created for the project.
> 
> Old token (9 decimals) - D77wfRvxzFgdAHd1C1gE5JuwuSq4QLSTxc3huB52WBXH
> https://explorer.solana.com/address/D77wfRvxzFgdAHd1C1gE5JuwuSq4QLSTxc3huB52WBXH
> 
> New Token (0 decimals) - 48A1pXHvottXTf954CMhZyoG7MdFjngLJCDKJS6iJUth
> https://explorer.solana.com/address/48A1pXHvottXTf954CMhZyoG7MdFjngLJCDKJS6iJUth

**Comment by numisman** [comment]
A perfect issue report, kind sir.  Props.
