### ISSUE TITLE
Logo URI fix  PR#14884

### ISSUE THREAD

**Issue by BEN1199** [solana-labs/token-list#14886]
- **I'm submitting a ...**
  [ *] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

I used an Arweave link for the logoURI in the token list but the logo does not appear on solscan or solana block explorer.
The token image is also uploaded in asset folder. Would you kindly fix this? Thanks!
"address": "2Hei1NUr23AyyG4rszQQysRkuQyvr2Z2EjHWVf8ZqjAS",
"symbol": "OLIVEBRANCH",
"name": "PEACE COIN ",
"decimals": 0,
"logoURI": "https://arweave.net/2X3Xh19ThGDQbQ6F9OULg5uO35N1dNI3rvxDFtCFWTc",
"tags": [
"NFT",
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
added comment in #14884

**Comment by BEN1199** [comment]
Thanks
