### ISSUE TITLE
ADD COINGECKO ID

### ISSUE THREAD

**Issue by soldev81** [solana-labs/token-list#14902]
Hi Team ,
I need to update Baby Tiger Information 
ADD coingeckoId babytigergold 

Please help us to merge this request
#14900

First Baby Tiger commited at
https://github.com/solana-labs/token-list/pull/8831/files

Our token already listed on COINGECKO
https://www.coingecko.com/en/coins/babytigergold

Token address
8JjBJdV73zPPmZvkgC91ni8RsbXWTkhpuSdxeZgaw6hD

Token name
Baby Tiger  (BABYTIGER)

**Comment by keone** [comment]
merged
