### ISSUE TITLE
Changing name of token #14769

### ISSUE THREAD

**Issue by Shreddedapes** [solana-labs/token-list#14912]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

first we have submitted the wrong token name in the pull request  , we have pulled another request in which the token name was changed ,we wanted to merge this commit, kindly merge it.

https://github.com/solana-labs/token-list/pull/14769/commits/

**Comment by keone** [comment]
added comment on PR

**Comment by malikh36** [comment]
sorry for again bothering you,what actually needed is to change the name of token to 'WHEY' is it possible to remove the token information Shreddedapes , so that we can create a new pull request with everything right

**Comment by keone** [comment]
as mentioned in the PR:
>this re-adds a new block for 5fTwKZP2AK39LtFN9Ayppu6hdCVKfMGVm79F2EgHCtsi instead of modifying the existing one: see https://github.com/solana-labs/token-list/pull/14769/files

starting from the current HEAD of main, you need edit solana.tokenlist.json, searching for `5fTwKZP2AK39LtFN9Ayppu6hdCVKfMGVm79F2EgHCtsi` and modifying that block
