### ISSUE TITLE
Changing Token Name #14769

### ISSUE THREAD

**Issue by Pengucci** [solana-labs/token-list#14913]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

first we have submitted the wrong token name in the pull request  , we have pulled another request in which the token name was changed ,we wanted to merge this commit, kindly merge it.

https://github.com/solana-labs/token-list/pull/14769/commits/

**Comment by malikh36** [comment]
your comment "this re-adds a new block for 5fTwKZP2AK39LtFN9Ayppu6hdCVKfMGVm79F2EgHCtsi instead of modifying the existing one: see https://github.com/solana-labs/token-list/pull/14769/files"

adding the new block will also works , if you please  do that.
