### ISSUE TITLE
I try add official website to existing token - need help

### ISSUE THREAD

**Issue by in3bit** [solana-labs/token-list#14927]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

I try add official website url: addo-family.com to existing ADDO token but Automerge not work with this, and please help!

My Commit is still opened in Pull request with subject:  
**Adding website #14921**

**Comment by in3bit** [comment]
My Commit is still opened in Pull request with subject:  
**Adding website #14921**

**Comment by keone** [comment]
merged

**Comment by in3bit** [comment]
Thanx @keone ;-)
