### ISSUE TITLE
Help merging update PR

### ISSUE THREAD

**Issue by white-stripes** [solana-labs/token-list#14960]
- **I'm submitting a ...**
  [ ] bug report
  [x ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Please help me merge this PR on updating token Logo icon - i was the author who added SIM to the token list 👍 
https://github.com/solana-labs/token-list/pull/14272

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
