### ISSUE TITLE
auto merge pull request failed #14973

### ISSUE THREAD

**Issue by Pengucci** [solana-labs/token-list#14975]
- **I'm submitting a ...**
  [x ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

 kindly merge this    'https://github.com/solana-labs/token-list/pull/14973'

**Comment by keone** [comment]
merged
