### ISSUE TITLE
Failed to  change website extension

### ISSUE THREAD

**Issue by franckmandon** [solana-labs/token-list#15146]
- **I'm submitting a ...**
  [ ] bug report
  [*] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I was willing to change the website address extension of my token.
I have created a new PR with the name "Changed Website Extension" #15106.
This request seems not to be eligible for automerge, ... still It wasn't about duplicating the token.

What should I do to push this change from my repository to the main without an "automerge error" ?
Thanks for your help.

**Comment by keone** [comment]
added comment on PR
