### ISSUE TITLE
Image assets `404 Not Found`

### ISSUE THREAD

**Issue by milorue** [solana-labs/token-list#15327]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

-  When my images were in this pr: https://github.com/solana-labs/token-list/pull/15313 they were fine but once the images were merged they are `404 not found` I can upload the images again here:

![starmonke](https://user-images.githubusercontent.com/3159469/150668448-10bf5d3c-7807-4622-ab75-3362816a0c99.png)

![whitelistmonke](https://user-images.githubusercontent.com/3159469/150668459-57601608-df29-4136-9e81-27f9bb84fec8.jpg)

**Comment by keone** [comment]
very strange
https://github.com/solana-labs/token-list/commit/74d5914d770d2f7c9665346aa3689f31889ebd5a
vs
https://github.com/solana-labs/token-list/pull/15313/files

**Comment by milorue** [comment]
has this been resolved yet @keone ?

**Comment by milorue** [comment]
Any update on this ticket @keone we are about to airdrop these tokens to wallets this week and trying to square away this small bit. Thanks for the help in advance :D

**Comment by keone** [comment]
i'm not sure, i agree it is strange that this commit that landed in our repo:
https://github.com/solana-labs/token-list/commit/74d5914d770d2f7c9665346aa3689f31889ebd5a#diff-9307f15841e180dd54a21e613a792ac19428f225ba2c1275de16147aa33f1609
has the images as tiny files

whereas the PR seems to summarize the commits as actually adding the files: https://github.com/solana-labs/token-list/pull/15313/files

my suggestion would be to upload the two images to your own repo (doesnt have to be a repo of the whole token-list, just a repo containing those images) and then push a PR to this repo changing the imageURI to that repo.  that way you control the content yourself and can be sure that it lands.

if you do that, link the PR here and i'll review asap

**Comment by milorue** [comment]
sure will do rn one sec

**Comment by milorue** [comment]
thanks so much @keone here is the pr https://github.com/solana-labs/token-list/pull/17069

**Comment by keone** [comment]
merged, thanks and sorry for the inconvenience

**Comment by milorue** [comment]
Thanks man u da best
