### ISSUE TITLE
Issue adding SLYM Coin 

### ISSUE THREAD

**Issue by MB3ll** [solana-labs/token-list#1536]
*I submitted a Pull Request (about 6 weeks ago now) to add a new coin, logo and related info to the network.
- 
-   [ ] bug report
  [ ] feature request
  [X] question about the decisions made in the repository
  [ ] question about how to use this project

My initial pull request was rejected. I deleted it, started the process again and believe i did everything correctly on my second attempt. The PR still hasn't been responded to, it's been 22 days since my second submission. 

Is this normal? If not, how can i proceed?

Thanks in advance

**Comment by SolDev-stack** [comment]
Please read the [SPL-token README](https://github.com/SolDev-stack/token-list/blob/main/README.md), and ensure your SPL-token info uses the correct [Uniswap format](https://github.com/SolDev-stack/token-lists/blob/main/README.md).

**Comment by keone** [comment]
There are just too many PRs due to so many people creating new coins
Please link your PR and someone will try to get to it

**Comment by MB3ll** [comment]
Hi,

My PR is linked below:

https://github.com/solana-labs/token-list/pull/974

Thanks
