### ISSUE TITLE
Changed Logo URL for SDO Token (Please merge)

### ISSUE THREAD

**Issue by thesolandao** [solana-labs/token-list#15487]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
[Changed logo url for SDO token.](https://github.com/solana-labs/token-list/pull/15486)

- **Other information** 
Logo url destination is changed. Please merge the PR.

**Comment by keone** [comment]
merged
