### ISSUE TITLE
Update token mints for devnet, automerge failing 

### ISSUE THREAD

**Issue by 0xDEADBEEFx** [solana-labs/token-list#15524]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Hey, I'd like to update the mint address for FAB, fUSD, fURA and fXAU on devnet.  PR opened at https://github.com/solana-labs/token-list/pull/15505 however validation seems to fail due to replacing the mint. 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
