### ISSUE TITLE
Can't add serumV3Usdc and coingeckoId

### ISSUE THREAD

**Issue by philippfo9** [solana-labs/token-list#15530]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
For a token, I want to add the coingeckoId & serumV3Usdc in the extensions object.
But there is always an automerge error stating serumV3Usdc is an unknown field: https://github.com/solana-labs/token-list/pull/15413

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
squashed and merged
