### ISSUE TITLE
XART token update failure

### ISSUE THREAD

**Issue by DMW-11** [solana-labs/token-list#15567]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x] question about how to use this project

- **Summary*
I made made an update to my token to change the address which and token symbol but this pull request has not been merged for almost 4 weeks. Is anyone able to help me address this please, next phase of our project is to link the Token to our NFT project

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
Pull request details below;
https://github.com/solana-labs/token-list/pull/12674

**Comment by keone** [comment]
squashed and merged
