### ISSUE TITLE
Trying to update a token issues

### ISSUE THREAD

**Issue by dc215007** [solana-labs/token-list#15663]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ x] question about how to use this project

- **Summary**
I'm trying to update my token's icon image and misc info (website, twitter), but can't figure out how or what I'm doing wrong.  PR #15300 error was "unsupported file modified: /dev/null".  Not sure how to update token.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by tongtongchain** [comment]
Can you please tell me how I can update logo URL in the JSON file? I did PR but it failed, do we need to follow some other way?

**Comment by keone** [comment]
yes, it needs to be manually merged

@dc215007 i see you closed the PR and deleted the source branch; please reopen and link the PR here and it can be merged manually

**Comment by dc215007** [comment]
Thank you @keone I redid the PR #15828 please manually merge.  Thank you so much.

**Comment by keone** [comment]
added comment in PR

**Comment by dc215007** [comment]
@keone Corrected the issues, thanks again for all your help.

**Comment by keone** [comment]
merged

**Comment by dc215007** [comment]
Sorry to bother you @keone but when I was checking on the results of this PR it was showing as closed instead of merged and I hadn't seen the changes effected - do I need to wait longer or did I mess up the PR?

**Comment by keone** [comment]
hm you're right, i must have accidentally merged it.  can you please reopen that PR?  (i think you deleted the branch so i cant reopen it easily)

**Comment by dc215007** [comment]
@keone No problem, thanks again for all your help.  Had to redo it, new PR #15990

**Comment by keone** [comment]
merged
