### ISSUE TITLE
I can't change TTCL logo url

### ISSUE THREAD

**Issue by tongtongchain** [solana-labs/token-list#15740]
- **I'm submitting a ...**
  [X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ X] question about how to use this project

- **Summary**
i'm trying to update the TTCL token url logo but automerge gives me error of "deleting".

can you please update the token logo url to this new one:
https://raw.githubusercontent.com/tongtongchain/token-list/main/assets/mainnet/E5xCoBy9pCNjtZHGjD57j498YidLh41sihnu6rSghJkr/ttcllogo.png

PR URL: https://github.com/solana-labs/token-list/pull/15745

token name: TTCL Token
token: E5xCoBy9pCNjtZHGjD57j498YidLh41sihnu6rSghJkr
- **Other information**

**Comment by tongtongchain** [comment]
@keone  I checked several issues/PR requests automerge issue and saw that you do manual updates if there is issue like mine. If possible please check this issue too. I saw that you asked to link PR in other PR issue, so I liked that too. Thank you

**Comment by keone** [comment]
squashed and merged
