### ISSUE TITLE
Update UXD Stablecoin icon/coingeckoId & UXP (UXD Protocol Token) icon

### ISSUE THREAD

**Issue by 0xCryptoSheik** [solana-labs/token-list#15782]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

  - #15780

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
