### ISSUE TITLE
Updating name and tags

### ISSUE THREAD

**Issue by acecard15** [solana-labs/token-list#15872]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Updating name and tags**

- **hello.. me i change the name of CommonXCoin) to CommonXCoin without " ) " typo..and add more tags
this is the address "2q39pHwFJUURyfypPaGgW2Y87pmAkj8iC8DV4z3DF19D"

**Comment by keone** [comment]
please link a PR

**Comment by acecard15** [comment]
hello.. #16065

**Comment by acecard15** [comment]
updating Name and add Tags #16065

**Comment by immacrypt** [comment]
@keone.. please allow him to make changes.. thank you for the noticed..

**Comment by keone** [comment]
merged
fyi most of those tags dont do anything
