### ISSUE TITLE
Critical Update: PHY tag edits + CoinGeko API

### ISSUE THREAD

**Issue by arkitoure** [solana-labs/token-list#15882]
Requesting merge of #15874 to Update PHY token - Modify tags + Add CoinGeko API id.

**Comment by arkitoure** [comment]
trying an automerge again with deleted tag 'health' added back. if seen before or after this action please take into account this change.

**Comment by keone** [comment]
merged
those tags dont do anything FYI

**Comment by arkitoure** [comment]
thx! strange thing about the tags....we had 'nft' listed in the tags a few versions back and phantom wallet pushed the token into the nft/collections section. Once removed it was listed in the wallet normally. I will drop the newly added tags on the next pull.
