### ISSUE TITLE
Please help to approve the PR to updating BIT token details 

### ISSUE THREAD

**Issue by 0xjordyV** [solana-labs/token-list#15897]
- **I'm submitting a ...**
  [ x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Please help to approve the PR to updating BIT token details. 
Changes: Decimals changed, and tag removed
Thank you very much.
#15896 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
