### ISSUE TITLE
Update SGW

### ISSUE THREAD

**Issue by Fiverr-Coin-Hunter** [solana-labs/token-list#16031]
Please approve. I've updated the Token Address on token details.
First PR #16006
Updated PR #16034

Thank You.

**Comment by Fiverr-Coin-Hunter** [comment]
Can you merge this @keone
Thank You.

**Comment by keone** [comment]
merged

**Comment by Fiverr-Coin-Hunter** [comment]
Thank You Very Much.

**Comment by Fiverr-Coin-Hunter** [comment]
> merged

Thank You Very Much. @keone
