### ISSUE TITLE
Updating existing entry.

### ISSUE THREAD

**Issue by page18** [solana-labs/token-list#16050]
- **I'm submitting a ...**
  [ ] bug report
  [x ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I used the wrong address for my token (used token account address instead of token address). Updated asset location and existing entry. Could someone help me approve the PR:

https://github.com/solana-labs/token-list/pull/16021

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
