### ISSUE TITLE
Issue solved  - Pull request failing with two different file types in same row (not connected at all to my listing)

### ISSUE THREAD

**Issue by Aqualibre** [solana-labs/token-list#16061]
@keone please attend to this issue PR #16024
I submitted a pull request that was accepted for automerge 

An automerge error came back regarding my image file (logo) linked to assets/main 
I updated this and committed changes 

Automerge approved - then at next batch run,  automerge bot returned the error of a totally unrelated token right at the top of the main list 
as follows: 

found removed line: - "logoURI": "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/CbNYA9n3927uXUukee2Hf4tm3xxkffJPPZvGazc2EAH1/logo.png",

This listing occurs at line 60 in the token list?? removed apparently occurs at line 66 in token list.
I have not edited anything at all in this line or any other lines at all 
I had no deleted line issues on first commit - so this is very strange 
and confirmed that I had only made 2 changes My token to assets/main (+Image) and addition of my token to json token list.

PLEASE NOTE THE FILE ON MY FORK AND THE ORIGINAL ARE DIFFERENT 
AT LINE 66 ??  ONE IS LISTED AS A .PNG AND THE OTHER .SVG

I checked again today they are now identical? so something strange has happened???
I will need  a  Manual merge as the Automerge Bot - is failing here at an unrelated line to my token add in. 

Please investigate & correct at your earliest chance 
Please see comparison of Solana-token list & My token list at line 60 where is error is supposed to be at line 66? 
The lines look the same line by line until you look at the file type. On the Solana list I pulled down its shows as a .SVG 
On My List its shows as a .PNG   How can this now be different as They are supposed to be the same lists?  

![Solana-token-list line 60](https://user-images.githubusercontent.com/96826689/151549162-33b03c81-f5e1-468a-a51c-7a534d4e7879.png)

![My Token list-line 60](https://user-images.githubusercontent.com/96826689/151549190-eb31b663-8046-474e-a6aa-c84c626640e4.png)

**Comment by keone** [comment]
look at your diff: https://github.com/solana-labs/token-list/pull/16024/files
it's massive
the check is appropriately failing, your diff should be minimal (should just be adding your one token)

**Comment by Aqualibre** [comment]
@keone, yes I saw that diff as well.

It only happened after I committed pull request and wasn't present when I made changes? at "compare across fork" stage
 
Other factors: I deleted a previous fork from my repository because of line earlier "no newline found" recurring error, I then requested new fork, solved the "no newline" error and got an automerge confirm this. (there was +61 -0 when I did this automerge, when merge happened it did this mass line deletion? 
 
What's the best solution: Should I close this pull request and start a new fork and make new submission? 
Will this cause a duplication of token submission to main branch, if I re-submit another pull request, after closing this one?

Thanks for highlighting the problem

**Comment by keone** [comment]
> What's the best solution: Should I close this pull request and start a new fork and make new submission?

Yes.  or rebase to main, but probably easiest to just fork from the HEAD of main

> Will this cause a duplication of token submission to main branch, if I re-submit another pull request, after closing this one?

Nope

**Comment by Aqualibre** [comment]
> > What's the best solution: Should I close this pull request and start a new fork and make new submission?
> 
> Yes. or rebase to main, but probably easiest to just fork from the HEAD of main
> 
> > Will this cause a duplication of token submission to main branch, if I re-submit another pull request, after closing this one?
> 
> Nope

Cool. Thanks. I will close my PR and do a new fork from main.

**Comment by Aqualibre** [comment]
@keone 

I successfully created new fork from main and listed token 16 lines 0 deletions (diffs) 
Despite this it wont automerge 

Please see attached thanks!
![New PR](https://user-images.githubusercontent.com/96826689/151702814-7afd7cca-23e2-4afb-9e22-a675e657146d.png)

**Comment by Aqualibre** [comment]
This issue was solved; I found that there was conflict caused by google chrome when using the web based Visual basic emulator for GitHub. Switching to Microsoft edge immediately solved the conflict and the errors stopped when I applied code for automerge to main branch - automerge approved.
