### ISSUE TITLE
Update Nosana token , automerge fails. Help

### ISSUE THREAD

**Issue by sjoerd-dijkstra** [solana-labs/token-list#16107]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

We're trying to update our token, but the automerge fails 👉 https://github.com/solana-labs/token-list/pull/13168

I'm a contributor to the Nosana project, and we like to add the `coingeckoId`, as well as update the logo because the current logo does no work well with many dApps (it's squared , rather than round).

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

n/a

Thanks for your review and consideration 🙏

**Comment by keone** [comment]
merged

**Comment by sjoerd-dijkstra** [comment]
thanks @keone !
