### ISSUE TITLE
Update LSTAR address

### ISSUE THREAD

**Issue by danilagarev** [solana-labs/token-list#16119]
- **I'm submitting a ...**
  [ ] bug report
  [*] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

Please approve. I've updated the Token Address on token details.
Updated PR #16115 

Thank You.

**Comment by keone** [comment]
merged
this is the 2nd address change on this same token, pls make up your mind :)

**Comment by danilagarev** [comment]
Thanks!
Sorry my boss changed his mind :(

**Comment by danilagarev** [comment]
> merged this is the 2nd address change on this same token, pls make up your mind :)

Thanks!
Sorry my boss changed his mind :(
