### ISSUE TITLE
Need Help Updating a Token Name

### ISSUE THREAD

**Issue by Cyborg360** [solana-labs/token-list#16173]
- **I'm submitting a ...**
  [ x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- Need help merging my PR
- PR [15970](https://github.com/solana-labs/token-list/pull/15970)

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
this commit has extraneous edits to other files: https://github.com/solana-labs/token-list/pull/15970/files

**Comment by Cyborg360** [comment]
Done, how about now

PR https://github.com/solana-labs/token-list/pull/16373

**Comment by keone** [comment]
good; merged
