### ISSUE TITLE
Token list does not have duplicate entries

### ISSUE THREAD

**Issue by k666-bit** [solana-labs/token-list#16170]
- **I'm submitting a ...**
  [ X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Just trying to update new social links, but the automerge fails , saying "Token list does not have duplicate entries".

here is the pull request https://github.com/solana-labs/token-list/pull/16160

**Comment by keone** [comment]
this commit re-adds the same block instead of modifying the existing one: https://github.com/solana-labs/token-list/pull/16160/files

**Comment by k666-bit** [comment]
> this commit re-adds the same block instead of modifying the existing one: https://github.com/solana-labs/token-list/pull/16160/files

Thank you. I redid it and now it's showing that coingeckoId isn't known? Has it been changed since?

https://github.com/solana-labs/token-list/pull/16375

**Comment by keone** [comment]
that error is misleading, it just means it needs to be manually merged
merged
