### ISSUE TITLE
Can not update data

### ISSUE THREAD

**Issue by CompendiumFi** [solana-labs/token-list#16220]
- **I'm submitting a ...**
  [X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Hello so we made a pull request and it went into all the test , however it didn't merge because I added a line , 
this is the pull request [https://github.com/solana-labs/token-list/pull/16206](url).
please let me know if .
Thank you 
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
https://github.com/solana-labs/token-list/pull/16206

**Comment by keone** [comment]
merged
