### ISSUE TITLE
Need to add coingeckoId "run" to RUN token 

### ISSUE THREAD

**Issue by runnode** [solana-labs/token-list#16300]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- I need to update RUN token to have a coingeckoId of "run". I tried a Pull request but realize you need a manual review to add it. Thank you so much!

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
squashed and merged https://github.com/solana-labs/token-list/pull/16293
