### ISSUE TITLE
Manual Change: Logo Update

### ISSUE THREAD

**Issue by ByteLock** [solana-labs/token-list#16331]
- **I'm submitting a ...**
  [ x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Im having issues updating the link for the image / logo of the asset

[Github PR Link](https://github.com/solana-labs/token-list/pull/16319#issue-1118352608)

**Comment by keone** [comment]
merged
