### ISSUE TITLE
Automerge Error

### ISSUE THREAD

**Issue by jiqqaman** [solana-labs/token-list#16380]
- **I'm submitting a ...**
  [x ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
wrong token address was used, trying to update to correct token

PR Link: https://github.com/solana-labs/token-list/pull/16376

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
