### ISSUE TITLE
Pull Request needs a maintainer?  Making sure I don't need to do anything else.

### ISSUE THREAD

**Issue by kidph** [solana-labs/token-list#16428]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x ] question about how to use this project

I'm new to this and made a pull request about 3 hours ago.  It says it needs a maintainer to review it?  Is that an actual person that must approve it and thus will take longer?  I'm not in any hurry, I just more or less want to make sure I'm not required to do anything further.

https://github.com/solana-labs/token-list/pull/16397

Thank you!

**Comment by keone** [comment]
please leave the issue open so that the bot can run automated checks

**Comment by kidph** [comment]
I found my error and closed the pull request but forgot to close this issue.  My apologies.
