### ISSUE TITLE
Can't update logo URI path

### ISSUE THREAD

**Issue by BlockchainWizard** [solana-labs/token-list#16440]
- **I'm submitting a ...**
  [ ] bug report
  [ X] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I have tried several times to update the logo on this token. First I deleted the old png file from the asset list and added a new one with an updated logo URI. Then I left the only image and just updated the new logo URI. This time I uploaded a new png and changed the logo URI. All approaches have failed.

Please let me know how I can update a logo URI going forward.

Here is the latest PR(https://github.com/solana-labs/token-list/pull/16433)

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
yes, it requires manual merge

merged

**Comment by BlockchainWizard** [comment]
> yes, it requires manual merge
> 
> merged

Ok, good to know going forward. I appreciate your help.
