### ISSUE TITLE
How do I update a token that needs a new name?

### ISSUE THREAD

**Issue by numisman** [solana-labs/token-list#16455]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [X ] question about how to use this project

- **Summary**
I created a token but the name has to be changed.  How should I make the changes to allow this to occur?  Do I need a maintainer to do a manual merge?
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by numisman** [comment]
One other note - we CANNOT lose the symbol

**Comment by keone** [comment]
yes, submit a PR and then link it here

**Comment by numisman** [comment]
https://github.com/solana-labs/token-list/pull/16759

Thanks @keone.  Please give me an ETA so that I can alert my client.

Thanks!

**Comment by numisman** [comment]
Hey @keone where are we with this one?  I need to give my client an update.

https://github.com/solana-labs/token-list/pull/16759 again is the link to the PR

**Comment by numisman** [comment]
Thanks so much @keone for the assist!  How long before the change is reflected on SolScan?
