### ISSUE TITLE
Who approves the pull requests?

### ISSUE THREAD

**Issue by calboru** [solana-labs/token-list#1645]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [x] question about the decisions made in the repository
  [ ] question about how to use this project

Who approves pull request for the new token list? Is this automated? Or a real person or people approving it?

**Comment by sahityakumarsuman** [comment]
I also wants to know it as its been so long i have submitted my token to the list and still its not merged with main branch

**Comment by 9thwall** [comment]
Is this the only way to add a token? 
Seems like this is no longer managed.

**Comment by armyofda12mnkeys** [comment]
is it just me or is the .json file format invalid now?
like right around here in the main branch (the array stops, but other people still putting their chainId's but aren't enclosing them in an object anymore ):
![image](https://user-images.githubusercontent.com/410112/140669361-8d987695-4197-4ff3-886c-ee7c2cb16081.png)

**Comment by samoboyz** [comment]
The devs have rug-pulled boys. Time to find a new rodeo.

**Comment by armyofda12mnkeys** [comment]
well my personal token did get auto-merged and i see the token image in Phantom wallet. but I wish the file was maintained more nicely. I submitted a PR last week fixing everyone's JSON so the file becomes valid hehe (but doubt anyone will merge it manually since it has to delete some properties and move things around).

**Comment by keone** [comment]
There are just too many PRs, please create an issue linking your PR if it needs manual review and someone will try to get to it.
