### ISSUE TITLE
Update Coingecko and Coinmarketcap link for Atlas Dex

### ISSUE THREAD

**Issue by yasiriqbal776** [solana-labs/token-list#16519]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I have update Coingecko and coinmarketcap id for our token Atlas Dex. 

[PR](https://github.com/solana-labs/token-list/pull/16515)

**Comment by keone** [comment]
merged
