### ISSUE TITLE
Update Token Name and Image

### ISSUE THREAD

**Issue by syco214** [solana-labs/token-list#16510]
- **I'm submitting a ...**
  [X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.) Hi here is the PR for the merge. https://github.com/solana-labs/token-list/pull/16508

**Comment by keone** [comment]
added comment in PR
