### ISSUE TITLE
Cannot upload new logo and change logo link

### ISSUE THREAD

**Issue by MTSami** [solana-labs/token-list#16600]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- Dear Concerned, I would like replace my old logo with a new logo and update the link, auto-merge doesn't allow that.
- Please refer to PR #16594 
- The token address is 7bFfvNZqJr2KFDjdP58MVud7kM9AMbXvoFcfAmgBHtfx
- I deleted the old logo and uploaded a new logo image in assets
- I updated the logo link in line number 93214 of src/tokens/solana.tokenlist.json
- Thank you for your kind consideration

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
