### ISSUE TITLE
error validating schema: chainId: conflicting values 103 and 0

### ISSUE THREAD

**Issue by matlirman** [solana-labs/token-list#16624]
- **I'm submitting a ...**
  [ X ] bug report
  [ ] feature request
  [  ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
-I just saw someone elses ticket with the same issue and you said it was because I accidentally touched the last line of the file. Any chance you can manually approve me so I dont have to wait the full hour again?

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by matlirman** [comment]
https://github.com/solana-labs/token-list/pull/16620

This is the specific pull request

**Comment by keone** [comment]
added comment on PR

**Comment by matlirman** [comment]
I got the same issue again. Can you please take a look and help me out?? Ive been getting this error for a long time now and I'm getting desperate 😅

**Comment by keone** [comment]
merged
