### ISSUE TITLE
Updating CP Token Logo

### ISSUE THREAD

**Issue by kidph** [solana-labs/token-list#16641]
- **I'm submitting a ...**
  [ x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Tried replacing image in current token address asset folder that I added yesterday, but it marks it as a deletion (I suppose deleting old one, replacing with new) Not sure how I should go about this.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Pull request - https://github.com/solana-labs/token-list/pull/16563

**Comment by keone** [comment]
merged
