### ISSUE TITLE
Error changing spl-token logo

### ISSUE THREAD

**Issue by syco214** [solana-labs/token-list#16658]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.) Hi, getting an automerge error when editing the existing logo image. Here's the PR https://github.com/solana-labs/token-list/pull/16508

**Comment by keone** [comment]
squashed and merged
