### ISSUE TITLE
Updating - Logo & Name - error duplicate token

### ISSUE THREAD

**Issue by ant-dev-panda** [solana-labs/token-list#16662]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Hello, I have updated my token on my depository and then tried to automerge.

I have updated;

1. Created a new logo on new URL and updated the new logo the correct assets folder
2. Changed token symbol and name
3. Added a website URL

Changing token name from SPRA to OKDev and changing logo [#16657](https://github.com/solana-labs/token-list/pull/16657/checks?check_run_id=5020245652)

[Direct Link here to see code changes](https://github.com/solana-labs/token-list/pull/16657/commits/ab857fb57b9d622b171fa76e2e447cb0c10fc4e4)

gh pr checkout 16657

Can someone please manually merge?

Thank you

**Comment by keone** [comment]
check https://github.com/solana-labs/token-list/pull/16657/files:
you can see that you're re-adding a block for `8V1QEHoWE41YvN99xRVpAJtUuXtPx1Bppi9TKYo26puP` instead of modifying the existing
this results in duplicate entry
