### ISSUE TITLE
Updating Logo, Description and decimals

### ISSUE THREAD

**Issue by Ob1iviou5** [solana-labs/token-list#16676]
- **I'm submitting a ...**
  [ ] bug report
  [X] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Trying to update Logo, Description and decimals.
Pull request is successful however getting an automerge error:
unsupported file modified: /dev/null

Can someone help or advise?

**Comment by keone** [comment]
please leave the PR open and link it here (i see you closed #16660)

**Comment by Ob1iviou5** [comment]
Hi,

Have just reopened the pull request

**Comment by Ob1iviou5** [comment]
Have just re-opened this

Thankyou for the help in advance btw

**Comment by Ob1iviou5** [comment]
https://github.com/solana-labs/token-list/pull/16660

**Comment by keone** [comment]
merged
fyi, decimals on F6ZyzgtCU37NgFGTKYfdBy7BKwzxNZVBDkB68v9Qp1ch looks to be 9 (you changed it to 0 here)

**Comment by Ob1iviou5** [comment]
Oh wow,

Was that really the error 😳
I was looking through it the entire time thinking there's nothing wrong
with that...

Haha, thankyou so so much for the help!

Would I need to go back in and amend this?

**Comment by keone** [comment]
no it was blocking because you were modifying existing entries; those need manual approval until team builds more automation

the decimals thing is just something i noticed.  it probably doesnt matter, apps generally use on chain data for that

if you want to fix the decimals, file another PR and link it

**Comment by Ob1iviou5** [comment]
Hey thankyou for merging this for me.

Does this mean the changes will take effect?

I was trying to update the name, symbol and logo and of course the decimals
too.

Doesn't matter about decimals but the logo picture and symbol does.

**Comment by Ob1iviou5** [comment]
Just checked, Thankyou so much for the help!
