### ISSUE TITLE
Clash Of Cars Token PR#16680

### ISSUE THREAD

**Issue by jesaiasmaia** [solana-labs/token-list#16681]
Hello guys I need to add the coingecko id into my token information. I've created the PR and there I added another useful links too. Thank you for all attention.

- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
please link the PR

**Comment by keone** [comment]
merged #16680
