### ISSUE TITLE
Is it allowed to create a pull requests for NFT's ? (Assuming there might be millions)

### ISSUE THREAD

**Issue by calboru** [solana-labs/token-list#1669]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [x] question about the decisions made in the repository
  [x] question about how to use this project

- **Summary**
Is it allowed to create a pull requests for NFT's ? (Assuming there might be millions)

**Comment by leoluk** [comment]
No, the token list does not track NFTs
