### ISSUE TITLE
Repo is getting huge (>1gb), maybe encourage use of arweave?

### ISSUE THREAD

**Issue by 21e8** [solana-labs/token-list#16723]
- **I'm submitting a ...**
  [ ] bug report
  [ x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Hi guys,
love this repo a lot! 
however ti is getting huge, trying to clone it rn and takes forever at 1mb/s.
I have been using arweave (and I also built a web uploader for arweave which I am happy to link) in order to avoid adding to it.
But maybe you should consider finding a better storage solution?

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
possibly related: #11897
