### ISSUE TITLE
Update AMMO info 

### ISSUE THREAD

**Issue by 21e8** [solana-labs/token-list#16727]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
https://github.com/solana-labs/token-list/pull/16724

Would love to merge an update.

Here the original PR:
https://github.com/solana-labs/token-list/pull/13433

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
