### ISSUE TITLE
I need to replace the token address, the old one is gone.

### ISSUE THREAD

**Issue by jdaniel96** [solana-labs/token-list#16757]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

I am relatively new to this, so I created a token to see if it worked, it did, and I thought I could simply burn the tokens and close the token account, so I could do the "real" one, instead I found out that you cannot do that, I want to use my old name and icon but now it is in the registry and I can't use it nor update the token address! I need to be granted permission to update the token address, please. I just made 3 test transactions to a phantom wallet.

My PR is the #16756

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions on how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
