### ISSUE TITLE
Changing token name from SPRA to OKDev and replacing logo #16763

### ISSUE THREAD

**Issue by ant-dev-panda** [solana-labs/token-list#16765]
- **I'm submitting a ...**
  [X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I have updated token name, symbol and logo
Web URL has been added

Due to changing existing token, Auto Merge failed 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

If you say I am creating a duplicate, should I re-fork and then edit. Or should I delete, merge, then add as new token.

Changing token name from SPRA to OKDev and replacing logo [#16763](https://github.com/solana-labs/token-list/pull/16763)

Thank you

**Comment by keone** [comment]
yes indeed, this diff adds a duplicate block for that address: https://github.com/solana-labs/token-list/pull/16763/files

just edit the block that is already in the json for that address
