### ISSUE TITLE
update the token website link #16798

### ISSUE THREAD

**Issue by whiterabbit-hub** [solana-labs/token-list#16802]
- **I'm submitting a ...**
  [ ] feature request
  [ ] question about the decisions made in the repository

- Hello sir/mam, my token MCOP has wrong website address. I copied someone else token link. Please update the link to https://metacopsnft.io. or merge request #16798.
- Also it can be classified as bug too as I  can make a new token use someone else social link and try to sell the coin to new web3 users.

**Comment by whiterabbit-hub** [comment]
can i get a response soon

**Comment by keone** [comment]
merged
