### ISSUE TITLE
Not eligible for automerge unsupported file modified: 

### ISSUE THREAD

**Issue by racegig** [solana-labs/token-list#16845]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ 1] question about how to use this project

Hello,
My Pull request for a new Token get rejected

I get this message

Not eligible for automerge (click details for more information)
unsupported file modified: HTFSPU2KwKh7nhBPUraTjd8jbhU2VA6Vm5XcdTSrHmfu/logo.png

logo.png is 8 Ko and 8 bits

![logo](https://user-images.githubusercontent.com/98869472/152210459-a82cf32a-5690-4df5-b7c8-40fe46c3c882.png)

I'm stuck there

Help please...

**Comment by keone** [comment]
please link a PR

**Comment by racegig** [comment]
There it is

https://github.com/solana-labs/token-list/pull/16841

Thanks

**Comment by keone** [comment]
ah yes, your logo needs to go in assets/mainnet/ADDRESS/
also fyi you saved your logo as .ppg

**Comment by racegig** [comment]
.PPG ? I tought you needed an .PNG ? Can you confirm? Is'nt .ppg a
powerpoint file?

Thanks in advance
Marc

**Comment by keone** [comment]
#17463
