### ISSUE TITLE
Attempted to change my token address to correct token address but its giving me a duplicate token error.

### ISSUE THREAD

**Issue by DanteLogan** [solana-labs/token-list#16858]
After merging my fork of the code i realized that i put the wrong token address and after changing it and attempting to do another pull request it is telling me there is a duplicate token which is already my token (CFP-ColdFusion Protocol)

**Comment by keone** [comment]
are you talking about https://github.com/solana-labs/token-list/pull/16843 ?

because it is indeed already in there
```
$ grep 3TVUHQgnmW1xqS5fTuDoNDay95DTRRbizbo962UN1KzX solana.tokenlist.json -B3 -A10
    },
    {
      "chainId": 101,
      "address": "3TVUHQgnmW1xqS5fTuDoNDay95DTRRbizbo962UN1KzX",
      "symbol": "CFP",
      "name": "ColdFusion Protocol",
      "decimals": 0,
      "logoURI": "https://raw.githubusercontent.com/DanteLogan/cfp-token/main/newlogo.png",
      "tags": [
        "social-token",
        "utility-token",
        "community-token"
      ]
    },
```

**Comment by DanteLogan** [comment]
Yes i am unfortunately I used the wrong token address and i thougj doing over a pull request with the correct address would change it. Is it possible for me to change the address?

**Comment by keone** [comment]
sorry i don't understand, is 3TVUHQgnmW1xqS5fTuDoNDay95DTRRbizbo962UN1KzX the wrong address or the right address?

**Comment by DanteLogan** [comment]
That is the wrong address, the correct address is 

CY7meunShZiLEdD9RgXYoMampEj6DZbD87EMLNKrBzAe

**Comment by keone** [comment]
your diff does NOT change the address to be that address though... look at what it does: https://github.com/solana-labs/token-list/pull/16843/files

just edit the file to change 3TVUHQgnmW1xqS5fTuDoNDay95DTRRbizbo962UN1KzX to CY7meunShZiLEdD9RgXYoMampEj6DZbD87EMLNKrBzAe and then commit that

**Comment by DanteLogan** [comment]
O i see so all i need to do is change the file name in the assests folder and then change the address in the json file?

**Comment by keone** [comment]
yeah

**Comment by DanteLogan** [comment]
So thats exactly what i did actually as i am now checking it over, but its saying its a duplicate token, so now im confused

**Comment by DanteLogan** [comment]
So i did it over and now this is the problem im getting:

found modified asset file assets/mainnet/CY7meunShZiLEdD9RgXYoMampEj6DZbD87EMLNKrBzAe/newlogo.png - only new assets are allowed

**Comment by keone** [comment]
please link a PR

**Comment by DanteLogan** [comment]
So i ended up just creating a new name and adding the correct address as a new token as time was a constraint for me
