### ISSUE TITLE
Update PAWS Info

### ISSUE THREAD

**Issue by billy93** [solana-labs/token-list#16854]
I'm submitting a ...
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

Summary

update PAWS info #16850 

Would love to merge an update.

Here the original PR:
#16232 

Other information (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
