### ISSUE TITLE
Update of Token image could not be automerged.

### ISSUE THREAD

**Issue by DarrenSG** [solana-labs/token-list#16852]
- **I'm submitting a ...**
  [X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
PR for the merge: #16851
I think the automerge could not handle update of information. Kindly help to merge this in, much appreciated!

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
