### ISSUE TITLE
Delete token from the list #16935

### ISSUE THREAD

**Issue by antonsemprimoznik** [solana-labs/token-list#16936]
I'm submitting a ...
[ ] bug report
[ x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

Summary
Hello, I would like to delete my token from list because of the issue with phantom wallet. It recognises token as NFT. I just sent pull request https://github.com/solana-labs/token-list/pull/16935. Sending it here since it has automerge-error. All other checks have passed.

Thank you

**Comment by keone** [comment]
merged
