### ISSUE TITLE
Changing token name from SPRA to OKDev and replacing logo #16937

### ISSUE THREAD

**Issue by ant-dev-panda** [solana-labs/token-list#16939]
- **I'm submitting a ...**
  [ X ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Hello

I have updated;

Created a new logo on new URL and updated the new logo the correct assets folder
Changed token symbol and name
Added a website URL

Can someone please manually merge?

PR #16937

Thank you

**Comment by keone** [comment]
merged
