### ISSUE TITLE
adding coingeckoId #16910

### ISSUE THREAD

**Issue by SwanLana** [solana-labs/token-list#16941]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x] question about how to use this project

- **Summary**
i,m trying to adding coingeckoId and update some information to my token. it said eligible to merge and branch has no conflicts, but automerge-error. 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

failed to normalize: failed to parse JSON: json: unknown field "discord"

https://github.com/solana-labs/token-list/pull/16910

**Comment by keone** [comment]
squashed and merged
