### ISSUE TITLE
need to change the address SEDS token

### ISSUE THREAD

**Issue by SEDS-kanchanaburi** [solana-labs/token-list#16987]
I'm submitting a ...
[ ] bug report
[ x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

Summary
Hello, I would like to change my token address.

Thank you
_Originally posted by @SEDS-kanchanaburi in https://github.com/solana-labs/token-list/issues/16976#issuecomment-1029177047_

**Comment by keone** [comment]
merged

**Comment by SEDS-kanchanaburi** [comment]
> merged

thank you so much
