### ISSUE TITLE
I have updated the logo link and manual approval required

### ISSUE THREAD

**Issue by cenisa** [solana-labs/token-list#17006]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [X] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Please have a look at https://github.com/solana-labs/token-list/pull/16940

I have updated the Dusty Market logo link and there is no duplicate this time. Please merge this change. Thank you!

**Comment by keone** [comment]
nope! this PR still has 2 commits: https://github.com/solana-labs/token-list/pull/16940/commits

you need to submit a PR (branch) with only the second one

i think you might be able to resolve the issue by fetching origin and then rebasing your branch back to main
