### ISSUE TITLE
Updating Token URI (original and newest commits provided)

### ISSUE THREAD

**Issue by Quellen-Dojo** [solana-labs/token-list#17022]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ x] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Requires manual merge.

I have updated the logo for Token Address 9X298b5Ypa64iCstzn7cQmND2kdgEFftUKTQSANmpbnw

PR: https://github.com/solana-labs/token-list/pull/16932

This is the update commit
https://github.com/solana-labs/token-list/pull/16932/commits/44d6c5d23e6e56b1cfddbf135fc41c8191665dae

This is my original commit:
https://github.com/solana-labs/token-list/pull/16919/commits/273f3c687039c811b94b12af691a62774c8aac60

Thank you!

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
