### ISSUE TITLE
Update url logo could not be automerged

### ISSUE THREAD

**Issue by drumbun** [solana-labs/token-list#17032]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- PR for the merge SEFU token url logo change #17015 
- May automerge could not handle update of information. Kindly help me to merge this in. Much appreciated.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
