### ISSUE TITLE
Duplicated symbol bug.

### ISSUE THREAD

**Issue by BlockchainWizard** [solana-labs/token-list#17058]
- **I'm submitting a ...**
  [X ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- 
This pull request was a test to see if a symbol could be duplicated. To my surprise it worked. I would have hoped that a symbol had to be unique and not duplicated. I was able to duplicate the symbol "WIN" which was done on both of these contracts:

https://solscan.io/token/Ghh9TRwCMjjGXFexdjqscqrcfwHsETRcxgvFi4puMftx
https://solscan.io/token/AWD7Rkh72ENAZUeHGP5mnubFPk8AeSN1ogosExdF4G2X

Here is the original PR where I did the duplicated symbol: https://github.com/solana-labs/token-list/pull/17050

I have also added another pull request to make a change to the symbol to be "LIME". Here is that PR: https://github.com/solana-labs/token-list/pull/17057

**I would hope that name or symbol could not be duplicated.**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by BlockchainWizard** [comment]
Please keep in mind, being able to duplicate a symbol OR name will create chaos now that SPL tokens are slated to be traded on CoinBase. Without uniqueness, it will be a huge deterrent to businesses to use Solana spa tokens. Please consider it a bug and address this as soon as possible.

If you don't mind, please respond to this message directly with your thoughts.

**Comment by BlockchainWizard** [comment]
Please merge this change to make my token name "Tequila" have the symbol "LIME" The first upload was a test, as mentioned above.

Here is the PR to make the change to the symbol: https://github.com/solana-labs/token-list/pull/17057

**Comment by keone** [comment]
merged #17057 

for the broader question, will leave this issue open

**Comment by BlockchainWizard** [comment]
> merged #17057
> 
> for the broader question, will leave this issue open

**Comment by BlockchainWizard** [comment]
"Closing" was unintentional.
