### ISSUE TITLE
Setting coingeckoId field

### ISSUE THREAD

**Issue by ssi91** [solana-labs/token-list#17095]
- **I'm submitting a ...**
  [ x ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
https://github.com/solana-labs/token-list/pull/17085
Auto-merge doesn't work with the `coingeckoId` field

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
