### ISSUE TITLE
Editing an already existing token

### ISSUE THREAD

**Issue by apesonspace** [solana-labs/token-list#17119]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ *] question about the decisions made in the repository
  [ ] question about how to use this project

- Hello, we included our token metadata in https://github.com/solana-labs/token-list/pull/16823, but we would like to update the address because we found some issues in the contract. So is there a way to do this because the auto-merge won't work due to the deleted lines.  

- There is already a pull request with the updated changes in https://github.com/solana-labs/token-list/pull/17118 but I think the merge has to be done manually since the bot will reject the updates.

Can someone help me?

**Comment by keone** [comment]
added comment in PR
