### ISSUE TITLE
change token name and symbol - @keone  Please check the comments.

### ISSUE THREAD

**Issue by quiztok** [solana-labs/token-list#17212]
Hello, I completed the token swap (ERC20 -> SPL-Token) with wormhole this time and changed the token name and symbol, but the details reflected after the change request were slightly different from what I expected, so I tried to modify it (update git token-list), but it is not reflected. The PR link for the error is as follows. What should I do if I want to modify it?

Token information to be updated.
 name : QUIZTOK
 symbol : QTCON-SOL

https://github.com/solana-labs/token-list/pull/17209

https://github.com/solana-labs/token-list/commit/46112dbf918639473bb303ede4ce912da1d8c277

**Comment by quiztok** [comment]
@keone 
I'm sorry for registering duplicate posts.
When will our token name and symbol modification be applied?
Or if we have to proceed with the update (git merge) to the json file again, when should we try to merge it?

**Comment by quiztok** [comment]
@keone
I'm sorry for registering duplicate posts.
When will our token name and symbol modification be applied?
Or if we have to proceed with the update (git merge) to the json file again, when should we try to merge it?

**Comment by keone** [comment]
i'm not sure what you're trying to do here
https://github.com/solana-labs/token-list/pull/17209 just deletes your entry, see https://github.com/solana-labs/token-list/pull/17209/files
is that what you want?

**Comment by quiztok** [comment]
> 



> 여기서 무엇을 하려는지 잘 모르겠습니다 #17209 그냥 항목을 삭제합니다. https://github.com/solana-labs/token-list/pull/17209/files 를 참조하세요. 그게 당신이 원하는 것입니까?

Yes, I want to change the current token name and symbol.
I would like to renew the token information (name, symbol, logo...) after reflecting the deleted json file on the mainnet (initializing token information).

**Comment by quiztok** [comment]
> 여기서 무엇을 하려는지 잘 모르겠습니다 #17209 그냥 항목을 삭제합니다. https://github.com/solana-labs/token-list/pull/17209/files 를 참조하세요. 그게 당신이 원하는 것입니까?


Yes, I want to change the current token name and symbol.
I would like to renew the token information (name, symbol, logo...) after reflecting the deleted json file on the mainnet (initializing token information).
