### ISSUE TITLE
URGENT - Duplicate Symbol & Name - PLEASE FIX FOR THE BENEFIT OF SOLANA

### ISSUE THREAD

**Issue by BlockchainWizard** [solana-labs/token-list#17232]
- **I'm submitting a ...**
  [X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- I am raising this issue again because of its importance. Please have someone address this issue. Duplicate symbols and name on the open market will limit the utility of Solana spl tokens. It may not inhibit the blockchain because of the unique token address but it will on exchanges. It is a HUGE oversight. Please address. 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
while i understand your concern, based on your commit history it looks like you're trying to squat on a bunch of symbols that you think would be desirable

https://github.com/solana-labs/token-list/commits?author=BlockchainWizard
https://github.com/solana-labs/token-list/commit/8c0fc529a50037642809483a85405ab74712a2d7

and then you're trying to get symbols uniquified to make your squats more valuable

please dont do this

**Comment by BlockchainWizard** [comment]
I understand your comment but it does not negate the fact that it is an issue with Solana. I am happy to not "squat" but I am a huge support of your blockchain. If this is not addressed it will be an issue. Do you not agree?

Not trying to be combative. I am trying to help your cause.

**Comment by BlockchainWizard** [comment]
In addition, if I am to promote Solana, however I do it is that not good for Solana. I am have vision...do you blame me for choosing Solana?

**Comment by BlockchainWizard** [comment]
In fact, I'll make this commitment...I will move all of my SOL to one account and you can delete my tokens if you agree to fix this issue. I have a larger need for this to work for one token that I do 34.

Deal?
