### ISSUE TITLE
Request Token info update #17252 - Remove coingeckoId

### ISSUE THREAD

**Issue by metamounts** [solana-labs/token-list#17254]
Please check MR 17252
https://github.com/solana-labs/token-list/pull/17252

Our Token Address:
9QXAu7FTf7hmswBQwKxvuqGgWH42FyQjqXJanUt6y4eC

We would like to remove the following attribute,
"coingeckoId": "metamounts".

Backstory - contracted dev pulled a rug on us, dumping our coins. Had to restart.

**Comment by keone** [comment]
added comment in PR

**Comment by keone** [comment]
merged
