### ISSUE TITLE
Token is listed but still showing as unrecognized token in phantom and explorer!

### ISSUE THREAD

**Issue by zakimzf** [solana-labs/token-list#17278]
Hi @keone #17231 this token has been successfully automerged into token-list  and its showing up on solscan also: https://solscan.io/token/E1vVoJmfr3Jyvwd8iFB7F1u9uwAeFNqkNxfzybHNyHuD
 Where as its not showing up on solana explorer (i know its in beta, still) https://explorer.solana.com/address/E1vVoJmfr3Jyvwd8iFB7F1u9uwAeFNqkNxfzybHNyHuD

Also phantom is unable to pick it up! I think this is a bug cause i have added many tokens into token-list every token appeared in phantom!

Please look into this and get back to me. Thanks.

**Comment by unimintco** [comment]
You just need to wait a little bit. If it's showing up in solscan, most likely it will by synced with the wallets at some point.

**Comment by Nakashikimono** [comment]
The Meta 4 token is still not showing in the phantom wallet. I noticed that token is in solscan but when I click on "program" it shows account TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA. when it should be showing account: AZiFyeTSAMPoYUBh4thbGWyQMj3gU5URwu9XE9iGj8wu. 

Any way we can fix this?

**Comment by Nakashikimono** [comment]
@keone It has been 2 days and my token has still not synced with my wallet, In fact, the Metadata on my wallet has changed. Do you have any advice on how to fix this issue? Or will the issue correct itself in due time?

**Comment by unimintco** [comment]
Solscan is showing the data, so the problem is with the wallet. Which one you're using?
Phantom (esp. on iOS) has some sync delays and what I assume caching issue, for me usually switching wallets back and forth triggers refetch of the metadata.
Can't tell anything about other wallets.
