### ISSUE TITLE
Changing Token Symbol 

### ISSUE THREAD

**Issue by yongbeam** [solana-labs/token-list#17309]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Change token symbol PR: 
[https://github.com/solana-labs/token-list/pull/13122](https://github.com/solana-labs/token-list/pull/13122)

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
