### ISSUE TITLE
Please change the Logo URI for Memoria (5XiE2JApnDwGc24PSY7y7stD4JxStkYPAH5tFVKAcrow) from this link:

### ISSUE THREAD

**Issue by TopDev711** [solana-labs/token-list#17300]
Please change the Logo URI for Memoria (5XiE2JApnDwGc24PSY7y7stD4JxStkYPAH5tFVKAcrow) from this link:

"logoURI": "https://github.com/Memoria-ORIA/Assets/blob/main/MemoriaLogo.png"

To this link:

"logoURI": "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/5XiE2JApnDwGc24PSY7y7stD4JxStkYPAH5tFVKAcrow/logo.png"

Thank you!

_Originally posted by @TopDev711 in https://github.com/solana-labs/token-list/issues/17296#issuecomment-1030651259_

**Comment by keone** [comment]
added comment in PR
