### ISSUE TITLE
Helloi don't know how to change my image into this type of url https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/

### ISSUE THREAD

**Issue by ghost** [solana-labs/token-list#17307]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by VortexHowl** [comment]
are you having the same problem i am? i used the wrong logo url and it wont show on SolScan, other explorer sites, or on wallets. when i try to change it, it wont let me merge the update to my tokens logo url.

**Comment by nftforArt** [comment]
it was good for me in the end you don't need to to anythind just wait 1-2days

**Comment by VortexHowl** [comment]
Ok thank you! I'm new to all this so I feel like I'm stumbling blind. Lol
