### ISSUE TITLE
Merge request OTK #16451

### ISSUE THREAD

**Issue by anisarif** [solana-labs/token-list#17342]
- **I'm submitting a ...**
  [ ] bug report
  [ x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- 
I added 2 tokens 6 days ago, and I need your help with the manual approval, please (OTK #16451)

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
added comment in PR

**Comment by anisarif** [comment]
> added comment in PR

Thank you
