### ISSUE TITLE
@Keone Update Memoria LOGO URL - in reference to #17296

### ISSUE THREAD

**Issue by TopDev711** [solana-labs/token-list#17407]
Hi,

Please update this change in the Memoria URL. 

This is the same request as Add Memoria Logo to Main Asset File #17296, however I was not able to push a commit to that Pull Request. 

I have closed Add Memoria Logo to Main Asset File #17296. 

Thank you.

_Originally posted by @TopDev711 in https://github.com/solana-labs/token-list/issues/17399#issuecomment-1030761225_

**Comment by Memoria-ORIA** [comment]
I have the Memoria logo in the Token-List>assets.mainnet folder. 

I just need help updating the Memoria URL. Please refer to PR#17399 and you'll see that update where I changed the Memoria URL. I need your help pulling that request. 

I know you guys are busy, so thank you for taking care of this. We all appreciated your hard work!!!

**Comment by keone** [comment]
merged https://github.com/solana-labs/token-list/pull/17296 and https://github.com/solana-labs/token-list/pull/17399
