### ISSUE TITLE
Change Nooft token address

### ISSUE THREAD

**Issue by nooftproject** [solana-labs/token-list#17509]
- I'm submitting a pull request to change token address:
- 
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- Hello! I changed the token address for the Nooft token (#17506 ). Please merge it. It is kind of urgent. Thank you in advance!

-(https://github.com/solana-labs/token-list/pull/17506)

**Comment by nooftproject** [comment]
Can you please help me with this?

**Comment by nooftproject** [comment]
I've seen that it had some merge problem. I modified again. Here is the new PR #17591

**Comment by keone** [comment]
merged
