### ISSUE TITLE
Need to update my token to reflect identifier changes

### ISSUE THREAD

**Issue by notmatical** [solana-labs/token-list#17568]
- **I'm submitting a ...**
  [ ] bug report
  [ x ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary** 
Need my Cosmic Token ID changed to my new one, I made a PR and automerger failed because of removed line.
https://github.com/solana-labs/token-list/pull/17545 is link to PR, check comments for link to original commit of the token.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
