### ISSUE TITLE
Token Name and Logo not showing in wallet

### ISSUE THREAD

**Issue by DanteLogan** [solana-labs/token-list#17569]
-After readding my token with a new Logo and name with the correct token address ,these changes are not reflected in my wallet e.g Phantom , however all changes are seen on Solscan

**Comment by k666-bit** [comment]
Same issue here. Something's not working quite right as I've made my commit on Friday and still hasn't propagated properly on client wallets. (It was almost instantly picked up by solscan and explorer)

**Comment by keone** [comment]
different apps sync from this repo at different rates
i believe phantom is a lot less frequent than solscan
