### ISSUE TITLE
adding coingeckoId #17412

### ISSUE THREAD

**Issue by dzmitry-lahoda** [solana-labs/token-list#17656]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x] question about how to use this project

- **Summary**

Adding  coingeckoId failed with `parse JSON: json: unknown field`. https://github.com/solana-labs/token-list/pull/17412

I checked:

1. our id is first and unique, never changed (like in other issues where it was renamed)
2. `coingeckoId` is letter by letter copied as name from other tokens
3. tried to create PR from scratch and put id into different places, same result

None of that helped. JSON seems correct.  Our token exists on coingecko.

https://www.coingecko.com/en/coins/tiny-colony

UPDATE: I see similar issues  with other tokens like https://github.com/solana-labs/token-list/issues/14408

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions on how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged; added comment on PR; sorry for the confusion
