### ISSUE TITLE
Update NEWTON asset and url

### ISSUE THREAD

**Issue by neftworld** [solana-labs/token-list#17809]
Hi everybody,

Sorry for generating extra work for you - I know you're busy.

When you have some time, please could you look at this PR:

#17767 

I'm trying to fix my asset and the URL. The old URL didn't display at all because I pointed it to an HTML page. Doh!

- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
