### ISSUE TITLE
Please check and approve the PR to change the logo of the project "Space Hamster "

### ISSUE THREAD

**Issue by LeRoYGo** [solana-labs/token-list#17868]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [X] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Please have a look at https://github.com/solana-labs/token-list/pull/17862

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
Please approve the PR for the project "Space Hamster". The logo has been changed.

**Comment by unimintco** [comment]
@LeRoYGo In order not to clutter issues you should ping the maintainers right on the pull request itself.
I believe [**@ keone**](https://github.com/keone) is our guy 👏🏻 

In the PR template it states:
> I agree to not ping anybody on Discord/Twitter/email about this pull request. Instead I will inquire by posting a new comment **in the pull request if needed**

I believe it goes for GitHub issues as well, not only channels listed there.

**Comment by LeRoYGo** [comment]
@unimintco All right, I'll close the subject. Maybe you can tell me how long it takes to check the PR in manual mode?
