### ISSUE TITLE
Manual review of token URI Update needed 

### ISSUE THREAD

**Issue by MarkSackerberg** [solana-labs/token-list#17882]
Hi,
can you please manually review PR #17860? Unfortunately the token image was added incorrectly in the PR that has been merged automatically.
The fixed URL is in this PR, but since the change is detected as deleted line a manual review is required.

Old URL: https://github.com/MarkSackerberg/token-list/blob/main/assets/mainnet/fujiCeCeP9AFDVCv27P5JRcKLoH7wfs2C9xmDECs24m/logo.png
New URL: https://raw.githubusercontent.com/MarkSackerberg/token-list/main/assets/mainnet/fujiCeCeP9AFDVCv27P5JRcKLoH7wfs2C9xmDECs24m/logo.png

Thank you very much for reviewing!

**Comment by keone** [comment]
merged
