### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by lynxerinc** [solana-labs/token-list#17901]
- **I'm submitting a ...**
  [ *] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ *] question about how to use this project

- **Summary**
I would need a manual check to change the token logo

PR: #17819

https://github.com/solana-labs/token-list/pull/17819

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
added comment to PR
