### ISSUE TITLE
Error duplicate token 

### ISSUE THREAD

**Issue by nerap** [solana-labs/token-list#17928]
Hi!

I did this pr like any normal pull request for the repo !  #17926 

But for some reason my pr didn't pass because "Duplicated token address".

That make no sens at all I don't understand why ? How do I fix this? modifying existing pr? The thing is the file is already modifying with the new token but the pr says that it doesn't but the token appear in the file, I don't understand what's happening right here.
Thx

**Comment by keone** [comment]
https://github.com/solana-labs/token-list/blob/main/README.md#duplicate-token

**Comment by keone** [comment]
closed due to inactivity, please reopen after addressing the above issue
