### ISSUE TITLE
Add coingecko id

### ISSUE THREAD

**Issue by sombeProject** [solana-labs/token-list#17941]
Hi Team ,
@keone 
I need to update our token Sombe Information
ADD coingeckoId "sombe"

Please help us to merge this request
#17937

commited at
https://github.com/solana-labs/token-list/pull/17937

Our token already listed on COINGECKO
https://www.coingecko.com/en/coins/sombe

Token address
JBjxHjFKMBvRa45PvYDaEVfecdYaV9pkwjnVjt2uSLxh

Token name
Sombe (SBE)

Thank you

**Comment by keone** [comment]
added comment on PR

**Comment by sombeProject** [comment]
update to PR #18060 
need manual merge.
Thank you

**Comment by keone** [comment]
look at the diff before posting:
https://github.com/solana-labs/token-list/pull/18060/files
same issue still
