### ISSUE TITLE
Fixing logo url

### ISSUE THREAD

**Issue by VortexHowl** [solana-labs/token-list#18019]
i made a token for my gamer group, mostly for a cool project for us to do.  but i used the wrong URL for the logo, and it wont show up on SolScan or the wallets.

I tried to just change the logo url to one that I've seen others use. 
https://raw.githubusercontent.com/VortexHowl/Acorn/main/30E9C0AF-8474-4B33-876E-609E2D5E189E.png

but because its a deletion. it wont let me merge.
can you guys help please? just trying to fix the goof i made at first. still learning.

fixing Acorn token URL #17483

**Comment by keone** [comment]
merged
