### ISSUE TITLE
Update request - add tags on tokens 

### ISSUE THREAD

**Issue by hikaru-meta** [solana-labs/token-list#18064]
- **I'm submitting a ...**
  [ ] bug report
  [ X] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
  https://github.com/solana-labs/token-list/pull/18034

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
