### ISSUE TITLE
MODIFY TOKEN KZOO

### ISSUE THREAD

**Issue by ChristianGaeta** [solana-labs/token-list#18073]
- **I'm submitting a ...**
  [ ] bug report
  [ x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
![image](https://user-images.githubusercontent.com/36098568/153437883-ab9b4ce7-de2b-4d39-b514-ba832abe1d6a.png)

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
 am trying to modify the token image icon and the request give me error during merge

**Comment by ChristianGaeta** [comment]
@keone

**Comment by keone** [comment]
please link a PR
