### ISSUE TITLE
error validating schema: chainId: conflicting values 103 and 0

### ISSUE THREAD

**Issue by iuliansafta** [solana-labs/token-list#18115]
- **I'm submitting a ...**
  [x ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

My Pull request for a new Token on devnet get rejected

I get this message:

Not eligible for automerge (click details for more information)
**error validating schema: chainId: conflicting values 103 and 0**

Link PR:

[18111](https://github.com/solana-labs/token-list/pull/18111)

Could you help me with this?

Thanks!

**Comment by keone** [comment]
looks like you got it to work; automerger succeeded

**Comment by iuliansafta** [comment]
Yes, I figure it out in the end. 
Thanks!
