### ISSUE TITLE
unable to identify why am failing to merge 

### ISSUE THREAD

**Issue by Muffin2021** [solana-labs/token-list#18148]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
please link a PR

**Comment by keone** [comment]
closed due to inactivity, please reopen with details
