### ISSUE TITLE
Update decimal fields on PoSB Token

### ISSUE THREAD

**Issue by LatinWally** [solana-labs/token-list#18187]
Change decimals from 0 (wrong) to 9 (correct). Automerge considers a deletion so it should be managed manually.

https://github.com/solana-labs/token-list/pull/18184

@keone

I'm the token creator: thank you very much in advance.

**Comment by keone** [comment]
added comment in PR

**Comment by LatinWally** [comment]
Thank you, I'm quite new to github... I was able to resubmit the request with a deletion and add.

https://github.com/solana-labs/token-list/pull/18698

Thank you @keone

**Comment by keone** [comment]
merged
