### ISSUE TITLE
Merging PR for tag removal

### ISSUE THREAD

**Issue by ArjanLuckyKat** [solana-labs/token-list#18180]
- **I'm submitting a ...**
  [ ] bug report
  [ x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Hiya, I've erronously added an NFT tag to our token and I'd like to remove it, my pr is here:
[#16962](https://github.com/solana-labs/token-list/pull/16962)
Thanks in advance!

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

@keone 
Original PR for token
#16122

**Comment by keone** [comment]
merged
