### ISSUE TITLE
Auto merge failed ,adding coingeckoid in extensions #17965

### ISSUE THREAD

**Issue by Pengucci** [solana-labs/token-list#18221]
- **I'm submitting a ...**
  [* ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

kindly merge the pull request #17965

**Comment by keone** [comment]
merged
