### ISSUE TITLE
I can't change SOLPAY logo url.

### ISSUE THREAD

**Issue by SolPayFinance** [solana-labs/token-list#1826]
- **I'm submitting a ...**
  [X ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [X ] question about how to use this project

- **Summary**
i'm trying to update the SolPay token url logo but automerge gives me error of "deleting".

can you please update the token logo url to this new one:
https://github.com/solana-labs/token-list/blob/main/assets/mainnet/zwqe1Nd4eiWyCcqdo4FgCq7LYZHdSeGKKudv6RwiAEn/logo.png

token name: SOLPAY
token: zwqe1Nd4eiWyCcqdo4FgCq7LYZHdSeGKKudv6RwiAEn

- **Other information**

**Comment by keone** [comment]
Please link a PR and reopen this
