### ISSUE TITLE
My token still unknown in wallet after more than 24 Hours 

### ISSUE THREAD

**Issue by limjame28** [solana-labs/token-list#18378]
Hello , im able to merged but why in my wallet still show unknown wallet , 

its been more than 24 hours 

any suggestion guys ??

**Comment by keone** [comment]
phantom updates its cache of this file every few days

**Comment by limjame28** [comment]
is it still okay if more than 24 hours ? But in my sol scan already updated the logo and the name but only in wallet not updating
