### ISSUE TITLE
Token-List PLAGUE Token Not Auto-Merging Any Help?

### ISSUE THREAD

**Issue by Zkris001** [solana-labs/token-list#18398]
- **I'm submitting a an issue with auto-merging to token-list**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [X] question about how to use this project

- **Hey everyone, I'm slowly learning on this side of things... but long story short I created my SPL token and followed the steps to get here with auto-merging in order to put the name and logo on mainnet. When I open the solana.tokenlist.json to edit it everything works accordingly... I do not delete unwanted code, or changed already existing code... I am adding my changes as new and that is it. I then save the solana.tokenlist.json and this creates a solana.tokenlist.json.bak. This is the file that is somehow causing me issues but its the specific issue that I cannot figure out. Here is my pull request below. Thank you for any insight in advance, its greatly appreciated.**

- **[Other information](https://github.com/solana-labs/token-list/pull/18314)**

**Comment by keone** [comment]
mismatching `{` and `}`, see https://github.com/solana-labs/token-list/pull/18314/files
