### ISSUE TITLE
Automerge error when updatng token logo

### ISSUE THREAD

**Issue by merchantmedia** [solana-labs/token-list#18428]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I would like to update my token logo with the PR #18410

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
