### ISSUE TITLE
Merge issue on EV1

### ISSUE THREAD

**Issue by everyonecoin** [solana-labs/token-list#18467]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [X] question about how to use this project

- **Summary**
I got a merge issue with my pull request. I'm trying to add our new token. I didn't delete any files.

When I looked at the details, it presented this. Our site was down when I submitted a pull request but it's up now.  
failed to verify website: https://everyonecoin.com/: failed to verify https://everyonecoin.com/ using HEAD request: Head "https://everyonecoin.com/": dial tcp 52.14.253.91:443: connect: connection refused

Here's my pull request.
https://github.com/solana-labs/token-list/pull/18281

I appreciate any help you can provide. Thank you!

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged

**Comment by everyonecoin** [comment]
Thank you! This is greatly appreciated.
