### ISSUE TITLE
My token doesn't show up in phantom wallet

### ISSUE THREAD

**Issue by limjame28** [solana-labs/token-list#18482]
Hello , my auto merge already done 2 days ago . I can see change in sol scan but why in my phantom wallet it still recgonize as unknown token ? How many days i have to wait until the token name and logo changed in phantom wallet

**Comment by limjame28** [comment]
https://solscan.io/address/FsSo44ZJUTSks1rVuqoCiPeCmZ9bj9ineTxvA2Dd7ki4 this is the sol scan

**Comment by keone** [comment]
added comment to https://github.com/solana-labs/token-list/blob/main/README.md#adding-new-token
