### ISSUE TITLE
Automerge failure: "found removed line"

### ISSUE THREAD

**Issue by SeogyuGim** [solana-labs/token-list#18526]
- **I'm submitting a ...**
  [v] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Decimal of my token is 8. and I want to update decimal to 9, but automerger always throw error with "found removed line: - "decimals": 8". 
Is there a way to fix this error? or just can't update fields for token information created once?

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Pull Request: https://github.com/solana-labs/token-list/pull/18517

**Comment by keone** [comment]
merged
