### ISSUE TITLE
Updating link for LIT token #18537

### ISSUE THREAD

**Issue by ohidurbappy** [solana-labs/token-list#18539]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Pull request: #18537

**Comment by keone** [comment]
merged
