### ISSUE TITLE
Update SolPay token Logo URL

### ISSUE THREAD

**Issue by SolPayFinance** [solana-labs/token-list#18565]
- **I'm submitting a ...**
  [ ] bug report
  [x ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

We want to change SolPay token logo url from the current one to the one at this link:

https://www.solpay.finance/img/logo_small-removebg-preview.png

Token address:

zwqe1Nd4eiWyCcqdo4FgCq7LYZHdSeGKKudv6RwiAEn

**Comment by keone** [comment]
please link a PR

**Comment by SolPayFinance** [comment]
what is a PR? @wildtangent @keone @siong1987 @kobak ?

**Comment by SolPayFinance** [comment]
our logo url is still the same..... why you closed the ticket. We still need to fix this!
