### ISSUE TITLE
Unable to Change FAKE Token Address / Symbol

### ISSUE THREAD

**Issue by faketrillionaire** [solana-labs/token-list#18608]
- **I'm submitting a ...**
  [*] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- I am unable to update the address of my token. I uploaded the address for the DevNet address  85Uap8Zmm2nBo8HSCZMuVbvS6NAwisKS7N8Gj5ok5kvk
- 
- I am trying to update symbol:FAKE, name:Fake Crypto Club to have the address of 7CUP43RKANiYByE2x1X4P1qoj64J9VBhJLyq5d1RzChc

- Other option would be to change symbol:FAKE -> FAKE_dev and name: Fake Crypto Club -> Fake Crypto Club Dev and I can create a new entry with the right address.

All permutation attempts to update/remove/move have failed on merging. 

Thank you,

**Comment by keone** [comment]
updates need to be manually merged
please link an open PR

**Comment by faketrillionaire** [comment]
PR #18726

Thank you very much.

**Comment by keone** [comment]
merged
