### ISSUE TITLE
Manual Merge Reques to update Logo

### ISSUE THREAD

**Issue by tsbsoltn** [solana-labs/token-list#18651]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Need help in merging my PR (https://github.com/solana-labs/token-list/pull/18649) manually, as I'm getting auto-merge error.

PR Change: Replaced existing logo with new.

CC: @keone 

-Thank You.

**Comment by keone** [comment]
merged
