### ISSUE TITLE
Request Logo Update SlyAF

### ISSUE THREAD

**Issue by ProCoreNFT** [solana-labs/token-list#18666]
- **I'm submitting a ...**
  [ X ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Request Logo update for PR#18612
My branch got messed up and now I cant update our logo. Thanks. 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
