### ISSUE TITLE
RICE update

### ISSUE THREAD

**Issue by kakasonz112** [solana-labs/token-list#18725]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
i would like to update my token name.
Currently
name: Rice Token
Symbol: RICE

to

name: RICE
Symbol: RICE

https://github.com/solana-labs/token-list/pull/18720

**Comment by keone** [comment]
added comment in PR

**Comment by kakasonz112** [comment]
> added comment in PR

You are right. I have done a few changes for new PR#18778

@keone

**Comment by keone** [comment]
merged
