### ISSUE TITLE
Need manually help to merge PR

### ISSUE THREAD

**Issue by svansie** [solana-labs/token-list#18739]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x] question about how to use this project

- Created an existing token on this account in January, I now want to update the token symbol. Please review my PR and help me with the merger, thank you. Regards PR #18737

**Comment by svansie** [comment]
@keone could you be kind and assist here?

**Comment by keone** [comment]
https://github.com/solana-labs/token-list#duplicate-token
