### ISSUE TITLE
Modifying existing token data

### ISSUE THREAD

**Issue by ajunrally** [solana-labs/token-list#18741]
- **I'm submitting a ...**
  [ ] bug report
  [X ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- PR request to update the token list to include a coingeckoID for sRLY token (https://github.com/solana-labs/token-list/pull/18740)

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
- https://github.com/solana-labs/token-list/pull/18740

**Comment by keone** [comment]
merged
