### ISSUE TITLE
Updating Logo for EliteCoin

### ISSUE THREAD

**Issue by LightYagami200** [solana-labs/token-list#18749]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I've submitted a PR to update logo for EliteCoin #18748 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
