### ISSUE TITLE
Need help in merging #18014

### ISSUE THREAD

**Issue by heisenberglit** [solana-labs/token-list#18779]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ x] question about how to use this project

- **Summary** - Updated the logo URI in the PR but its not merged yet.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by heisenberglit** [comment]
@keone  Can you please help to merge this PR ? I have updated the token logo 

PR - [#18014 ](https://github.com/solana-labs/token-list/pull/18014)
Token Name - NYN
Token Address - NYNKnLDu1WRacDTmqvMburqc31reUWQSSmoh4MxE3FB

**Comment by keone** [comment]
merged
