### ISSUE TITLE
Problem with updating logo

### ISSUE THREAD

**Issue by Solviewapp** [solana-labs/token-list#18793]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x ] question about how to use this project

- **Summary**
@keone One of our developers have uploaded our tokendetails including the logo, however he does not have acces to his github account anymore. We would like to change our current logo to https://github.com/Solviewapp/solviewlogo/blob/main/Solviewlogo%20copy.png?raw=true 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by Solviewapp** [comment]
> #18733 That is for updating SOLV token LOGO PR

Thanks

**Comment by keone** [comment]
that PR is closed and I can't reopen it bc the branch was deleted

**Comment by cierra2016** [comment]
Okay I will try again

**Comment by cierra2016** [comment]
#18843

**Comment by keone** [comment]
merged

**Comment by cierra2016** [comment]
Thanks
