### ISSUE TITLE
PoSB main-net token decimals update

### ISSUE THREAD

**Issue by LatinWally** [solana-labs/token-list#18819]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Change decimals from 0 (wrong) to 9 (correct). Automerge considers a deletion so it should be managed manually.

https://github.com/solana-labs/token-list/pull/18818

@keone : sorry previous submission was on devnet token, this one is on mainnet one. Thank you in advance for your help, really appreciated!

I'm the token creator: thank you very much in advance.

**Comment by keone** [comment]
squashed and merged
