### ISSUE TITLE
Please  manual review PR #18853

### ISSUE THREAD

**Issue by shifu78** [solana-labs/token-list#18863]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Hi,

I want to update token logos 
PR #18853

Can you manual check please ?

Thx in advance

**Comment by keone** [comment]
merged
