### ISSUE TITLE
Modifying existing token, please manual review #18882

### ISSUE THREAD

**Issue by slz-dev** [solana-labs/token-list#18886]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Hi,

I want to remove existing token and add new token with the same symbol/name/logo
PR https://github.com/solana-labs/token-list/pull/18882

Because existing token can't add metaplex metadata, I created new token.

Can you manual check please ?

Thanks.

**Comment by keone** [comment]
added comment on PR

**Comment by slz-dev** [comment]
> we can't merge this right now due to the above, can you please make the new element not the last element of the list?

can you please check again?

**Comment by keone** [comment]
thanks, merged
