### ISSUE TITLE
Changing Coldfusion Token (CFT) decimal places from 0 to 8

### ISSUE THREAD

**Issue by DanteLogan** [solana-labs/token-list#18900]
I am submitting t a pull request to get assistance in changing the decimal places for my token from 0 to 8. The name of the token is Coldfusion Token (CFT). This token was added under pull request #17179 and has a chain ID of 101.

**Comment by keone** [comment]
please link the PR where you change it from 0 to 8

**Comment by DanteLogan** [comment]
The PR for this is PR#19020 kindly note i changed this to 9 instead

**Comment by keone** [comment]
added comment in PR

**Comment by DanteLogan** [comment]
I closed that PR and reopened one under PR #19036.
