### ISSUE TITLE
Need to update FAKE Address to PR #18904

### ISSUE THREAD

**Issue by faketrillionaire** [solana-labs/token-list#18905]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- Unable to update token address for FAKE. I needed to create a new token for this since the decimals were not set correctly the first time

Please approve changing address to EzpSBrAdTU1AYdY6UWghFJRiq2WF39CUy3Tncrh82XiB

- Please approve PR #18904

**Comment by keone** [comment]
merged
please make up your mind :)

**Comment by faketrillionaire** [comment]
Thank you @keone ! 
I know. I know... Trying....
I gotta RTFM! :)
