### ISSUE TITLE
Automerge failure after 1 hour even after all checks good.. 

### ISSUE THREAD

**Issue by SOLreaper88** [solana-labs/token-list#18987]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ x] question about how to use this project

- I have been trying to simply update my links for my repository.. I create the pull request and push it.. everything is green until 1hr and then I get an automerge error by the bot.. what can be causing this? Thanks PR 
#18979

**Comment by keone** [comment]
please leave your PR open
