### ISSUE TITLE
Update MOSC Token

### ISSUE THREAD

**Issue by jdomingospt** [solana-labs/token-list#19047]
Trying to update the number of decimals and links of MOSC Token:

New commit:
https://github.com/solana-labs/token-list/pull/17870/commits/a3ede11d3c5102e7013685c6f22de1baad62da04

Original commit:
https://github.com/solana-labs/token-list/pull/17614

Thanks

**Comment by keone** [comment]
please link a PR for the new commit

**Comment by jdomingospt** [comment]
@keone 

New PR:
https://github.com/solana-labs/token-list/pull/19080
