### ISSUE TITLE
Deleting FiammaPSD Coin

### ISSUE THREAD

**Issue by SolanaTokenMerger** [solana-labs/token-list#19055]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Please Merge Following PR https://github.com/solana-labs/token-list/pull/19053
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
