### ISSUE TITLE
PURS Token logo change request

### ISSUE THREAD

**Issue by konradre** [solana-labs/token-list#19050]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- Update to logo img file

-Token added PR: https://github.com/solana-labs/token-list/pull/19031

**Comment by keone** [comment]
please link PR
assuming it was https://github.com/solana-labs/token-list/pull/19044, it has this issue: https://github.com/solana-labs/token-list#duplicate-token

**Comment by keone** [comment]
closed due to inactivity, please reopen after addressing the above issue
