### ISSUE TITLE
How long does it take for Phantom wallet to sync new tokens.

### ISSUE THREAD

**Issue by cmgonsalves** [solana-labs/token-list#19086]
- **I'm submitting a ...**
  [*] question about how to use this project

- token not shown within Phantom wallet.. token address is BpGRsBqgSNbGHb73cPL4SGqJTyr2zXomjFu3tX9LP9Vo

**Comment by keone** [comment]
https://github.com/solana-labs/token-list#scannerwallet-hasnt-updated-yet
