### ISSUE TITLE
Correction URL Stone Coin

### ISSUE THREAD

**Issue by AlanBeez** [solana-labs/token-list#19092]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Please merge following PR https://github.com/solana-labs/token-list/pull/19091
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
