### ISSUE TITLE
Not eligible for automerge - error validating schema: logoURI: invalid value

### ISSUE THREAD

**Issue by Andy2988c** [solana-labs/token-list#19101]
Hey, I am trying to add a token to the registry and I am receiving this error:

error validating schema: logoURI: invalid value "https://raw.githubusercontent.com/Andy2988c/crypto/main/Reverb.png " (out of bound ="^(ipfs|http[s]?)://(?:[a-zA-Z]|[0-9]|[$-_@.&+#]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+$")

This is my PR: https://github.com/solana-labs/token-list/pull/19025

Not quite sure what my issue is, would appreciate any help, thanks!

**Comment by keone** [comment]
because there is a space at the end of your logoURI
