### ISSUE TITLE
Deleting Khabi Coin and Correction HMATT Symbol #19165

### ISSUE THREAD

**Issue by SolanaTokenMerger** [solana-labs/token-list#19166]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Please merge Following PR https://github.com/solana-labs/token-list/pull/19165
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
PR was closed, please reopen it or close this issue
