### ISSUE TITLE
Quest website change

### ISSUE THREAD

**Issue by tolui** [solana-labs/token-list#19175]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
We are changing our token website. Please merge following PR. Thanks
https://github.com/solana-labs/token-list/pull/19170

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
