### ISSUE TITLE
added GEMS and icon update SOLERA

### ISSUE THREAD

**Issue by millionsols** [solana-labs/token-list#19171]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [X] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
added GEMS and icon update SOLERA
https://github.com/solana-labs/token-list/pull/19063

Updated image-url for SOLERA (auto-merge not possible) and added token GEMS. please confirm, thank you very much:)

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
