### ISSUE TITLE
Automerge error for PR #19173

### ISSUE THREAD

**Issue by mrukavishnikov** [solana-labs/token-list#19177]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [X] question about how to use this project

- **Automerge error for pull request #19173**

- **Other information** 
https://github.com/solana-labs/token-list/pull/19173 
Got automerge error: **error validating schema: chainId: conflicting values 103 and 0**

According to documentation this should be merged manually, please assist. Leaving PR open.

**Comment by keone** [comment]
https://github.com/solana-labs/token-list/blob/main/README.md#warning-about-the-last-element-in-the-list
^ Please do that and I'll merge

**Comment by mrukavishnikov** [comment]
> https://github.com/solana-labs/token-list/blob/main/README.md#warning-about-the-last-element-in-the-list ^ Please do that and I'll merge

Done. Please check if it can be merged now.

**Comment by keone** [comment]
merged
