### ISSUE TITLE
add UST tag stablecoin

### ISSUE THREAD

**Issue by antoineherzog** [solana-labs/token-list#19186]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
We need to add the tag stablecoin at UST

#17708 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by antoineherzog** [comment]
@keone please :)

**Comment by keone** [comment]
merged
