### ISSUE TITLE
Issue closed without answer

### ISSUE THREAD

**Issue by Kalizaaza** [solana-labs/token-list#19198]
I don't understand why the issue #19147 it was closed if I didn't get any answers...

**Comment by Kalizaaza** [comment]
?

**Comment by sachinbhoi29** [comment]
Same here bro, I even got merged comment, but still it didn't update my logo link :(

**Comment by Kalizaaza** [comment]
it's incredible!

**Comment by sachinbhoi29** [comment]
They merged mine today, so happy!

**Comment by Kalizaaza** [comment]
congrats bro!!!
happy for you!!
