### ISSUE TITLE
Issue, NEED HELP TO AUTOMERGE GLORY mint address #19128

### ISSUE THREAD

**Issue by GloriousXican** [solana-labs/token-list#19200]
- I'm submitting an issue because I need your help to auto merge the old information of the mint address of GLORY to the new address
  [ X] automerge

- **Summary**

- https://github.com/solana-labs/token-list/pull/19128

      },
    {
      "chainId": 101,
      "address": "HTr5SoWycrUdHbbrRQvxe9qhVraP196p8At7LrfPbpmr", INCORRECT AND OLD
      "address": "HmXgJwUzWfuvCZzUkbzVKYGggjjbq6qy1meKpPitj7Xu", CORRECT AND NEW
      "symbol": "GLORY",
      "name": "GLORIOUS GECKOS",
      "decimals": 6,
      "logoURI": "https://raw.githubusercontent.com/GloriousXican/ASSETS/main/coin-sglory.png",
      "tags": [
        "utility-token",
        "game-token",
        "game-currency",
        "GameFi",
        "Gaming"
      ],
      "extensions": {
        "twitter": "https://twitter.com/GeckosNFT",
        "website": "https://gloriousgeckos.com/"
      }

**Comment by keone** [comment]
added comment in PR

**Comment by keone** [comment]
closed due to inactivity, please reopen if this is still needed
