### ISSUE TITLE
add Sator_Logo.png

### ISSUE THREAD

**Issue by islaperfito** [solana-labs/token-list#1920]
- **I'm submitting a ...**
![Sator_Logo](https://user-images.githubusercontent.com/54420219/138305342-ee5d5c7a-d397-441a-844f-73b0652ec4ac.png)

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by SolDev-stack** [comment]
Please read the [SPL-token README](https://github.com/SolDev-stack/token-list/blob/main/README.md), and ensure your SPL-token info uses the correct [Uniswap format](https://github.com/SolDev-stack/token-lists/blob/main/README.md).

**Comment by keone** [comment]
Please submit a PR
