### ISSUE TITLE
Changing Logo / URL Challenges

### ISSUE THREAD

**Issue by k4y4rgh** [solana-labs/token-list#19222]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [x] question about the decisions made in the repository
  [x] question about how to use this project

- **Summary**

Looking to update the FRNT logo that was inputted wrong from the start. And possibly (but less important at this time) the website URL. I've forked and committed changes. It gets an automerge error, makes sense, but I'm just wanting to see what else can be done to move it forward. Thanks so much.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

PR: https://github.com/solana-labs/token-list/pull/19214
Commit: https://github.com/solana-labs/token-list/pull/19214/commits/057bdd03e93ef8f828ead46cd39b373c706a0943

**Comment by sachinbhoi29** [comment]
same here bro, updated incorrect logo and the bot doesn't support deleted line changes :(

**Comment by keone** [comment]
@k4y4rgh  merged
@sachinbhoi29 manual merge required; please open an issue to point us to it
