### ISSUE TITLE
Update twitter validation in auto merge

### ISSUE THREAD

**Issue by budbug7403** [solana-labs/token-list#19273]
- **I'm submitting a ...**
  [x] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

The twitter validation needs to be updated, for example [Cats on Crack](https://twitter.com/catsoncrack_) is a valid twitter handle but the current auto merge validation does not include '_' 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
- https://github.com/solana-labs/token-list/blob/1db8c79ccee5e216203c69d230be84b9db86472d/automerge/schema.cue#L107

**Comment by keone** [comment]
`\w` matches underscore

```
~/token-list/src/tokens  (main)$ grep twitter.com solana.tokenlist.json | grep \_ | wc
     530    1060   28536
```
