### ISSUE TITLE
[MANUAL REVIEW] I want to update my logo

### ISSUE THREAD

**Issue by sachinbhoi29** [solana-labs/token-list#19284]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [x] question about the decisions made in the repository
  [x] question about how to use this project

-  I want to update my logo link as the previous link was incorrect and not working, when I updated it, it failed to merge by the bot. It states that I have deleted a line.
-  I deleted my fork as it was failing to automerge, hope that is not an issue.
-  My PR request https://github.com/solana-labs/token-list/pull/19283

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged

**Comment by sachinbhoi29** [comment]
I can still see the old link, it's somehow not updated :(

**Comment by keone** [comment]
merged
