### ISSUE TITLE
[Manual Review] Change MYSTIC token address and decimal 

### ISSUE THREAD

**Issue by Lustrumi** [solana-labs/token-list#19281]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Hi there, I mistakenly created a token with decimal before.

Just need to replace the token address and decimal points. Thx.

https://github.com/solana-labs/token-list/pull/19280

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by sachinbhoi29** [comment]
Do you know how long does it take for manual review

**Comment by keone** [comment]
merged
