### ISSUE TITLE
[Manual Review] Update logo and tags

### ISSUE THREAD

**Issue by chris-hellon** [solana-labs/token-list#19316]
[ ] bug report
  [X] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

I'd like to update my logo and tags information, as these have changed since creation.

My PR is:

https://github.com/solana-labs/token-list/pull/19315

Thanks

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
