### ISSUE TITLE
changing token logo

### ISSUE THREAD

**Issue by DireWolfSolana** [solana-labs/token-list#19321]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [x] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I would like to update my token logo with the following;

PR https://github.com/solana-labs/token-list/pull/18003

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
you closed that PR already, but the problem its running into is explained in https://github.com/solana-labs/token-list#duplicate-token

**Comment by DireWolfSolana** [comment]
thank you for the help
sorry, i re-fork git, that caused PR to accidentally close.
i created new PR from new fork here is my new PR
https://github.com/solana-labs/token-list/pull/19332

Pada tanggal Sab, 19 Feb 2022 pukul 23.23 keone ***@***.***>
menulis:
