### ISSUE TITLE
[MANUAL REVIEW] still can't see my logo, changed the logo, please merge it with main branch, thanks

### ISSUE THREAD

**Issue by sachinbhoi29** [solana-labs/token-list#19341]
I'm submitting a ...
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository
[x] question about how to use this project

My logo doesn't appear,  so i had to chang my logo link and png file in assets. 
Deleted my old token who has incorrect token address and it was taking up the token name.
you can verify that the deleted token belongs to me as it has my github logo and the token address is incorrect.

My PR request https://github.com/solana-labs/token-list/pull/19283

Other information (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by Amayyuri** [comment]
I think it takes some time before it displays !

**Comment by sachinbhoi29** [comment]
thanks for the info

**Comment by sachinbhoi29** [comment]
is it not possible to merge :( ???

**Comment by keone** [comment]
merged

**Comment by sachinbhoi29** [comment]
Thanks a lot
Appreciate it!
