### ISSUE TITLE
Help with pull request for updating token logo

### ISSUE THREAD

**Issue by ketwebb** [solana-labs/token-list#19364]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ x] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
-  updating token #19348 I am not sure why this has failed auto merger. I just updated the image for my token. Any help?

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
- Used a branch from main which I want to add a change to my token location. I have only changed the file name in src/tokens/solana.tokenlist.json 
- Committed changed being:   from  "logoURI": "https://github.com/ketwebb/Sol_Tpken/blob/main/logo.png", to "logoURI": "https://raw.githubusercontent.com/ketwebb/Sol_Tpken/main/logo.png",

**Comment by keone** [comment]
merged
