### ISSUE TITLE
Help updating a token image URL and extension

### ISSUE THREAD

**Issue by mdtdnb** [solana-labs/token-list#19367]
- **I'm submitting a ...**
  [ ] bug report
  [X ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- Requesting to update token URL and adding extension. Link to pull request is: 
https://github.com/solana-labs/token-list/pull/19366

- **Other information** No changes to token address, name, or symbol are being made.

**Comment by keone** [comment]
added comment in PR

**Comment by keone** [comment]
linked PR was closed
