### ISSUE TITLE
Need help in solving Logo issue: Update AD2 Logo #19381 

### ISSUE THREAD

**Issue by asiandragoncoin** [solana-labs/token-list#19389]
- **I'm submitting a ...**
  [X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Having issue in getting logo to appear.
[Update AD2 Logo #19381](https://github.com/solana-labs/token-list/pull/19381) 
Please assist in looking into this. Followed all instructions accordingly, but give same result.

Reason ============
Not eligible for automerge
found removed line: - "logoURI":
============

Thank you

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
