### ISSUE TITLE
Automerge error for PR #19213

### ISSUE THREAD

**Issue by nickf12** [solana-labs/token-list#19407]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [X] question about how to use this project

-  Automerge error for pull request - [first commit for PFIN - Pecunia.Finance](https://github.com/solana-labs/token-list/pull/19213#issue-1143606578) 

- **Other information**
Got automerge error: found removed line: - "website": "https://questcoin.org/"
I don't see this line in the token-list.json

Can you please assist me with this?

**Comment by keone** [comment]
added comment in PR
