### ISSUE TITLE
Need help in solving Logo issue: Magika Token #19447

### ISSUE THREAD

**Issue by Hotel-Six** [solana-labs/token-list#19465]
- I'm submitting a change for Adding Magika Token #19447
  [ ] bug report
  [ ] feature request
  [ x] question about the decisions made in the repository
  [ x] question about how to use this project

I'm trying to change the picture for the token  I'm new to this and I can use some help 
here is the new URL for the token https://raw.githubusercontent.com/Hotel-Six/Mana-Token/main/Logo.png

**Comment by keone** [comment]
please leave the PR open so we can see what's wrong

**Comment by Hotel-Six** [comment]
Sorry I just I cant find the button to reopen

**Comment by keone** [comment]
automerged: https://github.com/solana-labs/token-list/pull/19508
