### ISSUE TITLE
Update Two Tokens PR #19477

### ISSUE THREAD

**Issue by gabrielhicks** [solana-labs/token-list#19478]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Add coingeckoId to BAPE token
Change HOZ token ID

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

I am the original author for both tokens.

**Comment by keone** [comment]
merged
