### ISSUE TITLE
[MANUAL REVIEW] Update ChikinCoin data and logo

### ISSUE THREAD

**Issue by ChikinDeveloper** [solana-labs/token-list#19487]
Hi! 
Here is the pull request :
[https://github.com/solana-labs/token-list/pull/19486/files](https://github.com/solana-labs/token-list/pull/19486/files)

Here is the initial commit for CKC :
`d01e051b2b3ce96a23e823f0b294c4ab6cea65f2`

**Comment by keone** [comment]
added comment on PR

**Comment by Ltei** [comment]
Hi! I made the requested changes

**Comment by keone** [comment]
thanks! merged
