### ISSUE TITLE
Changing HMTT Symbol

### ISSUE THREAD

**Issue by SolanaTokenMerger** [solana-labs/token-list#19534]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Please merge following PR https://github.com/solana-labs/token-list/pull/19533
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by gabriellahayden** [comment]
Are you still having issues fixing the bug issues?

**Comment by SolanaTokenMerger** [comment]
No bug issues, I just need to wait for Sir @keone to manually merge it!! Thank you @gabriellahayden!!

**Comment by gabriellahayden** [comment]
You can also manually merge it from there yourself

**Comment by keone** [comment]
merged
