### ISSUE TITLE
Add coingeckoid to DARC token #19145

### ISSUE THREAD

**Issue by leedc0101** [solana-labs/token-list#19531]
Hi Team ,
I need to update our token DARC Information
ADD coingeckoId "darcmatter-coin"

Please help us to merge this request
https://github.com/solana-labs/token-list/pull/19145

Having issue below
`Not eligible for automerge (click details for more information)
failed to normalize: failed to parse JSON: json: unknown field "coingeckoId"`

Our token already listed on COINGECKO
https://www.coingecko.com/en/coins/konstellation

Thank you

**Comment by keone** [comment]
merged
