### ISSUE TITLE
Need help in merging PR

### ISSUE THREAD

**Issue by heisenberglit** [solana-labs/token-list#19540]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ x] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Updated the logo of a token. Need help in merging the PR.

Token Name - NYN Token
Token Address -  NYNKnLDu1WRacDTmqvMburqc31reUWQSSmoh4MxE3FB

[#19459](https://github.com/solana-labs/token-list/pull/19459)

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by heisenberglit** [comment]
@keone Can you help merging this ?

**Comment by keone** [comment]
merged, sorry for delay

**Comment by heisenberglit** [comment]
Thanks man.
