### ISSUE TITLE
Trying to Change Logo:

### ISSUE THREAD

**Issue by czcr** [solana-labs/token-list#19578]
Trying again to change Logo #19570
I have tried multiple times to change the logo and the Auto Merge keeps rejecting it.
Please help.

**Comment by keone** [comment]
please reopen this and then we can merge it (we can't reopen it bc the branch was deleted)

**Comment by czcr** [comment]
oh...I have deleted the branch. Let me try to post another request and then update you here with that request number.
Thank you for your help
