### ISSUE TITLE
Trying to Change the Logo URL

### ISSUE THREAD

**Issue by andy-dey** [solana-labs/token-list#19579]
Trying again to change Logo URL #19572

I have tried multiple times to just change the Logo URL and Automerge is not accepting this.

Can I please request some to get this resolved. Please let me know if I am doing something wrong such that I can avoid this in future.

**Comment by keone** [comment]
added comment on PR

**Comment by czcr** [comment]
I have deleted the branch. Let me try to post another request and then update you here with that request number.
Thank you for your help
