### ISSUE TITLE
 Manual Review - update token CG and CMC #19616  by GonzaloAraujoC

### ISSUE THREAD

**Issue by GonzaloAraujoC** [solana-labs/token-list#19643]
'failed to normalize: failed to parse JSON: json: unknown field "coingeckoId"' 

Need help to update Token Info, i´m adding CMC, CG and Telegram info.
 
@keone  Can you help me? ... thanks.
 
Gonzalo.

**Comment by GonzaloAraujoC** [comment]
#19616 

The link of the PR ... thanks.

**Comment by keone** [comment]
merged
