### ISSUE TITLE
Can't update token info in solana.tokenlist.json file

### ISSUE THREAD

**Issue by nedrob** [solana-labs/token-list#1965]
- **I'm submitting a ...**
  [X ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I am trying to update the logo path in the solana.tokenlist.json file but get the error "Error: Pull request should not contain any deletions." I believe that this is because that file doesn't allow any edits to be made once the original info is merged. 

This means that if you make a mistake in the tokenlist file, you can't fix it. If the URL to your token or some other info changes, they you are stuck and would have to re-mint your token. This seems very restrictive. 

Can someone please let me know if there's a work-around?

Thanks. 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by SolDev-stack** [comment]
Please read the [SPL-token README](https://github.com/SolDev-stack/token-list/blob/main/README.md), and ensure your SPL-token info uses the correct [Uniswap format](https://github.com/SolDev-stack/token-lists/blob/main/README.md).

**Comment by keone** [comment]
You are correct, this requires manual review. Please link a PR
