### ISSUE TITLE
Update SLGT

### ISSUE THREAD

**Issue by jdomingospt** [solana-labs/token-list#19653]
Update SLGT tags

Original Pull Request: https://github.com/solana-labs/token-list/pull/19505
New Pull Request: https://github.com/solana-labs/token-list/pull/19652

Thanks

**Comment by keone** [comment]
the new PR is closed, please reopen it

**Comment by jdomingospt** [comment]
New pr: https://github.com/solana-labs/token-list/pull/19908
@keone

**Comment by keone** [comment]
merged
