### ISSUE TITLE
update MOSC 

### ISSUE THREAD

**Issue by jdomingospt** [solana-labs/token-list#19656]
Update MOSC tags

New Request: https://github.com/solana-labs/token-list/pull/19655
Last Update Request: https://github.com/solana-labs/token-list/pull/19080
Original Request: https://github.com/solana-labs/token-list/pull/17614

thanks!

**Comment by keone** [comment]
the new PR is closed, please reopen it

**Comment by jdomingospt** [comment]
new PR: https://github.com/solana-labs/token-list/pull/19905

**Comment by keone** [comment]
merged
