### ISSUE TITLE
Logo issue

### ISSUE THREAD

**Issue by andres-perez21** [solana-labs/token-list#19659]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- I changed my logo location and size and it is giving me an error. 

- https://github.com/solana-labs/token-list/pull/19630/commits/af190f0a85898920a4973d9e30df5e3b0109c061

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
please link a PR, not just a commit
