### ISSUE TITLE
Change DIRE token logo

### ISSUE THREAD

**Issue by DireWolfSolana** [solana-labs/token-list#19688]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [x] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
i try to change my token logo, commit able to merge and no conflicts but automerge error
here my PR https://github.com/solana-labs/token-list/pull/19332

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged

**Comment by DireWolfSolana** [comment]
thank you for the help

Pada tanggal Rab, 23 Feb 2022 pukul 11.57 keone ***@***.***>
menulis:
