### ISSUE TITLE
automerge error

### ISSUE THREAD

**Issue by sunnysideup72** [solana-labs/token-list#19694]
- **I'm submitting a ...**
  [ ] bug report
  [V] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Add AHA Token #19687

I tried more than 4 times and always automerge error 
please help me.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged; you were right to ask for manual review, the explanation is here: https://github.com/solana-labs/token-list#error-validating-schema-chainid-conflicting-values-103-and-0
