### ISSUE TITLE
pull request!!

### ISSUE THREAD

**Issue by ArcryptianNFT** [solana-labs/token-list#19693]
- **I'm submitting a ...**
  [ ] bug report
  [ x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
please  manually review my pull request. i dont know why it failed i need to add the $arc Token

https://github.com/solana-labs/token-list/pull/19692 PLEASE AND THANK YOU!!!

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
`duplicate token: token address AWLDWua47fVu5f8uxiCCLJPXBJAdsyRM11fESt8jRceo is already used`
explanation: https://github.com/solana-labs/token-list#duplicate-token
