### ISSUE TITLE
Removed unwanted entry #19728

### ISSUE THREAD

**Issue by rakshpma** [solana-labs/token-list#19730]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project
  [*] approval request for removing an entry from tokenlist.json

- **Summary**
Removed unwanted entry #19728
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
we had added couple of entries which are not required any more. these are safe to be deleted. Kindly review and approve the request.

**Comment by keone** [comment]
merged
