### ISSUE TITLE
Change my website link on my token pls

### ISSUE THREAD

**Issue by DemonKingdomNFT** [solana-labs/token-list#19752]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Hey I want to change my site in my token to :  https://demonkingdomnft.com/  #19719

**Comment by keone** [comment]
please make the change to solana.tokenlist.json and open a PR with this change

**Comment by DemonKingdomNFT** [comment]
My PR  https://github.com/solana-labs/token-list/pull/19719 

@keone
