### ISSUE TITLE
Automerge error for name 

### ISSUE THREAD

**Issue by running0x** [solana-labs/token-list#19769]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Our token name was originally rejected for using a symbol. We submitted another PR with updated name which was auto-closed just now - can it be reopened and merged? it is here ---> [Adding JFICall token #19755](https://github.com/solana-labs/token-list/pull/19755)

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
this was automerged and is in main now:

```

$ grep etCPUaMghWobVwxug5Vgxb6r3A7DEBdLKUywrnDrJeZ solana.tokenlist.json
      "address": "etCPUaMghWobVwxug5Vgxb6r3A7DEBdLKUywrnDrJeZ",
      "logoURI": "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/etCPUaMghWobVwxug5Vgxb6r3A7DEBdLKUywrnDrJeZ/logo.png",
```
