### ISSUE TITLE
Automerge error, adding token image and metadata

### ISSUE THREAD

**Issue by bootycoin69** [solana-labs/token-list#19763]
[- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)]
- 
- (https://github.com/solana-labs/token-list/commit/266c5af1064f16cdd66bd3ca56877b96e618efab)

**Comment by keone** [comment]
i think this is your PR?  https://github.com/solana-labs/token-list/pull/19745
it's failing to automerge due to a conflict; please follow the suggestion in https://github.com/solana-labs/token-list#warning-about-the-last-element-in-the-list and squash your commits into a single commit
