### ISSUE TITLE
Automerge error for closing PR abruptly and retrying

### ISSUE THREAD

**Issue by running0x** [solana-labs/token-list#19771]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Yesterday we submitted a PR for JFI-USDC, but we used the wrong token address. We quickly closed the PR, but the automerge bot flag had already been applied. Now the automerge will not correctly work. We would like to add our JFI-USDC token at the correct address with this PR --> https://github.com/solana-labs/token-list/pull/19658

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
okay
removed the other one in https://github.com/solana-labs/token-list/pull/19803

**Comment by keone** [comment]
merged #20516
