### ISSUE TITLE
Update SoldierXSolvivor Coin (SXS)

### ISSUE THREAD

**Issue by davigmacode** [solana-labs/token-list#19789]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
  I would like to remove a tag from my token info
  Update PR #19787
  Original PR #13970

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
`duplicate token: token address Ct7mbdwLmdFC6zgVRXFidvvgYbtGo2icsntNSSgzxoLs is already used`
explanation: https://github.com/solana-labs/token-list#duplicate-token

**Comment by davigmacode** [comment]
Changed PR to #19854 

Thanks

**Comment by keone** [comment]
merged
