### ISSUE TITLE
Modifying Existing Token 

### ISSUE THREAD

**Issue by Cyborg-Alpha** [solana-labs/token-list#19814]
- **I'm submitting a ...**
  [ ] bug report
  [X] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I am trying to modify my token address.
The PR link is https://github.com/solana-labs/token-list/pull/19227
Please see update to recent commit. 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
