### ISSUE TITLE
[Manual Merge Request] - Updating CHIMP token data

### ISSUE THREAD

**Issue by tsbsoltn** [solana-labs/token-list#19835]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- 
Need help in merging my PR (https://github.com/solana-labs/token-list/pull/19830) manually, as I'm getting auto-merge error because of the json element `telegram`

ERROR - `failed to normalize: failed to parse JSON: json: unknown field "telegram"`

PR Change: Added Twitter & Telegram extensions.

CC: @keone

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
