### ISSUE TITLE
manual merge request

### ISSUE THREAD

**Issue by aagusti1974** [solana-labs/token-list#19863]
- **I'm submitting a ...**
  [ ] bug report
  [] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Please need manual intervention to merge PR [19860](https://github.com/solana-labs/token-list/pull/19860) 
error reason is always : error validating schema: chainId: conflicting values 103 and 0 keeps
- **Other information** 
Tried twice modifying file src/token/solana.tokenlist.json differently but some "diff" at end of file keeps blocking the PR

**Comment by keone** [comment]
merged
