### ISSUE TITLE
add logo

### ISSUE THREAD

**Issue by Producenftguy** [solana-labs/token-list#19881]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
![logo](https://user-images.githubusercontent.com/99229705/155407425-0f3383cc-f77d-42e3-830e-be08e833b144.png)

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
to make changes, make a commit implementing the change, then submit a PR and link it here

**Comment by Producenftguy** [comment]
> to make changes, make a commit implementing the change, then submit a PR and link it here

thank you for that!
