### ISSUE TITLE
add Scythe Token 

### ISSUE THREAD

**Issue by Amayyur** [solana-labs/token-list#19893]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
this was automerged: https://github.com/solana-labs/token-list/pull/19892
