### ISSUE TITLE
https://github.com/solana-labs/token-list/pull/19927

### ISSUE THREAD

**Issue by AzEe416** [solana-labs/token-list#19928]
- **I'm submitting a ...**
  [ ] bug report
  [x ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

please approve!! thanks

**Comment by AzEe416** [comment]
Please work !!! ARC NAMING #19929
 please check and merge.. been trying for days now lol

**Comment by keone** [comment]
please see https://github.com/solana-labs/token-list#duplicate-token
this PR includes a 2 commits, one of which is already landed (creating your token)
also please leave your PR open, as we can't manually merge closed PRs
