### ISSUE TITLE
Modify token (removing "nft" tag)

### ISSUE THREAD

**Issue by nuttydev** [solana-labs/token-list#19946]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Trying to remove the NFT tag (I misunderstood what it meant so it messes up our utility-token as it is now being shown as an NFT).
I'm quite a github noob so wasn't sure how to "squash commits into a single commit for cleanliness" - I apologize for any inconviences it may cause.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Link to new PR (which removes "nft" tag): https://github.com/solana-labs/token-list/pull/19944

Link to original PR (which added the token): https://github.com/solana-labs/token-list/pull/19832

**Comment by keone** [comment]
https://github.com/solana-labs/token-list/blob/main/README.md#duplicate-token

**Comment by nuttydev** [comment]
Sorry for my mistake! This new PR should be correct: https://github.com/solana-labs/token-list/pull/20352

**Comment by nuttydev** [comment]
> https://github.com/solana-labs/token-list/blob/main/README.md#duplicate-token

Sorry for my mistake @keone ! This new PR should be correct: https://github.com/solana-labs/token-list/pull/20352

**Comment by keone** [comment]
merged
