### ISSUE TITLE
trying to change website link

### ISSUE THREAD

**Issue by DemonKingdomNFT** [solana-labs/token-list#19943]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Hey please change the website link mentioned in #19743 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by DemonKingdomNFT** [comment]
@keone

**Comment by keone** [comment]
duplicate token: token address 6VnsFohk6CQbaXoPTiQr5bHruEnuCqg94iwmnwrUj72M is already used
explanation / how to fix: https://github.com/solana-labs/token-list#duplicate-token
