### ISSUE TITLE
Can't update token list

### ISSUE THREAD

**Issue by MapMetrics** [solana-labs/token-list#1995]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I am trying to update the logo path in the solana.tokenlist.json file but get the error "Error: Pull request should not contain any deletions." 

Can someone please update the MMaps token to the right format 
    {
      "chainId": 101,
      "address": "EFqYVEitSUpUTj2d9LSqun4eZ4BzouFuTPqQzU4hNtsS",
      "symbol": "MMaps",
      "name": "MapMetrics",
      "decimals": 6,
      "logoURI": "https://raw.githubusercontent.com/solfinaprotocol/token-list/main/assets/mainnet/EFqYVEitSUpUTj2d9LSqun4eZ4BzouFuTPqQzU4hNtsS/logo.png",
      "tags": [
        "utility-token",
        "Community",
        "NFT"
      ],
      "extensions": {
        "website": "https://mapmetrics.org/"
      }
    },

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by SolDev-stack** [comment]
Please read the [SPL-token README](https://github.com/SolDev-stack/token-list/blob/main/README.md), and ensure your SPL-token info uses the correct [Uniswap format](https://github.com/SolDev-stack/token-lists/blob/main/README.md).

**Comment by keone** [comment]
If this is still an issue, please link a PR and reopen this!
