### ISSUE TITLE
Remove NFT from tags and include website and the discord for extensions

### ISSUE THREAD

**Issue by codenjobs** [solana-labs/token-list#19964]
- **I'm submitting a ...**
  [ ] bug report
  [x ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Hi there,

We would like to have the nft tag removed and our website and the discord channel included for the token metadatas.

The PR is at https://github.com/solana-labs/token-list/pull/19963

Thanks

**Comment by keone** [comment]
merged
