### ISSUE TITLE
Change Token Logo 

### ISSUE THREAD

**Issue by Kurizilla** [solana-labs/token-list#20023]
- I'm submitting a ...
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

Hi there,

I would like to have the token logo changed.

The PR is https://github.com/solana-labs/token-list/pull/20018

Thanks

**Comment by keone** [comment]
this was added by @Acumen-Protocol in https://github.com/solana-labs/token-list/pull/13584
@Acumen-Protocol can you please reply approving this change?

**Comment by Acumen-Protocol** [comment]
> this was added by @Acumen-Protocol in #13584 @Acumen-Protocol can you please reply approving this change?

Aprroved

**Comment by keone** [comment]
merged
