### ISSUE TITLE
MIKI token #19950

### ISSUE THREAD

**Issue by MagicGaric** [solana-labs/token-list#20022]
Please merge https://github.com/solana-labs/token-list/pull/19950

**Comment by MagicGaric** [comment]
Action taken: website link was deleted because website is not active yet.

**Comment by MagicGaric** [comment]
Any luck here? 
Just trying to add a token. Nothing crazy. 

Thank you.

**Comment by MagicGaric** [comment]
@keone

**Comment by keone** [comment]
sorry for the delay; the main issue is that your commit removes several other peoples' tokens: https://github.com/solana-labs/token-list/pull/19950/files
fix that and then it should automerge, but if it doesn't feel free to tag me here

**Comment by MagicGaric** [comment]
@keone I added the lines back, but it didn't automerge.

**Comment by keone** [comment]
looking at https://github.com/solana-labs/token-list/pull/19950/files, there is still:
* a whitespace diff on those lines you added bakc
* a permissions change from 100644 to 100755
please fix those and then it should automerge (but if it doesn't i can manually merge)

**Comment by MagicGaric** [comment]
@keone I removed the whitespace. 
Now I don't see any side effects in the "Files changed".
Could you please merge it manually?

**Comment by keone** [comment]
did you see the part about the permissions?

**Comment by MagicGaric** [comment]
@keone Could you please provide guidance regarding this permission change?
I am not sure how to change it.

**Comment by MagicGaric** [comment]
@keone permissions changed. 
Please let me know if you see something else, otherwise let's merge.

**Comment by MagicGaric** [comment]
@keone could you please let me know what should be done to proceed?

**Comment by keone** [comment]
https://github.com/solana-labs/token-list/pull/19950/files
now it looks like you changed the permissions of a bunch of files
my point was, just make sure no files' permissions change in your commit

**Comment by keone** [comment]
it was just easier for me to fix it directly, so I submitted this PR:
https://github.com/solana-labs/token-list/pull/20476
it should automerge momentarily

**Comment by MagicGaric** [comment]
You are the best @Keone. 
Thank you for ending my suffering.

**Comment by keone** [comment]
closing this ticket a #20476 automerged successfully
