### ISSUE TITLE
MODIFICATION OF AZA TOKEN'S ADRESS: commit 22ca5b00a1a55cd70e574d712c10caface9d02a0

### ISSUE THREAD

**Issue by Kalizaaza** [solana-labs/token-list#20046]
- **I'm submitting a  modification of AZA TOKEN's address

- **Summary**
-  i minted with an address and I sent the information on the Solana Token Registry with the same address but the first letter is a capital letter. Now i want edit the right adress token

- **Other information**
- https://github.com/solana-labs/token-list/commit/22ca5b00a1a55cd70e574d712c10caface9d02a0
- commit 22ca5b00a1a55cd70e574d712c10caface9d02a0
- Look at these two addresses:
https://explorer.solana.com/address/Ax7EjwgRaerUacfCAptcMnkckmf8Wiee5T9KLqSzsF6
https://explorer.solana.com/address/ax7EjwgRaerUacfCAptcMnkckmf8Wiee5T9KLqSzsF6 (mint address)

**Comment by Kalizaaza** [comment]
I don't know why the issue is closed if i haven't answers

**Comment by keone** [comment]
Fixed by #20036
You opened many duplicates

**Comment by Kalizaaza** [comment]
ok i understand
