### ISSUE TITLE
https://github.com/solana-labs/token-list/pull/19988

### ISSUE THREAD

**Issue by Apollo2006** [solana-labs/token-list#20042]
- **I'm submitting a ...**
  [ ] modification of TERP TOKEN's address and decimal place

- **Summary**
- I am the creator of the TERPS TOKEN and want to edit its token address and its decimal place
https://github.com/solana-labs/token-list/pull/19988

**Comment by keone** [comment]
added comment in PR

**Comment by Apollo2006** [comment]
@keone how long can it take for this to be updated?

**Comment by keone** [comment]
read my comment in the PR

**Comment by Apollo2006** [comment]
Does that mean the other one is duplicate and this is original? 
And it doesn't seem like my tokens data is updated.

**Comment by keone** [comment]
it means that in the current state, the new one is a duplicate and is being rejected

so if you want to bring in the new one, you need to delete the old one

**Comment by Apollo2006** [comment]
I thought deleting the code wasn't allowed since no deletion is merged, isn't modifying only allowed for this?

**Comment by keone** [comment]
both deletion and modification require manual merge.

i don't care which you do, but like i said in the comment in the PR, your current action is not modifying, it is simply adding a new entry which collides with the existing

**Comment by Apollo2006** [comment]
can i clone it again and edit the token address and its decimal place only and do a PR?

**Comment by keone** [comment]
yep!

**Comment by Apollo2006** [comment]
alright thanks!
