### ISSUE TITLE
pull request  #20052 

### ISSUE THREAD

**Issue by loosebucks** [solana-labs/token-list#20061]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ X] question about the decisions made in the repository
  [ ] question about how to use this project

- **I belive my pull request was approved because none of my steps came back rejected but i wanted to know typically how long it takes for the change to reflect onto phantom wallet and other wallets?**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
https://github.com/solana-labs/token-list#scannerwallet-hasnt-updated-yet
