### ISSUE TITLE
Want to remove the token submitted PR #20064

### ISSUE THREAD

**Issue by ash-ve25** [solana-labs/token-list#20076]
- **I'm submitting a ...**
  [ - ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I want to remove the token listed, I created the token with 9 decimals but it should be 0 and the image needs to be updated too.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
PR #20064

https://solscan.io/token/8YLVNaqXNL77NrW8J56SgT2ibUk1nekXAARz2TtBrenS
<img width="1361" alt="Screenshot 2022-02-25 at 7 00 12 PM" src="https://user-images.githubusercontent.com/3694876/155723532-ba3260ab-7570-45a2-a52b-fcf23e135dd5.png">
<img width="639" alt="Screenshot 2022-02-25 at 6 59 16 PM" src="https://user-images.githubusercontent.com/3694876/155723538-c2c75a40-6001-4f3a-bc7d-bfa3e1fb0e98.png">

**Comment by keone** [comment]
please submit a PR deleting that token and link it here

**Comment by ash-ve25** [comment]
Submitted the delete PR 
https://github.com/solana-labs/token-list/pull/20542

**Comment by keone** [comment]
merged, thanks
