### ISSUE TITLE
Rename STIMMY to SER Token

### ISSUE THREAD

**Issue by garrettbear** [solana-labs/token-list#20140]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Quick token rename. I submitted the original PR. 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
[https://github.com/solana-labs/token-list/pull/20139](https://github.com/solana-labs/token-list/pull/20139)

**Comment by keone** [comment]
merged
