### ISSUE TITLE
Update Fraydey Coin logo image

### ISSUE THREAD

**Issue by cyberspyde** [solana-labs/token-list#20168]
- **I'm submitting a ...**
  [ ] bug report
  [X ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Please check my coin logo, Fraydey COIN, it has been closed with auto-merge, Name, website, and information is changed, but the logo doesn't show up, its size is normal, and the logo is completely normal, why it doesn't show on my coin details on SolScan? I don't know what to do
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions on how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Update : [#20176](https://github.com/solana-labs/token-list/pull/20317)
Original : #20121[](https://github.com/solana-labs/token-list/pull/20121)

I have updated the commits, please check the update

**Comment by keone** [comment]
merged
