### ISSUE TITLE
Updates MARS WL Token Asset

### ISSUE THREAD

**Issue by musicdevghost** [solana-labs/token-list#20181]
- **I'm submitting a ...**
  [ ] bug report
  [x ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I would like to update MARS WL Token image.

Change:
Updates MARS WL Token Asset

Reference PRs:
Update PR: https://github.com/solana-labs/token-list/pull/20180
Original PR: https://github.com/solana-labs/token-list/pull/19409

- **Other information** 
Author: https://github.com/musicdevghost

**Comment by keone** [comment]
squashed and merged
