### ISSUE TITLE
I am updating the Logo path of my existing ODSY token but its not getting automerged

### ISSUE THREAD

**Issue by soutrikdeylive** [solana-labs/token-list#20217]
I'm submitting a ...
    [x] bug report
    [ ] feature request
    [ ] question about the decisions made in the repository
    [ ] question about how to use this project

    Summary

Hi,

I want to update token LOGO. I am updating the LOGO path of my existing ODSY token but its not getting automerged. Only the logo and LOGO path is updated but its not getting automerged.
PR https://github.com/solana-labs/token-list/pull/20204

Can you manual check please ?

Thanks in advance

_Originally posted by @soutrikdeylive in https://github.com/solana-labs/token-list/issues/20204#issuecomment-1052148764_

**Comment by keone** [comment]
merged
