### ISSUE TITLE
Build fails on website validation

### ISSUE THREAD

**Issue by musicdevghost** [solana-labs/token-list#20223]
- **I'm submitting a ...**
  [x ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
While trying to add a token, build keeps failing on website validation, I've used the same website before on other token it's already in current existing json file, nothing is wrong with website (to my knowledge) so something on validation side?

Website is: https://www.martianarmy.space

Build: https://github.com/solana-labs/token-list/pull/20214/checks?check_run_id=5345058535
PR: https://github.com/solana-labs/token-list/pull/20214

- **Other information**
Error: 
failed to verify website: https://www.martianarmy.space/: failed to verify https://www.martianarmy.space/ using HEAD request: context deadline exceeded

**Comment by keone** [comment]
weird
merged
