### ISSUE TITLE
Pull request build error #20266 to fix logo and socials

### ISSUE THREAD

**Issue by CryptoPique** [solana-labs/token-list#20268]
I'm submitting a ...
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

Summary
Logo was not showing after 1 day so i've updated the logo path and added socials as extensions.
Pull request got an error error: Build / build (pull_request) Failing after 1m — build (yarn error code 1)

Can someone help or advise?

- **Summary**

- **Other information** tryed to fix it but nothing to do, can't find the error. Pull request #20266

**Comment by keone** [comment]
added comment in PR
