### ISSUE TITLE
Logo Change for GoobyQuest

### ISSUE THREAD

**Issue by GoobyFRS** [solana-labs/token-list#20276]
Hello Solana Devs,
I created the token GoobyQuest back on December 16th 2021 here: https://github.com/solana-labs/token-list/pull/8688

But I somehow forgot to update the image link when I was following along with the NetworkChuck video

I have submitted a new PR here to fix this icon: https://github.com/solana-labs/token-list/pull/8816

Thank you for your help getting this fixed. My friends and family have started to trade around my token and keep asking why it says "K K Keith Koin" and yeah... hard to explain lol

Happy Saturday, GoobyFRS

**Comment by keone** [comment]
merged
