### ISSUE TITLE
Update: Remove nft tag from tokens PR #20284

### ISSUE THREAD

**Issue by gabrielhicks** [solana-labs/token-list#20285]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Update: Remove nft tag from tokens PR #20284

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
