### ISSUE TITLE
Manual Merge Pull Request #20283, error "chainId: conflicting values 103 and 0"

### ISSUE THREAD

**Issue by stevedsimkins** [solana-labs/token-list#20287]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project 

- **Summary**
Please manually merge pull request #20283, error was from deleted/added bracket at the bottom of the list resulting in "chainId: conflicting values 103 and 0" 

Please and thank you! 😁✨

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
