### ISSUE TITLE
Manual Merge PR#20293

### ISSUE THREAD

**Issue by cryptocurrencyinstitution** [solana-labs/token-list#20297]
- **I'm submitting a ...**
  [ x] bug report
  [x ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
error validating schema: chainId: conflicting values 103 and 0
This automerge error arises if you touched a line outside of your token block. Some text editors introduce a diff to the final line of the file.

These currently need to be manually merged; please submit an issue and link your PR.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
#20293 is closed
please leave it open so it can be manually merged if necessary
