### ISSUE TITLE
token approved and then removed? 

### ISSUE THREAD

**Issue by SolFrogsNFT** [solana-labs/token-list#2030]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [x ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
We added the token:

address: DhuzmUvC4YTRDJwFfPSynDCGaJcMotnqjdNcGeFFrQSD
name: Lilypad
symbol: PAD

It merged successfully and seemed to be approved within a few days - the name and logo was viewable on Solana explorer. However that does not seem to be the case anymore and it has gone back to being an unknown token with no logo. 

Is this normal in the process? or has it not been approved or bugged?

thanks

**Comment by SolDev-stack** [comment]
Please read the [SPL-token README](https://github.com/SolDev-stack/token-list/blob/main/README.md), and ensure your SPL-token info uses the correct [Uniswap format](https://github.com/SolDev-stack/token-lists/blob/main/README.md).

**Comment by keone** [comment]
it seems fine in https://solscan.io/token/DhuzmUvC4YTRDJwFfPSynDCGaJcMotnqjdNcGeFFrQSD
