### ISSUE TITLE
Manual review requested for PR #18317

### ISSUE THREAD

**Issue by Kalizaaza** [solana-labs/token-list#20318]
- **I'm submitting a ...**
  [ ] bug report
  [x ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
      Requesting an update to adress token (change one uppercase letter for one lowercase letter)

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
     Link to my PR: https://github.com/solana-labs/token-list/pull/18317

**Comment by keone** [comment]
this diff adds many new entries (repeated for the same address): https://github.com/solana-labs/token-list/pull/18317/files
