### ISSUE TITLE
Manual submit requested https://github.com/solana-labs/token-list/pull/20295

### ISSUE THREAD

**Issue by MMarleen** [solana-labs/token-list#20338]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project
 manual submit request.

- **Summary**
- I added the wrong URL when I initially added 'MolleCoin' and want to change the URL now to the correct one.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
https://github.com/solana-labs/token-list/pull/20295
personal fork: https://github.com/MMarleen/token-list

**Comment by keone** [comment]
merged
