### ISSUE TITLE
FIX MY LINK

### ISSUE THREAD

**Issue by DemonKingdomNFT** [solana-labs/token-list#20334]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Pull request #20333 
update link sir
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
