### ISSUE TITLE
Manual Merge Request for PR #20339

### ISSUE THREAD

**Issue by dukemtambo** [solana-labs/token-list#20341]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project
  [x] manual submit request

- **Summary**
- I added the wrong twitter username when I initially added 'Wezesha Token' and want to change the twitter username now to the correct one.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
https://github.com/solana-labs/token-list/pull/20339
Personal fork: https://github.com/dukemtambo/token-list

**Comment by keone** [comment]
merged
