### ISSUE TITLE
Manuel merge Request to make corrections in PR  #20409

### ISSUE THREAD

**Issue by BabyMenace** [solana-labs/token-list#20410]
- **I'm submitting a ...**
[X] Manuel Merge request

- **Summary**
When the tokens were first submitted not all the proper information was included. I am requesting a Manuel Merge of the changes listed below.  Thank You,

For Menace Token: NfZUsY5ZqdJFxcKjYxA3KgibKEP5wTUDNdCXJ43dtVo
-Change Name from BabyMenace to "MENACE"
-Repoint - logoURI to menacelogo.png
-Add Twitter and website link

For Chaos Token: 7pJ3ov6LZTgc4pxkWg8vopGEvYvjjYmfiZUjygMhQxKh
-Add website link

**Comment by keone** [comment]
merged
