### ISSUE TITLE
Manual merge required for #20177

### ISSUE THREAD

**Issue by Bernardvdv** [solana-labs/token-list#20431]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Can you please review PR #20177 as I had to update the logo URL.

https://github.com/solana-labs/token-list/pull/20177

**Comment by keone** [comment]
merged
