### ISSUE TITLE
PIQSOL Update, Pull Request #20463

### ISSUE THREAD

**Issue by bashforger** [solana-labs/token-list#20468]
**I'm submitting a ...**
  [ ] bug report
  [X] **feature request**
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

### Summary

[This pull request](https://github.com/solana-labs/token-list/pull/20463) is a patch to [prior pull request](https://github.com/solana-labs/token-list/pull/19155) created a few days ago. By accident instead of listing [mint address](https://explorer.solana.com/address/GVvSwwQDpqWTQu739vqatKyyCXan7G1fibU9d5cXvXeX/instructions), wallet [public address](https://explorer.solana.com/address/6TXTxd67i2218CW9uN9H9gSqa4N6oWHUNSA7PFUZronv) was listed in the token address field.

The list of changes are:
- [mint address](https://explorer.solana.com/address/GVvSwwQDpqWTQu739vqatKyyCXan7G1fibU9d5cXvXeX/instructions) updated
- Icon Updated because of Deformation in the wallet
- Tag added "nft-marketplace"
- Link to [official website](https://piqsol.com) added, other links can be verified from the website

Hope I listed everything you need, if you need any further input from my side, let me know. 
Thank you in advance.

**Comment by keone** [comment]
merged
thanks for the thorough links back to creation PR
