### ISSUE TITLE
Please update arauc token logo - PR number #20460

### ISSUE THREAD

**Issue by ffurtuoso** [solana-labs/token-list#20461]
- **I'm submitting a ...**
  [ ] bug report
  [X] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged

**Comment by ffurtuoso** [comment]
thanks @keone
