### ISSUE TITLE
Changing   Name : Parlay Coin to Parlay

### ISSUE THREAD

**Issue by WhiteElephantEco** [solana-labs/token-list#20473]
- **I'm submitting a ...**
  [ ] bug report
  [x ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

Please Accept my PR request For Changing the Token Name Thank you Here's my PR : https://github.com/solana-labs/token-list/pull/20472

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
you switched the file to `logo.png` but didn't update the `logoURI` in `solana.tokenlist.json`

**Comment by WhiteElephantEco** [comment]
@keone  hello sir i update the logoURI in solana.tokenlist.json and change the logo also please accept my request for changing the token name from" Parlay Coin" into "Parlay" Thank you.

**Comment by keone** [comment]
merged
