### ISSUE TITLE
Updates not in Effect, Pull request #20463

### ISSUE THREAD

**Issue by bashforger** [solana-labs/token-list#20481]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [X] question about how to use this project

### Summary

I have just updated the [Token](https://explorer.solana.com/address/GVvSwwQDpqWTQu739vqatKyyCXan7G1fibU9d5cXvXeX) Icon, links, and Mint Address. But unable to see changes in effect after 1+ Hours, neither in [Solana Explorer](https://explorer.solana.com/address/6TXTxd67i2218CW9uN9H9gSqa4N6oWHUNSA7PFUZronv) nor in the wallet. 

The list of changes made is listed in detail in [this issue](https://github.com/solana-labs/token-list/issues/20468).

Considering that I have a few innocent questions:
- How this project reflects on-chain data and allows edit access to these features on Solana.
- How much time it usually takes for changes to take effect in explorer & wallets?
- Are there any further steps needed to be performed in order for it to work properly?
- Am I missing anything in the process?

Let me know if you need further details from me regarding changes.

My thanks & Regards.

**Comment by keone** [comment]
https://github.com/solana-labs/token-list#scannerwallet-hasnt-updated-yet might help

**Comment by bashforger** [comment]
It's updated @keone it just took a while. Thanks
