### ISSUE TITLE
Manual merge - PR #20489

### ISSUE THREAD

**Issue by daishizenSensei** [solana-labs/token-list#20498]
Hello,

I'm trying to add our Token. We sent a pull request but we've an error : error validating schema: chainId: conflicting values 103 and 0
https://github.com/solana-labs/token-list/pull/20489

Can we merge manually? I tryed all.

Thank you

**Comment by keone** [comment]
added comment in PR

**Comment by daishizenSensei** [comment]
> added comment in PR

Hello, It's okay you can now manually merge :)

**Comment by keone** [comment]
merged
