### ISSUE TITLE
Icon change PR #20438

### ISSUE THREAD

**Issue by alexserra** [solana-labs/token-list#20506]
- **I'm submitting a ...**
  [ x] feature request

- **Summary**
good afternoon,
I have created a Solana token and I have put the wrong link to the image logo.
I have submitted a PR but it is not possible to auto-merge. can you please help me and merge it or tell me what to do with it in order to make it merge?

thanks a lot for your help!

Alessandro

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by alexserra** [comment]
if possible can you please also explain to me what did I do wrong? how should I submit a change in some of the features in the future?

thanks again!
Alessandro

**Comment by keone** [comment]
https://github.com/solana-labs/token-list#duplicate-token describes your issue
in particular look at https://github.com/solana-labs/token-list/pull/20438/commits - it includes 2 commits - it should only include the later one

**Comment by alexserra** [comment]
thanks @keone for your answer!

**Comment by keone** [comment]
https://github.com/solana-labs/token-list#duplicate-token also describes how to resolve :)

**Comment by keone** [comment]
it doesnt seem like you force-pushed to https://github.com/alexserra/token-list, can you confirm that origin points to that repo?

**Comment by alexserra** [comment]
good afternoon @keone.

yes it is

**Comment by alexserra** [comment]
here is the details to be super clear.
![image](https://user-images.githubusercontent.com/14082311/156428248-4c315aee-3d36-4aed-b6dd-754dfe29ec9b.png)

**Comment by keone** [comment]
understood, but that's still not what your PR does at this point in time: https://github.com/solana-labs/token-list/pull/20438/files
not sure what you're doing wrong but i'm just going to do it manually

**Comment by keone** [comment]
fixed in #20724

**Comment by xLoopCreativeAndyx** [comment]
Hey @alexserra Ive the same issue that you had can you pls explain to me what you did to fix the dupicate token error im so lost i dont have any ubunto skills you can assist me here or on dis rianlux13  | Invoker#6755
