### ISSUE TITLE
Request for Manual merge

### ISSUE THREAD

**Issue by Apollo2006** [solana-labs/token-list#20528]
- **I'm submitting a ...**
  [ .] request for the deletion of my token #20524 

- I want to delete my token and recreate it due to some issues with the token.
- https://github.com/solana-labs/token-list/pull/20524
-

**Comment by keone** [comment]
this doesn't delete TERP: see https://github.com/solana-labs/token-list/pull/20524/files to observe the impact

why?  because your PR includes both the 'add' and the 'delete' commit: https://github.com/solana-labs/token-list/pull/20524/commits

it needs to only contain the 'delete'

**Comment by Apollo2006** [comment]
My fork is behind and when I try to find the old token its not there, is there a way to fork it again with all the new PR and stuff?

Im trying to modify and delete the old token but its not in my forked repository

**Comment by keone** [comment]
as i mentioned in your other ticket, look at https://github.com/solana-labs/token-list#duplicate-token.  it contains instructions on how to rebase your fork back onto the latest version of main, which is exactly the problem you are describing

**Comment by keone** [comment]
forget it, i fixed it for you in #20546
