### ISSUE TITLE
Update token address

### ISSUE THREAD

**Issue by dericlima** [solana-labs/token-list#20543]
Hello,

I would like to update the token address and logo added by me a month ago.

This is the PR with the correct token address and logo: https://github.com/solana-labs/token-list/pull/20188

Thanks a lot in advance :))

**Comment by dericlima** [comment]
For reference, this is the original PR where I added the Zombieverse Token: This is the original PR where the token was added: https://github.com/solana-labs/token-list/pull/15403/files

**Comment by keone** [comment]
merged, thanks for the backlink
