### ISSUE TITLE
SunLight new adress modification PR

### ISSUE THREAD

**Issue by InfernalGG** [solana-labs/token-list#20566]
- **I'm submitting a ...**
  [ ] bug report
  [X] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

PR: https://github.com/solana-labs/token-list/pull/20564

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
