### ISSUE TITLE
Token modification

### ISSUE THREAD

**Issue by Isembart** [solana-labs/token-list#20563]
https://github.com/solana-labs/token-list/pull/20242
Hello I wanted to change the name and the symbol of the token I added.

**Comment by keone** [comment]
https://github.com/solana-labs/token-list#duplicate-token
in particular look at https://github.com/solana-labs/token-list/pull/20242/commits, it has your commits that _added_ the original token.  That's bad! Don't do that!  The above link explains how to resolve.
