### ISSUE TITLE
Token is added to tokenlist.json but not reflecting in the wallets.

### ISSUE THREAD

**Issue by cariocc** [solana-labs/token-list#20579]
- **I'm submitting a ...**
report regarding token added to tokenlist and pull request made but its not showing up in wallets.

 {
      "chainId": 101,
      "address": "Fg3NLKzwfnhtiEjnbn86wcZiGckuL5bzf61JGSqFi4ot",
      "symbol": "VVV",
      "name": "Vladimir-VS-Volodymyr",
      "decimals": 6,
      "logoURI": "https://raw.githubusercontent.com/VladVSVolod/Assets/main/VladVSVolod.png",
      "tags": [
        "Vlad-VS-Volod",
        "Charity"
      ],
      "extensions": {
        "website": "https://www.vladimir-volodymyr.com/"
      }

this is data added into tokenlist. somehow it is not reflecting. Any idea how to fix it?

**Comment by keone** [comment]
https://github.com/solana-labs/token-list#scannerwallet-hasnt-updated-yet
