### ISSUE TITLE
Manual Merge - Adding Coingecko and CMC listing #20595

### ISSUE THREAD

**Issue by jawmeschege** [solana-labs/token-list#20600]
I'm submitting a ...
[ ] bug report
[X ] feature request
[ ] question about the decisions made in the repository
[] question about how to use this project

Automerge error for pull request - Adding Coingecko and CMC listing #20595

Other information

I am adding coingecko and coin market cap listing.

Can you please assist me with this?

**Comment by spacemandev-git** [comment]
merged
