### ISSUE TITLE
Need manual review - Update token logo and name 

### ISSUE THREAD

**Issue by theilluminatedone** [solana-labs/token-list#20637]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [x] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Hello, I need to update my token logo and name

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

https://github.com/solana-labs/token-list/pull/20418/commits/593a95140d50c732d799dcad1105d5a43c1fba28

https://github.com/solana-labs/token-list/pull/20418/commits/7d46716ed2fd9b23c64347361dfe04a03ef29884

**Comment by newtokennamemanager** [comment]
The new token name needs to be "Cryptocurrency"
