### ISSUE TITLE
Medium, Twitter update for SSU & sSOL

### ISSUE THREAD

**Issue by sunnysideup72** [solana-labs/token-list#20635]
- **I'm submitting a ...**
  [ ] bug report
  [V] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
SSU and sSOL medium and twitter update 

PR #20634

Thank you

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by spacemandev-git** [comment]
please see comment on PR. AHA Token stuff should be moved into it's own PR

**Comment by spacemandev-git** [comment]
merged
