### ISSUE TITLE
HELP !!!!!!! PR= #20555

### ISSUE THREAD

**Issue by Poonamsingh080** [solana-labs/token-list#20648]
- **I'm submitting a NEW Token on solana token-list...**
- It through auto-merged error on PR. Kindly merged this PR for new token.

**Comment by Poonamsingh080** [comment]
{
      "chainId": 102,
      "address": "5UyMNrQCmXpWkg1Ew7VaTm8fuQXkA5nsaZHo6hKKTBQk",
      "symbol": "NOIDA",
      "name": "N token",
      "decimals": 8,
      "logoURI": "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/5UyMNrQCmXpWkg1Ew7VaTm8fuQXkA5nsaZHo6hKKTBQk/logo.png",
      "tag": [
        "social-token"
      ]
    }
    
    i cannot seem to add my coin Can you please help me

**Comment by spacemandev-git** [comment]
please include link to your PR

**Comment by Poonamsingh080** [comment]
PR_LINK: https://github.com/solana-labs/token-list/pull/20555

**Comment by spacemandev-git** [comment]
"tag" should be "tags". try again with the fix
