### ISSUE TITLE
Manual Merge PR #20641

### ISSUE THREAD

**Issue by 0xMsry** [solana-labs/token-list#20647]
- **I'm submitting a ...**
  [ ] bug report
  [X] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

Automerge error for pull request #20641 

Other information:
Changed the name as well as the svg file for my token LSDC. I don't believe any errors were made but automerge did not approve. Please assist when you have a moment. Thank you.

**Comment by keone** [comment]
merged

**Comment by 0xMsry** [comment]
Impeccable timing. Thanks!
