### ISSUE TITLE
help ! 

### ISSUE THREAD

**Issue by gingeronenft** [solana-labs/token-list#20658]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by gingeronenft** [comment]
"chainId": 101,
      "address": "5VQPTUA7GtHHjve58NjpNnVyq9vrrFyaiq7t3ZeaBkyz",
      "symbol": "FANTAPANTS",
      "name": "fanta pants",
      "decimals": 6,
      "logoURI": "https://raw.githubusercontent.com/gingeronenft/fantapants/e25799b3bbc3e82f695fd7e916fd71e19cf926f5/image-asset.png",
      "tags": [
        ,
        "meme-token"

i cant seem to add my coin to Json file can someone help

**Comment by gingeronenft** [comment]
i created a PR #20569 please help

**Comment by 21e8** [comment]
Hey, it might look weird but your coin was included, I can see it on latest master. Automerger closes PRs but still includes the code (magically)
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/40480041/156500454-892d6961-3772-4120-812a-7638debb8e68.png">

**Comment by spacemandev-git** [comment]
PR was closed
