### ISSUE TITLE
Token showing as "Unknown Token" on Phantom

### ISSUE THREAD

**Issue by SamchenZ** [solana-labs/token-list#20683]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [X] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Token visibile on Explorer/Solscan/Sollet wallet however showing as "Unknown Token" on Phantom

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
Explorer: https://explorer.solana.com/address/invSTFnhB1779dyku9vKSmGPxeBNKhdf7ZfGL1vTH3u

**Comment by keone** [comment]
please submit a PR adding an entry to solana.tokenlist.json
