### ISSUE TITLE
Update WL Token Metadata

### ISSUE THREAD

**Issue by 21e8** [solana-labs/token-list#20728]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Hi,

We have kinda messed up the distribution for a CM whitelist token, so we are creating a new one and need to make clear that this one is no longer valid.

Original PR: https://github.com/solana-labs/token-list/pull/20031
Update PR: https://github.com/solana-labs/token-list/pull/20727

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by spacemandev-git** [comment]
merged
