### ISSUE TITLE
BONES token logo update

### ISSUE THREAD

**Issue by hachiko-souldogs** [solana-labs/token-list#20823]
Hi, I am updating our token logo in PR #20822, please review and merge it. Thanks!

Original token PR is #18940

**Comment by keone** [comment]
merged

**Comment by xLoopCreativeAndyx** [comment]
hey dude ive the same problem
duplicate tokenadress do you know how to fix that i dont have github skills need help from the devs but they only send me the link https://github.com/solana-labs/token-list#duplicate-token and I still dont know what to do
