### ISSUE TITLE
token logo issue 

### ISSUE THREAD

**Issue by mohamadDev** [solana-labs/token-list#20906]
**I'm submitting a ...**
  [*] feature request

Pull request: [20861](https://github.com/solana-labs/token-list/pull/20861)

**Comment by luoyuxiang2** [comment]
[fff](url)

**Comment by mohamadDev** [comment]
@keone  i would appreciate if you check our pull requests too, we have launched and the logo does not match to the project logo 
thanks

**Comment by keone** [comment]
PR was closed
