### ISSUE TITLE
Luxnode Token Address Update

### ISSUE THREAD

**Issue by Trovvie** [solana-labs/token-list#20917]
I'd like to get the address of my current token LUX changed from LUXiTyV4h7rXpgvAYSAVPa2TPB3cjABvdenkWTGQEZa to LUXtYqPio747yRKNAwGw7j2BYxzeXeZKg8k6KnFSGz1

PR: https://github.com/solana-labs/token-list/pull/20914
Old PR: #20804

Thank you for your time!

**Comment by spacemandev-git** [comment]
https://github.com/solana-labs/token-list#duplicate-token
