### ISSUE TITLE
Change portal ticker

### ISSUE THREAD

**Issue by luke-truitt** [solana-labs/token-list#21152]
- **I'm submitting a ...**
  [x ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Changing the ticker of the Portals Floor Index to IVRY from PRTL to be more specific
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by luke-truitt** [comment]
Closes #21151

**Comment by keone** [comment]
squashed 58 commits :) and merged
