### ISSUE TITLE
Correcting the logo link so it shows on wallets and Solscan.

### ISSUE THREAD

**Issue by kaprebox** [solana-labs/token-list#21190]
Correcting the logo link so it shows on wallets and Solscan.

    "logoURI": "https://github.com/kaprebox/crypto/blob/main/evancoin.png",
    "logoURI": "https://raw.githubusercontent.com/kaprebox/crypto/main/evancoin.png",

_Originally posted by @kaprebox in https://github.com/solana-labs/token-list/pull/21180#pullrequestreview-901171409_

**Comment by keone** [comment]
https://github.com/solana-labs/token-list#duplicate-token
