### ISSUE TITLE
add webite to coin: Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by newtokennamemanager** [solana-labs/token-list#21197]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary** 
Hello, I'm trying to add the website of my token and am getting Error: Process completed with exit code 1. 

https://github.com/solana-labs/token-list/pull/21196/commits/218892e89a6777b4439531633e567e55c1fa43e2

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
please link a PR
