### ISSUE TITLE
i want to remove the nft tag

### ISSUE THREAD

**Issue by bbtokensol** [solana-labs/token-list#21227]
old: https://github.com/solana-labs/token-list/pull/20928
new: https://github.com/solana-labs/token-list/pull/21225

**Comment by bbtokensol** [comment]
any updates?

**Comment by saitho** [comment]
@bbtokensol Please check the errors in your Pull Request.
It did not only remove the NFT tag but also added a new token which already is present in the list.

**Comment by bbtokensol** [comment]
that was a token i made haha alright ill fix that
