### ISSUE TITLE
Update $MARS Token Address (Needs manual merge)

### ISSUE THREAD

**Issue by musicdevghost** [solana-labs/token-list#21226]
- **I'm submitting a ...**
  [ ] bug report
  [x ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Need to manually merge PR in order to update Token address, previous token was created without decimals, new token has 9 decimals.

Update PR: https://github.com/solana-labs/token-list/pull/21224
Original creation PR: https://github.com/solana-labs/token-list/pull/20214/files

- **Other information**
Goal is to update token decimals, so I had to create a new one to replace existing one.

**Comment by keone** [comment]
merged
