### ISSUE TITLE
Update Name Token Sensei

### ISSUE THREAD

**Issue by AntoniusVip** [solana-labs/token-list#21235]
Update Name Token Sensei

_Originally posted by @AntoniusVip in https://github.com/solana-labs/token-list/issues/21232#issuecomment-1060680218_

**Comment by keone** [comment]
`error validating schema: name: invalid value "SENSEI.Finance" (out of bound =~"^[ \w'+\-%/À-ÖØ-öø-ÿ:&\[\]\(\)]+$")`

dots are not allowed (because ppl were using it to spam advertise websites)
