### ISSUE TITLE
Change lily address

### ISSUE THREAD

**Issue by FredTheNoob** [solana-labs/token-list#21243]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I would like to change the address of my token from 5Knf3n9JT6cmSwXLPavQbvMHwSib2p4iEa1dWvnrFYBx to 6LaJKhZts2cJJPdo9v7XR4kHiLk9ERh16VLKjBUS8DxD.

PR:
- [#21148](https://github.com/solana-labs/token-list/pull/21148)

**Comment by spacemandev-git** [comment]
merged
