### ISSUE TITLE
Manual Merge Token Updates Request  #21328

### ISSUE THREAD

**Issue by Jericho7734** [solana-labs/token-list#21338]
- **I'm submitting a ...**
  [ ] bug report
  [X] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- Inadvertently duplicated my token entry on lines 125490-125497 then removed those lines causing auto-merge fail. Any help fixing this is appreciated. Thanks

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by spacemandev-git** [comment]
duplicate token issue: https://github.com/solana-labs/token-list#duplicate-token
please edit the existing token instead of adding it again as a new block. then reopen a new PR and we can merge.
