### ISSUE TITLE
Name Change rq

### ISSUE THREAD

**Issue by DefiantApeClub** [solana-labs/token-list#21334]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Change my token name #21333
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by DefiantApeClub** [comment]
@keone

**Comment by xLoopCreativeAndyx** [comment]
hey dude ive the same problem
duplicate tokenadress do you know how to fix that i dont have github skills need help from the devs but they only send me the link https://github.com/solana-labs/token-list#duplicate-token and I still dont know what to do

**Comment by spacemandev-git** [comment]
closing this issue. please edit the existing token instead of adding it in again and then submit a new PR
