### ISSUE TITLE
Manual review request: add usd-coin coingeckoId to USDC-Dev devnet token

### ISSUE THREAD

**Issue by mcintyre94** [solana-labs/token-list#21343]
- **I'm submitting a ...**
  [x] manual review request (per README)

- **Summary**

PR: https://github.com/solana-labs/token-list/pull/21342

- The token USDC-Dev is supposed to act like USDC in Devnet for testing purposes
- I've added the USDC coingeckoId so that wallets will display its value using USDC

**Comment by spacemandev-git** [comment]
merged
