### ISSUE TITLE
Repo requires Manual merge for updating the token logo

### ISSUE THREAD

**Issue by themaqs** [solana-labs/token-list#21366]
Hi;
My forked repo needs manual merging for changing the old logo.

Pull request: [#21124 ](https://github.com/solana-labs/token-list/pull/21124)

**Comment by spacemandev-git** [comment]
merged

**Comment by xLoopCreativeAndyx** [comment]
hey dude ive the same problem
duplicate tokenadress do you know how to fix that i dont have github skills need help from the devs but they only send me the link https://github.com/solana-labs/token-list#duplicate-token and I still dont know what to do

**Comment by themaqs** [comment]
> hey dude ive the same problem duplicate tokenadress do you know how to fix that i dont have github skills need help from the devs but they only send me the link https://github.com/solana-labs/token-list#duplicate-token and I still dont know what to do

Hi, You should find your old info on [solana.tokenlist.json](https://github.com/solana-labs/token-list/blob/main/src/tokens/solana.tokenlist.json), then update its fields.
after that you should  submit a PR, then raise an issue with a link to your PR (and leave the PR open) in order to request a manual review.
