### ISSUE TITLE
Manual merge logo Iraqi Dinars Token (IQD) - #21510

### ISSUE THREAD

**Issue by opals99** [solana-labs/token-list#21434]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by opals99** [comment]
Please manually add correct link per below: 

"logoURI": "https://raw.githubusercontent.com/opals99/ZWD-SOL/main/logo.png",

Logo attached 

Many thank
![logo](https://user-images.githubusercontent.com/79752684/157344163-d196971a-46fb-468f-85b1-d0b6ac662112.png)
s

**Comment by saitho** [comment]
@opals99 I believe you should submit a pull request for this.

**Comment by opals99** [comment]
Have submitted various, all have problems, hence my query ..

**Comment by opals99** [comment]
Refer to this link for Manual Review please: https://github.com/solana-labs/token-list/pull/21510

**Comment by spacemandev-git** [comment]
merged

**Comment by xLoopCreativeAndyx** [comment]
hey dude ive the same problem
duplicate tokenadress do you know how to fix that i dont have github skills need help from the devs but they only send me the link https://github.com/solana-labs/token-list#duplicate-token and I still dont know what to do

**Comment by opals99** [comment]
Sorry, not sure how to resolve that
