### ISSUE TITLE
Changing LogoURL Merge Error   update 2.0 #21459 (Merge Required)!

### ISSUE THREAD

**Issue by xLoopCreativeAndyx** [solana-labs/token-list#21467]
- **I'm submitting a ...**
  [ ] feature request

  I want to change the LogoURL because i took the wrong Link can anyone help me I get the Error Automerge " duplicate token "   new Link should be https://raw.githubusercontent.com/xLoopCreativeAndyx/-/main/logo.png 
Pull Request : update 2.0 #21459

**Comment by spacemandev-git** [comment]
https://github.com/solana-labs/token-list#duplicate-token

**Comment by xLoopCreativeAndyx** [comment]
> https://github.com/solana-labs/token-list#duplicate-token

@spacemandev-git hey i updated the PR and it shows me that i have already changed the LogoURL in my own Version but i still cant merge it. I dont really understand how to fix the error may you help me
