### ISSUE TITLE
Token Updated. Manual merge required ( Vladimir VS Volodymyr token update #21496 ) -  Opened several issues before

### ISSUE THREAD

**Issue by cariocc** [solana-labs/token-list#21528]
I have updated token infromation. Please overlook PR: Vladimir VS Volodymyr token update #21496

It wen thru all green now just need someone to manually accept please.

  {
      "chainId": 101,
      "address": "Fg3NLKzwfnhtiEjnbn86wcZiGckuL5bzf61JGSqFi4ot",
      "symbol": "VVV",
      "name": "Vladimir VS Volodymyr",
      "decimals": 6,
      "logoURI": "https://raw.githubusercontent.com/VladVSVolod/Assets/main/VladVSVolod.png",
      "tags": [
        "Vlad VS Volod",
        "Charity",
        "NFT",
        "MEME"
      ],
      "extensions": {
        "website": "https://www.vladimir-volodymyr.com/"
      }
    },

**Comment by spacemandev-git** [comment]
You added in the token as a new block instead of editing the existing one: https://github.com/solana-labs/token-list#duplicate-token
