### ISSUE TITLE
request manual review of PR

### ISSUE THREAD

**Issue by ki2tech** [solana-labs/token-list#21540]
- **I'm submitting a ...**
  [ ] request for manual review of PR - https://github.com/solana-labs/token-list/pull/20938

- **Summary** I originally added my token (Mises Coin) to JSON but had an improper format logo png so the logo never showed up. So I tried to correct it a few times and now I believe I have it all correct but it must be manually reviewed.

**Comment by spacemandev-git** [comment]
you're creating a new token rather than updating your own. see this for help: https://github.com/solana-labs/token-list#duplicate-token

tl;dr 
start from a fresh copy of the solana-list repo and go and edit the block that already has your token in and then merge it back.
