### ISSUE TITLE
Merge Required! Updating ULRpng

### ISSUE THREAD

**Issue by xLoopCreativeAndyx** [solana-labs/token-list#21554]
Updating URLpng #21552

I want to change the LogoURL because i took the wrong Link
Error Automerge " duplicate token " appears but i dont know how to change fix this error.
"checkout the latest HEAD of main and then re-apply your change (simpler for git newbies but incurring a bit of duplicate work)"
is what im supposed to do but i dont understand how to do it i tried really hard..

new Link should be https://raw.githubusercontent.com/xLoopCreativeAndyx/-/main/logo.png
Original Pullrequest :#21191
May you please fix this manually Im looking to all Issues but i cant solve it myself PLS help me 
@spacemandev-git @keone ty for your time

**Comment by xLoopCreativeAndyx** [comment]
![image](https://user-images.githubusercontent.com/97604276/157579163-09e40b64-d078-40fa-b15d-bb291fd441dd.png)
it just doesnt work at all pls merge this manaully im so lost

**Comment by spacemandev-git** [comment]
see this for help : https://github.com/solana-labs/token-list#duplicate-token
