### ISSUE TITLE
Manual Merge requested: for modify existing token

### ISSUE THREAD

**Issue by EricP0on** [solana-labs/token-list#21615]
There are PR where the token was originally added, as follows

- #14578
- #19850
- #19912

Now, i want to modify mainnet/testnet/testnet token's address, The PR is as follows

- #21596

**Comment by EricP0on** [comment]
@keone Please review it, thank you!

**Comment by EricP0on** [comment]
@spacemandev-git Please review it, thank you!

**Comment by spacemandev-git** [comment]
merged
