### ISSUE TITLE
Change TruSwap token logo rq

### ISSUE THREAD

**Issue by Msaqib0786** [solana-labs/token-list#21612]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by Msaqib0786** [comment]
logoURI: https://github.com/Msaqib0786/logo.png/blob/main/logo.png

**Comment by Msaqib0786** [comment]
@spacemandev-git

**Comment by spacemandev-git** [comment]
Please submit a PR with the logo changed

**Comment by Msaqib0786** [comment]
sir plz help me all time show me this error submit a PR logo changed
TruSwap token.
https://github.com/Msaqib0786/TRSlogo/blob/main/logo.png.png

**Comment by Msaqib0786** [comment]
Sir Why first and after 2hr
