### ISSUE TITLE
Error validating schema: chainId: conflicting values 103 and 0

### ISSUE THREAD

**Issue by AlexMGN** [solana-labs/token-list#21620]
- **I'm submitting a ...**
  [ X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
This error come from the automerge : 
error validating schema: chainId: conflicting values 103 and 0

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
Here is the PR : #21572

**Comment by spacemandev-git** [comment]
please see this to fix the error: https://github.com/solana-labs/token-list#error-validating-schema-chainid-conflicting-values-103-and-0
