### ISSUE TITLE
Manual Merge requested for adding serum extension

### ISSUE THREAD

**Issue by Tarzan-D** [solana-labs/token-list#21656]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Adding the serumv3usdt extension for Vidi Token since we created the pool.
PR: https://github.com/solana-labs/token-list/pull/21655
Old PR: https://github.com/solana-labs/token-list/pull/18331

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by Tarzan-D** [comment]
The old pr is for the token creation. Several days ago, we also created another issue since we needed to update the token address.
Here is the link for last PR: https://github.com/solana-labs/token-list/issues/20965

**Comment by spacemandev-git** [comment]
merged
