### ISSUE TITLE
Manual Merge: request to manually update TBILL token #21657

### ISSUE THREAD

**Issue by MoonCandy69** [solana-labs/token-list#21659]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
1. Logo (Asset) has been deleted, and a new logo has been uploaded
2. Token name was updated
3. Token logo from raw.github link was updated

Please approve following PR: https://github.com/solana-labs/token-list/pull/21657

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by MoonCandy69** [comment]
Confirming failure to merge. Kindly approve PR: https://github.com/solana-labs/token-list/pull/21657 at your earliest convenience.

Best regards

**Comment by spacemandev-git** [comment]
merged
