### ISSUE TITLE
please manual merge for dab101 thank you 

### ISSUE THREAD

**Issue by kronik720** [solana-labs/token-list#21671]
- **I'm submitting a ...**
  [ ] bug report
  [X ] feature request ,manual merge
[ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
found removed line: - "address": "7J2cEFFhMCsdUBWssnYfUG5z6zYJYCUaTNPTxH3k9aVY",

link to pr-  https://github.com/solana-labs/token-list/pull/21610

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by spacemandev-git** [comment]
The PR in question deleted over 6000 lines in the solana token list, please submit a PR with only your token changed
