### ISSUE TITLE
Manuel Merge Required! Updating LogoURL

### ISSUE THREAD

**Issue by rianlux00** [solana-labs/token-list#21711]
I created a new account because i wasnt able to fix the duplicate token error.
New PR: updating token LogoURL #21710
Original PR: #21191
Pls Merge it 
@spacemandev-git @keone ty for your time

**Comment by xLoopCreativeAndyx** [comment]
This PR is from my secound account it has the permission to change the LogoURL pls merge it 
I am the Owner of the Original PR #21191

**Comment by keone** [comment]
merged
