### ISSUE TITLE
Manual merge required! Vladimir vs volodymyr token info #21703 ( changed back to original and now removed - ) There is no duplicate entry of the token

### ISSUE THREAD

**Issue by cariocc** [solana-labs/token-list#21712]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by cariocc** [comment]
Please help me out with that i tried everything already. Pulled back commits, changed to original and then published the changes again. Checked for duplicate entries. Cannot find any

**Comment by spacemandev-git** [comment]
The token already exists on lines 121675 - 121688. Please edit this block rather than adding a new block. This will solve the duplicate token problem.

**Comment by cariocc** [comment]
> The token already exists on lines 121675 - 121688. Please edit this block rather than adding a new block. This will solve the duplicate token problem.

Can you please check now. I Still ran into automerge issue but everything should be fine now if i am right? Made new PR Update solana.tokenlist.json #21889

**Comment by keone** [comment]
merged
