### ISSUE TITLE
Update GOFX token details 

### ISSUE THREAD

**Issue by stunt101harm** [solana-labs/token-list#21733]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- Updating GOFX token information (adding coinmarketcap, coingecko APIs, and serumV3   ##address)
- from PR #21751
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by stunt101harm** [comment]
getting an auto-merge error `failed to normalize: failed to normalize JSON: hujson: line 2, column 6: invalid character ',' after object name`

**Comment by keone** [comment]
merged
