### ISSUE TITLE
Update Magic bean (BEAN) token name

### ISSUE THREAD

**Issue by PeterKoach** [solana-labs/token-list#21742]
- **I'm submitting a ...**
  [ ] bug report

- **Summary**

I want to fix the name of token `beanZG7tYRxHyTTm9pFSNqStL7AZFo2FirFkH1dLZzc`. It should be "Magic bean" instead of "BEAN".

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Original PR: https://github.com/solana-labs/token-list/pull/21707
New PR with the changed name: https://github.com/solana-labs/token-list/pull/21741

Thank you.

**Comment by keone** [comment]
merged
