### ISSUE TITLE
update token list error exit code 1, online suggestions didn't help only made it worst

### ISSUE THREAD

**Issue by BlockEmpire** [solana-labs/token-list#21761]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [*] question about how to use this project

- **Summary**
- error report exit code 1, unable to run yarn test. followed online suggestions made it worst 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions on how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Hi, the original err was,

1 test failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "test:unit" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.

when I google to try and fix it got worst, the original pull was also done by me using a different computer https://github.com/solana-labs/token-list/pull/21727 which only had one error, and now I made it worst with the current pull https://github.com/solana-labs/token-list/pull/21758 with two errors,

can you please help me fix this, or teach me what to do. thx

**Comment by spacemandev-git** [comment]
The duplicate token error means you tried to add a token instead of editting the existing token you have already added: https://github.com/solana-labs/token-list#duplicate-token
