### ISSUE TITLE
Changed logo file but i get automerge error

### ISSUE THREAD

**Issue by SolSecSociety** [solana-labs/token-list#21788]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Just trying to change the logo because it is not displaying well on the blockchain but the automerge failed.
How to do that ? Can't find out! Thanks     PR #21622
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by spacemandev-git** [comment]
You added a token instead of modifying the existing token in your PR: https://github.com/solana-labs/token-list#duplicate-token
