### ISSUE TITLE
Why would I get "unsupported file modified: /dev/null" while updating existing files?

### ISSUE THREAD

**Issue by gansaikhanshur** [solana-labs/token-list#21914]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x ] question about how to use this project

- **Summary**

I've created a pull request [here](https://github.com/solana-labs/token-list/pull/21913) but I get ```unsupported file modified: /dev/null```. I've only modified my folder in assets and tokenlist json file in source. How can I fix this or locate the problem?

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
expected error; this requires manual merge
merged
