### ISSUE TITLE
ADD ZOO TOKEN #21968

### ISSUE THREAD

**Issue by ChristianGaeta** [solana-labs/token-list#21988]
- **I'm submitting a ...**
  [x ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
https://github.com/solana-labs/token-list/pull/21968
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
![image](https://user-images.githubusercontent.com/36098568/158227793-98cecfd4-afc2-4972-908b-b42471b14f11.png)
Help me please

**Comment by spacemandev-git** [comment]
seems like it got closed so I think you managed to merge it?
