### ISSUE TITLE
logo changed TRS TruSwap token #22003

### ISSUE THREAD

**Issue by Msaqib0786** [solana-labs/token-list#22008]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by Msaqib0786** [comment]
Sir explain me why rejecting my PR. 
https://github.com/solana-labs/token-list/pull/21989
https://github.com/solana-labs/token-list/pull/22003

@spacemandev-git

**Comment by spacemandev-git** [comment]
merged
