### ISSUE TITLE
Adding new token, Workflows approval

### ISSUE THREAD

**Issue by Crypcho** [solana-labs/token-list#22022]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ x ] question about how to use this project

- **Summary**
2 workflows awaiting approval - cannot seem to solve this issue

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
[Pull Request](https://github.com/solana-labs/token-list/pull/22021)
![image](https://user-images.githubusercontent.com/101561264/158281234-b76eabe4-49a5-4640-8d5d-db4e6bc52d89.png)

**Comment by Crypcho** [comment]
@keone sorry for tag you seem to be the man with the answers for everything lol

**Comment by keone** [comment]
https://github.com/solana-labs/token-list#warning-about-the-last-element-in-the-list

**Comment by Crypcho** [comment]
> https://github.com/solana-labs/token-list#warning-about-the-last-element-in-the-list

WOW hah right in front of my face the whole time!!! thank youu

**Comment by Crypcho** [comment]
So I did exactly as stated, still getting the same issue, even on a new pull request from a new fork, restarting doesnt seem to work either. Build and codeQL dont run and require maintainer approval?
