### ISSUE TITLE
Build failed on PR

### ISSUE THREAD

**Issue by Crypcho** [solana-labs/token-list#22058]
- **I'm submitting a ...**
  [ x ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ x ] question about how to use this project

- **Summary**
Build / build (pull_request) failed

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
[PR Link](https://github.com/solana-labs/token-list/pull/22057#issue-1169422299)
running yarn test failed 
![image](https://user-images.githubusercontent.com/101561264/158352901-65ef943d-eeee-4ca2-8e23-5f8a1e149e32.png)

**Comment by Crypcho** [comment]
@keone Your info earlier really helped out but I am now stuck at this issue, would you have any solutions for me?

**Comment by keone** [comment]
it's failing because this one succeeded: https://github.com/solana-labs/token-list/pull/22053
