### ISSUE TITLE
Build failed on PR | Electons

### ISSUE THREAD

**Issue by jonaspead** [solana-labs/token-list#22073]
- **I'm submitting a ...**
  [ X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ X] question about how to use this project

- **Summary**
automerge error
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
-[https://github.com/solana-labs/token-list/pull/21642]

**Comment by spacemandev-git** [comment]
adding a token shouldn't result in conflicts, please make sure to add the token only at the end of the file.
