### ISSUE TITLE
auto-merge aaapoc - manual

### ISSUE THREAD

**Issue by solalchemist** [solana-labs/token-list#22116]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by solalchemist** [comment]
https://github.com/solana-labs/token-list/pull/22115

@keone

**Comment by solalchemist** [comment]
@spacemandev-git - i've tried it again using another method. not sure why anything was ever deleted.

thank you

**Comment by spacemandev-git** [comment]
your PR still has 130 thousand lines of the solana token list deleted.

**Comment by solalchemist** [comment]
i don't know why it keeps doing that? here, i've tried again...

https://github.com/solana-labs/token-list/pull/22231

**Comment by spacemandev-git** [comment]
yup it still says over 130k lines deleted. i don't know why, but i'd recommend closing this PR, and starting from a fresh copy of the solana token list and making a new PR with your edit.
