### ISSUE TITLE
Manual merge PR #21890

### ISSUE THREAD

**Issue by daishizenSensei** [solana-labs/token-list#22129]
Hello,

You closed my Issue without speak with me.
You said that the YAKU token was already used but yeah it's my token and i did a mistake the address was wrong.
I updated the token address, please merge it.

Thank you

**Comment by spacemandev-git** [comment]
To update the address you'll need to edit the *existing* token, not add a new token.

**Comment by daishizenSensei** [comment]
How to do that @spacemandev-git ?

**Comment by daishizenSensei** [comment]
I only modify my token on the list then ask a merge

**Comment by spacemandev-git** [comment]
Start from a fresh copy of the token list, find your token and modify it. You've instead added your token as a new listing, which will not work.
