### ISSUE TITLE
unsupported file modified

### ISSUE THREAD

**Issue by FireDragon2210** [solana-labs/token-list#22126]
- **I'm submitting a ...**
  [ ] bug report yes
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**  how do I fix this error ?

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by spacemandev-git** [comment]
what's your PR

**Comment by FireDragon2210** [comment]
#22124

**Comment by FireDragon2210** [comment]
> what's your PR

It's 22124

**Comment by spacemandev-git** [comment]
@FireDragon2210 it seems like the KeithKoin name is already taken, and cannot be used for your token.

**Comment by FireDragon2210** [comment]
I redid everything by copying it from a tutorial but it should be working > already
