### ISSUE TITLE
Remove my token

### ISSUE THREAD

**Issue by drahul540** [solana-labs/token-list#22172]
I have accidentally uploaded a logo, a token name with a test token.
I want to remove that test token which I uploaded because now I want to upload the token logo and name with a real token address.
And i have removed the fork repo from my github account.

Can you help me how can i remove that or should i raise a support ticket but where?

**Comment by SolanaTokenMerger** [comment]
You just need to fork again the Solanalabs/token-list, then delete the test token and make a new PR. After, you'll need to open a new issue and link your PR and wait for Solana Developer to manually apply the changes committed by you!! Hope this did help!!

**Comment by drahul540** [comment]
> You just need to fork again the Solanalabs/token-list, then delete the test token and make a new PR. After, you'll need to open a new issue and link your PR and wait for Solana Developer to manually apply the changes committed by you!! Hope this did help!!

i have fork again and delete my logo and json and then make a new PR. but it is failed.

**Comment by spacemandev-git** [comment]
Please link the PR

**Comment by spacemandev-git** [comment]
duplicate issue
