### ISSUE TITLE
Automerge Not working - Files Have conflict

### ISSUE THREAD

**Issue by mr-akin** [solana-labs/token-list#22188]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I'm trying to add a token but its failing to auto merge as files have conflicts.

Link to the PR: https://github.com/solana-labs/token-list/pull/22185

Please Help me out! Thanks.

**Comment by mr-akin** [comment]
Just Checked auto merge throwing a weird error:

`error validating schema: extensions.twitter: invalid value "https://twitter.com/weedheadsNFT/" (out of bound =~"^[https://twitter.com/(\\w){1,15}$](https://twitter.com/(%5C%5Cw)%7B1,15%7D$)")`

Link to PR: https://github.com/solana-labs/token-list/pull/22185

**Comment by spacemandev-git** [comment]
PR was closed
