### ISSUE TITLE
Electons Token

### ISSUE THREAD

**Issue by jonaspead** [solana-labs/token-list#22260]
- **I'm submitting a ...**
  [ X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [X ] question about how to use this project

- **Summary**
Build fail because of duplicate entry. I didnt
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by spacemandev-git** [comment]
please include PR. duplicate token can be fixed with this: https://github.com/solana-labs/token-list#duplicate-token
