### ISSUE TITLE
Not eligible for automerge (click details for more information): invalid asset path:

### ISSUE THREAD

**Issue by kutchstir** [solana-labs/token-list#22295]
I'm submitting a pull request
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

I get an error when trying to submit a pull request:

Not eligible for automerge (click details for more information): invalid asset path

Please can you assist on how to get that resolved?

**Comment by spacemandev-git** [comment]
please link your PR
