### ISSUE TITLE
pull #22306

### ISSUE THREAD

**Issue by solalchemist** [solana-labs/token-list#22308]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

https://github.com/solana-labs/token-list/pull/22306

**Comment by solalchemist** [comment]
i followed your instructions @spacemandev-git and started with a fresh fork, I think it was applying the previously failed commits.

this pull appears to have passed all the checks so I went ahead and opened an issue prematurely. thanks again for your help.

**Comment by spacemandev-git** [comment]
might be something up with your IDE, because the PR again shows 130k files deleted: https://github.com/solana-labs/token-list/pull/22306/files
