### ISSUE TITLE
Update: Token Symbol DA to DOPIES PR #22338

### ISSUE THREAD

**Issue by gabrielhicks** [solana-labs/token-list#22339]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Token Symbol DA to DOPIES PR #22338

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by spacemandev-git** [comment]
please link the PR in which you originally added the DA token to prove authorship

**Comment by gabrielhicks** [comment]
Sure! PR #18250

**Comment by spacemandev-git** [comment]
merged
