### ISSUE TITLE
How to update logo ?

### ISSUE THREAD

**Issue by SolSecSociety** [solana-labs/token-list#22346]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x] question about how to use this project

- **Summary**
I can't figure out how to update the logo, i get the automerge error every time i open a PR. Can someone post a little guide or tutorial on how to make changes in here ? 

the thing i do is to simply fork token-list in github desktop, update the logo file in the asset folder of my token and then push to origin but this is not working.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.):

the thing i do is to simply fork token-list in github desktop, update the logo file in the asset folder of my token and then push to origin but this is not working.

**Comment by SolSecSociety** [comment]
here the PR when i added the token to token list: #21163
here the PR of me trying to update the image in the assets folder: #22336

**Comment by spacemandev-git** [comment]
merged
