### ISSUE TITLE
Duplicate token error?

### ISSUE THREAD

**Issue by corruptdev** [solana-labs/token-list#22352]
- **I'm submitting a ...**
  [x ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ x] question about how to use this project

- **Summary**
- Hey, when I was submitting my pull request, I kept getting duplicate token error, but I'm not sure how that could be since there aren't any. If we could have it manually added or update that would be lovely. There is a pull request called add buddiezz token. Or if you could shoot me a dm on discord @corrupt#0999 It'd be greatly appreciated. Thanks

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by spacemandev-git** [comment]
https://github.com/solana-labs/token-list#duplicate-token
