### ISSUE TITLE
logo/icon replaced 

### ISSUE THREAD

**Issue by millionsols** [solana-labs/token-list#22350]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [X] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
+added Cockatoo #21713 
+added new icon/logo
https://github.com/solana-labs/token-list/pull/21713

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by spacemandev-git** [comment]
please link the PR in which you're replacing the Logo
