### ISSUE TITLE
I carefully checked, and could not find any mistake.

### ISSUE THREAD

**Issue by captozc** [solana-labs/token-list#22413]
I carefully checked, and could not find any mistake.
I think this PR need to be manually merged.

_Originally posted by @captozc in https://github.com/solana-labs/token-list/issues/22390#issuecomment-1072204544_

**Comment by spacemandev-git** [comment]
you're getting this error: https://github.com/solana-labs/token-list#error-validating-schema-chainid-conflicting-values-103-and-0
