### ISSUE TITLE
Duplicate token `CfNkADyvwg66yLtctbuDo381s6VqVC8583ur7uvooE43`

### ISSUE THREAD

**Issue by LightYagami200** [solana-labs/token-list#22415]
- **I'm submitting a ...**
  [*] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
My pull request is failing at build with duplicate error, but the token that it's giving error for is `CfNkADyvwg66yLtctbuDo381s6VqVC8583ur7uvooE43`

- **Other information** 
![image](https://user-images.githubusercontent.com/35832598/158975328-b094fd96-2da1-4c33-9a4d-c56664dba536.png)
That token is present twice in tokens.json and is constantly failing all pull requests - It'd be great if you could investigate it and remove that problematic token.

**Comment by swimmingyoshi** [comment]
im having the exact same token interefere with my token

**Comment by spacemandev-git** [comment]
duplicate removed.
