### ISSUE TITLE
I do not delete anything, I just add my token

### ISSUE THREAD

**Issue by Itsystemsproyect** [solana-labs/token-list#2243]
I do not delete anything, I just add some my touch and I get that I have deleted 260 lines and that's 3 times that I correct but nevertheless it remains the same until I cancel the pull request and send a new one and it tells me the same thing my touch is ITSC (ITS Cash)

**Comment by gimple** [comment]
what? this is a bunch of jibberish dude.

**Comment by SamuelMTDavies** [comment]
I think he is refering to adding his token to the file but the git diff is showing multiple line deletions and additions.

I've been having the same issue which is to do with Line ending differences between Mac Os and Windows etc

It would be good if this could be standardised or a little explainer to help people avoid this issue.

At present the file is a mix of different line endings.

**Comment by solanadonkeybusiness** [comment]
Can you guys fix this? It's pretty annoying.

Maybe we can have prettier or something run before pushing to repo?

**Comment by solanadonkeybusiness** [comment]
Most other commits fail the builds because of this.

**Comment by SamuelMTDavies** [comment]
The way I got around this was git app - p when committing that file and discarding all the "changes" except the real one at the end of the file.

**Comment by Itsystemsproyect** [comment]
If it is that of line break apparently and I can not solve it.
I use Linux I thought that was why I tried from windows but nothing follows the error, I did the test without adding any secure changes with CTRL + S and it came out as if I had deleted and added some lines.

**Comment by solanadonkeybusiness** [comment]
Samuel has the workaround. Make sure you're not changing the formatting via auto-formatter in IDE. 

Best advice was to use "git add -p" and then cherry pick the code sections that you want. 

HEEE-HAWWWWWW

**Comment by SamuelMTDavies** [comment]
@solanadonkeybusiness glad it worked. 

Original credit to @ragingbeluga who helped me with this.
