### ISSUE TITLE
Extension changed

### ISSUE THREAD

**Issue by Diego-Lara** [solana-labs/token-list#22495]
I'm submitting a ...
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project
Hi there,

I would like to add some extensions to ACM

The PR is https://github.com/solana-labs/token-list/pull/22494

Thanks :)

**Comment by spacemandev-git** [comment]
your PR deletes 96k files in the token list json. please fix that and resubmit.
