### ISSUE TITLE
Manual Merge #22380

### ISSUE THREAD

**Issue by vtllr** [solana-labs/token-list#22492]
Hi team,

Please merge https://github.com/solana-labs/token-list/pull/22380
Everything runs smoothly except the check " Token list does not have duplicate entries "
I do not believe it's because of my PR.

Thanks for your help!

**Comment by spacemandev-git** [comment]
you're getting this error: https://github.com/solana-labs/token-list#error-validating-schema-chainid-conflicting-values-103-and-0

**Comment by vtllr** [comment]
Ok sorry about. Opening a new RP right now
