### ISSUE TITLE
Pull Request Error

### ISSUE THREAD

**Issue by BuffaloChikn** [solana-labs/token-list#22543]
- **I'm submitting a pull request error
- https://github.com/solana-labs/token-list/pull/22117
- I'm getting the following error:

Not eligible for automerge (click details for more information)
found removed line: - "name": "Solana Token List",

**Comment by spacemandev-git** [comment]
your IDE is deleting 130k lines from solana token list; https://github.com/solana-labs/token-list/pull/22117/files 

please fix and resubmit

**Comment by BuffaloChikn** [comment]
my apologies but i have no idea how this happened nor do i have any idea how to complete your instructions. can you assist me?

**Comment by BuffaloChikn** [comment]
I added the missing lines from the latest update of solana token list. please verify that i have done so correctly,

**Comment by spacemandev-git** [comment]
the PR still shows most files deleted.
