### ISSUE TITLE
Token list does not have duplicate entries

### ISSUE THREAD

**Issue by alco139** [solana-labs/token-list#22555]
- **I'm submitting a ...**
  [ X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- so i was updating our token info , and adding a market , but the automerge fails , saying "Token list does not have duplicate entries".
and i just updated the repo !
here is the pull request [https://github.com/solana-labs/token-list/pull/22553#partial-pull-merging](https://github.com/solana-labs/token-list/issues/url)

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by spacemandev-git** [comment]
please link to PR

**Comment by alco139** [comment]
i dont know what that means, please write more

**Comment by alco139** [comment]
https://github.com/solana-labs/token-list/pull/22553  , this is not pr?

**Comment by spacemandev-git** [comment]
PR is closed
