### ISSUE TITLE
Need to update the token listing mint address

### ISSUE THREAD

**Issue by mr-akin** [solana-labs/token-list#22568]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Hey, I want to update the token address of my existing listing. 

Here is the PR: https://github.com/solana-labs/token-list/pull/22567#issue-1174373447

**Comment by mr-akin** [comment]
Hey man @spacemandev-git , can you please help me out to resolve my issue?

**Comment by spacemandev-git** [comment]
https://github.com/solana-labs/token-list#duplicate-token

you've readded your token instead of modifying the existing token
