### ISSUE TITLE
[Manual Review Needed] Merge #25585 with main branch, failed for no reason

### ISSUE THREAD

**Issue by overdeveloping** [solana-labs/token-list#22586]
I made a fork and put my token details in and only added my token and didn't delete or remove anything but merge still failed.

Add #22585 to main branch.

**Comment by beeman** [comment]
I think the reason is that there already exists a token with the symbol `WAT`:

<img width="771" alt="image" src="https://user-images.githubusercontent.com/36491/159160316-a92b0ce5-9f98-4a5f-bdf0-9522d678bdce.png">
