### ISSUE TITLE
update existing tokens USDx and EURfx

### ISSUE THREAD

**Issue by cereum** [solana-labs/token-list#22627]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
linked pr
https://github.com/solana-labs/token-list/pull/22626
original pr
https://github.com/solana-labs/token-list/pull/22344

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by spacemandev-git** [comment]
merged
