### ISSUE TITLE
Can't Edit Token's Logo

### ISSUE THREAD

**Issue by wicossy** [solana-labs/token-list#22640]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x] question about how to use this project

- **Summary**
- I can't change my token logo

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Correct PR;
https://github.com/solana-labs/token-list/pull/22638

Original PR(first-create);
https://github.com/solana-labs/token-list/pull/22631

**Comment by wicossy** [comment]
@spacemandev-git

**Comment by spacemandev-git** [comment]
In your PR you've readded your token, this will lead to duplicate token error, please modify the existing token and change the link to the new logo
