### ISSUE TITLE
Please update my mistake token address

### ISSUE THREAD

**Issue by skeleton8888** [solana-labs/token-list#22654]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x] question about how to use this project

- **Summary**
Please update my new address for DKM token.
https://github.com/solana-labs/token-list/pull/22653

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
My last commit in PR's comment.
https://github.com/solana-labs/token-list/commit/204973df27b25bf4858b236276aa25a38391c21a
Thanks!

**Comment by skeleton8888** [comment]
@spacemandev-git thanks!

**Comment by spacemandev-git** [comment]
merged
