### ISSUE TITLE
Need to update token logoURI

### ISSUE THREAD

**Issue by ivanmarreta** [solana-labs/token-list#22663]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
linked pr
https://github.com/solana-labs/token-list/pull/22660
original pr
https://github.com/solana-labs/token-list/pull/22650

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by ivanmarreta** [comment]
@spacemandev-git :)

**Comment by spacemandev-git** [comment]
merged
