### ISSUE TITLE
Remove website from token extension  #22670

### ISSUE THREAD

**Issue by Aslienv** [solana-labs/token-list#22680]
- **I'm submitting a ...**
  [x ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Remove website from token extension PR : update website token moto #22810
Please change my token with this update. 
Thanks

**Comment by Aslienv** [comment]
Hello, this is the commit related to the update : 9a385d5e0e1da1c65c1613b9ba3caa8f9cfab988 

and this is the commit + PR related to the creation of the token : 
add-token-moto #22556 
67ea95fbf795c8b74e36dd4b78e1621c00c98a96

**Comment by spacemandev-git** [comment]
merged
