### ISSUE TITLE
Manual Merge Required | ELL Token

### ISSUE THREAD

**Issue by teamelliel** [solana-labs/token-list#22736]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Require manual merge for error /dev/null

https://github.com/solana-labs/token-list/pull/22734

**Comment by spacemandev-git** [comment]
merged
