### ISSUE TITLE
PR Error #22667

### ISSUE THREAD

**Issue by ColliderCoin** [solana-labs/token-list#22749]
- Just a question
  [X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [X] question about how to use this project

- unsupported file modified: /dev/null   
- New automerge — Not eligible for automerge (click details for more information)

Token Address: EJt3iszkR6GKiV1YSyefB2GaHsXniyVAjAtS9mrxyTZR
Token Name: ColliderCoin
Token Symbol: MCCN
Logo: \assets\mainnet\EJt3iszkR6GKiV1YSyefB2GaHsXniyVAjAtS9mrxyTZR\collider_blue_coin.png
Link to the official homepage of token: https://collidercoin.com/

- When I click on the issue all it says is "unsupported file modified: /dev/null".  However, all I did was add my logo, add my token, and merge.  It doesn't give me any details of what the issue is.

**Comment by spacemandev-git** [comment]
closed PR
