### ISSUE TITLE
update of RYDE logo.png image manual review requested

### ISSUE THREAD

**Issue by BlockEmpire** [solana-labs/token-list#22779]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- [*]  Files changed 

PR #22778
updated logo.png of RYDE image
thx

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by spacemandev-git** [comment]
was added by @m33lucky-benny and needs approval by that account to do the change. added in this PR: https://github.com/solana-labs/token-list/pull/21715/files
