### ISSUE TITLE
[BUG] Automerge skipped token image

### ISSUE THREAD

**Issue by kevinhubertde** [solana-labs/token-list#22797]
- **I'm submitting a bug report**

- **Summary**
The automerge that runs every hour did not correctly upload the image of a token.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
pull request files: https://github.com/solana-labs/token-list/pull/22745/files
as you can see there is two images being uploaded with this request, the one that says WL did not get uploaded, while the others one yes.
if you look at the file for the first one (WL) it says 404
https://github.com/solana-labs/token-list/blob/main/assets/mainnet/5bFvtLN3kP34sas77XvWgoY4b5CFjQ7qAUJsKUSomLUJ/logo.png
so my WL token looks broken on solscan (https://solscan.io/token/5bFvtLN3kP34sas77XvWgoY4b5CFjQ7qAUJsKUSomLUJ)

**Comment by spacemandev-git** [comment]
please reupload the token image in a PR and I can approve.
