### ISSUE TITLE
Add CoingeckoId to Hiram

### ISSUE THREAD

**Issue by Hiram51** [solana-labs/token-list#22829]
Hello Team,

I've summit a PR to had coingecko Id Extensions to an existing token HIRAM.
Automerge failed.
Can someone merge it manually ?
Thanks in advance

Eric
(https://github.com/solana-labs/token-list/pull/20173)

**Comment by Ericl51** [comment]
Hello @keone : Can you please review and merge?
Thx
Eric51

**Comment by spacemandev-git** [comment]
merged
