### ISSUE TITLE
Add SerumV3 to Mofogasy token

### ISSUE THREAD

**Issue by Ericl51** [solana-labs/token-list#22828]
Hello Team,

I've summit a PR to add SerrumV3 extension to an existing token Mofogasy Token (MGT).
Had automerge issue.
Can you merge it manually

Thanks in advance
Eric

- **Other information** 
- https://github.com/solana-labs/token-list/pull/21139

**Comment by Ericl51** [comment]
Hello @keone : Can you please review and merge? 
Thx

**Comment by spacemandev-git** [comment]
https://github.com/solana-labs/token-list#error-validating-schema-chainid-conflicting-values-103-and-0
