### ISSUE TITLE
Add coingecko id to CASH

### ISSUE THREAD

**Issue by Arrowana** [solana-labs/token-list#22861]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Update CASH to have its coingecko id, see https://www.coingecko.com/en/coins/cashio-dollar

@0xghostchain please approve :)

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged :|
