### ISSUE TITLE
Modified link - no automerge

### ISSUE THREAD

**Issue by MorisBR** [solana-labs/token-list#22930]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I changed the broken link of my token, but needs manual automerge...
PR: Adjusted logo link on TRUFA Coin #22764 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by JoshTDLester** [comment]
Merged
