### ISSUE TITLE
Build keeps failing for pull request

### ISSUE THREAD

**Issue by joshwolff1** [solana-labs/token-list#23001]
- **I'm submitting a ...**
  [ X ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
The build for my pull request keeps failing.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Pull request here: https://github.com/solana-labs/token-list/pull/22998

It fails on the `validate.sh` script.

It says `tokens: invalid value`.

Not clear what's invalid. This is the JSON I'm submitting:

```
{
      "chainId": 101,
      "address": "cPQm9UM1ekMeAgRcYGLfNcBC65SLA8o2BVTaBUA7kTg",
      "symbol": "API",
      "name": "API Coin",
      "decimals": 9,
      "logoURI": "https://theblockchainapi-website.s3.amazonaws.com/logo512.png",
      "tags": [
        
      ],
      "extensions": {
        "twitter": "https://twitter.com/_BlockX_",
        "website": "https://blockchainapi.com/"
      }
    },
```

**Comment by Maxsos133** [comment]
same

**Comment by Marcuss17** [comment]
Happens to me also

**Comment by keone** [comment]
fixed by https://github.com/solana-labs/token-list/commit/ce587dace90f41254395141cd1bb808db5f89df1
