### ISSUE TITLE
Request update for tokens NOS and CSR

### ISSUE THREAD

**Issue by kookiekrak** [solana-labs/token-list#23018]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Update to tokens PR #23017 

previous automerged PR #21865

**Comment by spacemandev-git** [comment]
merged
