### ISSUE TITLE
My build keeps failling

### ISSUE THREAD

**Issue by Marcuss17** [solana-labs/token-list#23025]
- **I'm submitting a ...**
  [X ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I am trying to add my token to the token list. My token is almost the same as the others but my build keeps failing due to validation.

You can see here my build is failing:
![image](https://user-images.githubusercontent.com/46487685/159846547-aee348b3-97d4-47d0-ac64-528f94112f10.png)

You can see here how it looks almost the same as the one before (My TOKEN is the last one, WARI-WL):
![image](https://user-images.githubusercontent.com/46487685/159846624-029e601d-1dcb-4e60-b8b1-810f4f3ba254.png)

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
- Link to my PR: https://github.com/solana-labs/token-list/pull/23024

Thanks for any help!

**Comment by keone** [comment]
fixed by https://github.com/solana-labs/token-list/commit/ce587dace90f41254395141cd1bb808db5f89df1
