### ISSUE TITLE
Manual Review - Failed Token Merge

### ISSUE THREAD

**Issue by madisoncarsan** [solana-labs/token-list#23074]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
  - Failed token merge - here is [pull request](https://github.com/solana-labs/token-list/pull/21302)

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by spacemandev-git** [comment]
PR modified 1,600 lines of the solana token list and modified tons of different tokens. please modify only the token you wish to edit and submit a new PR
