### ISSUE TITLE
update CoinGecko ID

### ISSUE THREAD

**Issue by perlish** [solana-labs/token-list#23084]
Hi Team ,
I need to update our token SNS Information
ADD coingeckoId "synesis-one"

Please help us to merge this request
[https://github.com/solana-labs/token-list/pull/21957](https://github.com/solana-labs/token-list/pull/21957)

Having issue below
Not eligible for automerge (click details for more information) failed to normalize: failed to parse JSON: json: unknown field "coingeckoId"

Our token already listed on COINGECKO
https://www.coingecko.com/en/coins/synesis-one

Thank you

**Comment by spacemandev-git** [comment]
merged
