### ISSUE TITLE
add new token new contract addres new tokn name 

### ISSUE THREAD

**Issue by Saqibali03** [solana-labs/token-list#23089]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by Saqibali03** [comment]
https://github.com/solana-labs/token-list/pull/23072/
merged

**Comment by Saqibali03** [comment]
no hendal here merged issue. so please send me PR link where i am request for  merged problam

**Comment by spacemandev-git** [comment]
your PR doesn't make any changes.
