### ISSUE TITLE
Update logo for MARCUSS OPT TOKEN

### ISSUE THREAD

**Issue by Marcuss17** [solana-labs/token-list#23113]
- **I'm submitting a ...**
  [ ] bug report
  [X] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I want to update the logo of my token.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
PR with update of the logo: https://github.com/solana-labs/token-list/pull/23111
PR where the token was added: https://github.com/solana-labs/token-list/pull/23024

**Comment by spacemandev-git** [comment]
merged
