### ISSUE TITLE
Conflict on merge of TEX Coin

### ISSUE THREAD

**Issue by MorisBR** [solana-labs/token-list#23179]
- **I'm submitting a ...**
  [ ] bug report
  [X] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Need help to solve the branch conflict on PR 23178. 

Thanks in advance.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by spacemandev-git** [comment]
please link the PR in which you're making changes.

**Comment by MorisBR** [comment]
That was solved in other issue. Thanks.
