### ISSUE TITLE
adding TruSwap Coin token

### ISSUE THREAD

**Issue by mk3723** [solana-labs/token-list#23182]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by mk3723** [comment]
chek it sir what is the problem now why not
add my token in list ?
https://github.com/mk3723/token-list/pull/1

**Comment by trevor256** [comment]
You need another } near the end, you have 1 }


},
    {
      "chainId": 101,
      "address": "2VUUT4sHadwsqv5mG57MAcUiLbnkPp21oYEw5WwaiEqU",
      "symbol": "TRS",
      "name": "TruSwap Coin",
      "decimals": 9,
      "logoURI": "https://github.com/mk3723/TRS/blob/main/logo.png.png",
      "tags": [
        "stake-pool-token",
        "utility-token",
        "meme-token",
        "community-token"
      ]
`}`
    }
  ],
  "version": {

**Comment by mk3723** [comment]
chek it sir now https://github.com/solana-labs/token-list/pull/23245

@trevor256

**Comment by trevor256** [comment]
I'm actually in the same boat I think now we just have to wait #23267

**Comment by spacemandev-git** [comment]
you haven't changed any files in your commit. to update the token you gotta edit the file, make the changes, then commit for it to be available to be approved.
