### ISSUE TITLE
Added Coingekoid, description and Facebook page for Nooft Token

### ISSUE THREAD

**Issue by nooftproject** [solana-labs/token-list#23187]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

Added Coingekoid, description and Facebook page for Nooft Token

Please commit the changes.

https://github.com/solana-labs/token-list/pull/23186

Best regards,
Nooft Project Team

**Comment by nooftproject** [comment]
please commit the changes https://github.com/solana-labs/token-list/pull/23186 it is urgent

**Comment by nooftproject** [comment]
@keone

**Comment by spacemandev-git** [comment]
merged
