### ISSUE TITLE
Update Vivaion Logo

### ISSUE THREAD

**Issue by BifrostTitan** [solana-labs/token-list#23195]
- **I'm submitting a ...**
  [ ] bug report
  [X] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

*PR with update of the logo: https://github.com/solana-labs/token-list/pull/22672

PR with update of GeckoID: https://github.com/solana-labs/token-list/pull/17600
PR where the token was added: https://github.com/solana-labs/token-list/pull/13498

**Comment by BifrostTitan** [comment]
@spacemandev-git
Not sure who is active for reviews, but submitted a PR a few days ago

**Comment by spacemandev-git** [comment]
merged
