### ISSUE TITLE
Manual review required due to updating token name

### ISSUE THREAD

**Issue by CMHayden** [solana-labs/token-list#23199]
- **I'm submitting a ...**
  [ x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Hey! Wondering if a manual review for this PR can be done https://github.com/solana-labs/token-list/pull/22854 I created the original token, and made a typo on the name. Would like to change from $HILLS to $SHILLS

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by spacemandev-git** [comment]
merged
