### ISSUE TITLE
Please help to change RAVAverse token address PR#23246

### ISSUE THREAD

**Issue by RavaChronicles** [solana-labs/token-list#23247]
- **I'm submitting a ...**
  [ ] bug report
  [ x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by RavaChronicles** [comment]
@keone

**Comment by RavaChronicles** [comment]
please accept the token address changes @keone

**Comment by spacemandev-git** [comment]
merged
