### ISSUE TITLE
AutoMerge failed for PPWL 

### ISSUE THREAD

**Issue by Proto133** [solana-labs/token-list#23288]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project
  [x] failed automerge

- **Summary**
```error validating schema: chainId: conflicting values 103 and 0```
I am not sure what I did wrong and I'm sorry. Can some one help?

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
- I did think I caught an error, closed my initial PR (which also failed auto merge).

https://github.com/solana-labs/token-list/pull/23287

**Comment by spacemandev-git** [comment]
https://github.com/solana-labs/token-list#error-validating-schema-chainid-conflicting-values-103-and-0

**Comment by Proto133** [comment]
> https://github.com/solana-labs/token-list#error-validating-schema-chainid-conflicting-values-103-and-0

Thank you, I'm not sure how I missed that, but do I now have to fix it and resubmit? Or will the original PR be manually merged?
