### ISSUE TITLE
Update ApesPlanet extensions twitter link

### ISSUE THREAD

**Issue by affankhan43** [solana-labs/token-list#23365]
- **I'm submitting an update request to update the existing token extension**

here is PR link [https://github.com/solana-labs/token-list/pull/23341](https://github.com/solana-labs/token-list/pull/23341)
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by spacemandev-git** [comment]
merged
