### ISSUE TITLE
Required manual review for added coingeckoId and serumV3Usdc for FOSSIL 

### ISSUE THREAD

**Issue by ShukutaiDinos** [solana-labs/token-list#23403]
auto-merge failed because adding coingeckoId and serumV3Usdc for FOSISL token.

Here is a link to the pull requestion: #23402 

- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
