### ISSUE TITLE
Build Fails: Out of Bounds 

### ISSUE THREAD

**Issue by fitzmode** [solana-labs/token-list#23418]
- **I'm submitting a ...**
  [x ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- Automerge succeeds but build fails on an `Out Of Bound` error for a listed tokens' Twitter URL
- My PR: https://github.com/solana-labs/token-list/pull/23416

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by spacemandev-git** [comment]
issue fixed
