### ISSUE TITLE
Build Fails Twiiter Out Of Bounds Issue

### ISSUE THREAD

**Issue by iSyqozz** [solana-labs/token-list#23432]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

Build Error= Validate.sh exits with code 1 and out of bounds description

**Comment by gurrajman** [comment]
I have the same issue.

**Comment by spacemandev-git** [comment]
just pushed a fix, please wait and auto merge should work again
