### ISSUE TITLE
Build Fails Twitter

### ISSUE THREAD

**Issue by gurrajman** [solana-labs/token-list#23433]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
This is the error message I got:

Run PATH=$PATH:~/go/bin ./validate.sh
tokens.101[6](https://github.com/solana-labs/token-list/runs/5723109083?check_suite_focus=true#step:8:6)2.extensions.twitter: invalid value "https://www.twitter.com/bitoptionsfxt" (out of bound =~"^[https://twitter.com/(\\w){1,15}$](https://twitter.com/(//w)%7B1,15%7D$)"):
    ./automerge/schema.cue:10[7](https://github.com/solana-labs/token-list/runs/5723109083?check_suite_focus=true#step:8:7):12
    ./src/tokens/solana.tokenlist.json:137621:20
Error: Process completed with exit code 1.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Pull request link: https://github.com/solana-labs/token-list/pull/23429

**Comment by StefosGeo** [comment]
I have the same issue. Unable to merge anything until its fixed.

**Comment by spacemandev-git** [comment]
just pushed the fix, please wait and the automerge should be working again soon
