### ISSUE TITLE
Manual merging is needed.

### ISSUE THREAD

**Issue by captozc** [solana-labs/token-list#23477]
I added a comma at the end of line, to add tags and extensions below the line.
In this case, the comma is necessary, right?

I think manual merging is required.

The error message:
found removed line: - "logoURI": "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/9XVR3R8K2qVsyRRuP4Y6edLqmmmGAMHgcqcnoWR7MyCL/logo.png"

_Originally posted by @captozc in https://github.com/solana-labs/token-list/issues/23476#issuecomment-1081315078_

**Comment by keone** [comment]
merged
