### ISSUE TITLE
Update Logo

### ISSUE THREAD

**Issue by philipp0903** [solana-labs/token-list#23538]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

I uploaded a new png because the first one did not work (I think the size was too big), hope it works now. 

Link to my PR: https://github.com/solana-labs/token-list/pull/23531

Thanks for your support!

**Comment by spacemandev-git** [comment]
merged
