### ISSUE TITLE
GTA token wrong logoURI and no chance to merge it w/o deletion

### ISSUE THREAD

**Issue by wenddak1ng** [solana-labs/token-list#2355]
- **I'm submitting a request for change logoURI on GTA token**

Token which I'm added with name GTA includes wrong logo URI.
I'm asking for change URI to "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/9YdABeMBMjh5Pu8yPkJ9GETGWUT8KUK3B2RYBpjKNPsU/logo.svg".

Thanks a lot for your patience

**Comment by wenddak1ng** [comment]
Up request

**Comment by keone** [comment]
Please link a PR
