### ISSUE TITLE
Remove LHMINT

### ISSUE THREAD

**Issue by drllvm** [solana-labs/token-list#23563]
- **I'm submitting a ...**
  - [x] token removal request from mainnet

- **Summary**
  - added in this PR: https://github.com/solana-labs/token-list/pull/15667
  - removed in this PR: https://github.com/solana-labs/token-list/pull/23561
  - no longer needed (deprecated)

**Comment by drllvm** [comment]
Any chance we can get this merged? cc/ @spacemandev-git

It should be ready to merge (no conflicts, etc.)

Thanks a lot

**Comment by keone** [comment]
merged
