### ISSUE TITLE
Modify LOOT

### ISSUE THREAD

**Issue by drllvm** [solana-labs/token-list#23569]
- **I'm submitting a ...**
  - [x] token modification request from mainnet / devnet

- **Summary**
  - added in this PR: https://github.com/solana-labs/token-list/pull/6563
  - modified in this PR: https://github.com/solana-labs/token-list/pull/23567
  - reason: change decimals from 9 to 4 (need to create a new token for it)

**Comment by drllvm** [comment]
Any chance we can get this merged? cc/ @spacemandev-git

It should be ready to merge (no conflicts, etc.)

Thanks a lot

**Comment by drllvm** [comment]
@keone Is there anything missing here? Any chance we can merge this? It would be really helpful.

Thanks a lot for your help!

**Comment by keone** [comment]
merged
