### ISSUE TITLE
I keep getting error validating schema: chainId: conflicting values 103 and 0

### ISSUE THREAD

**Issue by TreeBurgers** [solana-labs/token-list#23583]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Struggling ALOT with this PR https://github.com/solana-labs/token-list/pull/23577

Tried many times now & i keep getting error validating schema: chainId: conflicting values 103 and 0... Lost at this point. Can it be manually fixed?

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by poisendev91** [comment]
did you got the solution of it

**Comment by spacemandev-git** [comment]
https://github.com/solana-labs/token-list#error-validating-schema-chainid-conflicting-values-103-and-0
