### ISSUE TITLE
Update Logo - Manual Merge Request PR#18896

### ISSUE THREAD

**Issue by imentus-rahul** [solana-labs/token-list#23629]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Link to my PR: https://github.com/solana-labs/token-list/pull/18896/

Thanks for your support!

**Comment by spacemandev-git** [comment]
the PR seems to have been closed already
