### ISSUE TITLE
Update Logo and Name - Manual merge request - PR#23633

### ISSUE THREAD

**Issue by imentus-rahul** [solana-labs/token-list#23638]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Link to my PR: https://github.com/solana-labs/token-list/pull/23633

Thanks for your support!

**Comment by spacemandev-git** [comment]
merged
