### ISSUE TITLE
src/tokens/solana.tokenlist.json:139919:1 - error TS1185: Merge conflict marker encountered.

### ISSUE THREAD

**Issue by Dopepirate** [solana-labs/token-list#23661]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

Found 3 errors.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build:main" exited with 2.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.

what should i do?

**Comment by spacemandev-git** [comment]
when trying to build it'll tell you why it's failing. look up the reason on the FAQ on the readme in the repository.
