### ISSUE TITLE
Automerge Issue #24042

### ISSUE THREAD

**Issue by HedHunterDevelopment** [solana-labs/token-list#24025]
- **I'm submitting an issue due to an automerge error due to removal of line:   "name": "Solana Token List",**
  [ x] bug report
  [ ] feature request
  [  ] question about the decisions made in the repository
  [ ] question about how to use this [project](url)

- **Summary**
Auto-merge detail is saying that I removed line 2:   "name": "Solana Token List",
The line is still there and no other issues were found.

- **Other information** (e.g. detailed explanation, st
ack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

![image](https://user-images.githubusercontent.com/93787549/161413332-3472e67d-5527-48ec-9883-1113f3f086f8.png)

**Comment by HHGDev** [comment]
Auto-merge error on line 2 at: "name": "Solana Token List", 
Screenshot posted above. Line is in fact there.

**Comment by HHGDev** [comment]
https://github.com/solana-labs/token-list/pull/24024

Link to PR.
