### ISSUE TITLE
Updating tags and new extensions for Destiny Token

### ISSUE THREAD

**Issue by Anonymous-Pentester** [solana-labs/token-list#24026]
Hi Team ,
I need to update our token Destiny tags and extensions.
Please help us to merge this request
https://github.com/solana-labs/token-list/pull/24015

Having issue below
Not eligible for automerge (click details for more information)
unsupported file modified: /dev/null

Thank you!

**Comment by Anonymous-Pentester** [comment]
@spacemandev-git

**Comment by Anonymous-Pentester** [comment]
@keone

**Comment by Anonymous-Pentester** [comment]
@Aslienv

**Comment by Anonymous-Pentester** [comment]
Please merge manually as I am sure it will need to be.

**Comment by Anonymous-Pentester** [comment]
@spacemandev-git

**Comment by Anonymous-Pentester** [comment]
Please merge manually as I am sure it will need to be.

**Comment by keone** [comment]
merged
