### ISSUE TITLE
Manual merge requested for PR

### ISSUE THREAD

**Issue by acfadmin** [solana-labs/token-list#24174]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Please merge this [PR](https://github.com/solana-labs/token-list/pull/23949)

- **Other information**
The names of the tokens ACF and FEED have been updated in the new PR. Manual merging is required
  
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by poisendev91** [comment]
did you got the answer

**Comment by acfadmin** [comment]
No, the PR is still open. Can you please merge it?
