### ISSUE TITLE
Update DUST Protocol logo & links

### ISSUE THREAD

**Issue by 0xchill** [solana-labs/token-list#24995]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
In PR https://github.com/solana-labs/token-list/pull/24994, I am updating the logo used for the DUST Protocol token, website & discord link (added in PR https://github.com/solana-labs/token-list/pull/16601 ).

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Hoping to have this merged soon since this is time sensitive. Thank you.

**Comment by Vestcomp** [comment]
Sorry to add this question here. We are looking for someone to add our token to the token lists. Can anyone help?

**Comment by xxmafiaxxx** [comment]
> Sorry to add this question here. We are looking for someone to add our token to the token lists. Can anyone help?

what u need?

**Comment by daddydonke** [comment]
Math checks out.  Ready for manual merge.

**Comment by 0xchill** [comment]
@keone could you please merge this PR? thanks :)
