### ISSUE TITLE
Update Ivory Token's name

### ISSUE THREAD

**Issue by Peartes** [solana-labs/token-list#25060]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Updating the Ivory Token token's name to suit the company's directive. The PR creating token is [here](https://github.com/solana-labs/token-list/pull/24908)

The new PR to update the token is [here](https://github.com/solana-labs/token-list/pull/25059)
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by daddydonke** [comment]
New PR is not linked

**Comment by Peartes** [comment]
Hi thanks for the update. Linked the new PR [here](https://github.com/solana-labs/token-list/pull/25059)
