### ISSUE TITLE
Change the logoURI of the MoppelCoin token

### ISSUE THREAD

**Issue by fleibfried** [solana-labs/token-list#2521]
- **I'm submitting a ...**
  [x ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

I have done a mistake in the logoURI for the 

`MoppelCoin` 

Token with the address

`E5H5mHzUA8pRSL4X2ovv4sZMSorYk56EtCbQExQveRGJ`

in the 

`src/tokens/solana.tokenlist.json`

file. So the correct logoURI should be:

`https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/E5H5mHzUA8pRSL4X2ovv4sZMSorYk56EtCbQExQveRGJ/logo.png`

It would be great if you could fix that? I would be happy to do it by myself but I cannot change the file since the automerge would fail then.

**NOTE THIS RELATES TO THE FOLLOWING OPEN PR:**    https://github.com/solana-labs/token-list/pull/3299

**Comment by SolDev-stack** [comment]
Please read the [SPL-token README](https://github.com/SolDev-stack/token-list/blob/main/README.md), and ensure your SPL-token info uses the correct [Uniswap format](https://github.com/SolDev-stack/token-lists/blob/main/README.md).

**Comment by keone** [comment]
Responded on the PR, please rebase onto main (sorry for the delay)
