### ISSUE TITLE
Logo URI Correction

### ISSUE THREAD

**Issue by 9thwall** [solana-labs/token-list#2557]
- **I'm submitting a ...**
  [*] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I set the logoURI to an external URI. 
`https://cdn.jsdelivr.net/gh/9thwall/Oridion/logo-v1.png`

Token Name: 
`Oridion`

Token Address:
`HiQg2CX9BU24gsgDVXg5DR437z5ptYvnT3KY1D7nqfAw`

In case this is incorrect and the logouri needs to be in assets/mainet, 
I merged the logo file into the asset/mainet. Please update the logo to 
https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/HiQg2CX9BU24gsgDVXg5DR437z5ptYvnT3KY1D7nqfAw/logo.png

**Comment by samoboyz** [comment]
woof

**Comment by SolDev-stack** [comment]
Please read the [SPL-token README](https://github.com/SolDev-stack/token-list/blob/main/README.md), and ensure your SPL-token info uses the correct [Uniswap format](https://github.com/SolDev-stack/token-lists/blob/main/README.md).

**Comment by keone** [comment]
Link a PR and reopen this
