### ISSUE TITLE
Modify LPFi token list

### ISSUE THREAD

**Issue by aperire** [solana-labs/token-list#25643]
- **I'm submitting a ...**
  [ ] bug report
  [ X ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Updated LPFi token logo, changed mint address, PR: https://github.com/solana-labs/token-list/pull/25641
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by AingCreation** [comment]
Need to pull manual

**Comment by kise999** [comment]
Why don't you make PR?

**Comment by monkeyMax-SVG** [comment]
Hi, @kise999 
We made PR but it has automerge-error.
Can you please do merge manually from your side? thank you.
