### ISSUE TITLE
Request for automerge, updates existing token, metadata stSOL

### ISSUE THREAD

**Issue by j-tulforov** [solana-labs/token-list#25755]
- **I'm submitting a ...**
  [x] feature request

Hi, please manually merge our updates to stSOL token.

Original PR: https://github.com/solana-labs/token-list/pull/740
New PR: https://github.com/solana-labs/token-list/pull/14424

[@ruuda ](https://github.com/ruuda) and [@hritique](https://github.com/hritique) can confirm changes. Also I'm in [lidofinance organisation](https://github.com/lidofinance). U can check it in [my profile](https://github.com/j-tulforov).

**Comment by hritique** [comment]
I confirm changes

**Comment by j-tulforov** [comment]
@joncinque @keone can u please merge it?

**Comment by leoluk** [comment]
Done
