### ISSUE TITLE
Update Picaso Token "LogoURI"

### ISSUE THREAD

**Issue by boosbasement** [solana-labs/token-list#25786]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- Please update the "LogoURI" for Picaso token. Original submission has wrong image. The updated PR has the correct one. https://github.com/solana-labs/token-list/pull/25506
Thanks

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
https://github.com/solana-labs/token-list/pull/25506

**Comment by leoluk** [comment]
Duplicate
