### ISSUE TITLE
Manual review request, Update to Token address/name/website for FLOAT and D3D

### ISSUE THREAD

**Issue by rodasemi5** [solana-labs/token-list#25995]
- **I'm submitting a ...**
  [] bug report
  [*] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- The address for both of these tokens needs to be updated and the names
- also the website for Dead Rejects needs to be updated
- PR: https://github.com/solana-labs/token-list/pull/25994

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by rodasemi5** [comment]
Any news on this update?

**Comment by JakeRoyRandall** [comment]
@keone @leoluk @spacemandev-git
