### ISSUE TITLE
Add usd value to token

### ISSUE THREAD

**Issue by Mynameispandan** [solana-labs/token-list#2667]
I would like to add usd value to the bamboo token 

5sM9xxcBTM9rWza6nEgq2cShA87JjTBx1Cu82LjgmaEg

**Comment by SolDev-stack** [comment]
Please read the [SPL-token README](https://github.com/SolDev-stack/token-list/blob/main/README.md), and ensure your SPL-token info uses the correct [Uniswap format](https://github.com/SolDev-stack/token-lists/blob/main/README.md).
