### ISSUE TITLE
Failed to auto Merged : found removed line: -  need manual merged

### ISSUE THREAD

**Issue by droidbitnft** [solana-labs/token-list#26903]
- **I'm submitting a ...**
  [X] bug report
  [X] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (Add Official Website DroidBits Token, and some bug i added decimal 6 but showing 9 on solscan.)
-New PR Fix https://github.com/solana-labs/token-list/pull/26910
Original PR https://github.com/solana-labs/token-list/pull/26572

**Comment by droidbitnft** [comment]
@keone could you please merge this PR? thanks :)

**Comment by droidbitnft** [comment]
hello , can you help me @mercs-shashank

**Comment by mercs-shashank** [comment]
What happened ?

**Comment by droidbitnft** [comment]
i need to update our website please approve manual merge thank a lot

**Comment by droidbitnft** [comment]
i need to update our website please approve manual merge thank a lot

**Comment by mercs-shashank** [comment]
i dont have authority to merge
