### ISSUE TITLE
Why don't you handle the issue? Is it a vacation?

### ISSUE THREAD

**Issue by yoo-pro** [solana-labs/token-list#27751]
There are a lot of people waiting, including me, and it seems that no one has been active for weeks.

Did it stop with the network? Please operate the ecosystem normally.

**Comment by balolo2** [comment]
I waited for almost a month but didn't get any response. Frustrating as fuck

**Comment by yoo-pro** [comment]
Many people have similar feelings.

**Comment by yoo-pro** [comment]
There is no response even if I send an email.

**Comment by balolo2** [comment]
Do you have the automerge issue as well?

**Comment by yoo-pro** [comment]
yes, im still waiting

**Comment by huyhn310** [comment]
Does anyone got updated? I waited for 3 weeks also. Seem noone care

**Comment by yoo-pro** [comment]
@keone

**Comment by balolo2** [comment]
did you manage to get it fixed?
