### ISSUE TITLE
Double Pull request, token issue...UNSUAL

### ISSUE THREAD

**Issue by AyoCodess** [solana-labs/token-list#2880]
https://github.com/solana-labs/token-list/pull/2843/files/31e7c6341bfe3733560e1ac5a145358322131946..1f1b026b03823f40c7e5ca13f76fb4e965543815

Hey, i've made this pull request or 2... i'm coming up against a few issues as its not automerging and as you can see i may have duplicated the pull request. im not sure if i done it correctly. Can you help? Thanks

1. https://github.com/solana-labs/token-list/pull/2843
2.  https://github.com/solana-labs/token-list/pull/2846

**Comment by AyoCodess** [comment]
can anyone help?

**Comment by SolDev-stack** [comment]
I can help.

**Comment by keone** [comment]
sorry for your trouble; your PRs are a huge diff against main so please rebase and then either reopen one of them or open a new PR and link it here
