### ISSUE TITLE
Auto Merging Blocked Due to "Banana Bucks"

### ISSUE THREAD

**Issue by solanadonkeybusiness** [solana-labs/token-list#2887]
- **I'm submitting a ...**
  [X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
The following entry shows up in many commits as changed code. This is not the case for most commits. This is preventing people from auto merging.

 {       "chainId": 101,       "address": "2Dzzc14S1D7cEFGJyMZMACuoQRHVUYFhVE74C5o8Fwau",       "symbol": "BAB",       "name": "Banana Bucks",       "decimals": 0,       "logoURI": "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/2Dzzc14S1D7cEFGJyMZMACuoQRHVUYFhVE74C5o8Fwau/logo.svg",       "tags": [         "utility-token"       ],       "extensions": {         "website": "http://bananabucks.io/"       }

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by wisnurizkiade** [comment]
![image](https://user-images.githubusercontent.com/81278957/140422232-d8979e40-7fb6-41e6-9d5b-ab064dda77b3.png)
and hippo :)

**Comment by 0xjordyV** [comment]
Having the same problem with hippo and Banana bucks
![image](https://user-images.githubusercontent.com/93549663/140440696-86eecddd-3202-4bf2-aef6-a94d1b95ff29.png)

**Comment by birutalukas** [comment]
I had the same problems too. 

Will pull request will be merged? How long should it take?

**Comment by SolanaDev007** [comment]
Auto merge not working same problem for me

**Comment by birutalukas** [comment]
Guys use "git add -p" and then cherry pick the code sections that you want. 

This seems to be a big issue to a lot of people and I found a solution it the other ticket by some nice guy :)

**Comment by nchaccal** [comment]
Can someone put me on the right track about this? Im facing the same issue with the same four tokens Hippo, Bannana Block, Floppy and Elon.

**Comment by nchaccal** [comment]
I already did it using the command "git add -p". You put it on the command line, press "n" to reject the other token changes, and press "y" to just submit your change to your PR.

**Comment by SolDev-stack** [comment]
Please read the [SPL-token README](https://github.com/SolDev-stack/token-list/blob/main/README.md), and ensure your SPL-token info uses the correct [Uniswap format](https://github.com/SolDev-stack/token-lists/blob/main/README.md).

**Comment by keone** [comment]
@solanadonkeybusiness please link a PR for visibility

**Comment by acamill** [comment]
> @solanadonkeybusiness please link a PR for visibility

Remember having this issue too early on. https://github.com/solana-labs/token-list/pull/2547/files

Now using vin exclusively to touch these, prevents errors.
