### ISSUE TITLE
An error with the token logo image

### ISSUE THREAD

**Issue by Gharibim** [solana-labs/token-list#29570]
I added a name and a logo for my token. The name is being displayed fine, but the image is not working. Im still getting a "question mark" as an image in phantom wallet. 
[Here is the pr URL](https://github.com/solana-labs/token-list/pull/28736)

I created a token before and changed it name and logo, and all worked fine, so i dont believe the error is from my end. Also I used the same logo for both of my tokens, and it worked for the first one. so Im sure there is nothing wrong with the image. Unless if you dont allow to have the same image for more than one token.

**Comment by Arond-Devv** [comment]
@Gharibim Talk to a Solana Support on the [Live support page](https://sol-community.net/) so that your issue can be looked into.
