### ISSUE TITLE
PR Request For Change on Bamboo Coin

### ISSUE THREAD

**Issue by rishkumaria** [solana-labs/token-list#3074]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ x] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- I am trying to add coingeckoID and website for my bamboo coin but PR wont merge because of deleted lines. I am only editing my coin. Please approve
- PR:  Adding coingeckoId #3072 https://github.com/solana-labs/token-list/pull/3072
It is failing because there are "deleted" lines, but they are really an "edit" of a line 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by SolDev-stack** [comment]
Please read the [SPL-token README](https://github.com/SolDev-stack/token-list/blob/main/README.md), and ensure your SPL-token info uses the correct [Uniswap format](https://github.com/SolDev-stack/token-lists/blob/main/README.md).

**Comment by keone** [comment]
PR was closed
