### ISSUE TITLE
Add SOLEM token logo & name

### ISSUE THREAD

**Issue by SolemPad** [solana-labs/token-list#3413]
` {
"chainId": 101,
"address": "6qAJ9W5XCb2JyrTRV8bcoXa6HmHNz9YikLMWK71dH1sY",
"symbol": "SOLEM",
"name": "SolemPad",
"decimals": 6,
"logoURI": "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/6qAJ9W5XCb2JyrTRV8bcoXa6HmHNz9YikLMWK71dH1sY/logo.png",
"tags": [],
"extensions": {
"website": "https://www.solempad.net/"
"twitter": "https://www.twitter.com/solempad"
"telegram": "https://t.me/solempad"
}
},

Hello Team please update my token name and ticker `

**Comment by solana-nft** [comment]
@SolemPad missing comma

`{
"chainId": 101,
"address": "6qAJ9W5XCb2JyrTRV8bcoXa6HmHNz9YikLMWK71dH1sY",
"symbol": "SOLEM",
"name": "SolemPad",
"decimals": 6,
"logoURI": "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/6qAJ9W5XCb2JyrTRV8bcoXa6HmHNz9YikLMWK71dH1sY/logo.png",
"tags": [],
"extensions": {
"website": "https://www.solempad.net/",
"twitter": "https://www.twitter.com/solempad",
"telegram": "https://t.me/solempad",
}
}`

**Comment by solana-nft** [comment]
{
"chainId": 101,
"address": "6qAJ9W5XCb2JyrTRV8bcoXa6HmHNz9YikLMWK71dH1sY",
"symbol": "SOLEM",
"name": "SolemPad",
"decimals": 6,
"logoURI": "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/6qAJ9W5XCb2JyrTRV8bcoXa6HmHNz9YikLMWK71dH1sY/logo.png",
"tags": [],
"extensions": {
"website": "https://www.solempad.net/",
"twitter": "https://www.twitter.com/solempad",
"telegram": "https://t.me/solempad"
}
}

**Comment by SolemPad** [comment]
I always fail, can you add that for me?
