### ISSUE TITLE
The solana.tokenlist.json file has gotten out of hand 

### ISSUE THREAD

**Issue by timothyBrake** [solana-labs/token-list#3479]
- **I'm submitting a ...**
  [ ] bug report
  [ x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

1. The **solana.tokenlist.json** isn't even valid json anymore as people just seem to add content at the end of the file without knowing what json is. They are putting content past the "version" property that should be in the "tokens" property. The file si also 23271 lines of JSON which is considerable amount and most likely isn't going to shrink but only expand.

2. Someone also committed a .**solana.tokenlist.json.swp**  as the .**gitignore** file doesn't exclude these hidden files. This swap file is used by **vim** and any user that tries to modify the file **solana.tokenlist.json** file to add tokens using **vim solana.tokenlist.json** will get a big warning and needs to manually delete that hidden file.

3. Opening the file in an Editor like IntelliJ, will have issues as IDEs try and format the json and possibly delete some spaces, tabs, etc... matching their code styling. This is not allowed however as there is a git auto merge check that fails because something was possibly deleted while opening the file. Even though users only added their lines of code, their IDE most likely did something to mess with the layout. Just looking at the amount of Issues at the moment seem to all have these types of issues.

Maybe a better solution would be to have a single directory per token (like the _/assets/tokenId/logo.png_) and have the user add all content needed for their token at this single location. All above issues would be fixed instant. E.g.
/tokens
   /TOKEN_ID
    logo.png
    token.json

token.json example would be:
`{
    "chainId": 101,
    "address": "YOUR_TOKEN_ID,
    "symbol": "YOUR_SYMBOL",
    "name": "YOUR_NAME",
    "decimals": 9,
    "logoURI": "logo.png",
    "tags": [
      "utility-token"
    ],
    "extensions": {
      "website": "https://url-to-your-website"
    }
  }`
Then improve the README.md file with these steps to take.

Then have some code running while processing the file **solana.tokenlist.json** to get all the **token.json** files in all directories and populate the file **"tokens"** property.
This would benefit all users adding new tokens and Solana developers in charge of checking the pull requests. As new users do NOT have to change any code from other users and thus no failed pull request and accidentally deleted lines due to formatting by IDEs.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by MagmoxGit** [comment]
Nice suggestion. I hope they consider this as it will solve most problems.

**Comment by kacipbuah** [comment]
Great idea

**Comment by MadJimJaspers** [comment]
Agreed, github/solana-labs is moving very slow these days, hard to get anything done!

**Comment by SolDev-stack** [comment]
Please read the [SPL-token README](https://github.com/SolDev-stack/token-list/blob/main/README.md), and ensure your SPL-token info uses the correct [Uniswap format](https://github.com/SolDev-stack/token-lists/blob/main/README.md).

**Comment by leoluk** [comment]
This was solved by the new automerge bot, which prevents any invalid changes to the JSON

**Comment by MadJimJaspers** [comment]
This hasn’t been solved, wha the heck you guys make this so hard to do, I have a green tick next to everything, it just needs approving

**Comment by timothyBrake** [comment]
Maybe it’s time to tell-open this ticket as the open pull request with merge issues has REALLY gotten out if hand and the build script ‘solution’ is obvious not a solution. This feature request displays a solution but anything is better than what is happening now.
