### ISSUE TITLE
[important] I need to remove "NFT" tag of my token

### ISSUE THREAD

**Issue by ngocbv** [solana-labs/token-list#3569]
I am the owner of PANDA coin, I added PANDA to token-list repo (#3114). I added NFT tag accidentally so PANDA token is only shown in Collectibles section while PANDA is not a Collectible. It has 10,000,000,000 token in total (https://explorer.solana.com/address/Aw8qLRHGhMcKq7rxs5XBNCd9oe3BvoAhpNMVz7AdGmty)

Please help me to merge this PR. Many thanks

_Originally posted by @ngocbv in https://github.com/solana-labs/token-list/issues/3297#issuecomment-964004924_

**Comment by nchaccal** [comment]
If you find the way to do it, please let me know. Im facing exactly the same problem since two weeks ago.

**Comment by ngocbv** [comment]
@nchaccal Yeah, hope someone in solana-labs see and merge this PR. I also raised the ticket to Phantom because we can't base on a tag to categorize a token is NFT or not, a NFT need some requirements like can't mint more, total supply is 1.

**Comment by nchaccal** [comment]
I did the same in Phanton and they told me I had to restart the app, obviously not working.

**Comment by nchaccal** [comment]
@ngocbv, did you find a solution for this? I've already tried modifying my tag from "NFT" to "NFT-Token", but no luck, the system still detects it as a delete.

**Comment by ngocbv** [comment]
@nchaccal not yet, we have to wait solana-labs employees

**Comment by samoboyz** [comment]
The rug has been pulled long ago boys. Devs are in Panama now.

**Comment by SolDev-stack** [comment]
@ngocbv Please edit your fork of main/assets as per the FAQ and submit a PR. The next scheduled merge is in 3 months.

**Comment by keone** [comment]
merged
