### ISSUE TITLE
Remove duplicate token

### ISSUE THREAD

**Issue by SecretSquirrelAssociation** [solana-labs/token-list#3642]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [x] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Initially, we added NUTS successfully but without the correct brackets. It's towards the bottom of token list. After realizing this, we added it again towards the top successfully. Both were merged, can you delete the first one with the wrong brackets, and keep the second one that is towards the top?

**Comment by SolDev-stack** [comment]
Please read the [SPL-token README](https://github.com/SolDev-stack/token-list/blob/main/README.md), and ensure your SPL-token info uses the correct [Uniswap format](https://github.com/SolDev-stack/token-lists/blob/main/README.md).

**Comment by keone** [comment]
Please link a PR!
