### ISSUE TITLE
Delete Duplicate Token Information due to automerge

### ISSUE THREAD

**Issue by 3LechesCake** [solana-labs/token-list#3909]
- **I'm submitting a ...**
  [ X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

During my initial pull request automerge worked no problem, however i identified that Phantom dont like more than x amount of characters for the symbol so had to update the symbol. Since this property is identified as delete the automerge failed, had to create a new record and automerge accepted the same, the problem is now we have a duplicate record on the token list. 

Can we please delete the token info for 3LechesCake and leave the valid one TresLeches since looks like is an acceptable symbol globally.

I suggest automerge to allow initial pull to be updated for better token info, or to use the TrustWallet Method of updating each token info on their info.json.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by 3LechesCake** [comment]
can i get the pull for the nft completed D2m2WoHKXdahVwA6gUxqfuCgxbUWv1S9y2p4mMRqnuWi

**Comment by 3LechesCake** [comment]
looks like no updates, will check back later.

**Comment by samoboyz** [comment]
Did you pay the fast track fee?

**Comment by 3LechesCake** [comment]
Looks like it merged now and is not duplicate, Going to close this issue for now and hope it gets merged to main.
