### ISSUE TITLE
Need to remove "NFT" tag of my token

### ISSUE THREAD

**Issue by nchaccal** [solana-labs/token-list#3970]
- **I'm submitting a ...**
  [X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- I need to remove the "NFT" tag of my token GHOST. I added by mistake and now my token its showing itself as a collectible on the Phantom Wallet. I've already tried modifying my tag from "NFT" to "NFT-Token", but no luck, the system still detects it as a 1 insertion + 1 delete. Can you please help me to merge it. Many thanks! 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by SolDev-stack** [comment]
Please read the [SPL-token README](https://github.com/SolDev-stack/token-list/blob/main/README.md), and ensure your SPL-token info uses the correct [Uniswap format](https://github.com/SolDev-stack/token-lists/blob/main/README.md).

**Comment by leoluk** [comment]
Just make a PR and it can get merged manually
