### ISSUE TITLE
Whitelist API for Tokens

### ISSUE THREAD

**Issue by canuckasaurus** [solana-labs/token-list#40]
- **I'm submitting a ...**
  [ ] bug report
  [X] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
If I plan on creating derivative tokens... aka stake token per epoch - this seems woefully inefficient as I am going to be posting every epoch to add tokens.
I suggest possibly a whitelist based API - sign-up requires code review to make sure it's done in line with guidance.

**Comment by mvines** [comment]
This repository can be made read-only as soon as the Token Metadata work that's happening https://github.com/solana-labs/solana-program-library/pull/1544 is completed and alive. At this point, you'll be able to create your own metadata in a fully decentralized way.

**Comment by bartosz-lipinski** [comment]
Please take a look at: https://www.notion.so/Metaplex-Developer-Guide-afefbc19841744c28587ab948a08cfac
