### ISSUE TITLE
Analysis not found in Code scanning results / CodeQL 

### ISSUE THREAD

**Issue by KENHAU** [solana-labs/token-list#4020]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ X] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Guys, finally I can submit my first pull request "first commit for TKB & TKB Coin #3988" for launching my first Solana Token, however, there are some problems that occur after auto-merge as below: 

1. Automerge / auto-merge (pull_request_target) Successful in 1m — auto-merge
2. **Code scanning results / CodeQL Completed in 1m — 1 analysis not found**
3. Summary Successful in 1s — no rules configured, just listening for commands
4. This branch has no conflicts with the base branch

Points 1, 3, 4 seem fine but only Point 2 said that 1 analysis was not found. After I click on the "Details", there was a table shown the following not found:

.github/workflows/codeql_analysis.yml:analyze/language:javascript | ✔️  Found | ❓  Not found

I am sure that I did not make any change against this file and I pushed the whole file of token-list for the pull request, is there any problems that I have missed? Or how can I fix it? please and thank you very much!

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by solkumadev** [comment]
I think they have to approve if you have a new account. Had the same issue, i have searched everywhere, cant find a solution. Did you find a solution to this?

**Comment by KENHAU** [comment]
> I think they have to approve if you have a new account. Had the same issue, I have searched everywhere, can't find a solution. Did you find a solution to this?

I created my account a few weeks ago and this is my first time to succeed to send a pull request, as your video said that you have got an email to inform you that succeed named your SPL token on the chain, how long have you waited for the email?

I have searched for a long time but still have not gotten the answer, I keep refreshing my email in hopes of the notification email from GitHub telling me that my token is named successfully on the chain, ha. Thank you so much for your advice and sharing.

**Comment by leoluk** [comment]
New automerger should fix this

**Comment by SkyCandy2** [comment]
> New automerger should fix this

What's the method of getting the **automerger** to work while in limbo? 
Says pull request not found for: 
> .github/workflows/build.yml:analyze/language:javascript
> .github/workflows/codeql-analysis.yml:analyze/language:javascript

**Comment by osmanbehluli** [comment]
I have the same problem right now, do anyone know how to solve?

**Comment by osmanbehluli** [comment]
> 

Did you found a solution?
