### ISSUE TITLE
[IMPORTANT] Need to edit tags of "Valknut (VAL)" - "Valknut Gold (Ticket)"

### ISSUE THREAD

**Issue by SolVikings** [solana-labs/token-list#4101]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
We have successfully merged the "Valknut Gold" (Ticket) token and the "Valknut" (Val) token to the token-list project, but since we use the "NFT" tag on our tokens, our tokens appear NFT section in the Phantom Wallet and make transactions very difficult. Could you please remove the nft tags from our tokens (Valknut Gold - Valknut)? It is very important for the development of our project. I wish you healthy days in these pandemic days. Regards.

Add Valknut Token pull request: https://github.com/solana-labs/token-list/pull/2663

Add Valknut Gold Token pull request: https://github.com/solana-labs/token-list/pull/3183

Github: https://github.com/SolVikings
Website: https://solvikings.com/
Discord: https://discord.com/solvikings
Twitter: https://twitter.com/solvikingsnft

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by SolDev-stack** [comment]
Please read the [SPL-token README](https://github.com/SolDev-stack/token-list/blob/main/README.md), and ensure your SPL-token info uses the correct [Uniswap format](https://github.com/SolDev-stack/token-lists/blob/main/README.md).

**Comment by SolVikings** [comment]
@certus-bot https://github.com/solana-labs/token-list/pull/4748

**Comment by SolVikings** [comment]
Thank you very much for getting back to my message.  Can you merge our pull request?  It is very important for the development of our project.  I wish you good health in these pandemic days.
