### ISSUE TITLE
Issue with the pull request "add solid bit token #1062"

### ISSUE THREAD

**Issue by sdsnake** [solana-labs/token-list#4138]
I'm submitting a pull request for adding my solid bit token but i failed 
  [ ] i got this error on build "Build / build (pull_request)" yarn test: 
"
 2 tests failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "test:unit" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
"
 I want add my token solid bit token
How  I can fix this?

Can you help me please?

I used vs code to format json.

**Comment by SolDev-stack** [comment]
Please read the [SPL-token README](https://github.com/SolDev-stack/token-list/blob/main/README.md), and ensure your SPL-token info uses the correct [Uniswap format](https://github.com/SolDev-stack/token-lists/blob/main/README.md).

**Comment by keone** [comment]
please link a PR and then reopen this issue
