### ISSUE TITLE
Delete 3vHSsV6mgvpa1JVuuDZVB72vYbeUNzW4mBxiBftwzHEA

### ISSUE THREAD

**Issue by rpinkney84** [solana-labs/token-list#4183]
- **I'm submitting a ...**
request to get the "assets/mainnet/3vHSsV6mgvpa1JVuuDZVB72vYbeUNzW4mBxiBftwzHEA" deleted. It's a file and we need a folder. It's blocking us from updating our logo on the explorer.

**Comment by SolDev-stack** [comment]
Please read the [SPL-token README](https://github.com/SolDev-stack/token-list/blob/main/README.md), and ensure your SPL-token info uses the correct [Uniswap format](https://github.com/SolDev-stack/token-lists/blob/main/README.md).
