### ISSUE TITLE
Code scanning results / CodeQL — 1 analysis not found. please aprobe the #4279

### ISSUE THREAD

**Issue by Itsystemsproyect** [solana-labs/token-list#4284]
- **I'm submitting a ...**
  [ ] bug report
  [*] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

I'm going for the eleventh attempt with the pull request, and there are already 2 times that all the controls have passed but 2 hours ago it came out that conflicts were generated and it was due to the version change to "0.2.295", and I canceled the request to solve it now they all passed again (4 successful controls and 1 neutral). How long will I have to wait for my ITSC token to be added?

**Comment by SolDev-stack** [comment]
Please read the [SPL-token README](https://github.com/SolDev-stack/token-list/blob/main/README.md), and ensure your SPL-token info uses the correct [Uniswap format](https://github.com/SolDev-stack/token-lists/blob/main/README.md).

**Comment by keone** [comment]
Sorry for the trouble! Please link a PR
