### ISSUE TITLE
URL Typo Fix please

### ISSUE THREAD

**Issue by bradleyjw** [solana-labs/token-list#4352]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

bradleyjw:patch-2

Pull request #4000  to fix a typo in the URL for the logo for our project. We errantly used assets rather than mainnet. 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

All other information is correct, just the path to logo. Thank you.

**Comment by SolDev-stack** [comment]
Please read the [SPL-token README](https://github.com/SolDev-stack/token-list/blob/main/README.md), and ensure your SPL-token info uses the correct [Uniswap format](https://github.com/SolDev-stack/token-lists/blob/main/README.md).
