### ISSUE TITLE
ANYONE PLEASE APPROVE MY PULL REQUEST

### ISSUE THREAD

**Issue by SolBoxer** [solana-labs/token-list#4359]
PLEASE APPROVE MY PULL REQUEST AS SOON AS POSSIBLE WE WANT TO LAUNCH OUR TOKEN.

PULL REQUEST LINK : https://github.com/solana-labs/token-list/pull/4356

**Comment by GemsGame** [comment]
we can only wait

**Comment by kacipbuah** [comment]
yes need to wait

**Comment by islaperfito** [comment]
pls approve https://github.com/solana-labs/token-list/pull/4172

**Comment by samoboyz** [comment]
ahahahahaha!! There's no-one here. It's all a scam!

**Comment by LizardCrypto** [comment]
Thought we all agreed to not ping/message/etc anyone about pull requests ..
.. ..

**Comment by CoinHunterFiverr** [comment]
+++ SCAM +++ https://github.com/Solana-Developer/token-lists#readme
DON'T Send Sol To C7JF4JYtVeEW9YPZVomcfCqTD1viQdzmFjbruq4TeDb1

**Comment by GemsGame** [comment]
> +++ SCAM +++ https://github.com/Solana-Developer/token-lists#readme DON'T Send Sol To C7JF4JYtVeEW9YPZVomcfCqTD1viQdzmFjbruq4TeDb1

you sent 0.25 sol to this guy? obviously this is not real developer. No any commits in solana blockchain

**Comment by bigearsenal** [comment]
I HAVE NOTHING TO DO WITH THIS Solana-Developer scammer https://github.com/solana-labs/token-list/issues/4442
