### ISSUE TITLE
We are community of 17k+ members eagerly waiting for PR merge

### ISSUE THREAD

**Issue by solcatcoin** [solana-labs/token-list#4376]
Please help us merge

We are SOLCATCOIN, and a big family of 17k+ members and 3000+ holders of $MEW token. We request the concerned person and the contributors to help merge this PR.  Thanks a lot. Do hop in our cat family discord   http://discord.gg/solcatcoin
Merge request : https://github.com/solana-labs/token-list/pull/4097

**Comment by solcatcoin** [comment]
Any help appreciated :)

**Comment by solcatcoin** [comment]
@bartosz-lipinski Help please :)

**Comment by samoboyz** [comment]
The Solana devs have rug-pulled boyz, time to find a new rodeo.

**Comment by akaoppa** [comment]
> Please read the [SPL-token README](https://github.com/SolDev-stack/token-list/blob/main/README.md), and ensure your SPL-token info uses the correct [Uniswap format](https://github.com/SolDev-stack/token-lists/blob/main/README.md).

Can someone ban this guy ? He is pretending to be a dev and ask people to pay a "fast track fee" to be listed faster on his own fork repo faser roflmao. Don't fall for this.

![image](https://user-images.githubusercontent.com/60573069/142195703-2c3ddde3-031b-4db7-acdd-9fc5d3f8f37d.png)
![image](https://user-images.githubusercontent.com/60573069/142195766-9fea615d-b629-4c5c-99d0-fa5ddf4afbb4.png)
![image](https://user-images.githubusercontent.com/60573069/142195819-b6cd0356-ddc8-4dcf-9ec7-ce1b0d67b386.png)

**Comment by Solana-Developer** [comment]
Banned.

**Comment by CoinHunterFiverr** [comment]
+++ SCAM +++ https://github.com/Solana-Developer/token-lists#readme
DON'T Send Sol To C7JF4JYtVeEW9YPZVomcfCqTD1viQdzmFjbruq4TeDb1

**Comment by WhiteElephantEco** [comment]
dm me we can help we just merged 2 tokens today. this is free so i anyone asking you for money using our logo do not talk to them.
