### ISSUE TITLE
Build issue on PR #4386

### ISSUE THREAD

**Issue by vladtoni** [solana-labs/token-list#4391]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Can someone manually check PR #4386 ? 
The build check fails but I checked the code a bunch of times and it shouldn't, don't know where to go from here.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by leoluk** [comment]
Remove the `#` sign from the token name
