### ISSUE TITLE
Basic sanity checking on PR's for Token lists

### ISSUE THREAD

**Issue by vp-making-it** [solana-labs/token-list#4404]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [x ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

I noticed a PR recently for something called "Otter Coin"
https://github.com/solana-labs/token-list/commit/2a8d25bfb09d00d024e620cf7d679ea152d0fff3

I checked and none of the links even go anywhere. The twitter is dead. Website is dead. Logo does not load.

If we're going to have some centralised gate for submitting tokens to the list, then some sort of validation should occur before being published.

Otherwise decentralise this process somehow so that tokens can be submitted in a permissionless way.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by samoboyz** [comment]
No one will ever read this

**Comment by LizardCrypto** [comment]
Cheers @Samoboyz

**Comment by akaoppa** [comment]
> Approved

You are reported to Solana Team for scam. Don't contact this guy, he's a scammer

**Comment by bigearsenal** [comment]
https://github.com/solana-labs/token-list/issues/4442

**Comment by leoluk** [comment]
Done
