### ISSUE TITLE
Why are some tokens getting merged while 1000+ ready-to-merge PRs are stuck unapproved? #4172

### ISSUE THREAD

**Issue by islaperfito** [solana-labs/token-list#4452]
- **I'm submitting a ...**
  [ ] bug report
  [x ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
My PR to update SAO token information has been sitting for 4 days, even with automerge label. I am wondering why other tokens are being approved automatically while 1000+ PRs with automerge label are sitting unmerged. 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
It is urgent that we get https://github.com/solana-labs/token-list/pull/4172 approved along with other qualifying PRs that meet the requirements.

**Comment by GemsGame** [comment]
Vitalik Buterin win?!

**Comment by gimple** [comment]
Honestly, 4 days is nothing.  It clearly states multiple times that there is going to be a wait for this, I am not at all a fan of the current setup, believe me, but, there is a large number of spam tokens and BS "projects" being listed on here, I think the people who are tasked with issuing merges are overwhelmed and I would like to believe that they are going through some of them manually to make sure that they are legit/not outright scams etc.  

I would say to wait another few days and see what happens, the usual wait time for this seems to be about 2 weeks and posting about it on here numerous times doesn't seem to help from what I can tell.  Hopefully this all gets resolved soon both for you and for the people who use Solana in general.

**Comment by bigchickendefi** [comment]
ive been waiting for about 14 days just to change a logo on my coin, just need one person to push it through. Auto merge failed with about 1300 other ones lol
