### ISSUE TITLE
Please merge this pr https://github.com/solana-labs/token-list/pull/4120

### ISSUE THREAD

**Issue by ArjLab** [solana-labs/token-list#4465]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by ArjLab** [comment]
[https://github.com/solana-labs/token-list/pull/4120/commits/aa043dbd54038cded91bc8bd57ca23bb73bb43a5](url)

**Comment by ArjLab** [comment]
[https://github.com/solana-labs/token-list/pull/4120](url)

**Comment by ArjLab** [comment]
[https://github.com/solana-labs/token-list/pull/4120]

**Comment by ArjLab** [comment]
https://github.com/solana-labs/token-list/pull/4120

**Comment by WhiteElephantEco** [comment]
if you need help dm me. this is for free so anyone posing and using our logo and would ask for money do not give anything.

**Comment by leoluk** [comment]
Your PR isn't getting merged because it contains invalid changes
