### ISSUE TITLE
SolDev333 submitted our token information taking advantage of the backlog of PR's

### ISSUE THREAD

**Issue by cept0r** [solana-labs/token-list#4467]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [x] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
This was our original PR done by a person we hired to help us out 5days ago https://github.com/solana-labs/token-list/pull/4139. [Coinhunter](https://github.com/CoinHunterFiverr) profile is now somehow not active anymore and I just found out that there is a new PR with our exact token information: https://github.com/solana-labs/token-list/pull/4464. We request that you invalidate this PR.
SolDev333 is a brand new GitHub account and it seems like there are other related issues on the issues list. This looks like a malicious attempt from an unknown actor. We hold the keys to the token account & website and we can prove it if necessary.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions on how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
Here is the message sent by CoinHunterFiverr: https://gyazo.com/39089c8acaafbebd73afec6e8e38e370, I've also reported SolDev333 for abusive behavior. 
I hope you reach out to us very soon with a solution for our issue meanwhile have a great day.

Regards,
cept0r 
WAGMI team

**Comment by chrisss11** [comment]
It'd be much appreciated if this could be solved as soon as possible.

**Comment by KickerBtc** [comment]
!!! PR #4464 IS A SCAM !!!

**Comment by cept0r** [comment]
@certus-bot It is our token, we hold the keys to our twitter, webpage and token accounts. And we're happy to prove it. I have no clue who SolDev333 is but I suspect he somehow got the person we hired to do #4139 banned. Please look into this.

Regards,
cept0r
WAGMI team

**Comment by cept0r** [comment]
We're doing it right now. I will link it in here and tag you once it's done thank you.

Regards,
cept0r
WAGMI team

**Comment by cept0r** [comment]
Here is our PR @certus-bot  https://github.com/solana-labs/token-list/pull/4476.

Regards,
cept0r
WAGMI team

**Comment by cept0r** [comment]
@certus-bot Thanks for your help! We very much appreciate it <3

Regards,
cept0r
WAGMI team
