### ISSUE TITLE
separation - proposal

### ISSUE THREAD

**Issue by crysptos** [solana-labs/token-list#4474]
- **I'm submitting a proposal**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Maybe is better if you can automate the PRs for token requests by placing a small json file in the same folder where the logo resides. Is simpler to automate the process and the list.json can be very clear and compact (for older versions to keep track too)
Everyone is messing with the same errors, putting tokens at the beginning or at the end, a lot of IDEs segmentation, and so on...

please take this into consideration, Solana has some traction and I want this project to succeed. 

have a nice day 
武士道 🍜

**Comment by bigearsenal** [comment]
I have told them about that.

**Comment by leoluk** [comment]
I think this is solved with the new automerger doing conflict-less semantic merges and ignoring syntax errors :)
