### ISSUE TITLE
Feature request: Add SECO and HOLY logoURI

### ISSUE THREAD

**Issue by olivbau** [solana-labs/token-list#451]
### Feature request

Is it possible to add a logo for SECO and HOLY tokens in `./assets/mainnet`?

### Files
-  HOLY
![HOLY](https://user-images.githubusercontent.com/11538800/123524260-58b59d80-d6c9-11eb-8fd4-e1de4f5441ab.png)

- SECO
![SECO](https://user-images.githubusercontent.com/11538800/123524261-58b59d80-d6c9-11eb-9e6d-f3239a760c63.png)

**Comment by MyanmarKibbutz** [comment]
Hi I am also looking for instructions on how to add a logo in /assets/mainnet
![logo](https://user-images.githubusercontent.com/88385687/128275104-a752870b-7195-4f37-adb1-7b52206347d5.png)
![NMS3232](https://user-images.githubusercontent.com/88385687/128275248-0aac3352-1bff-413c-887c-5f65722563e2.png)

**Comment by highacrypto** [comment]
![salvador](https://user-images.githubusercontent.com/88494986/128363659-6ebf1423-ab95-4f03-9b9c-4dd94a24100e.jpg)

**Comment by alanihsek** [comment]
Same for Legion Token http://www.legiontoken.net
Already minted on MintLab and still awaiting updates.
![LGN Token](https://user-images.githubusercontent.com/68668980/133846896-66c4c7f8-0ebc-49ab-b8dd-865418e6c73d.png)

**Comment by olivbau** [comment]
PR created #1098
