### ISSUE TITLE
unable to automerge: unknown field "serumV3Usdc"

### ISSUE THREAD

**Issue by nozdormu46** [solana-labs/token-list#4690]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Tried to add serumV3Usdc to an existing coin, and got this error during automerge:
`failed to normalize: failed to parse JSON: json: unknown field "serumV3Usdc"`

```
      "decimals": 9,
      "logoURI": "https://boryoku-dragonz-public.s3.us-east-2.amazonaws.com/BokuBrew.png",
      "extensions": {
        "serumV3Usdc": "Dvm8jjdAy8uyXn9WXjS2p1mcPeFTuYS6yW2eUL9SJE8p",
        "twitter": "https://twitter.com/BoryokuDragonz",
        "website": "https://boryokudragonz.io"
      }
```
file diff:
https://github.com/solana-labs/token-list/pull/4634/files

automerge error:
https://github.com/solana-labs/token-list/pull/4634/checks?check_run_id=4252836760

I am probably missing something obvious :(

**Comment by leoluk** [comment]
> I am probably missing something obvious :(

Yep, the automerger doesn't accept updates - that's why it didn't automerge.
