### ISSUE TITLE
please approave  #4651 PR manually

### ISSUE THREAD

**Issue by weed4man** [solana-labs/token-list#4700]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by weed4man** [comment]
The error is as per below

error validating schema: chainId: conflicting values 103 and 0

**Comment by leoluk** [comment]
The problem is likely this extra diff at the end:

<img width="307" alt="image" src="https://user-images.githubusercontent.com/859697/142653974-6aed91b2-9a15-472b-946e-3886ba4ef05a.png">
