### ISSUE TITLE
Not eligible for automerge. failed to normalize: failed to parse JSON: json: unknown field "coingeckoId"

### ISSUE THREAD

**Issue by ChihuahuaSol** [solana-labs/token-list#4930]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Hi just want to do a pull request in https://github.com/solana-labs/token-list/pull/4928 but I see automerge-error
Not eligible for automerge (click details for more information)
failed to normalize: failed to parse JSON: json: unknown field "coingeckoId"
Could someone fix this problem please?

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by lmvdz** [comment]
Apparently we're not allowed to add non existing fields to already existing entries :/

**Comment by leoluk** [comment]
Correct, needs manual review

**Comment by tampham47** [comment]
> Correct, needs manual review

I suggest adding a new rules:
- The owner of the block/token is able to add new fields into their block without manual reviews. That would speed up the process a lot I think

**Comment by leoluk** [comment]
> The owner of the block/token is able to add new fields into their block without manual reviews. That would speed up the process a lot I think

Yup, that's the plan - unfortunately, not straight-forward to implement.
