### ISSUE TITLE
solfina list instead of normal list 

### ISSUE THREAD

**Issue by MapMetrics** [solana-labs/token-list#5001]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ x] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
My SPL token with logo is uploaded to GitHub  with the token program but for some reason,the explorer goes to solfinaprotocol list instead of the regular list and doesnt show the logo, also not in the wallet.

![image](https://user-images.githubusercontent.com/92952377/142780719-9ae9f4d7-ceb1-45f4-8ba4-f5a384ac4e1c.png)

**Comment by keone** [comment]
looks like it was a copy paste error
fixed in https://github.com/solana-labs/token-list/pull/6096
