### ISSUE TITLE
New automerge doesn't allow same name in different chains (devnet vs mainnet) 

### ISSUE THREAD

**Issue by javmeister** [solana-labs/token-list#5013]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Token List Automerger / New automerge  doesn't allow duplicate name across chainIds while several tokens are already merged with both the same Symbol and Name in different chains.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Adding a second PR to create a new entry of an existing Token merged to the mainnet chain (101) fails with a `duplicate token: token name XYZ is already used`. ie [https://github.com/solana-labs/token-list/pull/5009/checks?check_run_id=4281436913](https://github.com/solana-labs/token-list/pull/5009/checks?check_run_id=4281436913)

Example of an existing token: `Aiko` shares both name and symbol in the mainnet and devnet chains:
https://github.com/solana-labs/token-list/blob/f049bd9b819aad31da2c07aafdfbe9fe190b62ea/src/tokens/solana.tokenlist.json#L2136
https://github.com/solana-labs/token-list/blob/f049bd9b819aad31da2c07aafdfbe9fe190b62ea/src/tokens/solana.tokenlist.json#L2157

We'd like to avoid having to add a `-TEST` to the devnet name+symbol.

**Comment by leoluk** [comment]
You're right, this is a bug - should be fixed!

**Comment by javmeister** [comment]
@leoluk  Thanks!!
