### ISSUE TITLE
Automerge rejects logo & meta data changes.

### ISSUE THREAD

**Issue by keisukew53** [solana-labs/token-list#5096]
- **I'm submitting a ...**
  [x] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Automerge rejects logo & meta data changes - I needed to update the logo and twitter link for KSAMO - KING SMAO.
However automerge doesn't even allow file changes.
Could you please review and approve my PR - https://github.com/solana-labs/token-list/pull/5249?
Thank you!

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
author was committer of https://github.com/solana-labs/token-list/commit/0186d0a9681a7a38718e188cc676d6dbab3408ac

**Comment by keone** [comment]
merged
