### ISSUE TITLE
Modification to logo for Seeded Network [PR manual merge]

### ISSUE THREAD

**Issue by 0xAzureDev** [solana-labs/token-list#5306]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
We want to modify our logo from an SVG to a PNG and it needs to be manually merged. 

Our PR is #5304 

Thank you @leoluk :)

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
Proof of ownership: Added Seeded Network #4986

**Comment by leoluk** [comment]
Modify the existing entry instead of adding a new one

**Comment by 0xAzureDev** [comment]
> Modify the existing entry instead of adding a new one

The merger bot automatically closes the PR

**Comment by leoluk** [comment]
It doesn't, it just adds a "failed" label

**Comment by 0xAzureDev** [comment]
> It doesn't, it just adds a "failed" label
> 
> (perhaps the old bot did? idk, the new one doesn't!)

I think there's confusion, the PR I sent as proof ( #4986) succeeded and added our token (with the new bot). The new PR is for modifying the token from SVG to PNG -> #5304

**Comment by leoluk** [comment]
Yeah, modify the existing entry instead of adding a new one

**Comment by 0xAzureDev** [comment]
![image](https://user-images.githubusercontent.com/86131084/143311941-1e4644e3-eb21-43de-9189-3511df8be4b7.png)

The previous PR for the initial addition of our token, from the attached screenshot, I cannot modify the existing entry because it's closed.

The new PR is  for modifying it which needs to be manually merged

**Comment by leoluk** [comment]
You need to modify the existing entry in the token list rather than adding a new one

**Comment by 0xAzureDev** [comment]
> You need to modify the existing entry in the token list rather than adding a new one

Do you mean the link for the logo rather than the PNG file?

**Comment by 0xAzureDev** [comment]
Modified the PR: #5391 

Sorry for the confusion hahaha @leoluk

**Comment by 0xAzureDev** [comment]
bump @leoluk
