### ISSUE TITLE
Need to merge open PR with small update (adds twitter)

### ISSUE THREAD

**Issue by javmeister** [solana-labs/token-list#5342]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Need to merge an open failed PR that adds our twitter account: #5151 
New automerge marked it as failed because the update "deletes" the existing line to add a comma at the end.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Original PR merging `SINGULARITY` token, for ownership: https://github.com/solana-labs/token-list/pull/4775

**Comment by leoluk** [comment]
> New automerge marked it as failed because the update "deletes" the existing line to add a comma at the end.

Even without the comma it would refuse since we can't check ownership automatically yet. Should be merged now!

**Comment by javmeister** [comment]
> Even without the comma it would refuse since we can't check ownership automatically yet. Should be merged now!

Interesting, then we will hold off on more updates until we can do a bulk one. Thanks for the quick turnaround @leoluk !
