### ISSUE TITLE
Need manual merge

### ISSUE THREAD

**Issue by SolPoodleInu** [solana-labs/token-list#5379]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
i got an error from automerger for my website was down, now it is working 

but everytime i tried to add a new pull i got an error as "duplicate token"
#5378 <-- this is my merge
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
this was added here: https://github.com/solana-labs/token-list/commit/4029109333c67e35b11a0e28e5637c795464da20
