### ISSUE TITLE
Update DAWG token coingeckoId

### ISSUE THREAD

**Issue by kishorerabha** [solana-labs/token-list#5400]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request

- **Please approve my PR to add the coingeckoId field https://github.com/solana-labs/token-list/pull/5396**

**Comment by keone** [comment]
the field is coingeckoId
please squash your commits

**Comment by kishorerabha** [comment]
coingeckoId thats what i typed. check again please

**Comment by keone** [comment]
weird, ok yeah thats a false alarm
merged
