### ISSUE TITLE
Update Jungle coingeckoId

### ISSUE THREAD

**Issue by monkeycow123** [solana-labs/token-list#5421]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- Need approval for my pull request to get coingeckoid field added. #5418

**Comment by keone** [comment]
author was committer of https://github.com/solana-labs/token-list/commit/f02b75e6af415b72aa8c790633526bcacb40a97b
merged
