### ISSUE TITLE
Update $THANKS Token

### ISSUE THREAD

**Issue by quinqu** [solana-labs/token-list#5422]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I need a manual merge for https://github.com/solana-labs/token-list/pull/5419. All the checks have passed, so it seems good to go. Thanks!

**Comment by quinqu** [comment]
Auto merge check did not pass now.

**Comment by keone** [comment]
Committer was author of https://github.com/solana-labs/token-list/commit/00bc9ca13b13ba8f16d6171b702b78b5dde3f2be, merging
