### ISSUE TITLE
automerge not merging when I change the logo

### ISSUE THREAD

**Issue by fogsy** [solana-labs/token-list#5426]
[x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project
@leoluk 
I am trying to get this logo update to go through its saying:
Not eligible for automerge (click details for more information)
found removed line: - "logoURI": "https://pbs.twimg.com/profile_images/1260288995323502598/9aAFR0pr_400x400.jpg",

- **Summary**
here is the commit
https://github.com/solana-labs/token-list/pull/5411/commits/0202d7fda527097973536e33540d16adbd059146

Not eligible for automerge (click details for more information)
its saying I removed the logo the logo was swapped and I added one to the repo since using hard coded links doesnt work on some wallets

**Comment by fogsy** [comment]
Not eligible for automerge (click details for more information)
its saying I removed the logo the logo was swapped and I added one to the repo since using hard coded links doesnt work on some wallets

**Comment by fogsy** [comment]
anything on this guys ? its really annoying when you get a message saying logo removed and well it was not removed it was replaced I tried 25 times now to update a logo we might re-consider and move back to ERC-20 at this rate we ll never get this thing out please help

**Comment by keone** [comment]
Sorry for your trouble, please link a PR!

**Comment by narana2** [comment]
I'm having the same issue. Is there a fix?

**Comment by keone** [comment]
i believe the PR was https://github.com/solana-labs/token-list/pull/5033
bad PR that deleted another token in the process. closed
