### ISSUE TITLE
failed automerge with coingeckoId

### ISSUE THREAD

**Issue by meany** [solana-labs/token-list#5445]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
See https://github.com/solana-labs/token-list/pull/5440

**Comment by hfcoin** [comment]
Same here, failed add coingeckoId and serumV3usdc

**Comment by keone** [comment]
merged
@hfcoin pls open an issue for yours
