### ISSUE TITLE
Request to update logo and add twitter

### ISSUE THREAD

**Issue by mpretti** [solana-labs/token-list#5484]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [X] question about how to use this project

- **Summary**
- #5472 was marked failed because it was changing an existing logo instead of creating a new one. A previous PR (#1416) failed because it tried to delete the original and add a new logo file (SVG).

- What is the process to update a logo of an existing token ?

- Original PR that created the PERK token entry and original image: 
- #5 
@watdev2018 (original creator of PERK token) can confirm that updating logo is approved and desired.

**Comment by watdev2018** [comment]
Thanks @mpretti yes my intention is to merge #5472 since the other PR #1416 is stalled

**Comment by keone** [comment]
thanks for the clear affirmation @watdev2018 
merged
