### ISSUE TITLE
Request to update CRYY to CRYY/USDC (#5489)

### ISSUE THREAD

**Issue by nomadicmonad** [solana-labs/token-list#5492]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ x] question about how to use this project

- **Summary**

The PR text mentions that we should ask for manual merges for updates -- I hope we found the correct place.

Would it be possible to merge #5489 manually? Our team didn't understand that the ticker should have the /USDC suffix. Thank you!

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
I don't think this is right, it shouldn't have /USDC here.  Closing
