### ISSUE TITLE
Request to merge PR #5543 - Change decimals and new address

### ISSUE THREAD

**Issue by Pubbus** [solana-labs/token-list#5545]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [x] question about the decisions made in the repository
  [x] question about how to use this project

- **Summary**
The PR text mentions that we should ask for manual merges for updates -- I hope we found the correct place.

Would it be possible to merge #5543 manually? We can't mint more token with current decimals (9).

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
there doesnt seem to be a token here: https://solscan.io/account/6HusCnR1e3RKiLuzMCUzBZkaUTvjGYvT6EisRXGWPa5n

**Comment by Pubbus** [comment]
Hi @keone, thanks for your help, because it is on 103 (devnet)
https://explorer.solana.com/address/6HusCnR1e3RKiLuzMCUzBZkaUTvjGYvT6EisRXGWPa5n?cluster=devnet

**Comment by keone** [comment]
I see, thanks
