### ISSUE TITLE
Reqeust to Add coingecko and coinmarketcap to an existing token

### ISSUE THREAD

**Issue by nozdormu46** [solana-labs/token-list#5562]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Can you please merge this request? 
https://github.com/solana-labs/token-list/pull/5291

Thanks

**Comment by keone** [comment]
looks good, merged
