### ISSUE TITLE
Can't modify BOFB Logo

### ISSUE THREAD

**Issue by fabianhortiguela** [solana-labs/token-list#5585]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Hi, I tried to modify bofb’s logo in every possible manner but was not successful. Can someone please help me? doing a pull request manually or how should I do this modification? Because I can’t change the same file because it only allows to add files but not modify them.
**[PR #5579](https://github.com/solana-labs/token-list/pull/5579/commits/25b191b59a8dc861738968db0db1ed061d365ef9)** 

Thanks

**Comment by keone** [comment]
3 files added: https://github.com/solana-labs/token-list/pull/5579/files
please only add 1
also please squash into a single commit
