### ISSUE TITLE
Want to change wrong address of my LP token, manual review and merge required

### ISSUE THREAD

**Issue by tolui** [solana-labs/token-list#5598]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [x] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I added my LP token recently but unfortunately I found that I added my LP token with wrong address, now I want to change it to correct one but automerge declined my PR. Can you review and merge it manually. please 
PR: https://github.com/solana-labs/token-list/pull/5563
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
you should probably update or remove the website in the extensions block
