### ISSUE TITLE
Upload Boo logo

### ISSUE THREAD

**Issue by nchaccal** [solana-labs/token-list#5685]
- **I'm submitting a ...**
  [] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- I need to upload the logo of my token. It's doesn't have any, but when try to automerge, it's always fail. I already made the PR. Can you please upload manually please.
 
[Pull Request #4529](https://github.com/solana-labs/token-list/pull/4529) 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
user was the commiter of https://github.com/solana-labs/token-list/commit/fa67eb343bb39c03ab2e73b7b8b174f218949849
merged
