### ISSUE TITLE
Want to change wrong address of my LP token, manual review and merge required

### ISSUE THREAD

**Issue by Acidastro** [solana-labs/token-list#5722]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [x] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- I want to correct my mistake. Wrong address
- Can you review and merge it manually. please
PR: https://github.com/solana-labs/token-list/pull/4600
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
user was committer of 7824e9e, merged
