### ISSUE TITLE
Update TTT logo. Please review

### ISSUE THREAD

**Issue by ymdrkh** [solana-labs/token-list#5741]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I updated the logo with correct paddings. Here is my pull request:
https://github.com/solana-labs/token-list/pull/5727

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
user was the committer of https://github.com/solana-labs/token-list/commit/e75b58ef8d8bd31a759f0ad085ef1e44f7a8a8ae

merged
