### ISSUE TITLE
Please merge https://github.com/solana-labs/token-list/pull/5554

### ISSUE THREAD

**Issue by ArjLab** [solana-labs/token-list#5751]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

-  https://github.com/solana-labs/token-list/pull/5554

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
can confirm https://twitter.com/_Naxar points to naxar.net now, merged

**Comment by ArjLab** [comment]
@keone Thank you man
