### ISSUE TITLE
automerger fails with "error validating schema: chainId: conflicting values 103 and 0"

### ISSUE THREAD

**Issue by GrgrLmml** [solana-labs/token-list#5799]
- **I'm submitting a ...**
  [ x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
My PR #5709 always fails automerge with "error validating schema: chainId: conflicting values 103 and 0" . I neither refer to chainId 103 nor chainId 0. There are reports from other user facing the same problem. 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by g-flex** [comment]
Same here.
Figured something?

Cheers

**Comment by GrgrLmml** [comment]
No, the entire token list PR process seems broken. It's a bit frustrating that even in the web3 world, we still depend on a central authority.

**Comment by g-flex** [comment]
Ok dude I figured it out, check [this comment](https://github.com/solana-labs/token-list/issues/4700#issuecomment-974201031): if you are having that last line change too, that's braking the PR.
To solve, instead of `git add .` just go `git add -p .` and skip the change mentioned above.

This worked for me x
@GrgrLmml

**Comment by GrgrLmml** [comment]
@g-flex you saved my day. Now the error perfectly makes sense ... just the error message not so much

**Comment by jessekauppi** [comment]
I had the same issue, that fixed it thanks! Weird error message...
