### ISSUE TITLE
Manual Review Required for Token Update

### ISSUE THREAD

**Issue by kyobodrakes** [solana-labs/token-list#5826]
- **I'm submitting a ...**
  [ ] bug report
  [ x ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Requesting a manual review of this update: https://github.com/solana-labs/token-list/pull/5825
Original Pull Request: https://github.com/solana-labs/token-list/pull/5787

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by kyobodrakes** [comment]
@leoluk 

Thank you for reviewing the past manual requests. Hope you can do the same here, thank you!

**Comment by kyobodrakes** [comment]
@keone 

Any chance you can take a look at this?

**Comment by keone** [comment]
author was author of e015a1e
decimals is indeed 9 on https://solscan.io/token/BFJ6rAVroCPaYbvgcT11ku4NG4KbfX3gWDGrbEUJ7r34

merged

**Comment by kyobodrakes** [comment]
Hi @keone,

Sorry for the troubles but it seems I forgot to remove the "nft" tag and it's still introducing my token as a NFT instead on Phantom. I added a new PR.

https://github.com/solana-labs/token-list/pull/6277

Is it possible to get this open again?

**Comment by keone** [comment]
merged
