### ISSUE TITLE
Manual review request to add coingeckoID for Solabrador

### ISSUE THREAD

**Issue by RickardVMiun** [solana-labs/token-list#5839]
- **I'm submitting a manual review request**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- For some reason its not possible to add coingeckoID to your existing token, i can see the reason but it leaves me with little to no choice on what to do, i can't ping anyone in discord and i'm barely allowed to write about it, so i'll just post here instead.

- https://github.com/solana-labs/token-list/pull/5890
- The pull request above should work and it does not alter any other code, it simply adds my id which is the same id as my project name. I hope someone can add this manually, i'd appreciate it a lot.

**Comment by RickardVMiun** [comment]
@leoluk 

I see you've done this in the past, perhaps you could help us out aswell?
Any help would be **greatly** appreciated

**Comment by keone** [comment]
confirmed coingeckoid
confirmed serum address
confirmed decimals=9 on https://solscan.io/token/GLmaRDRmYd4u3YLfnj9eq1mrwxa1YfSweZYYZXZLTRdK

merged.
side note, as a matter of hygiene it'd be better to squash your commits before requesting this
