### ISSUE TITLE
Manual review request to add coingeckoID for WAGMI

### ISSUE THREAD

**Issue by neutralskew** [solana-labs/token-list#5853]
- **I'm submitting a manual review request**
  [ ] bug report
  [x ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

For some reason, it's not possible to add coingeckoID to your existing token.

#5846 

The pull request above should work and it does not alter any other code, it simply adds my id which is the same id as my project 
name. Hope to hear from you guys soon!

@leoluk
I believe you helped us before. Hopefully you have time to help us again.

Regards,
neutralskew

**Comment by keone** [comment]
seems reasonable, not sure why that check failed. merged
