### ISSUE TITLE
How to change logo? 

### ISSUE THREAD

**Issue by bbcolts94** [solana-labs/token-list#5954]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
We are looking to change our logo, due to the lack of knowledge at the time we did not use the best method. 
What is the best way to do this, as we cannot change it. 
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
Please link a PR

**Comment by bbcolts94** [comment]
> Please link a PR

https://github.com/solana-labs/token-list/pull/6099 - Thank you!

**Comment by keone** [comment]
merged
