### ISSUE TITLE
Manual Review Required for Token Update

### ISSUE THREAD

**Issue by izayoido** [solana-labs/token-list#5963]
[- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ *] question about the decisions made in the repository
  [ *] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)]
- 
-  I am from the WOOF team and we would like to ask if you could change our logo to this updated, Solana colored one as we already changed it everywhere except onchain?
- (https://github.com/solana-labs/token-list/pull/5958)

**Comment by keone** [comment]
whoever originally committed woof should affirm that this is ok in this comment thread

**Comment by izayoido** [comment]
In the PR tree, the original committer has written.
Please check it
https://github.com/solana-labs/token-list/pull/5958

**Comment by keone** [comment]
merged

**Comment by 0xNyk** [comment]
Thank you guys - really appreciate!

Would there be an option to exclude the 1nc1nerator111111111111111 burn wallet off our Total Supply please?

Coingecko and Coinmarketcap cant show the correct Max Supply as they dont belive the wallet is real. 

Its 98% of our supply which is burned and is hurting our visibility on those platforms.


If not, do you know how other projects did it, when they used the 1nc1nerator wallet?


Thank you a lot and all the best!
