### ISSUE TITLE
Manual Review Required For GIGCO (GQO -> GIG)

### ISSUE THREAD

**Issue by frankdevryer** [solana-labs/token-list#5981]
- **I'm submitting a ...**
  [ ] bug report
  [*] feature request
  [*] question about the decisions made in the repository
  [*] question about how to use this project

- **Summary**
We changed our companies name together with our token name / ticker. We would like to update to the new info in the pull request.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
https://github.com/solana-labs/token-list/pull/5979

**Comment by keone** [comment]
can confirm gigqo.com redirects to gigco.com, merging
