### ISSUE TITLE
Manual review request update twitter and website url

### ISSUE THREAD

**Issue by shibainusolana** [solana-labs/token-list#5983]
- **I'm submitting a ...**
  [+] feature request

- **Summary**
Hello, please help us to add twitter link and change website url address. Thanks

https://github.com/solana-labs/token-list/pull/5950

**Comment by keone** [comment]
Please have the original committer @GemsGame affirm this is ok
https://github.com/solana-labs/token-list/commit/2c6d0c24

**Comment by GemsGame** [comment]
> Please have the original committer @GemsGame affirm this is ok [2c6d0c2](https://github.com/solana-labs/token-list/commit/2c6d0c24)

@keone  yep, i'm approve this actions.

**Comment by keone** [comment]
merged
