### ISSUE TITLE
Regarding Update Solana Token list

### ISSUE THREAD

**Issue by bitadx** [solana-labs/token-list#5986]
I am trying to pull request for update our token name on list which is #3451 from last 24 days but still not working. Kindly look in to the matter and please resolve this issue. thanks

**Comment by keone** [comment]
Please rebase your branch onto main, it's very out of date

**Comment by bitadx** [comment]
ok i just did it again with new PR. #6079

**Comment by bitadx** [comment]
Now i am having an issue regarding Automerge and it says invalid LogoURl error. What does it mean?

**Comment by keone** [comment]
logoURI needs to be a full url, in this case it should be `https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/yWrsPP55pxTXWBnuReEd7B1gTFqLsfbhP3ZvnGCdrE4/Logo.png` (it would be nice if you lowercased Logo as well)

**Comment by bitadx** [comment]
I did it this time again, now the error is unsupported file modified: solana.tokenlist.json

**Comment by keone** [comment]
Please link a PR

**Comment by bitadx** [comment]
https://github.com/solana-labs/token-list/pull/6116

**Comment by keone** [comment]
you uploaded a second copy of the tokenlist in that PR, don't do that!

**Comment by bitadx** [comment]
Ok you closed that one right. So what should i do now?

**Comment by keone** [comment]
reopen it and push a correct commit to that branch
or file a new PR and link it here.
I'm sorry but no one can help you with how to use git or github, there are too many people trying to push new tokens

**Comment by bitadx** [comment]
Do you have any examples so i can see how to do it correct way? First i need to download that solana json file right and then in the end i need to add my token information without comma at the end. And then upload it from my repository right? Correct. What about logo link. How to add that link of logo.
