### ISSUE TITLE
Remove tags $TURNT

### ISSUE THREAD

**Issue by SavoTiki** [solana-labs/token-list#5988]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Hello, i need a manual merge for this pull request #5987 to remove tags
Thanks

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
User was committer of same token https://github.com/solana-labs/token-list/commits?author=SavoTiki&since=2021-11-01&until=2021-12-01
merged
