### ISSUE TITLE
Manual review requested for Quest token and Quest-USDT lp token

### ISSUE THREAD

**Issue by tolui** [solana-labs/token-list#6077]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
1. Description and tags added for Quest token
2. Token address change (it created first with wrong address) for QUEST-USDT LP token
Please approve following PR https://github.com/solana-labs/token-list/pull/6076
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
