### ISSUE TITLE
Manual review requested for TRTLS

### ISSUE THREAD

**Issue by nochsol** [solana-labs/token-list#6086]
- **I'm submitting a ...**
  [ ] bug report
  [ x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
CoingeckoId extension added for Turtles Token (TRTLS)
Please approve following PR #6085 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
The PR is not allowing merge right now due to conflicts, can you please squash it into a single commit? I think then it should work

**Comment by nochsol** [comment]
I tried but I got error on automerge: `failed to normalize: failed to parse JSON: json: unknown field "coingeckoId"`
#6113 can you check this pr?
@keone

**Comment by keone** [comment]
merged
