### ISSUE TITLE
Manual review for DRINK extension update

### ISSUE THREAD

**Issue by solanadrink** [solana-labs/token-list#6091]
Update our extension on tokens-list.json

**Comment by solanadrink** [comment]
pr #6065

**Comment by keone** [comment]
can you pls fix the formatting (number of spaces)?

**Comment by solanadrink** [comment]
done

**Comment by solanadrink** [comment]
done man

Pada tanggal Jum, 3 Des 2021 pukul 22.04 keone ***@***.***>
menulis:

**Comment by keone** [comment]
merged
