### ISSUE TITLE
Manual Review Required for Token Update

### ISSUE THREAD

**Issue by MeowCoinSolana** [solana-labs/token-list#6118]
- **I'm submitting a ...**
  [ X] feature request

- **Summary**

Hi.
I submitted this PR 16 days ago but haven't receive any updates since => https://github.com/solana-labs/token-list/pull/4487

Can I have any help ?
Thanks for your actions.

**Comment by MeowCoinSolana** [comment]
Can you help me on this ? @keone  Thanks

**Comment by keone** [comment]
Sorry for the delay. Can you please delete the original `logo.png` and submit a smaller logo (our limit is 200 kb, but as small as possible) and then tag me and I'll review.

**Comment by keone** [comment]
Also, it would be nice if you fixed the spacing, see https://github.com/solana-labs/token-list/pull/4487/files

**Comment by MeowCoinSolana** [comment]
Hi @keone 
Thanks for your review.
So instead, I replaced the logo.png with the new logo, and reduced the size to 90 kb. I deleted the logo2.png
Also, I fixed the spacing on the tokenlist.json.

Thanks,

**Comment by keone** [comment]
awesome! all checks now pass; it will automerge in the next hour

**Comment by MeowCoinSolana** [comment]
Unfortunately, the automerge failed @keone

**Comment by keone** [comment]
Oh right you updated the logo.  Manually merged
