### ISSUE TITLE
Duplicated Address on list Frog8vt6gmuuUuuerd7ispP6yavssBUtMpEP5DCEuUgD - $FROG Token

### ISSUE THREAD

**Issue by aosagula** [solana-labs/token-list#6140]
- **I'm submitting a ...**
  [X ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
thanks
https://github.com/solana-labs/token-list/pull/6141

**Comment by Fiverr-Coin-Hunter** [comment]
Thank You
