### ISSUE TITLE
Manual Review Required - Removal of 'NFT' tag.

### ISSUE THREAD

**Issue by kyobodrakes** [solana-labs/token-list#6278]
- **I'm submitting a ...**
  [ ] bug report
  [ x ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Requesting the removal of the "NFT" tag as well.

New PR: https://github.com/solana-labs/token-list/pull/6277
Old Commits: 

https://github.com/solana-labs/token-list/commit/e015a1e9fd3590ac4cfe813fe2b5b38498d460f3
https://github.com/solana-labs/token-list/commit/5783e92fc815eee1008a8b34c0b6140ac81d30fd

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by kyobodrakes** [comment]
@keone @leoluk 

Please review, thank you! I appreciate all of your hardwork.

**Comment by keone** [comment]
merged
