### ISSUE TITLE
Edit of old token account address

### ISSUE THREAD

**Issue by AbdallaMalik** [solana-labs/token-list#6288]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [x ] question about the decisions made in the repository
  [ ] question about how to use this project

- **please approve the PR to remove the old address of GUMA token as we had to separate the token account from other projects token accounts  so created a new token **

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
please link the PR

**Comment by AbdallaMalik** [comment]
#6286
