### ISSUE TITLE
token already listed but url link not updating

### ISSUE THREAD

**Issue by kodingx** [solana-labs/token-list#6300]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
please link the PR

**Comment by kodingx** [comment]
https://github.com/solana-labs/token-list/pull/6299 
I just want proper logo to display.
Thanks
