### ISSUE TITLE
Removing Token Metadata

### ISSUE THREAD

**Issue by HFaour** [solana-labs/token-list#6308]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x] question about how to use this project

- **Summary**
I've successfully merged information about a token I've created. Looking to remove it due to error in number of tokens minted.

- **Other information** 
You guys are amazing, thank you for building something awesome =)

Hi team! I'm looking to remove a token's metadata please. I'd like to know if this is possible. I've linked the PR below. Thanks!

https://github.com/solana-labs/token-list/pull/6248

**Comment by keone** [comment]
this PR doesnt seem to do anything (0 files changed in https://github.com/solana-labs/token-list/pull/6248/files)

**Comment by HFaour** [comment]
Hi @keone sorry! Can you please have another look https://github.com/solana-labs/token-list/pull/6421.

Much appreciated <3

**Comment by keone** [comment]
merged https://github.com/solana-labs/token-list/pull/6421
note that this deleted that token
and then added another

**Comment by HFaour** [comment]
Thank you!!, you beautiful creature <3
