### ISSUE TITLE
Exclude 1nc1nerator address off max supply for WOOF

### ISSUE THREAD

**Issue by 0xNyk** [solana-labs/token-list#6337]
Thank you guys - really appreciate the last change!

Would there be an option to exclude the 1nc1nerator111111111111111 burn wallet off our Total Supply please?

Coingecko and Coinmarketcap cant show the correct Max Supply as they dont belive the wallet is real.

Its 98% of our supply which is burned and is hurting our visibility on those platforms.

If not, do you know how other projects did it, when they used the 1nc1nerator wallet?

Thank you a lot and all the best!

**Comment by wisnurizkiade** [comment]
sorry if I am wrong,
maybe you can use spl-token burn to make your suppy correct

**Comment by keone** [comment]
token-list doesn't control this
