### ISSUE TITLE
failed to normalize JSON: hujson: line 2, column 1: invalid character 'ï' at start of value

### ISSUE THREAD

**Issue by j-d-sanchez** [solana-labs/token-list#6430]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
Hello, 
My automerger failed due to an "invalid character "i" at start of value" in a certain column and row. 
How can we fix this?

**Comment by j-d-sanchez** [comment]
BTW I am new here, thank you sooo much in advance.

**Comment by j-d-sanchez** [comment]
this is the exact issue:

failed to normalize: failed to normalize JSON: hujson: line 2, column 1: invalid character 'ï' at start of value

**Comment by j-d-sanchez** [comment]
Hi @keone Could you please help me?
the pull request is 6525 and it is the fourth time I try merging and it is constantly failing due to the same error.
Thank you so much in advance

**Comment by keone** [comment]
i think there is a bad character on line 2 (the `{`)

**Comment by j-d-sanchez** [comment]
Thanks Keone! I appreciate your reply 😊
I was able to create another pull request and merge it 👍🏼
