### ISSUE TITLE
RWC Token Updating PNG LOGO and logoURI

### ISSUE THREAD

**Issue by AbdallaMalik** [solana-labs/token-list#6507]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [x ] question about the decisions made in the repository
  [ ] question about how to use this project

- **
updating the Current Token Logo from JPG to PNG and the Token logo link as well 
**
PR 
#6506

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
we autoreject large files, please size down below 200kb
