### ISSUE TITLE
PR Update Twitter account #6363

### ISSUE THREAD

**Issue by aosagula** [solana-labs/token-list#6548]
- **I'm submitting a ...**
  [ x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
Please consider force the merge, I need to change the twitter account. Buy the auto-merge not allow me, this kind of update.
Could you force?

Thanks in advance

**Comment by keone** [comment]
merged
