### ISSUE TITLE
error validating schema: chainId: conflicting values 103 and 0

### ISSUE THREAD

**Issue by Icus101** [solana-labs/token-list#6552]
pls i keep getting an automerge error while trying to use the token-list repo,any help on how i can fix this pls

**Comment by ceribbo** [comment]
Same problem here

**Comment by keone** [comment]
i have seen various submissions erroring like that; that generally means you put the new json block in the wrong place, like one level too deep (inside another coin's block).  link a PR and someone can verify that that's the issue (but please try to take this advice and resubmit)

**Comment by keone** [comment]
https://github.com/solana-labs/token-list/pull/6637 is an example of the problem i mentioned

**Comment by avalanx** [comment]
Hi keone. I have the same issue. this is my PW: https://github.com/solana-labs/token-list/pull/6637. I have added my code at the last position. So I had to add a comma to the previous coins block. Can that cause the error? I left everything else untouched. The level should be ok, its not in another coins block. Would be great if you could check. Here you can see my code: https://github.com/solana-labs/token-list/pull/6637/commits/f56e4051c94066b8d4bc6a951dce3100c6091f76

**Comment by keone** [comment]
actually nvm, i agree that it seems like a red herring or an unrelated error. will look into it

**Comment by thomasflx** [comment]
I had the same problem. The issue was vccode adding a newline at the end of the tokenlist file.
Disabling the editorconfig extension allowed me to remove the line and submit it properly.

**Comment by j-d-sanchez** [comment]
I used TextEdit in Mac and had the same "error validating schema: chainId: conflicting values 103 and 0" 
I was adding extensions to a token.

**Comment by j-d-sanchez** [comment]
error persists error validating schema: chainId: conflicting values 103 and 0

**Comment by j-d-sanchez** [comment]
PR# 10956

**Comment by hugoProActive** [comment]
Hi,
I have the same with PR #11568. 
Did you find a solution ?
Thanks

**Comment by ssi91** [comment]
> Hi, I have the same with PR #11568. Did you find a solution ? Thanks

https://github.com/solana-labs/token-list/issues/6552#issuecomment-991998267

**Comment by robtg4** [comment]
Same issue with PR #11613

**Comment by beeman** [comment]
Same with PR #11689

**Comment by VortexHowl** [comment]
has there been an update? I'm getting this same issue with PR #11644

**Comment by beeman** [comment]
> has there been an update? I'm getting this same issue with PR #11644

Try getting rid of the last line here. That's what made it work for me.

![629F938F-1246-41E5-855B-27057349768E](https://user-images.githubusercontent.com/36491/148477805-3aa0263f-52ba-471e-a04f-2b591b64e5ee.jpeg)

**Comment by Aqualibre** [comment]
Hi guys. is anyone using Visual Studio (pressing "period" button)  to activate the console in Github (or did use it) to edit fork before committing it their own repository? 
I have exact same error. Looks like Visual Studio might be causing errors? Im not sure? 
I have "No newline error" the red circle - stating a line was deleted
Cant automerge as conflicting values 103 and 

Beeman above says he solved it - but I cant tell what he did? 
I assume he deleted line 66691 ?? anyway I've tried a series of different line deletions - nothing has worked so far
I can see its missing at 66678 above _ I have same type of issue. I have tried to use little red arrow to re-add line 
but that's not worked??

Be great to know if someone has worked it out...
Thanks

**Comment by VortexHowl** [comment]
I eventually just used Notepad to edit the json file. My editor, Atom, kept
auto formatting and deleting then adding that line

**Comment by solpomdeveloper** [comment]
I have the same issue on doughdao add #17029 could you help me?

**Comment by beeman** [comment]
> I have the same issue on doughdao add #17029 could you help me?

Remove your trailing slash

**Comment by keone** [comment]
see explanation here: https://github.com/solana-labs/token-list#error-validating-schema-chainid-conflicting-values-103-and-0
