### ISSUE TITLE
Issue with logo Url pull request not merging #6399

### ISSUE THREAD

**Issue by kodingx** [solana-labs/token-list#6610]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
https://github.com/solana-labs/token-list/pull/6399 is invalid json.  you added your block onto the very end of the file instead of putting it into the big list

**Comment by keone** [comment]
please fix and re-push, then it should automerge
