### ISSUE TITLE
Manual Review Required - Add CoinGecko ID

### ISSUE THREAD

**Issue by MeowCoinSolana** [solana-labs/token-list#6611]
- **I'm submitting a ...**
  [ ] bug report
  [X] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Automerge failed when adding the coin gecko ID to Kitty Coin.
Can anyone kindly merge this PR ? https://github.com/solana-labs/token-list/pull/6605

Thank you

**Comment by keone** [comment]
merged; check out rebasing to squash your commits next time

**Comment by dzmitry-lahoda** [comment]
i have similar. will rebase and squash. so error is hard to undrestand.
