### ISSUE TITLE
Logo update

### ISSUE THREAD

**Issue by rendo-sol** [solana-labs/token-list#6653]
- **I'm submitting a ...**
  [ x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

I would like to update my token logo with the following;

PR #6652

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
