### ISSUE TITLE
change Token Tags

### ISSUE THREAD

**Issue by AbdallaMalik** [solana-labs/token-list#6661]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ x] question about the decisions made in the repository
  [ ] question about how to use this project

- ** to edit token tags from NFT to utility since inside phantom wallet it got treated as NFT , and we could only send singles , and the token is not an NFT  plz do merge to fix the token  **

PR #6660 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
