### ISSUE TITLE
Under Review

### ISSUE THREAD

**Issue by systemtechs** [solana-labs/token-list#6696]
- I'm submitting a [x] question about how to use this project

- PR states "This workflow is awaiting approval from a maintainer"

- Can you advise on how to speed up the approval or how to contact the Maintainer, or is it just a process of waiting?
  
Many Thanks 
Systemtechs

**Comment by keone** [comment]
please link a PR
is it https://github.com/solana-labs/token-list/pull/6558 ?

**Comment by systemtechs** [comment]
Hi Keone, yes it is #6558.

Many thanks

**Comment by keone** [comment]
this PR adds a submodule called `token-list`, bad

see https://github.com/solana-labs/token-list/pull/6558/files#diff-b1631d0e3d52286eda5c37dbb1412922b2b1104891e91a095759c188a95ca8f6

**Comment by systemtechs** [comment]
How do I correct this. Delete and readd or is there something that you can do?

**Comment by keone** [comment]
delete the submodule in a new commit and push to your branch

**Comment by systemtechs** [comment]
I cannot seem to do this. Is there any way to remove all the commits and submodule adds so I can start the process again cleanly?

**Comment by systemtechs** [comment]
You can close this now. I have removed all requests. Thanks for your help with this.
