### ISSUE TITLE
Need update BOT token info for upcomming IDO

### ISSUE THREAD

**Issue by kienstarbots** [solana-labs/token-list#6786]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [x] question about the decisions made in the repository
  [ ] question about how to use this project

My PR https://github.com/solana-labs/token-list/pull/6695
I need to update our token info - BOT token. The old address was wrong. We move to new address to correct our metadata. We can't create metadata because we set the mint authority to None before do that. Now I need to create other token for our project. Our old token just  created and doesn't have anyone own.
We are going to do our IDO so please review and approve PR.
Thanks!

**Comment by keone** [comment]
merged
