### ISSUE TITLE
Token info final update

### ISSUE THREAD

**Issue by HFaour** [solana-labs/token-list#6867]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x] question about how to use this project

- **Summary**
Hi Guys, looking for a final update to the token, can someone please see https://github.com/solana-labs/token-list/pull/6842 when they have a chance? <3

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
I really appreciate the support <3

**Comment by keone** [comment]
merged.
a comment: this repo is used by hundreds of projects, it's not designed for your test tokens
