### ISSUE TITLE
logo not displaying and I changed url #6399 

### ISSUE THREAD

**Issue by kodingx** [solana-labs/token-list#6923]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged.
please spend some time learning how to use git, it's not reasonable for us to merge a PR with 22 individual commits in it that look like complete trial and error
