### ISSUE TITLE
Updating RWC Token Logo 

### ISSUE THREAD

**Issue by AbdallaMalik** [solana-labs/token-list#6978]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ x] question about the decisions made in the repository
  [ ] question about how to use this project

- **Plz approve Updating of RWC Logo From JPG TO PNG 
Thanks in Advance**

PR 
#6976 6976

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
