### ISSUE TITLE
decimal update

### ISSUE THREAD

**Issue by jack21m** [solana-labs/token-list#6979]
- **I'm submitting a ...**
  [ x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Could you please merge the decimal update request ?  
https://github.com/solana-labs/token-list/pull/6959

 PR: update decimal #6959

**Comment by keone** [comment]
merged
