### ISSUE TITLE
Please help to approve the PR to updating LNFTxLIQ token details

### ISSUE THREAD

**Issue by hikaru-meta** [solana-labs/token-list#7157]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Please help to approve the PR to updating LNFTxLIQ token details. Thank you very much.
https://github.com/solana-labs/token-list/pull/7156

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
