### ISSUE TITLE
Need to change the token address on $FJB devnet address used instead of main net

### ISSUE THREAD

**Issue by Texaglo** [solana-labs/token-list#7178]
- **I'm submitting a ...**
  [x ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
need to adjust Token address the wrong one was used in the building process and we need to adjust the record
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

we just need to change the token from: 56pFm4cg2CkbxgQJjS5mPtUYZ3hbJseXuaafWfx7bhxq to 97ner9bBhnmbg1yZXMh85WNYsYSLTqUb4RvyMttD57fh as well as the folder in assets thats named 56pFm4cg2CkbxgQJjS5mPtUYZ3hbJseXuaafWfx7bhxq needs to be changed to  97ner9bBhnmbg1yZXMh85WNYsYSLTqUb4RvyMttD57fh everything else shoud stay the same the logo the logo url.. 

here is my pull request:

https://github.com/solana-labs/token-list/pull/7176
 
here is the original pull request:

https://github.com/solana-labs/token-list/pull/7139

**Comment by keone** [comment]
merged
