### ISSUE TITLE
Decimals incorrect on solscan

### ISSUE THREAD

**Issue by ps3460** [solana-labs/token-list#7221]
- **I'm submitting a ...**
  [ *] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
PR 7070
https://github.com/solana-labs/token-list/pull/7070/files
I'm struggling to get my PR to complete, but I've noticed my decimals are incorrect as well.
On Sol they say 9 but my code says 0
https://solscan.io/token/A2ALonhy5FnjbhwY9BgVsrLhEodTFd8jMfJ2V3nZDNpy

Thank you in advance for your help

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by ps3460** [comment]
Deleting code and retrying

**Comment by ps3460** [comment]
Tried to delete and readd, but auto-merge rules stopped that

{
      "chainId": 101,
      "address": "A2ALonhy5FnjbhwY9BgVsrLhEodTFd8jMfJ2V3nZDNpy",
      "symbol": "PSC",
      "name": "The PS Coin",
      "decimals": 0,
      "logoURI": "https://raw.githubusercontent.com/ps3460/crypto/main/logolg.png",
      "tags": [
        "social-token"
      ],
      "extensions": {
        "description": "The PS Coin"
      }
   },

**Comment by keone** [comment]
you need to modify the existing block for A2ALonhy5FnjbhwY9BgVsrLhEodTFd8jMfJ2V3nZDNpy; the PR you linked just adds another block

**Comment by ps3460** [comment]
https://github.com/solana-labs/token-list/pull/7558

Is that ok?

**Comment by keone** [comment]
merged that change.
note that you didn't update decimals in that change
