### ISSUE TITLE
I'm trying to change my logo, not sure what's going wrong. I keep getting an automerge-error.  Please help!

### ISSUE THREAD

**Issue by narana2** [solana-labs/token-list#7228]
I'm trying to change my logo, not sure what's going wrong. I keep getting an automerge-error.  Please help!

_Originally posted by @narana2 in https://github.com/solana-labs/token-list/pull/7213#pullrequestreview-829609052_

**Comment by qian262** [comment]
Try checking if you've uploaded your image to the correct location.

Do not upload to narana2/token-list* you need to upload to narana2/Crypto (or whatever name you created in your repository

**Comment by narana2** [comment]
The location is in the solana.tokenlist.json. 

The only thing I'm trying to change is is the link for logoURI and I'm getting this error:
found removed line: - "logoURI":"https://github.com/narana2/PITC/blob/main/PITC_logo.png",
please help I've tried to change it three times and keep getting this error.

**Comment by qian262** [comment]
try using this link format instead:
https://raw.githubusercontent.com/narana2/token-list/main/assets/mainnet/"place your token address here"/PITC_logo.png

**Comment by narana2** [comment]
That's what I'm trying to change it too but it won't let me merge it . I'm trying to change "logoURI":"https://github.com/narana2/PITC/blob/main/PITC_logo.png"
to
"logoURI":"https://raw.githubusercontent.com/narana2/PITC/main/PITC_logo.png"

I am still getting this error in the auto merge: 
"found removed line: - "logoURI":"https://github.com/narana2/PITC/blob/main/PITC_logo.png","

**Comment by keone** [comment]
merged
