### ISSUE TITLE
there is a duplicate token in the token-list causing everyone to error, address 97ner9bBhnmbg1yZXMh85WNYsYSLTqUb4RvyMttD57fh

### ISSUE THREAD

**Issue by c9obvi** [solana-labs/token-list#7426]
- **I'm submitting a ...**
  [ X ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
there is a duplicate token in the token list causing everyone and error address 97ner9bBhnmbg1yZXMh85WNYsYSLTqUb4RvyMttD57fh

This is causing duplication merge errors for anyone forking -- somehow that initial duplicate got through causing forks after to to not merge token-list.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by bentnoze** [comment]
+1

**Comment by c9obvi** [comment]
Looks like deleting the duplicate caused it to notice the chainID deleted, I copy pasted the main branch JSON in and added my token again -- I see the duplicate is still in there and I see the most recent tokens as new as ours already in and listed properly in explorers.

If this fails with a duplicate not sure what to do? Delete the entire duplicate entry except the key value pair of "chainId" : 101 ?

**Comment by keone** [comment]
thanks, fixed by #7499

**Comment by c9obvi** [comment]
@keone Thank you 🙏
