### ISSUE TITLE
please accept update changes to our token Phant

### ISSUE THREAD

**Issue by marlon80** [solana-labs/token-list#7598]
- **I'm submitting a ...**
  [ ] bug report
  [x ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

please accept changes to our token phant i made changes for update in twitter link and discord link thank you here is my pr: 
https://github.com/solana-labs/token-list/pull/4908

**Comment by keone** [comment]
squashed and merged
