### ISSUE TITLE
Update Existing Token

### ISSUE THREAD

**Issue by natefduncan** [solana-labs/token-list#7631]
- **I'm submitting a ...**
  [ ] bug report
  [ x ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Updated name, symbol, and tag data on the token - same address. Not sure if the new PR (#7630) will be auto-merged by the bot. 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
your PR re-adds 7uhJguD9nMQUE4Vka7EXqF2xeZbuQ5ehPt3cbTBomvXM; the commit needs to modify the existing entry
