### ISSUE TITLE
Update data on VortX Token

### ISSUE THREAD

**Issue by MilesBellum** [solana-labs/token-list#7647]
- **I'm submitting a ...**
  [ ] bug report
  [ X ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Update name, tag data, logo URI, and extensions like the website and twitter account. The PR is [#7722](https://github.com/solana-labs/token-list/pull/7722)

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
this token (with `5itxjY1UM58Z2y77rkW5cRZt6qx8WGAtg6Q36NszDaXa`) was already added; your PR would create a duplicate address, see https://github.com/solana-labs/token-list/pull/7722/checks?check_run_id=4513319448
