### ISSUE TITLE
Please update the VIBES token tags to replace "nft" with "game"

### ISSUE THREAD

**Issue by rangsikitpho** [solana-labs/token-list#7765]
Here is the pull request for the update: https://github.com/solana-labs/token-list/pull/2149

Thanks in advance!

**Comment by keone** [comment]
could you please rebase this to main? it's failing to manually merge

**Comment by rangsikitpho** [comment]
@keone rebased to main, let me know if you need anything else.

**Comment by keone** [comment]
thanks, merged
