### ISSUE TITLE
Update Token Symbol and Name

### ISSUE THREAD

**Issue by natefduncan** [solana-labs/token-list#7779]
- **I'm submitting a ...**
  [ ] bug report
  [ x ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Had incorrect commits yesterday (my apologies). Submitted a new PR (#7778) with just the changes to the file and nothing else. 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
