### ISSUE TITLE
Updating of SOLDEX Logo URL & Logo

### ISSUE THREAD

**Issue by vikas-speqto** [solana-labs/token-list#7868]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ x] question about the decisions made in the repository
  [ ] question about how to use this project

**- Plz approve Updating of SOLDEX Logo URL because old URL is wrong and update Soldex logo icon
Thanks in Advance**

PR
[6450](https://github.com/solana-labs/token-list/pull/6450)

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
