### ISSUE TITLE
Add ANGLE token: automerge failing

### ISSUE THREAD

**Issue by teddav** [solana-labs/token-list#7871]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I opened a PR to add a token: https://github.com/solana-labs/token-list/pull/7555
The automerge keeps failing because it cannot fetch the Coingecko URL. The Coingecko is right tough and loads well. I think it's an issue with the automerge workflow. I also checked directly with the Coingecko API and the ID is right: https://api.coingecko.com/api/v3/coins/ageur

I pushed a few different commits to test different setup, and even if I remove the "coingeckoId" field, I still get an error and it doesn't merge: `chainId: conflicting values 103`

**Comment by keone** [comment]
strange, there might have been a transient coingecko issue at the time (503 is transient)
merged
