### ISSUE TITLE
Please Update Logo

### ISSUE THREAD

**Issue by BXReid** [solana-labs/token-list#7982]
- **I'm submitting a feature request

- **I'd like have the SolanaFi logo added to SolScan.io and Raydium.io if possible

Mint address for the token is: 8udZmv2RrHpU8rPZhphUGhHpmyAqc9UzV4UihpThKvYh

IMG URL is: https://i.postimg.cc/L5CBqv1H/icon-3.png

I'm not a coder, so apologies if this is not the correct format or avenue to submit this request. Thank you!!

**Comment by BXReid** [comment]
Website is: www.solanafi.io

**Comment by keone** [comment]
this needs to be submitted as a commit containing a diff to solana.tokenlist.json, see some of the other recent commits in this repo as an example
