### ISSUE TITLE
Token info update

### ISSUE THREAD

**Issue by Solanyx** [solana-labs/token-list#7996]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary** 
Can you please remove NFT tag because phantom wallet recognises token as a NFT because of that. We submitted pull request: [Solanyx token update #7972](https://github.com/solana-labs/token-list/pull/7972/commits) Thanks

![Screenshot 2021-12-14 at 20 01 27](https://user-images.githubusercontent.com/96029424/146063314-224f6d96-6912-49d6-b5cd-80053a0a30f3.png)

**Comment by keone** [comment]
merged
