### ISSUE TITLE
[bug] $basis token coingeckoId (unkown field) whilst it is valid

### ISSUE THREAD

**Issue by cryptoboole** [solana-labs/token-list#8173]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
The pull request is failing because it says `failed to normalize: failed to parse JSON: json: unknown field "coingeckoId"`
But checking the entire repo thoroughly, it's correct and the market is valid

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

https://github.com/solana-labs/token-list/pull/8038/checks?check_run_id=4526905028

**Comment by cryptoboole** [comment]
@keone a kind request to have a look at this when you have a minute.

Thank you in advance

**Comment by keone** [comment]
merged
