### ISSUE TITLE
Solana Explorer Is not picking correct URL of Soldex Token Logo

### ISSUE THREAD

**Issue by vikas-speqto** [solana-labs/token-list#8182]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ x] question about the decisions made in the repository
  [ ] question about how to use this project

Yesterday We updated Soldex token Logo and URL, that PR is already merged. After that, we are able to see updated logo on solscan below is URL for [Soldex token](https://solscan.io/token/CH74tuRLTYcxG7qNJCsV9rghfLXJCQJbsu7i52a8F1Gn) on Solscan.
But on explorer soldex token is still taking wrong logo URL, merged code is not reflecting there. Below is explorer URL for [Soldex token](https://explorer.solana.com/address/CH74tuRLTYcxG7qNJCsV9rghfLXJCQJbsu7i52a8F1Gn)

PR merged [6450](https://github.com/solana-labs/token-list/pull/6450)

Kindly help me, where else I need to update URL of Soldex Icon which will Fix wrong URL of Soldex token on explorer.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
given that solscan looks fine (https://solscan.io/token/CH74tuRLTYcxG7qNJCsV9rghfLXJCQJbsu7i52a8F1Gn) it must be a solana explorer caching issue where they only update from token-list every so often
