### ISSUE TITLE
Token Logo Update

### ISSUE THREAD

**Issue by LeeChunHao2000** [solana-labs/token-list#8186]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I submitted pull request: SYP token update #8177 Thanks

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
