### ISSUE TITLE
Failed to verify website

### ISSUE THREAD

**Issue by chptokenadmin** [solana-labs/token-list#8188]
- **I'm submitting a ...**
  [ *] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
failed to verify website: https://cryptohealthplus.com/: failed to verify https://cryptohealthplus.com/ using HEAD request: Head "https://cryptohealthplus.com/": read tcp 10.1.0.26:53756->72.167.191.69:443: read: connection reset by peer shows up even when that website has been verified via mx records.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
1. https://github.com/solana-labs/token-list/pull/8126/checks?check_run_id=452967332
![Issue_SS001](https://user-images.githubusercontent.com/95162570/146171858-adcf3c23-06c6-489c-9d5e-b72852f18ffc.png)

**Comment by chptokenadmin** [comment]
Hello and thank you for your last email. Please see the pull request information below. We are still having issues with getting this fixed. It is needed for a dev to manually modified it so our website will be verified. Look at the screen shot below that shows our website is verified. I really appreciate your help in this matter as we have been working on this for over a month now. Thank you, 

![Screenshot 2022-01-21 205839 Website Github Verification ](https://user-images.githubusercontent.com/95162570/150715570-2710d0cf-6cd3-4a25-ac1b-588733f1a238.png)

**Comment by keone** [comment]
i believe this was resolved in another issue

**Comment by chptokenadmin** [comment]
Thank you so much for your help!

Michael Coscarelli

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
