### ISSUE TITLE
SolanaFi Token #8030 logo update

### ISSUE THREAD

**Issue by BXReid** [solana-labs/token-list#8211]
- **I'm submitting a feature request**

- **auto-merge error came up, so I updated logo for SolanaFi Token #8030 ** 

- **Not sure if it updated on the official Solana token list. I'm a rookie, so any help is appreciated. I really want my tokens info to reflect in Solscan, Thank you**

**Comment by keone** [comment]
the proper path is assets/mainnet/ADDRESS/logo.png
note how only your logo is in the wrong place: https://github.com/solana-labs/token-list/tree/3c3457db6881d13e6fc1c73b191dd47e72dabf2e/assets

**Comment by BXReid** [comment]
Thank you for your response and help :)
