### ISSUE TITLE
Request Token info update #8205 - Add coingeckoId

### ISSUE THREAD

**Issue by soldev81** [solana-labs/token-list#8216]
Please check MR [8205](https://github.com/solana-labs/token-list/pull/8205/files#diff-827c1376911cec5eb14653be1a34f430bcfb675b355c19c23c352633d625da50)
https://github.com/solana-labs/token-list/pull/8205

Our Token Address: 
J7WYVzFNynk9D28eBCccw2EYkygygiLDCVCabV7CupWL

Here is our token information on COINGECKO
https://www.coingecko.com/en/coins/mongoosecoin

We wanna added 
"coingeckoId": "mongoosecoin".

**Comment by soldev81** [comment]
[8205](https://github.com/solana-labs/token-list/pull/8205/files#diff-827c1376911cec5eb14653be1a34f430bcfb675b355c19c23c352633d625da50)

**Comment by keone** [comment]
merged
