### ISSUE TITLE
please accept my update info for solar token

### ISSUE THREAD

**Issue by WhiteElephantEco** [solana-labs/token-list#8239]
- **I'm submitting a ...**
  [ ] bug report
  [x ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
i add info for solar token: 
 "serumV3Usdc" :  "BHfFJM36MirbBtLCcnZokwRvxUPxk7Ez6EAT6k44q6Go"
"coingeckoId" :  "solar"
"coinmarketcap" :  "https://coinmarketcap.com/currencies/solardex/"

please accept the merge here is my pull request:
https://github.com/solana-labs/token-list/pull/8236

**Comment by keone** [comment]
squashed and merged
