### ISSUE TITLE
Please merge automerge doesnt accept

### ISSUE THREAD

**Issue by samuskyio** [solana-labs/token-list#8263]
- **I'm submitting a ...**
  [ ] bug report
automerge coingeckoId, discord, serumV3Usdc, coinmarketcap doesnt work
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
added:
coingeckoId
coinmarketcap
serumV3Usdc
discord

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
Please merge

**Comment by keone** [comment]
please link a PR
is it https://github.com/solana-labs/token-list/pull/8197/files ?

**Comment by keone** [comment]
squashed and merged https://github.com/solana-labs/token-list/pull/8197
