### ISSUE TITLE
Request for pull requests approval on ShibaMini 

### ISSUE THREAD

**Issue by AntimonyIQ** [solana-labs/token-list#827]
- **I'm submitting a request to approval of pull requests for shibaMini token...**

  [ ] Solana.tokenlist.json
  [ ] ShibaMini Token data approval

**Comment by SolDev-stack** [comment]
Please read the [SPL-token README](https://github.com/SolDev-stack/token-list/blob/main/README.md), and ensure your SPL-token info uses the correct [Uniswap format](https://github.com/SolDev-stack/token-lists/blob/main/README.md).

**Comment by keone** [comment]
please link a PR!
