### ISSUE TITLE
Delete token from the list

### ISSUE THREAD

**Issue by Solanyx** [solana-labs/token-list#8280]
- **I'm submitting a ...**
  [ ] bug report
  [ x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Hello, I would like to delete my token from list because of the issue with phantom wallet. It recognises token as NFT.  I just sent pull request [Delete token from the list #8275](https://github.com/solana-labs/token-list/pull/8275).
Thank you

**Comment by keone** [comment]
merged
