### ISSUE TITLE
project is now failing to publish npm package due to size

### ISSUE THREAD

**Issue by keone** [solana-labs/token-list#8358]
error Couldn't publish package: "https://registry.npmjs.org/@solana%2fspl-token-registry: Payload Too Large"
info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.

e.g. https://github.com/solana-labs/token-list/runs/4540534584?check_suite_focus=true

**Comment by tuphan-dn** [comment]
Any fixes on that mate. 7 days for no update on @solana/spl-token-registry. Hope it can be fixed soon.

**Comment by sjchmiela** [comment]
Does the package need to include all assets (couldn't they be excluded in `package.json` from ending up in the tarball)?

After all `solana.tokenlist.json` doesn't reference them by path (only by the absolute URL to GitHub CDN) so there's no reason for the consumer of the package to go into the package content and look into `assets` manually or programmatically. 🤔

**Comment by tuphan-dn** [comment]
> Does the package need to include all assets (couldn't they be excluded in `package.json` from ending up in the tarball)?
> 
> After all `solana.tokenlist.json` doesn't reference them by path (only by the absolute URL to GitHub CDN) so there's no reason for the consumer of the package to go into the package content and look into `assets` manually or programmatically. 🤔

Totally agree, these assets are referred and fetched by urls, so I think we can remove the assets folder to lighten up the package.

**Comment by sjchmiela** [comment]
That should do it — https://github.com/solana-labs/token-list/pull/9747

**Comment by keone** [comment]
thanks for the fix @sjchmiela !
