### ISSUE TITLE
Please add my token  - first time contributor waiting for review

### ISSUE THREAD

**Issue by tgnphotography** [solana-labs/token-list#8383]
Hi, 

   Github has told me that First-time contributors need a maintainer to approve running workflows. Could you please review my pull request and add my token. 

 add tgnpc token #7818 

Thank you,

**Comment by keone** [comment]
that's not the issue, the issue is described here: https://github.com/solana-labs/token-list/pull/7818/checks?check_run_id=4542105821

you committed a toplevel `logo.png` and also deleted a few other coins: https://github.com/solana-labs/token-list/pull/7818/files
