### ISSUE TITLE
Banana Bucks token decimals 0

### ISSUE THREAD

**Issue by abbas-unmarshal** [solana-labs/token-list#8454]
- **I'm submitting a ...**
  [ *] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
The decimals for banana bucks on the token list present in the repo is 0 whereas when we have a look at the same token in the explorer then the decimals is shown as 9

**Comment by keone** [comment]
please submit a PR
