### ISSUE TITLE
Update TOKEN website 

### ISSUE THREAD

**Issue by soldev81** [solana-labs/token-list#8489]
Our Merge Request:
https://github.com/solana-labs/token-list/pull/8473

Our Token Address
3fFHsncY59ue2HPduo1KhbZRWYRd8iek5tj88sPXMgFk

Token name: Floki Viking (FLOKI)

Our Twitter Information Already Update New Website 
https://twitter.com/FlokiVikingSOL

**Comment by keone** [comment]
merged
