### ISSUE TITLE
Update decimals of TTT (issue for DEXs, inconsistency mint & list decimals)

### ISSUE THREAD

**Issue by ymdrkh** [solana-labs/token-list#8504]
- **I'm submitting a ...**
  [ ] bug report
  [ *] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Please review https://github.com/solana-labs/token-list/pull/8501

There is decimals updated, we have inconsistency of mint & list decimals.
Added telegram channel and few changes to logo.
Thanks

**Comment by keone** [comment]
merged
