### ISSUE TITLE
updated logo for WvzG 1880 coin

### ISSUE THREAD

**Issue by wvzg1880** [solana-labs/token-list#8513]
pr
#8494

open task
updated logo

token
5QW1HrbmwcYq36XS4VFEzjAezXBqqXBmBYDKgcdDbwu2

Thx in advance!

**Comment by keone** [comment]
duplicate token: token address 5QW1HrbmwcYq36XS4VFEzjAezXBqqXBmBYDKgcdDbwu2 is already used
