### ISSUE TITLE
Update logo link for LabR token

### ISSUE THREAD

**Issue by jtomacic** [solana-labs/token-list#8530]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ x] question about how to use this project

- **Summary**

Hello, I'm new to all this, so I apologize for my mistakes. I submitted a pull request #8084, and I used the incorrect logo link for the Lab R token ( Hdi94P9m8m6xn4fgQenSqsLg8MAVKumCXrcgzrXqJDvC ). The correct logo link is:

https://raw.githubusercontent.com/jtomacic/crypto/main/logo.png

Could you please update the list with above link (preferable) or tell me how I can do it myself (if that's an option?).
Thank you in advance for your support.

**Comment by keone** [comment]
please submit a PR with a commit making that change

**Comment by jtomacic** [comment]
Ok, I will try again, but are there any instructions on how to do this properly? As you will see I made two attempts already,  PR 8114  and PR 8224, both failed due to my lack of knowledge on this.

Thanks
