### ISSUE TITLE
Update GTA token details

### ISSUE THREAD

**Issue by wenddak1ng** [solana-labs/token-list#8542]
Hello! About 1 month ago I pushed wrong info in tokenlist for GTA token. Then I tried to fix it myself but automerge detected all changes as deletions. Now I'm tried to add token again but it doesn't passed tests because token already has in tokenlist. Please help me update details manually because now I'm added more extensions, correct tags and logoURI.

Pull request: https://github.com/solana-labs/token-list/pull/8540

Thank you so much <3

**Comment by keone** [comment]
duplicate token: token address 9YdABeMBMjh5Pu8yPkJ9GETGWUT8KUK3B2RYBpjKNPsU is already used
