### ISSUE TITLE
Please allow token icon fix PR #8543

### ISSUE THREAD

**Issue by CKSLLC** [solana-labs/token-list#8548]
- **I'm submitting a ...**
  [ ] bug report
  [X] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
PR #8543 to update Crypto King Coin token icon.  Please allow this correction.  Thanks.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
