### ISSUE TITLE
Please approve my PR #8532, chenge icon for fresh Token

### ISSUE THREAD

**Issue by arcavacatalab** [solana-labs/token-list#8564]
- **I'm submitting a ...**
  [ ] bug report
  [ X] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
 Please approve my PR #8532 ,I've changed the icons url for the Fresh Token.

Thanks

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
