### ISSUE TITLE
Edit logo for OXYG - OxyGem

### ISSUE THREAD

**Issue by OxySpace** [solana-labs/token-list#8570]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I submitted pull request to edit logo of OxyGem: [Edit logo for OXYG - OxyGem #8567](https://github.com/solana-labs/token-list/pull/8567#issue-1082424156) Thanks

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
