### ISSUE TITLE
Update My token Information 

### ISSUE THREAD

**Issue by soldev81** [solana-labs/token-list#8597]
I wanna update our Token Information : Website , Twitter
Token : GGupQCMnyEmHKcqFu72qCTm6yEYpVyhouY9dSAMEXLsC
name: Dogecoin Cash
symbol: DOGEC
I wannan add the website : 
https://www.dogecoincash.info
Twitter
https://twitter.com/dogec_cash
Please check My MR :
https://github.com/solana-labs/token-list/pull/8591

**Comment by soldev81** [comment]
Our token already verified on Nomics, you can check it . 
https://nomics.com/assets/dog5-dogecoin-cash

**Comment by keone** [comment]
can you please link the commit where you added DOGEC?

**Comment by soldev81** [comment]
> can you please link the commit where you added DOGEC?

Hi here is my comit its mereged for longtime 
https://github.com/solana-labs/token-list/pull/3847

**Comment by soldev81** [comment]
Can you help me check this one today ?

**Comment by keone** [comment]
merged
