### ISSUE TITLE
Request update icon url

### ISSUE THREAD

**Issue by Kittysolana** [solana-labs/token-list#8705]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Hi Team! Our token has wrong url, due to file on wrong location. We've done a pull request a month ago. Please help to merge, thank you.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
Pull Request #4577

**Comment by keone** [comment]
merged
