### ISSUE TITLE
Please update our token url

### ISSUE THREAD

**Issue by kadekjr** [solana-labs/token-list#8707]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Our logo doesn't appear on some platforms on solana. We are aware that placing the wrong location can cause the logo to be lost. we have done a Pull Request, please help to merge again.
Feel free to contact me back, thank you.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
Pull Request #4581

**Comment by keone** [comment]
merged
