### ISSUE TITLE
Update twitter and add website, discord, serum information

### ISSUE THREAD

**Issue by rainclouds11** [solana-labs/token-list#8709]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Help us to update our twitter account. We also added more information.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
Pull Request here #5317

**Comment by keone** [comment]
squashed and merged
