### ISSUE TITLE
Please help us update some links & the logo

### ISSUE THREAD

**Issue by dogelana** [solana-labs/token-list#8748]
- **I'm submitting a ...**
  [ ] bug report
  **[X] feature request** 
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Hello,

I hope you are very well today! 

We just need some links updated, as well as the logo for our project. I have opened a pull request for this and need it manually merged.

I really appreciate the help.

[https://github.com/solana-labs/token-list/pull/8746]

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
https://github.com/solana-labs/token-list/pull/8746

**Comment by keone** [comment]
can you clarify the difference between your coin (DGLN, E6UU5M1z4CvSAAF99d9wRoXsasWMEXsvHrz3JQRXtm2X, dogelana.com) and the other dogelana (DLANA, DogeLZECE9CthXasBLFxgeA2umEyt8CcV7Jsf6P5ZTFo, dogelana.io)?  

it seems that previously both entries were pointing to the same telegram and twitter (i guess your links were pointing to the telegram and twitter links that dogelana.io occupies)

**Comment by dogelana** [comment]
Hello @keone thanks for reaching out,

DLANA token was an imposter token who tried to steal our ideas. 

We already input the Telegram and Twitter and CoinGecko links on the GitHub repository before we actually owned those links, and then DLANA the imposter fake (Dogelana TOKEN not Dogelana) came and registered the links to steal them from us. 

So we just need them changed. 

We are working with CoinGecko and CoinMarketCap to get the links back for us.

**Comment by dogelana** [comment]
You can refer to this post from the past for more information but I closed this one at the time. @keone 

https://github.com/solana-labs/token-list/pull/5985

**Comment by dogelana** [comment]
@keone Any update on this one?

**Comment by dogelana** [comment]
@keone your swift help would be appreciated, this is a roadblock for our project currently.

**Comment by dogelana** [comment]
Hello @keone , any chance we might be able to get some help on this one? Our team and holders have been patiently and eagerly awaiting great results.

We truly and greatly appreciate your time and attention.

In the meantime, I hope your Christmas was great and that your New Year is too!

**Comment by dogelana** [comment]
Happy New Year, @keone !!!

Hope you're doing well! :D 

Hoping you can take another look at this. We are about to reach $100,000 market cap.!
