### ISSUE TITLE
updating name and logo for WVZG 

### ISSUE THREAD

**Issue by wvzg1880** [solana-labs/token-list#8771]
- **I'm submitting a ...**
  [ ] bug report
  [X] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
  RP update WVZG Token https://github.com/solana-labs/token-list/pull/8494 
  trying to update name and token logo, but having troubles.
  - the new name is ment to be "Wilhelm von zur Gathen 1880"
  - the new logo is ment to be "1880coin.png"
  Please allow this correction.
  Many thx in advance!

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
