### ISSUE TITLE
Request Token info update #8377 - Add coingeckoId

### ISSUE THREAD

**Issue by metamounts** [solana-labs/token-list#8825]
Please check MR 8377
#8377

Our Token Address:
9QXAu7FTf7hmswBQwKxvuqGgWH42FyQjqXJanUt6y4eC

Here is our token information on COINGECKO
https://www.coingecko.com/en/coins/metamounts

We wanna added
"coingeckoId": "metamounts".

**Comment by keone** [comment]
this was added by DefiantDev, can you please have them comment here approving this?
```
commit a370145fd6f78faa52f415abadec7f90c1e678b1
Author: DefiantDev <DefiantDev@users.noreply.github.com>
Date:   Fri Dec 10 19:44:31 2021 +0000

    Add MOUNT
    
    Closes #6712
```

**Comment by metamounts** [comment]
gotcha

**Comment by DefiantDev** [comment]
approved
