### ISSUE TITLE
Requesting token CA93 info update PR #8887

### ISSUE THREAD

**Issue by rellikeno** [solana-labs/token-list#8895]
- **I'm submitting a **
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- Hi I'm requesting token CA93 info update as per PR #8887
- i have tried multiple times to update the information with new pull requests, modifying existing token and patches etc. but was unable to complete automerge

new PR #8887 has information
- correct logo uri
- website/facebook and youtube address
- decimal update
- token tags

if this is not the correct way to update the token information please let me know the process.

thank you
@rellikeno

**Comment by keone** [comment]
i'm having trouble merging this because it edits the location of your token's block, which then creates a conflict.  can you please make it edit the block in-place?

**Comment by rellikeno** [comment]
@keone , i did try in place change but didn't work.
i have raised new PR #8912 
thank you for helping out.
