### ISSUE TITLE
Maya Token Address updated

### ISSUE THREAD

**Issue by jesaiasmaia** [solana-labs/token-list#8896]
Change Token Address.

I changed my token address, PR #8889. I just change the address and commit again, but it add my token information again, guys I just want change my token address on json file.

Is it possible handle it manually? Don't pass in auto-merge because the token name was duplicated.

Old Address: JFgnsmpFP3e8vTtWEBsKonPaCsb3cmdyhHwhN7HTAGW
New Address: 3aAYh35n81F8HPG2QBdE48aYdzGFj2fsLccg91X4AcRc

**Comment by keone** [comment]
your PR has a massive diff to main: https://github.com/solana-labs/token-list/pull/8889/files

please commit a minimal diff, open a PR, and then open an issue here for manual review
