### ISSUE TITLE
Update MAYA Token Address PR #8909

### ISSUE THREAD

**Issue by jesaiasmaia** [solana-labs/token-list#8911]
Change Token Address.

I changed my token address, PR #8909. I just change the address and commit again, but it add my token information again, guys I just want change my token address on json file.

Is it possible handle it manually? Don't pass in auto-merge because the token name was duplicated.

Old Address: JFgnsmpFP3e8vTtWEBsKonPaCsb3cmdyhHwhN7HTAGW
New Address: 3aAYh35n81F8HPG2QBdE48aYdzGFj2fsLccg91X4AcRc

** The moderator ask for me doing again with fell changes

**Comment by keone** [comment]
merged

**Comment by jesaiasmaia** [comment]
How many hours to take effect on solana explorer?
