### ISSUE TITLE
Requesting token CA93 info update as per PR #8912 

### ISSUE THREAD

**Issue by rellikeno** [solana-labs/token-list#8926]
**I'm submitting a **
[x] bug report

### Summary

Hi I'm requesting token CA93 info update as per PR #8912 (Correction to PR# 8887 - CA93 Token info update)

i have tried multiple times to update the information with new pull requests, modifying existing token and patches etc. but was unable to complete automerge

my previous issue #8895 and PR #8887 was unsuccessful in automerge (including PR #8912)

i have raised this new issue to highlight PR #8912 as the info is update in place of the token block as suggested by @keone and hopefully can be merged successfully

new PR #8912  has information in the '_correct token block place_'
- correct logo uri
- website/facebook and youtube address
- decimal update
- token tags

if this is not the correct way to update the token information please let me know the process.

thank you
@rellikeno

**Comment by keone** [comment]
merged. it's good etiquette to close the other PR/issue
