### ISSUE TITLE
Logo not showing up on Token

### ISSUE THREAD

**Issue by nicholhai** [solana-labs/token-list#9120]
- **I'm submitting a ...**
  [*] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Code scanning compared refs/heads/main (commit 146350b) with refs/pull/9106/merge (commit 6a81dc5) and refs/heads/main (commit d2f694e).

Tried to add logo to token: DDpPE1qBRLFfKYnmaGgnimSXNX3cYhRNBe5r8AC9tYRF and submitted a pull request but the auto merge failed

**Comment by keone** [comment]
https://github.com/solana-labs/token-list/pull/9106
