### ISSUE TITLE
duplicate token: token address

### ISSUE THREAD

**Issue by jakin2021** [solana-labs/token-list#9149]
I am unable to proceed with my pull request due tho the this error; duplicate token: token address is already used.
How do I locate this duplicate? As it won't allow me to successfully make my request with auto-merge.

 #9112

**Comment by jakin2021** [comment]
@keone could you help me take a look at this please, and thank you.

**Comment by keone** [comment]
you already added it in https://github.com/solana-labs/token-list/commit/5f9e9ba18608626c068b881717583da8cdd49792

**Comment by jakin2021** [comment]
I appreciate the response @keone your right I have, but not sure how to close that as I have made a new one. I didn't realise creating this new one will been seen as a duplicate. could you help me with this please?

**Comment by keone** [comment]
it's just a text file: make the diff that you want to get the file into the correct state, commit that, and open a PR

**Comment by jakin2021** [comment]
@keone I made the difference already in my new pull request but, it is still telling me it is a duplicate. If possible I would like to delete all created files under MANSA MUSA and start again but I'm also unsure how to do that apologies if I seem simple.

**Comment by keone** [comment]
i'm sorry, but there are too many PRs for maintainers to make changes for you or instruct you on how to use git. figure that out or get a friend to help you and link a PR

**Comment by jakin2021** [comment]
@keone  thank you
