### ISSUE TITLE
BitZera in solsan.io has been duplicated

### ISSUE THREAD

**Issue by grglzrv** [solana-labs/token-list#9259]
Today I have updated the BitZera's token with https://solscan.io/token/DkmdmfVCP8bvAYXGRz8ENjPM2aPkVE51CvBjne1qvxyk 

but the old one https://solscan.io/token/GvmkvNUQPvHR7J68e1YuyabSLzuMCE4GPTuAUcwL3V6Z is exists yet,

Could you please delete this one https://solscan.io/token/GvmkvNUQPvHR7J68e1YuyabSLzuMCE4GPTuAUcwL3V6Z

**Comment by keone** [comment]
it takes some time for solscan to update their cache
