### ISSUE TITLE
We would like to change our token name from  "name": "UBIK Token" to   "name": "UBIK" 

### ISSUE THREAD

**Issue by UbikCapital** [solana-labs/token-list#9295]
- **I'm submitting a ...**
  [ ] bug report
  [x ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
We would like to change our token name from: UBIK Token with: UBIK
Thanks
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
please submit a PR
