### ISSUE TITLE
Unable to Upload new Token into SOLANA.TOKENLIST.JSON

### ISSUE THREAD

**Issue by Akshit-Panapuzha** [solana-labs/token-list#9296]
- **I'm submitting a ...**
  [ * ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I am getting this error after having logged in and confirmed my identity. If anyone can give some guidance, I would appreciate it.
remote: Permission to solana-labs/token-list.git denied to URunner21.
fatal: unable to access 'https://github.com/solana-labs/token-list.git/': The requested URL returned error: 403

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

None

**Comment by keone** [comment]
you cannot push directly to this repo, you must push to your fork and then create a PR
