### ISSUE TITLE
Token Updates - Please Review

### ISSUE THREAD

**Issue by JonLittleIT** [solana-labs/token-list#9312]
Hi I am needing to update settings so symbol shows in solana explorer.

https://github.com/solana-labs/token-list/pull/9173/

Let me know if I Have done this correct or if changes are needed thank you.

**Comment by keone** [comment]
this isn't a token mint; shouldn't even be in this repo: https://solscan.io/account/D9pXQfzq8MnhLGP8eo9BhuEmx2vSCaQg9ivkwNVHeCFc
