### ISSUE TITLE
Add more VortX data

### ISSUE THREAD

**Issue by MilesBellum** [solana-labs/token-list#9520]
- **I'm submitting a ...**
  [ ] bug report
  [ X ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I've changed the symbol, name, the social networks and logo of my token. The PR is [9516](https://github.com/solana-labs/token-list/pull/9516)

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
