### ISSUE TITLE
DELETE NOLE NPC (We swapped to NPC DAO)

### ISSUE THREAD

**Issue by nolecoin** [solana-labs/token-list#9560]
- **I'm submitting a ...**
  [ ] bug report
  [X ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
We swapped from NOLE NPC to NPC DAO. NPC DAO is added to token list but we want to delete NOLE NPC. Please manually merge PR #9558

You can check swap info in this medium article https://medium.com/@npcdao/npc-dao-swap-and-rebranding-completed-bff57c65914c that is uploaded to our new website (https://npcdao.io)

Thank you!

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
merged
