### ISSUE TITLE
Issue adding extensions

### ISSUE THREAD

**Issue by dintapp** [solana-labs/token-list#9685]
We'd like to update our Token Information : Website , Twitter

Token : 8KzT4VfvzULfbyAE8PS7qzD3zNv6v2Bb4sKMx2v4Qu8e
name: Dintcoin
symbol: DTC

**I'd like to add our website :**
https://dint.com

**Twitter**
https://twitter.com/dint

Please check My PR:
https://github.com/solana-labs/token-list/pull/9660/commits/887e7657769c1646a45d71b78335acf9875a20a2

**Comment by keone** [comment]
merged #9660
