### ISSUE TITLE
Coingecko check fails

### ISSUE THREAD

**Issue by NorbertBodziony** [solana-labs/token-list#9768]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Created two PR with new tokens both of them fails on coingecko check. Endpoint are correct.
https://github.com/solana-labs/token-list/pull/9760
https://github.com/solana-labs/token-list/pull/9056
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
weird, seems like some sort of cloudflare issue
merged #9760 
for #9056 see PR

**Comment by keone** [comment]
merged
