### ISSUE TITLE
change NFT tag

### ISSUE THREAD

**Issue by bentnoze** [solana-labs/token-list#9947]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Phantom wallet recognised our token as an NFT rather than a SPL token due to its "NFT" tag, PR #9946 to remove "NFT" tag and replaced with "GOBLINS"

**Comment by keone** [comment]
merged
