### ISSUE TITLE
Non-square logo failing to display on solscan

### ISSUE THREAD

**Issue by ninjajoe9** [solana-labs/token-list#9963]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I incorrectly uploaded a logo for my token that wasn't a square .png file and I believe as a result this is why it isn't displaying in solscan and other solana token searches.

my token address is AsJkh4kbD2UszLxztWQ49AHj6NkK8UMYbpGmnDdpNCf6 and is called Nin-En (NINE)

the logo at https://github.com/ninjajoe9/crypto/blob/main/logo.png is correct and the information in the solana.tokenlist.json is correct, but I can't update the logo in assets/mainnet folder. 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

I have tried to pull-request twice (#9665 and #9944) unsuccessfully. If the new file could be uploaded for me manually I would appreciate it. Correct file attached. 
![logo](https://user-images.githubusercontent.com/48168373/147140237-5ba34882-4c04-4802-b310-81d2ba926904.png)

**Comment by keone** [comment]
merged #9944
